### ISSUE TITLE
ftp.freetds.org is down

### ISSUE THREAD

**Issue by coderjoe** [FreeTDS/freetds#101]
Not sure where else to leave this. ftp.freetds.org is down and I'm not sure where else to point people for official stable source tarballs.

**Comment by avit** [comment]
It would also be helpful if the released versions were tagged here so this could serve as a stable backup source.

I found [this source](https://fossies.org/linux/privat/freetds-1.00.26.tar.gz/) but it only contains the single latest version so it's not helpful as a source. The homebrew package manager uses it as a mirror:

https://github.com/Homebrew/homebrew-core/blob/master/Formula/freetds.rb

**Comment by jmsmistral** [comment]
ftp.freetds.org still down.

Also, agree with @avit

**Comment by ticktricktrack** [comment]
We've got the same problem here.

**Comment by ssxenon01** [comment]
Elasticbeanstalk is messing with deployment cuz of this, i'm in deep shit now :(

**Comment by garethcokell** [comment]
If you're having issues with elasticbeanstalk, please add your voice to this thread requesting an updated yum package so that there is no need to compile from source: https://forums.aws.amazon.com/thread.jspa?threadID=249375

**Comment by ticktricktrack** [comment]
You can use `gem 'tiny_tds', git: 'https://github.com/ticktricktrack/tiny_tds.git'` now, I've hardcoded the fossies url instead of the ftp server.

cc @ssxenon01

**Comment by freddy77** [comment]
Sent a mail to server administrator.

**Comment by johnthepink** [comment]
Seems to be back up now.

**Comment by coderjoe** [comment]
Closing as it seems to be back.

**Comment by hobbsenigma** [comment]
Old thread, but the ftp server seems to be down again.

**Comment by freddy77** [comment]
is back now

**Comment by trietphm** [comment]
@freddy77 is it down again?

**Comment by freddy77** [comment]
It seems so, in the meantime you can use http://www.freetds.org/files/, I'll contact the admin.

**Comment by trietphm** [comment]
Thank, it is back 👍
