### ISSUE TITLE
Join mailing list

### ISSUE THREAD

**Issue by bbrownaip** [FreeTDS/freetds#102]
I would like my email to be added to the FREETDS mailing list (https://lists.ibiblio.org/mailman/listinfo/freetds). 

Thanks.

**Comment by freddy77** [comment]
I would need your e-mail address. You can send to me privately (to avoid spam).
You can find my address on the mailing list (Frediano).

**Comment by bbrownaip** [comment]
I just sent you an email (hopefully).  Thank you.

**Comment by freddy77** [comment]
joined, thanks
