### ISSUE TITLE
Should `dbsettime` override the per-connection timeout settings?

### ISSUE THREAD

**Issue by attilahorvath** [FreeTDS/freetds#105]
I am working on adding per-connection timeout settings to TinyTDS, a Ruby gem which uses this library (https://github.com/rails-sqlserver/tiny_tds/pull/348).

I came across this issue that if we first assign a per-connection timeout value with `dbsetopt(connection, DBSETTIME, timeout, 0)` then later on call `dbsettime(timeout)`, this new timeout setting will override all the previously set timeouts for existing connections. It's pretty clearly happening in the implementation of `dbsettime` here: https://github.com/FreeTDS/freetds/blob/fc820490336c50d5c175d2a15327383256add4c9/src/dblib/dblib.c#L4105-L4123.

I was just wondering if this is the intended behaviour. I assumed that the global timeout setting should only be used for connections that don't have a unique timeout set for them.

If this is indeed a bug, I'd be happy to submit a patch to fix this.

**Comment by freddy77** [comment]
Hi, was trying to check Microsoft documentation but apparently they removed everything about dblib.
I would say this is undefined behaviour at the moment.
Who win between global and local is not defined.
dtsettime (function) has to change all connection for compatibility with Sybase (which does not support dbsetopt(DBSETTIME)).
I think however that not changing the overridden ones make sense, Sybase application won't use dbsetopt(DBSETTIME) so the compatibility is retained for such apps.
Patch welcome.

**Comment by attilahorvath** [comment]
I've submitted a PR for this: https://github.com/FreeTDS/freetds/pull/107. The Travis build is failing for some reason though (worked for me just fine locally).

**Comment by freddy77** [comment]
Merged PR.
