### ISSUE TITLE
Security contact or best way to send sensitive bugs

### ISSUE THREAD

**Issue by brandonprry** [FreeTDS/freetds#108]
Hi, what is the best way to communicate potentially security-sensitive bugs in FreeTDS?

Thanks

**Comment by freddy77** [comment]
Would be the first time we have such issues.
Maybe you can contact me privately (you can easily find my address on the ML).

**Comment by brandonprry** [comment]
Thanks, I will organize the crashes and relevant information and shoot them your way.
