### ISSUE TITLE
Crash due to null pointer access in tds_alloc_row

### ISSUE THREAD

**Issue by mind-ranger** [FreeTDS/freetds#109]
TDSRET
tds_alloc_row(TDSRESULTINFO * res_info)
{
	int i, num_cols = res_info->num_cols;
	unsigned char *ptr;
	TDSCOLUMN *col;
	TDS_UINT row_size;

	row_size = 0;
	for (i = 0; i < num_cols; ++i) {
		col = res_info->columns[i];

		col->column_data_free = NULL;

		row_size += col->funcs->row_len(col); // <----  crashed at this line, col->funcs is NULL
                                       // because sometimes only part of the columns are returned/parsed 
                                       // from server response, the rest columns were left zeros

		row_size += (TDS_ALIGN_SIZE - 1);
		row_size -= row_size % TDS_ALIGN_SIZE;
	}
        //.......

**Comment by freddy77** [comment]
How did you manage to get this? Are you writing a server?
I'm actually working on related stuff. One potential path is the handling of colname token (which is only 4.2 protocol version).

**Comment by mind-ranger** [comment]
Yes I'm writing a server, it receives http requests and translate them into sql queries and send them to sql server to get result, there's a thread pool, each thread in the pool maintains a freetds connection to sql server.
The crash happened when it query 152 columns from a table, the log shows that only the first 132 columns were valid, the rest columns were all zeros, I'm not sure if it's related to the number of columns, or the number of threads.

**Comment by freddy77** [comment]
Are you sure you are using a new protocol version?
Are you serializing correctly every request + answer to sql server?
This should happens more on unknown reply from the server or old (4.2) protocol.
Nothing came to my mind on 132 or 152 (beside 132 is the old printer limit for columns and should be quite big queries).
Should be easy to understand from a core dump. Can you provide one?

**Comment by mind-ranger** [comment]
I'm using the default settings of 1.0.27 version, not sure about the protocol version.
I call dbinit() to initialize the library, call dblogin(), dbopen() to connect to server, call dbcmd() and dbsqlexec() to execute sql statement.

The coredump file is about 160MB, how can I send it to you?

BTW, the number of columns that successfully parsed is 120, not 132.

**Comment by freddy77** [comment]
Hi, can you use a stronger compressor like xz? Also I need the executable. Yes, you can send directly to me.
Thanks

**Comment by mind-ranger** [comment]
by email? what's your email address?

**Comment by freddy77** [comment]
Thanks. It's a error propagation/handling problem. The server closed the connection while sending the result set header and this caused the issue. The connection was already closed at the time of the crash, the code should never attempted to use the result set.

**Comment by freddy77** [comment]
Fixed in master and stable.
