### ISSUE TITLE
encryption = off treated like encryption = request in the freetds.conf file in login.c

### ISSUE THREAD

**Issue by gjcarrette** [FreeTDS/freetds#110]
There is a bug in login.c that causes encryption = off to be treated as encryption = request
whenever HAVE_OPENSSL is defined.  This is easily seen by using the tsql command
with TDSDUMPCONFIG and TDSDUMP defined and a Microsoft SQL Server that is TLS capable.
When you see tls.c mentioned in the TDSDUMP file you know it was not turned off.

Here is my test, where I edit the config file to have the encryption directive either missing (default)
or set to one of the 3 legal values, off, request, require. The strace helps validate what
config files were really used in the test.

```
  rm -f /tmp/freetds.check.*; \
  env FREETDSCONF=$HOME/freetds.conf \
      TDSDUMPCONFIG=/tmp/freetds.check.config.txt TDSDUMP=/tmp/freetds.check.log.txt \
      strace -f -s 128 -o /tmp/freetds.check.strace.txt /usr/local/bin/tsql -S JDBC -U guest -P sybase < /dev/null
```

**Comment by freddy77** [comment]
Patch sound good. However I think the default should then be changed to request to not break lot of mssql configurations. Not sure what will happen to Sybase.

**Comment by freddy77** [comment]
Merged, thanks
