### ISSUE TITLE
Which version to install

### ISSUE THREAD

**Issue by thedumbtechguy** [FreeTDS/freetds#111]
I want to install a new version from git.

I would like to know if I should target a specific tag or commit. Which would you recommend I use for production?

I was looking at `branch-1_00` tag.

**Comment by freddy77** [comment]
Nor tag not specific commit. There is a stable branch (currently Branch-1_00) and master which is supposed to be less stable and subject to change or even break. So the reply is the last stable branch.
This branch is used to snapshots too ("Last stable release" from http://www.freetds.org/software.html).
