### ISSUE TITLE
tds71_do_login encryption byte value?

### ISSUE THREAD

**Issue by hankinsoft** [FreeTDS/freetds#112]
In tds71_do_login, there is the following code:

```
#if !defined(HAVE_GNUTLS) && !defined(HAVE_OPENSSL)
	/* not supported */
	tds_put_byte(tds, 2);
#else
    tds_put_byte(tds, login->encryption_level >= TDS_ENCRYPTION_REQUIRE ? 1 : 0);
#endif
```

Is there any documentation on what this value represents (maybe an enum of some sort)? I've had a look at the Microsoft TDS documentation (https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/MS-TDS/[MS-TDS]-160714.pdf) which states that its for encryption, but not what the values represent. Also took a look here: http://www.freetds.org/tds.html, but I cannot find any info about field.

Thanks!

**Comment by freddy77** [comment]
Look at section 2.2.6.5 of MS document, specifically the values are ENCRYPT_OFF, ENCRYPT_ON, ENCRYPT_NOT_SUP and ENCRYPT_REQ.
Yes, I should use some constant for them, now that there are :-)

**Comment by ramiro** [comment]
> 've had a look at the Microsoft TDS documentation (https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/MS-TDS/[MS-TDS]-160714.pdf)

This is a great resource. Didn't know there was such a document describing TDS. Thanks!
