### ISSUE TITLE
`for xml path` splits results into multiple rows

### ISSUE THREAD

**Issue by hankinsoft** [FreeTDS/freetds#115]
Reproducible using freetds 1.00.33 on macOS installed via homebrew.
Using `DBVERSION_73`

This query:
`SELECT * FROM table for xml AUTO, TYPE;`

Works fine, the column type comes back as SYBMSXML and the results are processed properly (dbnextrow returns a single row with the entire xml result).

This query however:
`SELECT * FROM table for xml path('tablename');`

Instead seems to be processed as a SYBNTEXT and although it should return a single row, calling `dbnextrow` instead seems to populate partial results. Rather than one row containing the entire xml as Microsoft sql management studio would receive, the xml result gets split up into many rows (see http://i.imgur.com/JPaO13Y.png).

Please let me know if I can provide any more details.

**Comment by freddy77** [comment]
A TDSDUMP (see http://www.freetds.org/userguide/logging.htm) would help understand if is the server that splits the strings or the client.

**Comment by hankinsoft** [comment]
TDSDUMP for the query which gets split into multiple rows is here:
https://pastebin.com/raw/scEHPCdq

Not sure if helpful, but the TDSDUMP for `xml AUTO, TYPE` (which returns one row) is here:
https://pastebin.com/raw/4RvQUTrx

**Comment by hankinsoft** [comment]
Further research it looks like some versions of Microsofts sqlcmd have the same issue (https://connect.microsoft.com/SQLServer/feedback/details/786004/sqlcmd-with-xml-on-break-lines-on-large-output) and has a specific setting (:XML ON) to handle turning this on/off. So this may not be anything with freetds.

**Comment by freddy77** [comment]
Yes, the server is just returning 2 row instead of 1...
Can you post a network dump with :XML ON (sqlcmd). But I think the reason is that it set the binary format (which is not still supported by FreeTDS).

**Comment by hankinsoft** [comment]
Sure, here is a packet capture from wireshark. As far as I can tell it still gets sent in two separate rows. Maybe sqlcmd.exe reassembles the xml itself.

[sqlcmd.zip](https://github.com/FreeTDS/freetds/files/967009/sqlcmd.zip)

**Comment by freddy77** [comment]
The packet capture has the same 2 line rows. Basically the server returns 2 rows of NTEXT type with a maximum of 4K bytes. Not clear why sqlcmd in mssql 2008 returns just a single row. Maybe uses other options or detect this server bug. Who to change the :XML option? Did you use sqlcmd from mssql 2008 or a newer version? Quite bad MS closed the bug report without even giving a reason.

**Comment by hankinsoft** [comment]
Sorry that was using SQLCMD from SQL Server 2014. I'll setup a 2008 VM and post the results, but it will take me a few days to get it completed.

**Comment by freddy77** [comment]
Sorry, were you able to test it? Seems to me a server bug more than a library one.

**Comment by hankinsoft** [comment]
Haven't been able to test, but I agree that its a server bug rather than a library one. I'll go ahead and close the issue. Thanks!
