### ISSUE TITLE
Will not build without SSL/TLS support

### ISSUE THREAD

**Issue by gnbond** [FreeTDS/freetds#117]
1.00.38, trying to build from source.  This box did not have guntls-devel or openssl-devel installed and the build failed when linking server/tdssrv:

make[2]: Entering directory `/home/gnb/freetds-1.00.38/src/server'
  CCLD     tdssrv
./.libs/libtdssrv.a(packet.o): In function `tds_write_packet':
/home/gnb/freetds-1.00.38/src/tds/packet.c:750: undefined reference to `tds_ssl_deinit'
collect2: error: ld returned 1 exit status

I think this is because the stub routines in freetds/tls.h that are used when HAVE_GNUTLS and HAVE_OPENSSL are not defined are all specified as "static inline"

Installing the devel package is not enough, you also need to explicitly add --with-gnutls to configure.

The attached patch _seems_ to fix it and _seems_ benign, and it now compiles without a TLS library defined.

[diffs-tls.txt](https://github.com/FreeTDS/freetds/files/994888/diffs-tls.txt)

**Comment by freddy77** [comment]
Static inline should be perfectly fine. Which compiler version are you using?
Can you post your config.h file?

**Comment by freddy77** [comment]
Found, missing include.
Fixed.
