### ISSUE TITLE
BCP_SETL() and bcp_getl() have inconsistant API

### ISSUE THREAD

**Issue by gnbond** [FreeTDS/freetds#119]
The login packet in TDS protocol seems to have odd semantics - if the byte is zero, then BCP is allowed.

The BCP_SETL() macro knows this and reverss the value so that BCP_SETL(c, 1) sets this byte to zero in tds_

however the bcp_getl() function just returns the byte un-interpreted, so the following assertion will fail:
BCP_SETL(con, TRUE);
assert(bcp_getl(con)|);

Code: BCP_SETL() eventually calls tds_set_bulk():

tds_set_bulk(TDSLOGIN * tds_login, TDS_TINYINT enabled)
{
        tds_login->bulk_copy = enabled ? 0 : 1;
}

bcp_getl(LOGINREC * login)
{
        TDSLOGIN *tdsl = login->tds_login;

        tdsdump_log(TDS_DBG_FUNC, "bcp_getl(%p)\n", login);

        return (tdsl->bulk_copy);
}

**Comment by gnbond** [comment]
Attached test program fails on FreeTDS but succeeds with real sybase library.
[bcp_getl_bug.c.txt](https://github.com/FreeTDS/freetds/files/1009416/bcp_getl_bug.c.txt)

dev-ost:~/freetds-1.00.38$ gcc -I$HOME/freetds-1.0/include -L$HOME/freetds-1.0/lib bcp_getl_bug.c  -lsybdb && ./a.out
a.out: bcp_getl_bug.c:10: main: Assertion `bcp_getl(c)' failed.
Aborted (core dumped)
dev-ost:~/freetds-1.00.38$ gcc -I /opt/sybase/OCS-15_0/include bcp_getl_bug.c -L /opt/sybase/OCS-15_0/lib -lsybdb64
dev-ost:~/freetds-1.00.38$

**Comment by freddy77** [comment]
Actually seems that tds_set_bulk is wrong, looking at login code should be

tds_login->bulk_copy = enabled ? 1 : 0;

**Comment by freddy77** [comment]
Fixed (not so easy at it seems)
