### ISSUE TITLE
Status of the Connection Pooling Feature

### ISSUE THREAD

**Issue by domaindrivendev** [FreeTDS/freetds#122]
Firstly, I want to thank all the folks who work on this project - it's vital to some of the work I'm doing. I have a couple of personal OSS projects and I know the effort that goes into it. Thank you so much.

We have an interesting problem that the pooling server might solve in a very clean way. Essentially, we want to use it as a TDS relay/proxy where incoming TDS requests (over VPN from an external client) are forwarded to a local SQL Server using Windows authentication. The client would not be domain-joined but the pooling server would. In other words, _client-to-pool_ would need to use regular authentication and then _pool-to-server_ would use Windows authentication.

When I first read the docs, I was thinking holy sh%t this is exactly what we need :) Then I saw that it only supports TDS 4.2. I believe the target server is 7.2 or above. So ... just wanted to confirm the following:

- The 4.2 support is in fact an upper limit and there's no workaround to this you're aware of
- The pooling server can support domain logins for pooled connections

Any insight would be greatly appreciated.

Thanks

**Comment by freddy77** [comment]
The good news is that FreeTDS 1.00 support newer protocol versions. Where did you read is limited to 4.2? Maybe I miss to update documentation.
Currently however the pool server uses the same sql login (so no domain logins) for server (so pool -> sql server) and clients (so client -> pool) making your case not possible. Don't think would be too hard to support this use case however, adding support for domain logins from the client is not as easy but between pool and server should be easier.

**Comment by excalq** [comment]
http://www.freetds.org/userguide/tdspool.htm notes: 
> The FreeTDS connection pool currently only supports TDS version 4.2. This restriction applies to both the client-to-pool and pool-to-server connections!

Good to know that FreeTDS 1.00 has support for newer TDS versions in this capacity.

**Comment by freddy77** [comment]
Not sure if 1.00 actually support this or just master.
Just added a changed to support different user/password for server side which is the change you need.
The policy of the project is not to backport new feature (like this) in the "stable" branch but only fixes.
But the only unstable thing in master is some Sybase behaviour so is safe to use master for MS SQL Server.
Small notes: TDS version from 7.1 are supported, no encryption at the moment (you can specify request but not require on freetds.conf), use same TDS version for client and server.
