### ISSUE TITLE
build: compilation error EFD_CLOEXEC for older kernels

### ISSUE THREAD

**Issue by mckaygerhard** [FreeTDS/freetds#124]
when compiled lasted from git i get following error, i suspect its the gnutls related:

```
data.c: In function ‘tds_sybblob_get’:
data.c:1553: warning: unused variable ‘serialization_type’
  CC     net.lo
net.c: In function ‘tds_wakeup_init’:
net.c:774: warning: implicit declaration of function ‘eventfd’
net.c:774: error: ‘EFD_CLOEXEC’ undeclared (first use in this function)
net.c:774: error: (Each undeclared identifier is reported only once
net.c:774: error: for each function it appears in.)
net.c:774: error: ‘EFD_NONBLOCK’ undeclared (first use in this function)
```

**Comment by mckaygerhard** [comment]
recompile with openssl and no! its a build issue.. please some help

**Comment by mckaygerhard** [comment]
seems its since the commit 5c96df7673cbac44b0d8870aa6864e8b

**Comment by mckaygerhard** [comment]
i found the commit related, its 98b869f488fc230a8fce1b6a544eea06864830fb and now i can made a patch ... seems EFD_CLOEXEC and EFD_NONBLOCK are only availabel since linux 2.6.27..

i know its quite older but many systems still runs these kernels with special modified patch, most embebed systems and i have one in a fingerprint hardware embebed in a case metal that connects to a sybase database....

**Comment by freddy77** [comment]
Fixed

**Comment by mckaygerhard** [comment]
a question on 3b67ec801acbccf047b0c39bfadc3969ef2a8785#commitcomment-22450076  (https://github.com/FreeTDS/freetds/commit/3b67ec801acbccf047b0c39bfadc3969ef2a8785#commitcomment-22450076)  the autotools build system are now deprecated? the header inclusion are not necesary on the autotools build system?

**Comment by freddy77** [comment]
No, there is a change for configure.ac too. The other files (like the configure script) are autogenerated from configure.ac.

**Comment by mckaygerhard** [comment]
but in i think in configure.ac in line 306 aproximadelly

**Comment by mckaygerhard** [comment]
sorry for noise.. the stupid chromium cache browser does not show the complete commit.. (the configure.ac part are borrowed, its a bug in rendering xorg integration) many thanks for the change.. i don't specked u made the fix but great thanks!
