### ISSUE TITLE
[FreeTDS][SQL Server]Communication link failure SQLSTATE IS: 08S01

### ISSUE THREAD

**Issue by Veerbhadra277** [FreeTDS/freetds#125]
I am using  FreeTDS 0.95 (Release date 8 June 2015) and running ejabberd on centOS7, and using azure mssql server as ejabberd database suddenly a following exception continuously, it was working smoothly since 1 year. 

`2017-06-14 07:50:57.020 [error] <0.12821.3>@ejabberd_sql:check_error:1033 SQL query 'Q48949371' at {ejabberd_sm_sql,127} failed: <<"[FreeTDS][SQL Server]Communication link failure SQLSTATE IS: 08S01">>
2017-06-14 07:50:57.020 [error] <0.12821.3>@ejabberd_sm_sql:get_sessions:133 failed to select from 'sm' table: {error,<<"[FreeTDS][SQL Server]Communication link failure SQLSTATE IS: 08S01">>}
`

It looks like freeTDS connection issue with Azure MSSQL, seen similar issue [https://github.com/processone/ejabberd/issues/1437](url)

can anyone help to resolve this issue ?

**Comment by Veerbhadra277** [comment]
I got TDSDUMP here i could found where it fails first time

`odbc.c:3452:_SQLExecute: odbc_process_tokens returned result_type 4040
odbc.c:4545:SQLNumResultCols(0x15a7c50, 0x7ffe323e3712)
odbc.c:4625:_SQLRowCount(0x15a7c50, 0x7ffe323e3718),  -1 rows 
odbc.c:4636:SQLRowCount returns 0, row count -1
odbc_export.h:195:SQLDescribeCol(0x15a7c50, 1, 0x7ffe323e3170, 255, 0x7ffe323e3140, 0x7ffe323e3142, 0x7ffe323e3148, 0x7ffe323e3144, 0x7ffe323e3146)
odbc.c:1803:SQLBindCol(0x15a7c50, 1, -16, 0x1574050, 4, 0x155af70)
odbc.c:4033:SQLFetch(0x15a7c50)
odbc.c:3768:_SQLFetch(0x15a7c50, 1, 0)
token.c:549:tds_process_tokens(0x15807b0, 0x7ffe323e3000, 0x7ffe323e3004, 0x6508)
util.c:165:Changed query state from PENDING to READING
token.c:564:processing result tokens.  marker is  d1(ROW)
token.c:1951:tds_process_row(): reading column 0 
data.c:534:tds_get_data: type 56, varint size 0
data.c:587:tds_get_data(): wire column size is 4 
util.c:165:Changed query state from READING to PENDING
odbc.c:3630:odbc_process_tokens: tds_process_tokens returned 0
odbc.c:3631:    result_type=4040, TDS_DONE_COUNT=0, TDS_DONE_ERROR=0
odbc.c:3703:odbc_process_tokens: returning result_type 4040
convert_tds2sql.c:241:odbc_tds2sql: src is 56 dest = -16
odbc.c:4033:SQLFetch(0x15a7c50)
odbc.c:3768:_SQLFetch(0x15a7c50, 1, 0)
token.c:549:tds_process_tokens(0x15807b0, 0x7ffe323e3000, 0x7ffe323e3004, 0x6508)
util.c:165:Changed query state from PENDING to READING
token.c:564:processing result tokens.  marker is  fd(DONE)
token.c:2080:tds_process_end: more_results = 0
		was_cancelled = 0
		error = 0
		done_count_valid = 1
token.c:2097:                rows_affected = 1
token.c:2100:tds_process_end() state set to TDS_IDLE
util.c:165:Changed query state from READING to IDLE
util.c:83:logic error: cannot change query state from IDLE to PENDING
util.c:165:Changed query state from IDLE to IDLE
odbc.c:3630:odbc_process_tokens: tds_process_tokens returned 0
odbc.c:3631:    result_type=4052, TDS_DONE_COUNT=10, TDS_DONE_ERROR=0
odbc.c:3673:odbc_process_tokens: row_count=1
odbc.c:3900:SQLFetch: NO_DATA_FOUND
odbc.c:869:SQLMoreResults(0x15a7c50)
token.c:549:tds_process_tokens(0x15807b0, 0x7ffe323e3180, 0x7ffe323e3184, 0x15914)
token.c:552:tds_process_tokens() state is COMPLETED
odbc.c:3630:odbc_process_tokens: tds_process_tokens returned 1
odbc.c:3631:    result_type=4052, TDS_DONE_COUNT=0, TDS_DONE_ERROR=0
odbc.c:895:SQLMoreResults: result_type=4046, row_count=-1, lastrc=0
mem.c:648:tds_free_all_results()
odbc.c:906:SQLMoreResults: row_status=0
odbc.c:908:SQLMoreResults: row_count=-1, lastrc=0
odbc.c:4078:SQLFreeHandle(3, 0xodbc.c:1789:SQLAllocStmt(0x12f84a0, 0x1323fa0)
odbc.c:1684:_SQLAllocStmt(0x12f84a0, 0x1323fa0)
odbc.c:4513:SQLGetStmtAttr(0x1325c10, 10010, 0x7ffd7d6d2d98, 8, (nil))
odbc.c:4513:SQLGetStmtAttr(0x1325c10, 10011, 0x7ffd7d6d2d98, 8, (nil))
odbc.c:4513:SQLGetStmtAttr(0x1325c10, 10012, 0x7ffd7d6d2d98, 8, (nil))
odbc.c:4513:SQLGetStmtAttr(0x1325c10, 10013, 0x7ffd7d6d2d98, 8, (nil))
odbc_export.h:263:SQLExecDirect(0x1325c10, SELECT 1;, -3)
prepare_query.c:198:parsing 0 parameters
odbc.c:3283:_SQLExecute(0x1325c10)
odbc.c:3300:_SQLExecute() starting with state 5
error.c:414:odbc_errs_add: "Communication link failure"
error_export.h:6:SQLGetDiagRec(3, 0x1325c10, 1, 0x7ffd7d6d28a0, 0x7ffd7d6d2894, 0x7ffd7d6d28b0, 512, 0x7ffd7d6d2898)
error.c:565:SQLGetDiagRec: "[FreeTDS][SQL Server]Communication link failure"
error_export.h:6:SQLGetDiagRec(3, 0x1325c10, 2, 0x7ffd7d6d28a0, 0x7ffd7d6d2894, 0x7ffd7d6d28b0, 512, 0x7ffd7d6d2898)
error_export.h:6:SQLGetDiagRec(3, 0x1325c10, 1, 0x7ffd7d6d2e20, 0x7ffd7d6d2a0c, 0x7ffd7d6d2a1c, 1004, 0x7ffd7d6d2a0a)
error.c:565:SQLGetDiagRec: "[FreeTDS][SQL Server]Communication link failure"
error_export.h:6:SQLGetDiagRec(3, 0x1325c10, 2, 0x7ffd7d6d2e20, 0x7ffd7d6d2a0c, 0x7ffd7d6d2a4b, 957, 0x7ffd7d6d2a0a)
odbc.c:4078:SQLFreeHandle(3, 0x1325c10)
odbc.c:4179:_SQLFreeStmt(0x1325c10, 1, 0)
odbc.c:1789:SQLAllocStmt(0x12f84a0, 0x1323fa0)
odbc.c:1684:_SQLAllocStmt(0x12f84a0, 0x1323fa0)
odbc.c:4513:SQLGetStmtAttr(0x1325c10, 10010, 0x7ffd7d6d2d98, 8, (nil))
odbc.c:4513:SQLGetStmtAttr(0x1325c10, 10011, 0x7ffd7d6d2d98, 8, (nil))
odbc.c:4513:SQLGetStmtAttr(0x1325c10, 10012, 0x7ffd7d6d2d98, 8, (nil))
odbc.c:4513:SQLGetStmtAttr(0x1325c10, 10013, 0x7ffd7d6d2d98, 8, (nil))
odbc_export.h:263:SQLExecDirect(0x1325c10, SELECT 1;, -3)`

and last error log goes on repeatedly, I hope i will help to understand the problem @freddy77

**Comment by freddy77** [comment]
This error should indicate that the server closed the connection and you are keeping sending the same query.

From the log it seems (beside missing the end of lines) that there's an hole:

mem.c:648:tds_free_all_results() odbc.c:906:SQLMoreResults: row_status=0 odbc.c:908:SQLMoreResults: row_count=-1, lastrc=0 odbc.c:4078:SQLFreeHandle(3, 0xodbc.c:1789:SQLAllocStmt(0x12f84a0, 0x1323fa0) odbc.c:1684:_SQLAllocStmt(0x12f84a0, 0x1323fa0) odbc.c:4513:SQLGetStmtAttr(0x1325c10, 10010, 0x7ffd7d6d2d98, 8, (nil)) 

The "SQLFreeHandle(3, 0x" should not continue with a "odbc.c:...". Maybe the missing log contained at least who closed the connection. Would be useful to enable raw network data in the log but could be pretty verbose on production.

**Comment by Veerbhadra277** [comment]
Thanks @freddy77  for quick reply,
Please find some more detail TDSDUMP below, also i have send complete TDSDUMP on your mail id (freddy77@gmail.com) as it is bit heavy.


`util.c:165:Changed query state from READING to PENDING
odbc.c:3630:odbc_process_tokens: tds_process_tokens returned 0
odbc.c:3631:    result_type=4049, TDS_DONE_COUNT=0, TDS_DONE_ERROR=0
odbc.c:3703:odbc_process_tokens: returning result_type 4049
odbc.c:3452:_SQLExecute: odbc_process_tokens returned result_type 4049
token.c:549:tds_process_tokens(0x15807b0, 0x7ffe323e3980, 0x7ffe323e3984, 0x6914)
util.c:165:Changed query state from PENDING to READING
token.c:564:processing result tokens.  marker is  d1(ROW)
token.c:680:tds_process_tokens::SET_RETURN stopping on current token
util.c:165:Changed query state from READING to PENDING
odbc.c:3630:odbc_process_tokens: tds_process_tokens returned 0
odbc.c:3631:    result_type=4040, TDS_DONE_COUNT=0, TDS_DONE_ERROR=0
odbc.c:3703:odbc_process_tokens: returning result_type 4040
odbc.c:3452:_SQLExecute: odbc_process_tokens returned result_type 4040
odbc.c:4545:SQLNumResultCols(0x15a7c50, 0x7ffe323e3712)
odbc.c:4625:_SQLRowCount(0x15a7c50, 0x7ffe323e3718),  -1 rows 
odbc.c:4636:SQLRowCount returns 0, row count -1
odbc_export.h:195:SQLDescribeCol(0x15a7c50, 1, 0x7ffe323e3170, 255, 0x7ffe323e3140, 0x7ffe323e3142, 0x7ffe323e3148, 0x7ffe323e3144, 0x7ffe323e3146)
odbc.c:1803:SQLBindCol(0x15a7c50, 1, -16, 0x156fd90, 4, 0x155af70)
odbc.c:4033:SQLFetch(0x15a7c50)
odbc.c:3768:_SQLFetch(0x15a7c50, 1, 0)
token.c:549:tds_process_tokens(0x15807b0, 0x7ffe323e3000, 0x7ffe323e3004, 0x6508)
util.c:165:Changed query state from PENDING to READING
token.c:564:processing result tokens.  marker is  d1(ROW)
token.c:1951:tds_process_row(): reading column 0 
data.c:534:tds_get_data: type 56, varint size 0
data.c:587:tds_get_data(): wire column size is 4 
util.c:165:Changed query state from READING to PENDING
odbc.c:3630:odbc_process_tokens: tds_process_tokens returned 0
odbc.c:3631:    result_type=4040, TDS_DONE_COUNT=0, TDS_DONE_ERROR=0
odbc.c:3703:odbc_process_tokens: returning result_type 4040
convert_tds2sql.c:241:odbc_tds2sql: src is 56 dest = -16
odbc.c:4033:SQLFetch(0x15a7c50)
odbc.c:3768:_SQLFetch(0x15a7c50, 1, 0)
token.c:549:tds_process_tokens(0x15807b0, 0x7ffe323e3000, 0x7ffe323e3004, 0x6508)
util.c:165:Changed query state from PENDING to READING
token.c:564:processing result tokens.  marker is  fd(DONE)
token.c:2080:tds_process_end: more_results = 0
		was_cancelled = 0
		error = 0
		done_count_valid = 1
token.c:2097:                rows_affected = 1
token.c:2100:tds_process_end() state set to TDS_IDLE
util.c:165:Changed query state from READING to IDLE
util.c:83:logic error: cannot change query state from IDLE to PENDING
util.c:165:Changed query state from IDLE to IDLE
odbc.c:3630:odbc_process_tokens: tds_process_tokens returned 0
odbc.c:3631:    result_type=4052, TDS_DONE_COUNT=10, TDS_DONE_ERROR=0
odbc.c:3673:odbc_process_tokens: row_count=1
odbc.c:3900:SQLFetch: NO_DATA_FOUND
odbc.c:869:SQLMoreResults(0x15a7c50)
token.c:549:tds_process_tokens(0x15807b0, 0x7ffe323e3180, 0x7ffe323e3184, 0x15914)
token.c:552:tds_process_tokens() state is COMPLETED
odbc.c:3630:odbc_process_tokens: tds_process_tokens returned 1
odbc.c:3631:    result_type=4052, TDS_DONE_COUNT=0, TDS_DONE_ERROR=0
odbc.c:895:SQLMoreResults: result_type=4046, row_count=-1, lastrc=0
mem.c:648:tds_free_all_results()
odbc.c:906:SQLMoreResults: row_status=0
odbc.c:908:SQLMoreResults: row_count=-1, lastrc=0
odbc.c:4078:SQLFreeHandle(3, 0x15a7c50)
odbc.c:4179:_SQLFreeStmt(0x15a7c50, 1, 0)
odbc.c:1789:SQLAllocStmt(0x157f4a0, 0x15aafa0)
odbc.c:1684:_SQLAllocStmt(0x157f4a0, 0x15aafa0)
odbc.c:4513:SQLGetStmtAttr(0x15a7c50, 10010, 0x7ffe323e3ae8, 8, (nil))
odbc.c:4513:SQLGetStmtAttr(0x15a7c50, 10011, 0x7ffe323e3ae8, 8, (nil))
odbc.c:4513:SQLGetStmtAttr(0x15a7c50, 10012, 0x7ffe323e3ae8, 8, (nil))
odbc.c:4513:SQLGetStmtAttr(0x15a7c50, 10013, 0x7ffe323e3ae8, 8, (nil))
odbc_export.h:263:SQLExecDirect(0x15a7c50, SELECT 1;, -3)
prepare_query.c:198:parsing 0 parameters
odbc.c:3283:_SQLExecute(0x15a7c50)
odbc.c:3300:_SQLExecute() starting with state 0
mem.c:648:tds_free_all_results()
util.c:165:Changed query state from IDLE to WRITING
util.c:165:Changed query state from WRITING to PENDING
packet.c:740:Sending packet
0000 01 01 00 1a 00 00 01 00-53 00 45 00 4c 00 45 00 |........ S.E.L.E.|
0010 43 00 54 00 20 00 31 00-3b 00                   |C.T. .1. ;.|

tls.c:174:GNUTLS: level 5:
  REC[0x15a50b0]: Preparing Packet Application Data(23) with length: 26 and min pad: 0
tls.c:174:GNUTLS: level 9:
  ENC[0x15a50b0]: cipher: AES-256-CBC, MAC: SHA384, Epoch: 1
tls.c:174:GNUTLS: level 11:
  WRITE: enqueued 101 bytes for 0x15807b0. Total 101 bytes.
tls.c:174:GNUTLS: level 11:
  WRITE FLUSH: 101 bytes in buffer.
tls.c:151:in tds_push_func
tls.c:174:GNUTLS: level 11:
  WRITE: wrote 101 bytes, 0 bytes left.
tls.c:174:GNUTLS: level 5:
  REC[0x15a50b0]: Sent Packet[4481] Application Data(23) in epoch 1 and length: 101
token.c:549:tds_process_tokens(0x15807b0, 0x7ffe323e3980, 0x7ffe323e3984, 0x6914)
util.c:165:Changed query state from PENDING to READING
tls.c:128:in tds_pull_func
tls.c:174:GNUTLS: level 10:
  READ: Got 5 bytes from 0x15807b0
tls.c:174:GNUTLS: level 10:
  READ: read 5 bytes from 0x15807b0
tls.c:174:GNUTLS: level 10:
  RB: Have 0 bytes into buffer. Adding 5 bytes.
tls.c:174:GNUTLS: level 10:
  RB: Requested 5 bytes
tls.c:174:GNUTLS: level 5:
  REC[0x15a50b0]: SSL 3.3 Application Data packet received. Epoch 0, length: 96
tls.c:174:GNUTLS: level 5:
  REC[0x15a50b0]: Expected Packet Application Data(23)
tls.c:174:GNUTLS: level 5:
  REC[0x15a50b0]: Received Packet Application Data(23) with length: 96
tls.c:128:in tds_pull_func
tls.c:174:GNUTLS: level 10:
  READ: Got 96 bytes from 0x15807b0
tls.c:174:GNUTLS: level 10:
  READ: read 96 bytes from 0x15807b0
tls.c:174:GNUTLS: level 10:
  RB: Have 5 bytes into buffer. Adding 96 bytes.
tls.c:174:GNUTLS: level 10:
  RB: Requested 101 bytes
tls.c:174:GNUTLS: level 5:
  REC[0x15a50b0]: Decrypted Packet[4479] Application Data(23) with length: 31
packet.c:639:Received packet
0000 04 01 00 1f 00 66 01 00-81 01 00 00 00 20 00 38 |.....f.. ..... .8|
0010 00 d1 01 00 00 00 fd 10-00 c1 00 01 00 00 00    |........ .......|

token.c:564:processing result tokens.  marker is  81(TDS7_RESULT)
token.c:1573:processing TDS7 result metadata.
mem.c:648:tds_free_all_results()
token.c:1598:set current_results (1 column) to tds->res_info
token.c:1605:setting up 1 columns
token.c:1542:tds7_get_data_info: 
	colname = 
	type = 56 (int)
	server's type = 56 (int)
	column_varint_size = 0
	column_size = 4 (4 on server)
token.c:1614: name                 size/wsize      type/wtype      utype  
token.c:1615: -------------------- --------------- --------------- -------
token.c:1620:                            4/4            56/56            0
util.c:165:Changed query state from READING to PENDING
odbc.c:3630:odbc_process_tokens: tds_process_tokens returned 0
odbc.c:3631:    result_type=4049, TDS_DONE_COUNT=0, TDS_DONE_ERROR=0
odbc.c:3703:odbc_process_tokens: returning result_type 4049
odbc.c:3452:_SQLExecute: odbc_process_tokens returned result_type 4049
token.c:549:tds_process_tokens(0x15807b0, 0x7ffe323e3980, 0x7ffe323e3984, 0x6914)
util.c:165:Changed query state from PENDING to READING
token.c:564:processing result tokens.  marker is  d1(ROW)
token.c:680:tds_process_tokens::SET_RETURN stopping on current token
util.c:165:Changed query state from READING to PENDING
odbc.c:3630:odbc_process_tokens: tds_process_tokens returned 0
odbc.c:3631:    result_type=4040, TDS_DONE_COUNT=0, TDS_DONE_ERROR=0
odbc.c:3703:odbc_process_tokens: returning result_type 4040
odbc.c:3452:_SQLExecute: odbc_process_tokens returned result_type 4040
odbc.c:4545:SQLNumResultCols(0x15a7c50, 0x7ffe323e3712)
odbc.c:4625:_SQLRowCount(0x15a7c50, 0x7ffe323e3718),  -1 rows 
odbc.c:4636:SQLRowCount returns 0, row count -1
odbc_export.h:195:SQLDescribeCol(0x15a7c50, 1, 0x7ffe323e3170, 255, 0x7ffe323e3140, 0x7ffe323e3142, 0x7ffe323e3148, 0x7ffe323e3144, 0x7ffe323e3146)
odbc.c:1803:SQLBindCol(0x15a7c50, 1, -16, 0x1574050, 4, 0x155af70)
odbc.c:4033:SQLFetch(0x15a7c50)
odbc.c:3768:_SQLFetch(0x15a7c50, 1, 0)
token.c:549:tds_process_tokens(0x15807b0, 0x7ffe323e3000, 0x7ffe323e3004, 0x6508)
util.c:165:Changed query state from PENDING to READING
token.c:564:processing result tokens.  marker is  d1(ROW)
token.c:1951:tds_process_row(): reading column 0 
data.c:534:tds_get_data: type 56, varint size 0
data.c:587:tds_get_data(): wire column size is 4 
util.c:165:Changed query state from READING to PENDING
odbc.c:3630:odbc_process_tokens: tds_process_tokens returned 0
odbc.c:3631:    result_type=4040, TDS_DONE_COUNT=0, TDS_DONE_ERROR=0
odbc.c:3703:odbc_process_tokens: returning result_type 4040
convert_tds2sql.c:241:odbc_tds2sql: src is 56 dest = -16
odbc.c:4033:SQLFetch(0x15a7c50)
odbc.c:3768:_SQLFetch(0x15a7c50, 1, 0)
token.c:549:tds_process_tokens(0x15807b0, 0x7ffe323e3000, 0x7ffe323e3004, 0x6508)
util.c:165:Changed query state from PENDING to READING
token.c:564:processing result tokens.  marker is  fd(DONE)
token.c:2080:tds_process_end: more_results = 0
		was_cancelled = 0
		error = 0
		done_count_valid = 1
token.c:2097:                rows_affected = 1
token.c:2100:tds_process_end() state set to TDS_IDLE
util.c:165:Changed query state from READING to IDLE
util.c:83:logic error: cannot change query state from IDLE to PENDING
util.c:165:Changed query state from IDLE to IDLE
odbc.c:3630:odbc_process_tokens: tds_process_tokens returned 0
odbc.c:3631:    result_type=4052, TDS_DONE_COUNT=10, TDS_DONE_ERROR=0
odbc.c:3673:odbc_process_tokens: row_count=1
odbc.c:3900:SQLFetch: NO_DATA_FOUND
odbc.c:869:SQLMoreResults(0x15a7c50)
token.c:549:tds_process_tokens(0x15807b0, 0x7ffe323e3180, 0x7ffe323e3184, 0x15914)
token.c:552:tds_process_tokens() state is COMPLETED
odbc.c:3630:odbc_process_tokens: tds_process_tokens returned 1
odbc.c:3631:    result_type=4052, TDS_DONE_COUNT=0, TDS_DONE_ERROR=0
odbc.c:895:SQLMoreResults: result_type=4046, row_count=-1, lastrc=0
mem.c:648:tds_free_all_results()
odbc.c:906:SQLMoreResults: row_status=0
odbc.c:908:SQLMoreResults: row_count=-1, lastrc=0
odbc.c:4078:SQLFreeHandle(3, 0xodbc.c:1789:SQLAllocStmt(0x12f84a0, 0x1323fa0)
odbc.c:1684:_SQLAllocStmt(0x12f84a0, 0x1323fa0)
odbc.c:4513:SQLGetStmtAttr(0x1325c10, 10010, 0x7ffd7d6d2d98, 8, (nil))
odbc.c:4513:SQLGetStmtAttr(0x1325c10, 10011, 0x7ffd7d6d2d98, 8, (nil))
odbc.c:4513:SQLGetStmtAttr(0x1325c10, 10012, 0x7ffd7d6d2d98, 8, (nil))
odbc.c:4513:SQLGetStmtAttr(0x1325c10, 10013, 0x7ffd7d6d2d98, 8, (nil))
odbc_export.h:263:SQLExecDirect(0x1325c10, SELECT 1;, -3)
prepare_query.c:198:parsing 0 parameters
odbc.c:3283:_SQLExecute(0x1325c10)
odbc.c:3300:_SQLExecute() starting with state 5
error.c:414:odbc_errs_add: "Communication link failure"
error_export.h:6:SQLGetDiagRec(3, 0x1325c10, 1, 0x7ffd7d6d28a0, 0x7ffd7d6d2894, 0x7ffd7d6d28b0, 512, 0x7ffd7d6d2898)
error.c:565:SQLGetDiagRec: "[FreeTDS][SQL Server]Communication link failure"
error_export.h:6:SQLGetDiagRec(3, 0x1325c10, 2, 0x7ffd7d6d28a0, 0x7ffd7d6d2894, 0x7ffd7d6d28b0, 512, 0x7ffd7d6d2898)
error_export.h:6:SQLGetDiagRec(3, 0x1325c10, 1, 0x7ffd7d6d2e20, 0x7ffd7d6d2a0c, 0x7ffd7d6d2a1c, 1004, 0x7ffd7d6d2a0a)
error.c:565:SQLGetDiagRec: "[FreeTDS][SQL Server]Communication link failure"
error_export.h:6:SQLGetDiagRec(3, 0x1325c10, 2, 0x7ffd7d6d2e20, 0x7ffd7d6d2a0c, 0x7ffd7d6d2a4b, 957, 0x7ffd7d6d2a0a)
odbc.c:4078:SQLFreeHandle(3, 0x1325c10)
odbc.c:4179:_SQLFreeStmt(0x1325c10, 1, 0)
odbc.c:1789:SQLAllocStmt(0x12f84a0, 0x1323fa0)
odbc.c:1684:_SQLAllocStmt(0x12f84a0, 0x1323fa0)
odbc.c:4513:SQLGetStmtAttr(0x1325c10, 10010, 0x7ffd7d6d2d98, 8, (nil))
odbc.c:4513:SQLGetStmtAttr(0x1325c10, 10011, 0x7ffd7d6d2d98, 8, (nil))
odbc.c:4513:SQLGetStmtAttr(0x1325c10, 10012, 0x7ffd7d6d2d98, 8, (nil))
odbc.c:4513:SQLGetStmtAttr(0x1325c10, 10013, 0x7ffd7d6d2d98, 8, (nil))
odbc_export.h:263:SQLExecDirect(0x1325c10, SELECT 1;, -3)
prepare_query.c:198:parsing 0 parameters
odbc.c:3283:_SQLExecute(0x1325c10)`

Thanks,
Veer

**Comment by Veerbhadra277** [comment]
[freetds.zip](https://github.com/FreeTDS/freetds/files/1077888/freetds.zip)

**Comment by Veerbhadra277** [comment]
@freddy77 did you got freeTDS logs? did you found anything?

**Comment by freddy77** [comment]
Hi, sorry for the late reply. The logs are quite useless. It seems that they are overwritten. What I suspect is that different processes are writing in the same file overwriting it. Maybe you didn't enable the "dump file append" option or that writing in a single file from multiple processes is broken. In the latter case you can set TDSDUMP to empty ("export TDSDUMP=" in bash) and the logs will be placed in /tmp as freetds.log.<PID>. These should be more helpful.

**Comment by freddy77** [comment]
Did you try what I suggested?
Do you still have connection issues?

**Comment by freddy77** [comment]
Closing. Please reopen with update information

**Comment by brobaniuc** [comment]
Hi,
I have the same issue, just that I know why the connection gets closed.
We use MSSQL cluster and for patching we move the instance to another node of MSSQL and after patching is done we move it back. This normally would take at top 5 seconds per operation.
Can we configure somehow to not drop the SQL connection completely. The Connection string it always remains the same,
Thanks, Bogdan R.
