### ISSUE TITLE
offline installation git log error

### ISSUE THREAD

**Issue by jtan25** [FreeTDS/freetds#128]
Due to one my machines being offline, I downloaded the zip and tried to build from source. I am running into the following issues. Is there a way for me to make install without it being a git repo? Also  I have doxygen installed. 
![jtan25](https://user-images.githubusercontent.com/8901270/27400982-f0cdd6fa-568f-11e7-8fb1-fa814042c551.png)

**Comment by freddy77** [comment]
Weird, the file should be distributed to if you downloaded a tarball should be there. And if you are using git you should have git. Unless you downloaded tarball using a git snapshot, in this case possibly you have this issue.
You can download a recent master snapshot from ftp://ftp.freetds.org/pub/freetds/current/ or a "stable" one from ftp://ftp.freetds.org/pub/freetds/stable/

**Comment by jtan25** [comment]
issue resolved by downloading tarball, i had originally downloaded the github.zip
