### ISSUE TITLE
fisql doesn't properly handle GO within multi-line comment

### ISSUE THREAD

**Issue by craigahobbs** [FreeTDS/freetds#134]
1. Create a file, test.sql, with the following contents:

```
/*
select * from foo
go
*/
```
2. Execute the following command:

```
fisql -S localhost -U username -P password -i test.sql
```
Expected: No error
Actual: Error

> 1>> /*
> 2>> select * from foo
> 3>> go
> Msg 113, Level 15, State 1:
> Server 'craigh', Line 3:
> Missing end comment mark '*/'.
> DB-LIBRARY error:
> 	General SQL Server error: Check messages from the SQL Server
> 1>> */
>

**Comment by freddy77** [comment]
Fixed in master. Did a bit of refactory of the code, mostly split the big main function and fixed some issues with some commands.
