### ISSUE TITLE
Host releases via HTTP

### ISSUE THREAD

**Issue by l8nite** [FreeTDS/freetds#135]
We're running into issues with our corporate network ACL's interfering with the high-numbered ports required for transferring the FreeTDS releases via FTP. Would it be possible to have your releases hosted on an HTTP mirror and/or Github Downloads directly?

**Comment by freddy77** [comment]
Yes, you can use git and github but the official distros are still the ftp as they remove autoconf needs and use a more official version. Trying to configure the server, I need some admin support.

**Comment by freddy77** [comment]
Added support for HTTP on the software page
