### ISSUE TITLE
ODBC SQLTables call with wildcard arguments does not return results

### ISSUE THREAD

**Issue by gordthompson** [FreeTDS/freetds#136]
When I use the [tables](https://github.com/mkleehammer/pyodbc/wiki/Cursor#tablestablenone-catalognone-schemanone-tabletypenone) method of a pyodbc Cursor object to try and retrieve all tables in the database I get no results when using FreeTDS ODBC but I do get results when I use Microsoft's SQL Server ODBC driver for Linux. I'm using the same versions of unixODBC (2.3.1) and pyodbc (4.0.17); the only difference is the ODBC driver.

The python code is

```python
tbl_info = crsr.tables('%', '%', '%', 'TABLE').fetchall()
```

The ODBC call is the same for both drivers

```
[ODBC][19976][1501176660.859121][SQLTables.c][204]
        Entry:
            Statement = 0x28e4480
            Catalog Name = [%][length = 1 (SQL_NTS)]
            Schema Name = [%][length = 1 (SQL_NTS)]
            Table Name = [%][length = 1 (SQL_NTS)]
            Table Type = [TABLE][length = 5 (SQL_NTS)]
[ODBC][19976][1501176660.862313][SQLTables.c][421]
        Exit:[SQL_SUCCESS]
```

but SQL Profiler shows that the call results in a different command being sent to the server. 

For Microsoft's ODBC driver it is

```sql
exec [sys].sp_tableswc N'%',N'%',N'%',N'''TABLE''',@fUsePattern=1
```

while FreeTDS ODBC sends

```sql
sp_tables @table_name='', @table_owner='', @table_qualifier='%' 
```

When I use FreeTDS ODBC to invoke the `tables` method with no arguments

```python
tbl_info = crsr.tables().fetchall()
```

the ODBC call is

```
[ODBC][20538][1501178750.402408][SQLTables.c][204]
        Entry:
            Statement = 0x1544800
            Catalog Name = [NULL]
            Schema Name = [NULL]
            Table Name = [NULL]
            Table Type = [NULL]
[ODBC][20538][1501178750.793568][SQLTables.c][421]
        Exit:[SQL_SUCCESS]
```

and FreeTDS ODBC sends the SQL call

```sql
exec sp_tables 
```

which returns just the information for the current catalog (database), as one might expect.

I confirmed this behaviour with the latest stable version of FreeTDS (1.00.48).

**Comment by freddy77** [comment]
That's actually weird, there is specific code to use sp_tablewc to support wildcards (wc) getting tables. Are you sure you are using the right protocol version?

**Comment by gordthompson** [comment]
I hadn't specified a TDS version because `tsql -C` told me that the default version was `auto`, specifically

~~~
Compile-time settings (established with the "configure" script)
                            Version: freetds v1.00.48
             freetds.conf directory: /usr/local/etc
     MS db-lib source compatibility: yes
        Sybase binary compatibility: no
                      Thread safety: yes
                      iconv library: yes
                        TDS version: auto
                              iODBC: no
                           unixodbc: yes
              SSPI "trusted" logins: no
                           Kerberos: no
                            OpenSSL: no
                             GnuTLS: no
                               MARS: no
~~~

So I tried again with a simplified version of my test script that included version 7.3 in the connection string

~~~python
from pprint import pprint
import pyodbc
print("pyodbc version " + pyodbc.version)
conn_str = (
	'Driver=FreeTDS;'
	'Server=192.168.1.114;'
	'Port=49242;'
	'TDS_Version=7.3;'
	'Database=myDb;'
	'UID=sa;PWD=whatever;'
	)
cnxn = pyodbc.connect(conn_str, autocommit=True)
print("FreeTDS version " + cnxn.getinfo(pyodbc.SQL_DRIVER_VER))
crsr = cnxn.cursor()
tbl_info = crsr.tables('%', '%', '%', 'TABLE').fetchall()
print("crsr.tables('%', '%', '%', 'TABLE') returned {} row(s):".format(len(tbl_info)))
pprint(tbl_info)
crsr.close()
cnxn.close()
~~~

producing

~~~
pyodbc version 4.0.17
FreeTDS version 01.00.0048
crsr.tables('%', '%', '%', 'TABLE') returned 6 row(s):
[('master', None, None, None, None),
 ('msdb', None, None, None, None),
 ('myDb', None, None, None, None),
 ('ReportServer$SQLEXPRESS', None, None, None, None),
 ('ReportServer$SQLEXPRESSTempDB', None, None, None, None),
 ('tempdb', None, None, None, None)]
~~~

I double-checked SQL Profiler to confirm that the command being sent was still

~~~sql
exec sp_tables @table_name=N'',@table_owner=N'',@table_qualifier=N'%'
~~~

**Comment by freddy77** [comment]
Can you enable odbc trace and check the SQLTables/SQLTablesW call?
I think the TDSDUMP should contain the same information too (and much more).

**Comment by freddy77** [comment]
I tried to reproduce with a C test (changing tables.c test).
The test passed, the query executed is, correctly, sp_tableswc, using both master and Branch-1_00.
Looking at the code the usage of sp_tableswc requires:
- using ODBC version 3. Looked at pyodbc code and it uses only version 3;
- having METADATA_ID attribute set to FALSE (the default). pyodbc don't set this option;
- using wildcard in catalog name, which is the case ('%' in catalog name);
- using a Microsoft database (you are using, I can see from the log);
- using a server version starting from SQL 2000 (and I can see from the logs you are using surely SQL 2008).

I'll check better the logs tomorrow.

**Comment by gordthompson** [comment]
Thanks for looking into this. As a check, I just tested with the latest nightly snapshot and the output from my script was the same except that it said

~~~
FreeTDS version 01.00.0194
~~~

instead of

~~~
FreeTDS version 01.00.0048
~~~

**Comment by freddy77** [comment]
The 01.00.194 version is weird and wrong if based on master.
Beside that I found and fixed the mistake. SQL_NTS and some other combination caused the problem.
Tests are running now but no reason why they should fail (did manual tests on the specific case).
