### ISSUE TITLE
FreeTDS fails to compile on OpenVMS

### ISSUE THREAD

**Issue by bryancl** [FreeTDS/freetds#138]
When trying to install Freetds with Compaq C V6.5-001 on OpenVMS Alpha V7.3-2, I get the following error:
$ MMS/MACRO="ODBC"=1/EXTENDED_SYNTAX

CC/DECC /DEFINE=("UNIXODBC","_THREAD_SAFE"=1)/PREFIX=(ALL)/FLOAT=IEEE/IEEE=DENORM/OBJECT=[.SRC.TDS]BULK.OBJ /NAMES=(AS_IS,SHORTENED) /INCLUDE=("./","./include",[.src.odbc],ODBC_INCDIR) [.SRC.TDS]BULK.C

static inline void tds_raw_mutex_lock(tds_raw_mutex *mtx)
..............^
%CC-E-NOSEMI, Missing ";".
at line number 36 in file DISK10:[xxx.FREETDS.FREETDS-1_00_48.INCLUDE.FREETDS]THREAD.H;1
...

This project obviously builds and runs elsewhere, yet I cannot see what is causing this error (even with full expanded listings), nor can I isolate it by simplifying the source.  Is this a recognized problem?  Are there any further suggestions on resolving this problem?

**Comment by freddy77** [comment]
2017-08-07 8:19 GMT+01:00 bryancl <notifications@github.com>:

> When trying to install Freetds with Compaq C V6.5-001 on OpenVMS Alpha
> V7.3-2, I get the following error:
> $ MMS/MACRO="ODBC"=1/EXTENDED_SYNTAX
>
> CC/DECC /DEFINE=("UNIXODBC","_THREAD_SAFE"=1)/PREFIX=(ALL)/FLOAT=
> IEEE/IEEE=DENORM/OBJECT=[.SRC.TDS]BULK.OBJ /NAMES=(AS_IS,SHORTENED)
> /INCLUDE=("./","./include",[.src.odbc],ODBC_INCDIR) [.SRC.TDS]BULK.C
>
> static inline void tds_raw_mutex_lock(tds_raw_mutex *mtx)
> ..............^
> %CC-E-NOSEMI, Missing ";".
> at line number 36 in file DISK10:[xxx.FREETDS.FREETDS-1_
> 00_48.INCLUDE.FREETDS]THREAD.H;1
> ...
>
> This project obviously builds and runs elsewhere, yet I cannot see what is
> causing this error (even with full expanded listings), nor can I isolate it
> by simplifying the source. Is this a recognized problem? Are there any
> further suggestions on resolving this problem?
>
> Is it the only error? Does it compile successfully other sources?
Is not clear the offending code. Does the compiler support inline?

Frediano

**Comment by bryancl** [comment]
Frediano,
The compiler is the same version as the one listed in the documentation that came with the source.  I personally do not use “inline” so I have not verified that it is supported.  However, it appears not.  Apologies for not picking up such an obvious cause.  Tunnel vision I guess. I will check out our latest layered products disks are a later compiler.


Regards,
Bryan C

**Comment by bryancl** [comment]
Frediano,
I have sorted out the issue with “inline” by using the qualifier /ACCEPT=C99_KEYWORDS when compiling, but then I am unsure what to do with the macros

I1             20518 # define TDS_UNLIKELY(x)            (x)
I1             21686 #define TDSDUMP_LOG_FAST if (TDS_UNLIKELY(tds_write_dump)) tdsdump_log
I1             21687 #define tdsdump_log TDSDUMP_LOG_FAST

which seem to cause the following error (multiple times):

                  22882 tdsdump_log(TDS_DBG_FUNC, "tds7_build_bulk_insert_stmt(%p, %p, %p, %d)\n", tds, clause, bcpcol, first);
                                ........1
%CC-E-BADMCRORECURS, (1) Recursive expansion of macro "tdsdump_log" exceeded 1024 levels and was terminated.

       E        if ((tds_write_dump)) if ((tds_write_dump)) if ((tds_write_dump)) if ((tds_write_dump)) if ((tds_write_dump)) if (
       E      (tds_write_dump)) if ((tds_write_dump)) if ((tds_write_dump)) if ((tds_write_dump)) if ((tds_write_dump)) if ((tds_w
       E      rite_dump)) if ((tds_write_dump)) if ((tds_write_dump)) if ((tds_write_dump)) if ((tds_write_dump)) if ((tds_write_d


Any suggestions how this macro substitution can be limited?  Otherwise Iwill just disable it totally.


Regards,
Bryan C

From: Bryan Claire
Sent: Tuesday, 8 August 2017 5:40 PM
To: 'FreeTDS/freetds' <reply@reply.github.com>
Subject: RE: [FreeTDS/freetds] FreeTDS fails to compile on OpenVMS (#138)

Frediano,
The compiler is the same version as the one listed in the documentation that came with the source.  I personally do not use “inline” so I have not verified that it is supported.  However, it appears not.  Apologies for not picking up such an obvious cause.  Tunnel vision I guess. I will check out our latest layered products disks are a later compiler.


Regards,
Bryan C

**Comment by bryancl** [comment]
And I see that string_to_result has the same problem:

CC/DECC/ACCEPT=C99_KEYWORDS /DEFINE=("UNIXODBC","_THREAD_SAFE"=1)/PREFIX=(ALL)/FLOAT=IEEE/IEEE=DENORM/OBJECT=[.SRC.TDS]CONVERT.OBJ /NAMES=(AS_IS,SHORTENED) /INCLUDE=("./"
,"./include",[.src.odbc],ODBC_INCDIR) [.SRC.TDS]CONVERT.C

                return string_to_result(tmp_str, cr);
.......................^
%CC-W-TOOMANYACTLS, Too many actual parameters in the invocation of the macro "string_to_result".
at line number 635 in file DISK10:[xxxxxx.WORK.FREETDS.FREETDS-1_00_48.SRC.TDS]CONVERT.C;1

                return string_to_result(tmp_str, cr);
.......................^
%CC-E-BADMCRORECURS, Recursive expansion of macro "string_to_result" exceeded 1024 levels and was terminated.
at line number 635 in file DISK10:[xxxxxx.WORK.FREETDS.FREETDS-1_00_48.SRC.TDS]CONVERT.C;1


What compiler should I be using for this code?


Regards,
Bryan C

From: Bryan Claire
Sent: Friday, 11 August 2017 6:34 AM
To: 'FreeTDS/freetds' <reply@reply.github.com>
Subject: RE: [FreeTDS/freetds] FreeTDS fails to compile on OpenVMS (#138)

Frediano,
I have sorted out the issue with “inline” by using the qualifier /ACCEPT=C99_KEYWORDS when compiling, but then I am unsure what to do with the macros

I1             20518 # define TDS_UNLIKELY(x)            (x)
I1             21686 #define TDSDUMP_LOG_FAST if (TDS_UNLIKELY(tds_write_dump)) tdsdump_log
I1             21687 #define tdsdump_log TDSDUMP_LOG_FAST

which seem to cause the following error (multiple times):

                  22882 tdsdump_log(TDS_DBG_FUNC, "tds7_build_bulk_insert_stmt(%p, %p, %p, %d)\n", tds, clause, bcpcol, first);
                                ........1
%CC-E-BADMCRORECURS, (1) Recursive expansion of macro "tdsdump_log" exceeded 1024 levels and was terminated.

       E        if ((tds_write_dump)) if ((tds_write_dump)) if ((tds_write_dump)) if ((tds_write_dump)) if ((tds_write_dump)) if (
       E      (tds_write_dump)) if ((tds_write_dump)) if ((tds_write_dump)) if ((tds_write_dump)) if ((tds_write_dump)) if ((tds_w
       E      rite_dump)) if ((tds_write_dump)) if ((tds_write_dump)) if ((tds_write_dump)) if ((tds_write_dump)) if ((tds_write_d


Any suggestions how this macro substitution can be limited?  Otherwise Iwill just disable it totally.


Regards,
Bryan C

From: Bryan Claire
Sent: Tuesday, 8 August 2017 5:40 PM
To: 'FreeTDS/freetds' <reply@reply.github.com>
Subject: RE: [FreeTDS/freetds] FreeTDS fails to compile on OpenVMS (#138)

Frediano,
The compiler is the same version as the one listed in the documentation that came with the source.  I personally do not use “inline” so I have not verified that it is supported.  However, it appears not.  Apologies for not picking up such an obvious cause.  Tunnel vision I guess. I will check out our latest layered products disks are a later compiler.


Regards,
Bryan C

**Comment by freddy77** [comment]
I would say you need a not buggy and a bit more recent one. Buggy as preprocessor macro does not expand recursively so your preprocessor is buggy. More recent as inline is defined by C99 although mostly implementations added it a decade before. inline can be worked around by a "#define inline".

**Comment by bryancl** [comment]
This is strange, because I am using what is listed in the documentation.  I also get the same result with HP C V7.3-009 on OpenVMS Alpha V8.4 which is about as recent as I can get.

So looking at the #defines involved here, apart from TDS_UNLIKELY they are object type defines which result in a simple text substitution.

Are you using a non-HP complier?  If so, I would be interested to check it out.


Regards,
Bryan C

**Comment by freddy77** [comment]
Sorry for the delay. Craig A. Berry is supporting the OpenVMS port. I don't a OpenVMS machine to test. You can try contacting Craig directly (you can find his contact email on the logs).

**Comment by bryancl** [comment]
No, we have redesigned the application to remove the need for ODBC altogether .


Regards,
Bryan C

**Comment by freddy77** [comment]
Your compiler is not C compatible, closing the issue. FreeTDS is a C project.

**Comment by bryancl** [comment]
The compiler I am using is the standard compiler supplied with OpenVMS by HP.  I have tried compilers supplied with both 7.3-2 and 8.4, so I do not see how they can be “not C compatible”.

Regards,
Bryan C

**Comment by freddy77** [comment]
Preprocessor macros do not expand recursively in C.
