### ISSUE TITLE
Remove include roken.h show

### ISSUE THREAD

**Issue by inode64** [FreeTDS/freetds#139]
Show this error when I have installed heimdal, I search in the code and I don't found any references to this classes or functions.

Show report in gentoo:
https://bugs.gentoo.org/show_bug.cgi?id=585592

-------------------------------------------------------
/bin/sh ../../libtool  --tag=CC   --mode=compile x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I../../include  -I../../include -DUNIXODBC -DHAVE_UNISTD_H -DHAVE_PWD_H -DHAVE_SYS_TYPES_H -DHAVE_LONG_LONG -DSIZEOF_LONG_INT=8 -I/usr/include  -D_REENTRANT -D_THREAD_SAFE -DDEBUG=1 -Wall -Wstrict-prototypes -Wmissing-prototypes -Wno-long-long -Wpointer-arith -pthread -O2 -pipe -march=nehalem  -Wdeclaration-after-statement -c -o threadsafe.lo threadsafe.c
libtool: compile:  x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I../../include -I../../include -DUNIXODBC -DHAVE_UNISTD_H -DHAVE_PWD_H -DHAVE_SYS_TYPES_H -DHAVE_LONG_LONG -DSIZEOF_LONG_INT=8 -I/usr/include -D_REENTRANT -D_THREAD_SAFE -DDEBUG=1 -Wall -Wstrict-prototypes -Wmissing-prototypes -Wno-long-long -Wpointer-arith -pthread -O2 -pipe -march=nehalem -Wdeclaration-after-statement -c threadsafe.c  -fPIC -DPIC -o .libs/threadsafe.o
In file included from ../../include/freetds/tds.h:55:0,
                 from threadsafe.c:73:
../../include/replacements.h:79:0: aviso: se redefinió "strlcpy"
 #define strlcpy(d,s,l) tds_strlcpy(d,s,l)
 ^
In file included from threadsafe.c:65:0:
/usr/include/roken.h:146:0: nota: esta es la ubicación de la definición previa
 #define strlcpy rk_strlcpy
 ^
In file included from ../../include/freetds/tds.h:55:0,
                 from threadsafe.c:73:
../../include/replacements.h:109:0: aviso: se redefinió "strlcat"
 #define strlcat(d,s,l) tds_strlcat(d,s,l)
 ^
In file included from threadsafe.c:65:0:
/usr/include/roken.h:149:0: nota: esta es la ubicación de la definición previa
 #define strlcat rk_strlcat
 ^
In file included from threadsafe.c:73:0:
../../include/freetds/tds.h:150:2: aviso: la declaración de la función no es un prototipo [-Wstrict-prototypes]
  TDS_USMALLINT _res:10;
  ^
../../include/freetds/tds.h:150:2: error: el campo de bits ‘__res_state’ tiene un tipo inválido
make[4]: *** [Makefile:556: threadsafe.lo] Error 1

**Comment by freddy77** [comment]
Both fixed.
