### ISSUE TITLE
Build failures with LibreSSL

### ISSUE THREAD

**Issue by orlitzky** [FreeTDS/freetds#143]
We have a report on Gentoo of a build failure against LibreSSL:

https://bugs.gentoo.org/show_bug.cgi?id=621430

I found a similar report for FreeBSD (just search for "freetds" on the page):

https://wiki.freebsd.org/LibreSSL/Ports

The gist of it is,

```
tls.c:946:55: error: ‘TLS_ST_OK’ undeclared (first use in this function)
  ret = SSL_connect(con) != 1 || SSL_get_state(con) != TLS_ST_OK;
                                                       ^~~~~~~~~
```

I don't know how to fix it off the top of my head, but it looks like no one reported it here, so I might as well.

**Comment by freddy77** [comment]
Try this patch
```
diff --git a/src/tds/tls.c b/src/tds/tls.c
index 38e8228c..4d2c5159 100644
--- a/src/tds/tls.c
+++ b/src/tds/tls.c
@@ -95,6 +95,9 @@ BIO_get_data(const BIO *b)
        return b->ptr;
 }
 #define TLS_client_method TLSv1_client_method
+#endif
+
+#ifndef TLS_ST_OK
 #define TLS_ST_OK SSL_ST_OK
 #endif
 
```
but honestly also the warnings about not defined function are quite scary too.

**Comment by orlitzky** [comment]
I asked the reporter of the Gentoo bug to please try again with the patch, and he was nice enough to do it and post all of the information again from that run. Unfortunately, the build crashed somewhere else. This is the full build log for v1.00.53 with the above patch applied:

https://621430.bugs.gentoo.org/attachment.cgi?id=488790

I think the only "gotcha" with respect to our package is that we run autoreconf at the beginning.

**Comment by freddy77** [comment]
Could you try last master version?

**Comment by freddy77** [comment]
Found a machine to test. And a new small fix.

**Comment by orlitzky** [comment]
Thanks, I added a "live" version of the freetds ebuild in Gentoo that will pull from github's master branch. I'll report back if there are any problems.

**Comment by orlitzky** [comment]
It works, thanks again!
