### ISSUE TITLE
SQL Server 2017 Support

### ISSUE THREAD

**Issue by zzzeek** [FreeTDS/freetds#146]
I notice on the list archives at http://lists.ibiblio.org/pipermail/freetds/2017q2/030177.html that SQL Server 2017 is still a TODO (if I'm reading correctly).    SQL Server 2017 is now, at least for us linux folks, the most simple to run SQL Server ever, as you can [run the docker container](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker) and have a completely installed SQL Server with local network access running in 30 seconds.    This part works.

Basic TDS does not seem to work.   Freetds 0.95.81-1 on fedora:

```
tsql -H localhost -p 1401 -U scott -P scottspassword

locale is "en_US.UTF-8"
locale charset is "UTF-8"
using default charset "UTF-8"
129Error 20004 (severity 9):
	Read from the server failed
	OS error 115, "Operation now in progress"
Error 20002 (severity 9):
	Adaptive Server connection failed
There was a problem connecting to the server
```

I've tried a few TDSVER values but SQL Server 2017 just laughs at them.

**Comment by freddy77** [comment]
From this log it appears the server has no TCP socket open or is open not at port 1401.
You should check with a netstat command or similar.

**Comment by zzzeek** [comment]
Did all that.  however, I've upgraded my Fedora and started fresh and now it is working.
