### ISSUE TITLE
DATE type doesn't work with CT-lib

### ISSUE THREAD

**Issue by jalegido** [FreeTDS/freetds#147]
I would like to do this query in SQL Server 2012 or greater with ct-lib:
`select cast('2017-01-02' as date)`
When I use CT api with version CS_TDS_70 ct_describe always returns CS_DATAFMT.datatype as CS_CHAR_TYPE. This is right as DATE type was added in version 7.3

But when I use version CS_TDS_74 ct_describe returns CS_CHAR_TYPE because _ct_get_client_type returns CS_FAIL.

I'm debugging the code and I see that server column type is SYBMSDATE instead SYBDATE as we could wait. I think SYBMSDATE is procesed in dblib, but in ct-lib don't.

**Comment by freddy77** [comment]
Looks not straight forward to fix. Even the internal conversions (from libTDS to CTLib API) rely on cs_convert which handle CS_DATE_TYPE as having Sybase format (32 bit integer) while Microsoft format is completely different.

**Comment by jalegido** [comment]
Thanks.
have you the precise format Microsoft is using? If so, I can use it to process the value. In other case, I must use the string value to translate this type.

**Comment by freddy77** [comment]
Added support for it.

**Comment by jalegido** [comment]
I'll try test it next week.
Thank you very much.
