### ISSUE TITLE
Sqsh 2.5.16.1 wont compile vs Freetds

### ISSUE THREAD

**Issue by AssedoZion** [FreeTDS/freetds#150]
Hi,

I'm failing to compile sqsh in front of FreeTds :
The version of sqsh is 2.5.16.1
The version of FreeTds is 0.91
The version of Sybase is 15.5
The system is a HP UX 11i
I did exactly what was specified : 
Modified the global variable $SYBASE to the Freetds path but did not help.
I'm not used to compile on unix and so, Makefile options are not obvious to me, I would appreciate a lot if someone more experienced could help :

Here is the output I get :

uhptsts1s1:sybase /data/tusers/sybdba/sqsh/sqsh-2.5_MSQL/src>make
gcc -g -O2 -DSQSH_RC='"/usr/local/etc/sqshrc:${HOME}/.sqshrc"'            -I/usr/local/freetds/include  -I/tusers/sybase/OCS-15_0/include   -c -o cmd_bcp.o cmd_bcp.c
In file included from cmd_bcp.c:28:
/usr/local/freetds/include/bkpublic.h:42: error: expected ')' before '*' token
/usr/local/freetds/include/bkpublic.h:47: error: expected ')' before '*' token
/usr/local/freetds/include/bkpublic.h:48: error: expected ')' before '*' token
/usr/local/freetds/include/bkpublic.h:51: error: expected ')' before '*' token
/usr/local/freetds/include/bkpublic.h:52: error: expected ')' before '*' token
/usr/local/freetds/include/bkpublic.h:57: error: expected ')' before '*' token
cmd_bcp.c: In function 'cmd_bcp':
cmd_bcp.c:333: warning: incompatible implicit declaration of built-in function 'index'
cmd_bcp.c:423: error: 'BLK_VERSION_110' undeclared (first use in this function)
cmd_bcp.c:423: error: (Each undeclared identifier is reported only once
cmd_bcp.c:423: error: for each function it appears in.)
cmd_bcp.c:465: error: 'BLK_VERSION_100' undeclared (first use in this function)
cmd_bcp.c:951: error: 'CS_BLK_IN' undeclared (first use in this function)
cmd_bcp.c:1018: error: 'CS_BLK_BATCH' undeclared (first use in this function)
cmd_bcp.c:1086: error: 'CS_BLK_ALL' undeclared (first use in this function)
cmd_bcp.c:1113: error: 'CS_BLK_CANCEL' undeclared (first use in this function)
make: *** [cmd_bcp.o] Error 1

I precise that I had to modify the INCLUDE_PATH and to add the one of Sybase to reduce the number of errors, but now I dont see where can I go.

**Comment by freddy77** [comment]
0.91? Considering we release about every 1/2 years and that's 3 version earlier is 4/5 years old.

**Comment by AssedoZion** [comment]
Hi,
Sorry, I didnt pay attention to the version date, now I downloaded the very last stable version called 'freetds-patched from 2017-09-13 17:08.
I still have an error :
uhptsts1s1:sybase /data/tusers/sybdba/sqsh/sqsh-2.5_MSQL/src>make
gcc -g -O2 -DSQSH_RC='"/usr/local/etc/sqshrc:${HOME}/.sqshrc"'            -I/usr/local/freetds/include  -I/tusers/sybase/OCS-15_0/include   -c -o cmd_alias.o cmd_alias.c
In file included from sqsh_config.h:282,
                 from cmd_alias.c:26:
sqsh_compat.h:50: error: conflicting types for 'strerror'
/usr/local/lib/gcc/ia64-hp-hpux11.31/4.2.3/include/string.h:111: error: previous declaration of 'strerror' was here
cmd_alias.c: In function 'cmd_alias':
cmd_alias.c:71: warning: incompatible implicit declaration of built-in function 'index'
make: *** [cmd_alias.o] Error 1

The version of gcc is : 
 gcc -v
Using built-in specs.
Target: ia64-hp-hpux11.31
Configured with: ../gcc/configure
Thread model: posix
gcc version 4.2.3

**Comment by freddy77** [comment]
All the new errors you are having are not related to FreeTDS but to sqsh.
Please refer to SQSH website.
