### ISSUE TITLE
Freetds throwing compile error on AIX 7.1

### ISSUE THREAD

**Issue by raj4721** [FreeTDS/freetds#152]
Hello Team,

I am using freetds 1.00.55 on AIX 7.1 but ./configure throwing error 'Cannot find or open conftest.c'

Checked but no such file exists.
Please help

**Comment by raj4721** [comment]
![freetds](https://user-images.githubusercontent.com/31924618/30378085-acc6e5f2-98af-11e7-8689-d00a751d6877.JPG)

**Comment by raj4721** [comment]
Tried with both compilers but failing with same error

gcc-4.9.4-1.aix7.1.ppc.rpm and XL C/C++ for AIX, V13.1.3

**Comment by freddy77** [comment]
Actually very weird was working for me.
There was a mistake in configure.ac which was generating an invalid configure.
Fixed, snapshot should be automatically generated tomorrow morning.

**Comment by raj4721** [comment]
Hello Freddy, thank a lot for quick support. Can you please let me changes to be done in configure.ac so I can do as it's critical for one issue. Thanks.
