### ISSUE TITLE
bsqldb: Msg 20017, Level 9 Unexpected EOF from the server 

### ISSUE THREAD

**Issue by bernardocaldas** [FreeTDS/freetds#155]
I'm getting an error while running bsqldb. For some reason, I'm getting an Unexpected EOF. I'm attaching the dump below. I'm using debian jessie and using freetds from apt-get. I've also tried building from source (last stable version), and then I get an error saying type 66 (unsigned int) is not supported. I don't know if they are somehow related, but thought I should report both errors.

14:24:24.055444 635 (dblib.c:4639):dbsqlok(0x1af85f0)
14:24:24.055458 635 (dblib.c:4669):dbsqlok() not done, calling tds_process_tokens()
14:24:24.055464 635 (token.c:540):tds_process_tokens(0x1af8fb0, 0x7ffdf712a6c8, 0x7ffdf712a6cc, 0x6914)
14:24:24.055471 635 (util.c:156):Changed query state from PENDING to READING
14:29:35.641183 635 (util.c:331):tdserror(0x1af8290, 0x1af8fb0, 20017, 115)
14:29:35.641234 635 (dblib.c:7929):dbperror(0x1af85f0, 20017, 115)
14:29:35.641242 635 (dblib.c:7981):20017: "Unexpected EOF from the server"
14:29:35.642038 635 (dblib.c:8002):"Unexpected EOF from the server", client returns 2 (INT_CANCEL)
14:29:35.642586 635 (util.c:361):tdserror: client library returned TDS_INT_CANCEL(2)
14:29:35.642616 635 (util.c:384):tdserror: returning TDS_INT_CANCEL(2)
14:29:35.642892 635 (util.c:156):Changed query state from READING to DEAD
14:29:35.643151 635 (token.c:555):processing result tokens.  marker is  0()
14:29:35.643171 635 (token.c:122):tds_process_default_tokens() marker is 0()
14:29:35.643175 635 (token.c:125):leaving tds_process_default_tokens() connection dead
14:29:35.643179 635 (util.c:104):logic error: cannot change query state from DEAD to PENDING

**Comment by freddy77** [comment]
Which server are you using? unsigned int is only Sybase. Which query are you sending?

**Comment by bernardocaldas** [comment]
Sybase IQ. It's a simple select statement on an unsigned integer field. From what I've seen, when Freetds tries to get the column width it fails because it doesn't know about UINT. Is that correct?
________________________________

**Comment by freddy77** [comment]
From the part of the log you sent the server disconnected for some reason after sending a query.
There's no attempt to format the column.

**Comment by bernardocaldas** [comment]
Hum, you're right. I tried different things and versions of FreeTDS, in this one the error is generic. Do you have any idea? I'll try to reproduce the error I was describing in the most recent version, in the meantime.

**Comment by bernardocaldas** [comment]
On the latest freetds version, this is the error:
bsqldb:213: dbsqlsend(): OK
bsqldb:221: dbsqlok(): OK
bsqldb:369: calling dbresults: OK
Result set 1
Allocating buffers
Allocating compute buffers
Metadata
col     name                            source                          type             size    varies
------  ------------------------------  ------------------------------  ---------------  ------  ------
     1                     A                     A              int       4       1
     2                 B                 B     unsigned int       4       1
type 66 not supported, sorry

**Comment by bernardocaldas** [comment]
10:36:17.107705 4110 (token.c:547):processing result tokens.  marker is  61(ROWFMT2)
10:36:17.107728 4110 (token.c:1771):tds5_process_result2
10:36:17.107736 4110 (mem.c:651):tds_free_all_results()
10:36:17.107743 4110 (token.c:1795):num_cols=5
10:36:17.107755 4110 (token.c:1861):col 0:
10:36:17.107760 4110 (token.c:1862):	column_name=[A]
10:36:17.107766 4110 (token.c:1868):	flags=20 utype=7 type=38 varint=1
10:36:17.107772 4110 (token.c:1871):	colsize=4 prec=0 scale=0
10:36:17.107781 4110 (token.c:1861):col 1:
10:36:17.107787 4110 (token.c:1862):	column_name=[B]
10:36:17.107792 4110 (token.c:1868):	flags=20 utype=29 type=68 varint=1
10:36:17.107798 4110 (token.c:1871):	colsize=4 prec=0 scale=0
10:36:17.107806 4110 (token.c:1861):col 2:
10:36:17.107811 4110 (token.c:1862):	column_name=[C]
10:36:17.107816 4110 (token.c:1868):	flags=20 utype=10 type=108 varint=1
10:36:17.107822 4110 (token.c:1871):	colsize=14 prec=30 scale=8
10:36:17.107830 4110 (token.c:1861):col 3:
10:36:17.107837 4110 (token.c:1862):	column_name=[D]
10:36:17.107842 4110 (token.c:1868):	flags=20 utype=10 type=108 varint=1
10:36:17.107849 4110 (token.c:1871):	colsize=14 prec=30 scale=8
10:36:17.107857 4110 (token.c:1861):col 4:
10:36:17.107862 4110 (token.c:1862):	column_name=[E]
10:36:17.107865 4110 (token.c:1868):	flags=20 utype=10 type=108 varint=1
10:36:17.107868 4110 (token.c:1871):	colsize=14 prec=30 scale=8
10:36:17.107873 4110 (util.c:165):Changed query state from READING to PENDING
10:36:17.107878 4110 (dblib.c:4712):dbsqlok() found result token
10:36:17.107931 4110 (dblib.c:1700):dbresults(0x19f32f0)
10:36:17.107941 4110 (dblib.c:1705):dbresults: dbresults_state is 1 (_DB_RES_RESULTSET_EMPTY)
10:36:17.107947 4110 (token.c:532):tds_process_tokens(0x19f3bd0, 0x7ffd8800c7d8, 0x7ffd8800c7dc, 0x6914)
10:36:17.107954 4110 (util.c:165):Changed query state from PENDING to READING
10:36:17.107960 4110 (token.c:547):processing result tokens.  marker is  d1(ROW)
10:36:17.107966 4110 (token.c:653):tds_process_tokens::SET_RETURN stopping on current token
10:36:17.107972 4110 (util.c:165):Changed query state from READING to PENDING
10:36:17.107976 4110 (dblib.c:1726):dbresults() tds_process_tokens returned 0 (TDS_SUCCESS),
			result_type TDS_ROW_RESULT
10:36:17.107980 4110 (dblib.c:1689):dbresults returning 1 (SUCCEED)
10:36:17.107992 4110 (dblib.c:1840):dbnumcols(0x19f32f0)
10:36:17.108000 4110 (dblib.c:4814):dbnumcompute(0x19f32f0)
10:36:17.108034 4110 (dblib.c:1866):dbcolname(0x19f32f0, 1)
10:36:17.108040 4110 (dblib.c:3038):dbcolsource(0x19f32f0, 1)
10:36:17.108045 4110 (dblib.c:2860):dbcoltype(0x19f32f0, 1)
10:36:17.108049 4110 (dblib.c:3063):dbcollen(0x19f32f0, 1)
10:36:17.108053 4110 (dblib.c:3112):dbvarylen(0x19f32f0, 1)
10:36:17.108057 4110 (dblib.c:6291):dbprtype(56)
10:36:17.108146 4110 (dblib.c:2605):dbbind(0x19f32f0, 1, 1, 0, 0x1a19d90)
10:36:17.108157 4110 (dblib.c:2841):dbwillconvert(SYBINT4, SYBCHAR)
10:36:17.108161 4110 (convert.c:3060):tds_willconvert(56, 47)
10:36:17.108165 4110 (convert.c:3072):tds_willconvert(56, 47) returns yes
10:36:17.108169 4110 (dblib.c:2709):dbnullbind(0x19f32f0, 1, 0x1a1a838)
10:36:17.108173 4110 (dblib.c:1866):dbcolname(0x19f32f0, 2)
10:36:17.108176 4110 (dblib.c:3038):dbcolsource(0x19f32f0, 2)
10:36:17.108180 4110 (dblib.c:2860):dbcoltype(0x19f32f0, 2)
10:36:17.108320 4110 (dblib.c:3063):dbcollen(0x19f32f0, 2)
10:36:17.108333 4110 (dblib.c:3112):dbvarylen(0x19f32f0, 2)
10:36:17.108389 4110 (dblib.c:6291):dbprtype(66)

**Comment by bernardocaldas** [comment]
@freddy77 DIfferent error, I don't know if they are related.

**Comment by freddy77** [comment]
Closing, bsqldb related, not expected production ready.
