### ISSUE TITLE
Empty result set reported for TDS INFO messages.

### ISSUE THREAD

**Issue by joshuahlang** [FreeTDS/freetds#156]
Using FreeTDS 1.00.55 the following SQL as input to fisql:

    SELECT 'First SELECT' AS ColumnName;
    PRINT 'After first select ...';
    SELECT 'Second SELECT' AS ColumnName;
    PRINT 'After second select ...';
    GO

yields the following:

    Changed database context to 'master'.
    Changed language setting to us_english.
    1>> SELECT 'First SELECT' AS ColumnName;
    2>> PRINT 'After first select ...';
    3>> SELECT 'Second SELECT' AS ColumnName;
    4>> PRINT 'After second select ...';
    5>> GO
    ColumnName                                      
    ------------------------------------------------
    First SELECT                                    
    
    (1 rows affected)
    After first select ...
    ColumnName                                      
    ------------------------------------------------
    
    ColumnName                                          
    ----------------------------------------------------
    Second SELECT                                       
    
    (1 rows affected)
    After second select ...
    ColumnName                                          
    ----------------------------------------------------

Note the empty result sets after each of the informational messages generated by the *PRINT* statements. I'd expect the column metadata to be cleared after receiving a TDS *Done* token, but that doesn't seem to be the case? I believe this causes **dbnumcols** to return non-zero, indicating to clients that there is a valid result set when in fact there is only an informational message. This appears to have been introduced in the *1.00.23* build (by one of the commits on 2016-12-05).

**Comment by freddy77** [comment]
Not so easy to do actually.
Yes, the record set is not removed when a DONE is received and this allows to query the column list for instance if there are no rows.
I think would be safer to remove the record set when a INFO is received. Note that a INFO token can happen inside a record set (to report error in a given row).

**Comment by joshuahlang** [comment]
I'm not nearly as familiar with the TDS protocol as you, so I'll defer to your best judgement as to what the proper fix is. Is it agreed then that this is unexpected/incorrect behavior?

**Comment by freddy77** [comment]
In this case is more related to internal libTDS state. Currently the record set is reset when a new header is received and different libraries rely on this. But surely this is incorrect when a message outside a record set is received.

**Comment by freddy77** [comment]
Fixed

**Comment by joshuahlang** [comment]
Thanks for the quick response!.

This seems to fix my example, however, the issue persists in a simple case using `SET`:

```
SELECT 'SELECT' AS ColumnName;

DECLARE @Msg NVARCHAR(MAX);

SET @Msg = 'After first select ...';
GO
```

```
Changed database context to 'master'.
Changed language setting to us_english.
1>> SELECT 'SELECT' AS ColumnName;
2>> 
3>> DECLARE @Msg NVARCHAR(MAX);
4>> 
5>> SET @Msg = 'After first select ...';
6>> GO
ColumnName              
------------------------
SELECT                  

(1 rows affected)
ColumnName              
------------------------

(1 rows affected)
1>> 
```

Looking at the wire capture, SQL Server is returning a `DONE` message for the `SET` command, with 1 row affected. I guess I would expect this result to not be reported by a client such as fisql (SQL Server Management Studio does not report it).
