### ISSUE TITLE
CS_BIGTIME

### ISSUE THREAD

**Issue by jalegido** [FreeTDS/freetds#157]
Since your commit 48a62badb5c77397de26eb40d9f74055ef9cde29, I can use FreeTDS with Microsoft DATE and TIME. Thank you very much.
But, when I wanted use TIME format, I wasted time to inspect the returned value. After inspecting your code, I saw that the returned value was BIGTIME. But I didn't know what format it is.

I think, this line 
typedef CS_UBIGINT CS_BIGTIME;
in cspublic.h:142 could help people to use this value.

**Comment by freddy77** [comment]
Added types to cstypes.h
