### ISSUE TITLE
Unexpected EOF from the server, windows, pymssql

### ISSUE THREAD

**Issue by M0rtalW0mbat** [FreeTDS/freetds#159]
I use pymssql 2.1.3 installed from http://www.lfd.uci.edu/~gohlke/pythonlibs/#pymssql, python 3.6.2 32bit on Windows 10 64bit, i dont khow precisely with version of FreeDTS use my pymssql bundle, but pymssql.get_dbversion() report 'freetds v0.95'.

My test is pretty simple: connect to db, select some info, connection closing, but once out of hundred i catch exception: <class 'pymssql.OperationalError'> (20017, b'DB-Lib error message 20017, severity 9:\nUnexpected EOF from the server (x.x.x.x:p)\nDB-Lib error message 20002, severity 9:\nAdaptive Server connection failed (x.x.x.x:p)\n')

Cross link from pymssql github: https://github.com/pymssql/pymssql/issues/54

**Comment by freddy77** [comment]
We don't support 0.95.
