### ISSUE TITLE
Unable to select database using -D when connecting to an Azure database

### ISSUE THREAD

**Issue by powelleric** [FreeTDS/freetds#160]
`USE statement is not supported to switch between databases. Use a new connection to connect to a different database.`

The error results when trying to connect to an Azure database.  I am actually familiar with this issue but I *swore* it had been resolved in the recent versions of freetds.

In fact, I was [once](https://stackoverflow.com/a/41726254/2117491) able to get freebcp working using the `-D` flag.  

Now, however, I am trying to use `bsqldb` and I find myself up against the issue once again.

> ~/sandbox/freetds/freetds-1.00.9/src/apps/bsqldb  -U user@server -S serv -P 'p@ssword' -D dev -i tmp.sql
Msg 40508, Level 16, State 1
Server 'serv', Line 1
        USE statement is not supported to switch between databases. Use a new connection to connect to a different database.
lt-bsqldb: error: severity 16 > 10, exiting

**Comment by freddy77** [comment]
Yes, quite some utilities uses still dbuse which cause the "USE database_name" query to be send.
Fixed with https://github.com/FreeTDS/freetds/commit/e5d6163089e209125ccbe09e07d953ff1a4b4b44 for bsqldb.

**Comment by powelleric** [comment]
Thank you.  I really, really appreciate your help.
I believe that has fixed the issue.  Can you fix the same thing for `fisql`?

**Comment by freddy77** [comment]
Fixed
