### ISSUE TITLE
Error when using bsqldb: "type 36 not supported, sorry"

### ISSUE THREAD

**Issue by powelleric** [FreeTDS/freetds#161]
I don't know how to get anything more verbose from the program.

```
$> ~/sandbox/freetds/master/src/apps/bsqldb  -U user@server -S serv -P 'p@ssword' -D "prod" -i tmp.sql
type 36 not supported, sorry
```

**Comment by powelleric** [comment]
I was able to get some insight to this problem.  It seems like it is almost certainly an issue with outputting a GUID.

When using `bsqldb`, the query fails with this message:



```
> ~/sandbox/freetds/master/src/apps/bsqldb  -U xxx@xxx -S xxx -P 'xxx' -D dev -i tmp.sql -v                                                                                                                                                18:50:19
lt-bsqldb:191: Verbose operation enabled
lt-bsqldb:240: Query:
        --test
        select top 10 Id
        from Sales
lt-bsqldb:214: dbsqlsend(): OK
lt-bsqldb:222: dbsqlok(): OK
lt-bsqldb:370: calling dbresults: OK
Result set 1
Allocating buffers
Allocating compute buffers
Metadata
col     name                            source                          type             size    varies
------  ------------------------------  ------------------------------  ---------------  ------  ------
     1                              Id                              Id  uniqueidentifier      16       1
type 36 not supported, sorry
```
_EDIT:  I almost forgot to mention that if I change the query to output a non-GUID column(s), then `bsqldb` works perfectly fine.  It seems to be only when the results include a GUID._

However, with `fisql` everything is great.  Unfortunately, I need `bsqldb` because I want an output file with just the data and no logging output.

```
> ~/sandbox/freetds/master/src/apps/fisql/fisql  -U xxx@xx -S xx -P 'xx' -D dev -i tmp.sql                                                                                                                                              18:50:13
Changed database context to 'dev'.
Changed language setting to us_english.
1>> --test
2>> select top 10 Id
3>> from Sales
4>> GO
Id
------------------------------------
84F29918-0D85-4DEC-B58D-001B8B991C9F
08F91F82-DF72-473B-B786-002227174EDD
62A031F2-EC1E-40DA-860B-0029A23BDADB
7364A828-9327-4C3C-A5E7-002BE7C048ED
5A60B802-A584-458A-B6C8-002F3E31E7D3
1D95140F-7832-4FD0-A071-0047363ADA82
2270196D-0372-4A1D-AF16-00474CCB00C6
7881DF65-C6C9-4686-BFFF-004C0D0BCE4F
71E86071-F412-483D-A6BB-0055A0BD300B
E75C552A-1B41-4C6F-8323-0063BD8B2283

(10 rows affected)
1>> ⏎
```

@freddy77 and FreeTDS contributors:
Thanks a bunch in advance for your help with this issue and for supporting FreeTDS in general.  I am stuck on Ubuntu 12.04 and I would be in big trouble without you.

**Comment by freddy77** [comment]
Could you use tsql? The bsql* utility are not in a production state.

**Comment by powelleric** [comment]
Thank you for pointing that out, @freddy77.  I didn't actually realize tsql could be used to produce a tab-delimited file.  I just tried it and it is indeed handling the GUIDs correctly.  

The one thing that it is missing compared to bsqldb is that with tsql you must use 'GO' for every command.  bsqldb has a feature where: "The last batch need not be followed by "go"" (taken from man page).  This is nice for simple scripts that only have one select operation.

Currently, if you forget "GO", tsql just does nothing.  I'm worried this is going to be a recurring mistake I make.

Maybe I am just being picky now but I thought I would share that anyway.  Happy to create a new issue for that feature if you'd be willing to implement it.

Thanks again for all your help thus far!

**Comment by freddy77** [comment]
Just implemented the "go" suggestion on tsql.
I'll close the issue for bsqldb.
