### ISSUE TITLE
float type displays too many decimals 

### ISSUE THREAD

**Issue by ldconfig10** [FreeTDS/freetds#163]
I compiled the latest version of freetds after cloning the git repo using ./autogen.sh. 

When doing a query to MS SQL Server(2008),
It shows something like 3.549999999999999, instead of 3.55. 
In simple query mode, SSMS result UI shows 3.55
In edit mode UI, SSMS also shows 3.55
In previous version of tsql(4.2) that I installed from Ubuntu repo, it also showed 3.55

The query I used is the following:
`select round({column name}, 2, 0) from {tbl}
`
I am aware of the trouble if storing a number as FLOAT type in SQL Server, however, I have used the round() function to handle this issue. Why tsql is still showing those too many decimals?

Thanks,

**Comment by freddy77** [comment]
round or not is still a floating point.
But in src/tds/convert.c (tds_convert_real) the format string is "%.9g" which seems to indicate 9 digits while single precision has 24 bits (1 implicit) mantissa that is 8 digits. Can you try replacing with "%.8g" ?

**Comment by freddy77** [comment]
This was done in https://github.com/FreeTDS/freetds/commit/78501e196 and I think make perfectly sense.

**Comment by ldconfig10** [comment]
I see. So this is by design. Thanks.

**Comment by ldconfig10** [comment]
However, the result from the following query is not intuitive for me.

SELECT
  ROUND('1.3278100',6,0)                     AS x0,
  ROUND('1.3278200',6,0)                     AS y0,
  ROUND('1.3278100',6,1)                     AS x1,
  ROUND('1.3278200',6,1)                     AS y1,

  ROUND(CAST( '1.3278100' AS FLOAT), 6, 0)   AS a0,
  ROUND(CAST( '1.3278200' AS FLOAT), 6, 0)   AS b0,
  ROUND(CAST( '1.3278100' AS FLOAT), 6, 1)   AS a1,
  ROUND(CAST( '1.3278200' AS FLOAT), 6, 1)   AS b1,

  ROUND(CAST( '1.3278100' AS DECIMAL(9,1)), 6, 0)   AS i0,
  ROUND(CAST( '1.3278200' AS DECIMAL(9,1)), 6, 0)   AS j0,
  ROUND(CAST( '1.3278100' AS DECIMAL(9,1)), 6, 1)   AS i1,
  ROUND(CAST( '1.3278200' AS DECIMAL(9,1)), 6, 1)   AS j1
;
go

OUTPUT:
1.3278099999999999      1.32782 	1.327809        1.32782 
1.3278099999999999      1.32782 	1.327809        1.32782 
1.3     1.3     1.3     1.3

I understand the third row of the result, but the discrepancy between result like 1.32780999999999 and 1.32782 at the same row confuses me. Could anyone help? 

More importantly, , in my actual production query, I am not able to mange to use round(cast{NUM as decimal(4,2), 4, 2) to output a number with two decimals; the result are always having too many trailing digits.

**Comment by freddy77** [comment]
The same format is returned by Microsoft sqlcmd utility using MSSQL 2017.
Why you have to cast to numeric and then round? The cast already do the rounding and numeric assure a given amount of digits.

**Comment by freddy77** [comment]
Closing, not a FreeTDS issue.
