### ISSUE TITLE
Subscription request

### ISSUE THREAD

**Issue by cejackson51** [FreeTDS/freetds#165]
Please subscribe me to the freetds mailing list at cejackson51@gmail.com. I'm working on improving the Wireshark TDS dissector and I feel that I will be able to get lots of input and test data from the TDS list.

I was subscribed years ago, but that probably fell off. I think that one may have been craigj@iacnet.com or cjackso@galegroup.com.

Craig Jackson

**Comment by freddy77** [comment]
done
