### ISSUE TITLE
incorrect encoding with tds version 7.3

### ISSUE THREAD

**Issue by Splarv** [FreeTDS/freetds#167]
I have to connect to M$ SQL,
	Microsoft SQL Server 2008 R2 (SP1) - 10.50.2500.0 (X64) 
	Jun 17 2011 00:54:03 
	Copyright (c) Microsoft Corporation
	Enterprise Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1) 
(Hypervisor)
freetds version
$ dpkg -s freetds-bin
Package: freetds-bin
Status: install ok installed
Priority: optional
Section: database
Installed-Size: 713
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Source: freetds
Version: 0.91-6.1build2
Depends: libc6 (>= 2.17), libgnutls30 (>= 3.5.3), libgssapi-krb5-2 (>= 1.14+dfsg), libodbc1 (>= 2.3.1), libreadline7 (>= 6.0), libsybdb5 (>= 0.82), freetds-common

OS Ubuntu 17.10 amd64

According to the freetds docs I must use version of protocol tds 7.3 in freetds.conf for M$ SQL Server 2008. But with 7.3 (and 7.4 too) I see wrong charset.

$ tsql -S nehoteevka -U user -P password
locale is "LC_CTYPE=ru_RU.UTF-8;LC_NUMERIC=ru_RU.UTF-8;LC_TIME=en_DK.UTF-8;LC_COLLATE=ru_RU.UTF-8;LC_MONETARY=ru_RU.UTF-8;LC_MESSAGES=en_US.UTF-8;LC_PAPER=ru_RU.UTF-8;LC_NAME=ru_RU.UTF-8;LC_ADDRESS=ru_RU.UTF-8;LC_TELEPHONE=ru_RU.UTF-8;LC_MEASUREMENT=ru_RU.UTF-8;LC_IDENTIFICATION=ru_RU.UTF-8"
locale charset is "UTF-8"
using default charset "UTF-8"
1> select top 1 Name from Status
2> go
Name
�������
(1 row affected)

But with 7.2, 7.1, 7.0 version of tds this looked fine. This is for 7.2:

$ tsql -S nehoteevka -U user -P password
locale is "LC_CTYPE=ru_RU.UTF-8;LC_NUMERIC=ru_RU.UTF-8;LC_TIME=en_DK.UTF-8;LC_COLLATE=ru_RU.UTF-8;LC_MONETARY=ru_RU.UTF-8;LC_MESSAGES=en_US.UTF-8;LC_PAPER=ru_RU.UTF-8;LC_NAME=ru_RU.UTF-8;LC_ADDRESS=ru_RU.UTF-8;LC_TELEPHONE=ru_RU.UTF-8;LC_MEASUREMENT=ru_RU.UTF-8;LC_IDENTIFICATION=ru_RU.UTF-8"
locale charset is "UTF-8"
using default charset "UTF-8"
Error 100 (severity 11):
	unrecognized msgno
1> select top 1 Name from Status
2> go
Name
Активен
(1 row affected)

But there is I see error (and may be will be problems with datetime2 and so), but charset is fine.

**Comment by freddy77** [comment]
FreeTDS version 0.91 supports up to 7.2 version of the protocol.
