### ISSUE TITLE
warning: macro 'AM_ICONV' not found in library

### ISSUE THREAD

**Issue by cbalano** [FreeTDS/freetds#172]
I am trying to compile FreeTDS 1.0 on Alpine Linux  3.6.2. There is already a freetds package installable via "apk add", but it lacks Kerberos support, which I absolutely need.

I installed all packages described in INSTALL.GIT, plus gettext 0.19.8.1-r1. Still, when I execute autogen.sh, I get the erros below. Any idea why this might be?

/root/freetds# ./autogen.sh
running /usr/bin/autoreconf in /root/freetds:
configure.ac:123: warning: macro 'AM_ICONV' not found in library
configure.ac:97: error: required file './compile' not found
configure.ac:97:   'automake --add-missing' can install 'compile'
configure.ac:69: error: required file './config.guess' not found
configure.ac:69:   'automake --add-missing' can install 'config.guess'
configure.ac:69: error: required file './config.sub' not found
configure.ac:69:   'automake --add-missing' can install 'config.sub'
configure.ac:18: error: required file './install-sh' not found
configure.ac:18:   'automake --add-missing' can install 'install-sh'
configure.ac:18: error: required file './missing' not found
configure.ac:18:   'automake --add-missing' can install 'missing'
src/apps/Makefile.am: error: required file './depcomp' not found
src/apps/Makefile.am:   'automake --add-missing' can install 'depcomp'
parallel-tests: error: required file './test-driver' not found
parallel-tests:   'automake --add-missing' can install 'test-driver'
autoreconf: automake failed with exit status: 1
configure.ac:123: warning: macro 'AM_ICONV' not found in library
configure.ac:123: warning: macro 'AM_ICONV' not found in library
configure.ac:123: error: possibly undefined macro: AM_ICONV
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1

**Comment by freddy77** [comment]
The missing AM_ICONV macro means you need some additional package in your environment.
The missing files should be installed automatically by the script.
You can easily download a new package with all you need from ftp://ftp.freetds.org/pub/freetds/stable/ (1.00.77 is the last version as today).

**Comment by belegnar** [comment]
For debian-like distros run
# apt install -y gettext

**Comment by hobbsenigma** [comment]
I had gettext installed, but needed gettext-devel on redhat.

**Comment by sayrilkun** [comment]
this works for me!

**Comment by freddy77** [comment]
The initial issue here was that gettext package was not installed. So installing it fixed the issue. Recently there's another issue related to gettext but that's another issue.
