### ISSUE TITLE
Empty recordsets with num_cols > 0

### ISSUE THREAD

**Issue by fandrieu** [FreeTDS/freetds#175]
This is a follow up to #156 

After executing SET-like statements, SQL Server returns a "DONE" token.
This produces an empty recordset in FreeTDS, but it can be identified because it doesn't have any column.

But this doesn't work after a regular recordset has been received: the number of columns reported stays the same, it's not reset to 0.

So, with the following query:
```sql
set arithabort on
select 1
set arithabort on
select 2
```
I would expect 4 results, with 0, 1, 0, 1 columns
But the actual number of columns reported is 0, 1, 1, 1.

To be clear, I [wrote a test](https://github.com/FreeTDS/freetds/commit/32f307d3f0c0d9358e93eca6caadd14a358e59bb) showing this using dblib.

**Comment by fandrieu** [comment]
After some digging, it appears this is somewhat related to commit 34e1f699f66c4837ebe1e0b46c5c58415f8fada7
Before that there were no empty recordsets in between real ones.
(so this may be a dblib only issue...)

So [I tried a fix](https://github.com/FreeTDS/freetds/commit/e68d09df67a61fdcb6cc41598d3dc93f72ed6f73) (with my very limited understanding of FreeTDS internals, sorry): resting res_info in this exact spot.
It solves my test case, but I have no idea of the implications...

**Comment by freddy77** [comment]
Tests looks good, there are some minor style but nothing weird.
I'll try to check with Sybase dblib to see the difference.
The fix looks working with the current tests but I would just call tds_free_all_results and not allocating a 0 column recordset, not having a recordset if the same (tested too).
Sometimes I wonder is was a mistake from my side to to that change...

**Comment by fandrieu** [comment]
Thanks for looking into this and sorry for the late reply.
I just opened PR #184 with a cleaned up patch using `tds_free_all_results`

**Comment by freddy77** [comment]
Merged, thanks
