### ISSUE TITLE
fail to compile

### ISSUE THREAD

**Issue by gzliudan** [FreeTDS/freetds#182]
command are:
git clone https://github.com/FreeTDS/freetds.git
cd freetds/
./autogen.sh
make

below is error message:
make[3]: Entering directory `/root/freetds/src/apps/fisql'
  CC       fisql.o
fisql.c: In function ‘reset_ibuf’:
fisql.c:255:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for (int i = 0; ibuf && i < ibuflines; i++) {
  ^
fisql.c:255:2: note: use option -std=c99 or -std=gnu99 to compile your code
make[3]: *** [fisql.o] Error 1

**Comment by freddy77** [comment]
Fixed.
