### ISSUE TITLE
Reading SQL Server nvarchar fields with size more than 1500 chars has issues

### ISSUE THREAD

**Issue by ashishmundrajll** [FreeTDS/freetds#186]
Hi All,

We are facing the issue listed in http://www.freetds.org/userguide/troubleshooting.htm where instead of varchar, we have nvarchar as datatype which preserves Unicode in SQL Server. If our nvarchar field has more than 1500 chars, we receive segment fault exception.

I tried using CAST(nvarcharField AS ntext) and used SET TEXTSIZE 10000, but that also does not resolve the issue.

Thanks and Regards,
Ashish

**Comment by freddy77** [comment]
Which protocol version are you using?
Which FreeTDS version?
The issue you mentioned is quite old.
The 1500 limit is quite weird looks like more an ethernet packet size than something related to TDS.

**Comment by ashishmundrajll** [comment]
We are using tds version 7.2
The cron job that fetches the data is in a VM hosted in Microsoft Azure which fetches the data from a Microsoft Azure SQL database. We do not explicitly set any packet size (and there is also no place in Azure to set it as well). Also, 1500 was just an example, we do have some fields with 2000 nvarchar already in our select clause, but now we want to add one more field of 6000 chars which is not being supported. There is no special character in this new fields and its same as previous field.

**Comment by freddy77** [comment]
I don't see any reason why should fail. Which library are you using? Can provide a TDSDUMP?

**Comment by freddy77** [comment]
Closing, no reply.
