### ISSUE TITLE
Disable error messages or set up warning level

### ISSUE THREAD

**Issue by chichivica** [FreeTDS/freetds#188]
Hi guys, thanks for awesome project. 

I'm calling stored procedure to fetch some data, everything works like a charm,
but I'm instantly getting error messages about binding to non-existing column for each and every query.

```
 Msg 20032, Level 7
Attempt to bind to a non-existent column

 Msg 20032, Level 7
Attempt to bind to a non-existent column

 Msg 20032, Level 7
Attempt to bind to a non-existent column

```
![](https://i.imgur.com/Ecs0HjN.png)

How I can tune error messages level or perhaps I missunderstand smth?

**Comment by freddy77** [comment]
Where does this came this error? Which library/tool are you using?

**Comment by freddy77** [comment]
Closing, no reply in more than a month. I suppose is fixed now.
