### ISSUE TITLE
freebcp: import non-numeric data

### ISSUE THREAD

**Issue by powelleric** [FreeTDS/freetds#189]
I am very confused about how to use freebcp to import non-numeric data into a table.  I can provide exact examples from my terminal, but maybe my description is enough.

**Note: I am trying to copy data to Azure SQL Server**

When I created a table with a single bigint column.  I was able to use freebcp just fine.

`freetds/src/apps/freebcp testtable in data.txt -U user@server -S server -P 'pass' -D dev -c -e upload.err`

However, when I tried to upload data to a table that had nvarchar column, I get the error below, where 'CustomerName' is the first field in the table:

```
Starting copy...
Msg 2717, Level 16, State 2
Server 'tgp', Line 1
        The size (8000) given to the parameter 'CustomerName' exceeds the maximum allowed (4000).
Msg 2717, Level 16
General SQL Server error: Check messages from the SQL Server
```

My data file is tab-delimited with standard unix newline characters at the end of each record.

An example would be:
```
Eric 123﻿ abc
```

**Comment by freddy77** [comment]
Looks like the utility is currently using the varchar limit and not nvarchar one and the server correctly complaints.
Which FreeTDS version are you using?
Can you send a TDSDUMP?
Which is the table definition?

**Comment by freddy77** [comment]
Are you sure you are not using version 0.91 or former?
I saw you are using Ubuntu which unfortunately by default came with such obsolete version.

**Comment by powelleric** [comment]
I was using whatever version was current on Github at the time I posted the issue.  

Could the TDS protocol version be an issue? For example, in my conf file I am using version 7.  I read somewhere that later versions handle varchars differently.

```
# test server
[mytest]
        host = mytest.database.windows.net
        database = dev
        port = 1433
        tds version = 7.0
```

I was just working with a test table but I think the table definition was something like: 

```
create table testtable (
	CustomerName nvarchar(2000)
);
```

I still don't have my old ubuntu server back up but I can try freebcp on my Mac installation later.  Let me know if you see any issues with the table def or protocol version.

Thanks again for all your help!  Much appreciated.

**Comment by freddy77** [comment]
Just tried, I create the maximum length nvarchar(4000), exported and imported again, no problems with both Branch-1_00 and master, checked the network packets and everything seems fine here.
I'm using utf-8 which could be an issue but is not. No idea what can be your issue beside an old version like maybe using the distro package by mistake instead of the compiled one.

**Comment by powelleric** [comment]
Yet again this is working perfectly on my Mac.  Still no Ubuntu server to test on, which is the OS where I experienced the original issue.  

I will just chalk this up to my own user error.  Maybe the wrong package, like you said.

Thanks a bunch for your help and sorry about any confusion.
