### ISSUE TITLE
Debian packages are old

### ISSUE THREAD

**Issue by freddy77** [FreeTDS/freetds#193]
This is just an issue to not forget trying to have this package updates in Debian, see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=803258

**Comment by powelleric** [comment]
This would really be great.  As you know, I had quite a bit of issues on Ubuntu (and more untold troubles getting the drivers originally set up).  It would be simply amazing to get the distro package updated.

**Comment by salewski** [comment]
Just noting that the upstream bug was marked as fixed on `2018-02-20` for Debian package version `'freetds-common-1.00.82-1'`, and the package changelog shows an additional `'*-2'` version of the package released right behind that one (which is the latest available in Debian testing ("buster") at the moment).

**Comment by mckaygerhard** [comment]
please close this issue debian now have fresh enought packages!

**Comment by freddy77** [comment]
Good, in the unstable there's 1.00.104! Good!
