### ISSUE TITLE
SQLSetConnectAttr SQL_ATTR_LOGIN_TIMEOUT not functioning

### ISSUE THREAD

**Issue by jerrycl** [FreeTDS/freetds#199]
`.` . .not for me, on Slackware Linux 14.1, I installed the master (as of today), and odbc.c:odbc_connect uses the dbc->attr.connection_timeout to time out an inital connect, which is fine, but if a program sets SQL_ATTR_LOGIN_TIMEOUT, according to the ODBC docs, it's supposed to use that value.  

This is messing up pyodbc, which is trying to follow the ODBC spec: https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlsetconnectattr-function

I suggest a possible fix:

    index 292f68d..76adaf5 100644
    --- a/src/odbc/odbc.c
    +++ b/src/odbc/odbc.c
    @@ -377,6 +377,10 @@ odbc_connect(TDS_DBC * dbc, TDSLOGIN * login)
        if (dbc->attr.connection_timeout)
                login->connect_timeout = dbc->attr.connection_timeout;
 
    +  /* but override with login timeout, if set */
    +       if (dbc->attr.login_timeout)
    +               login->connect_timeout = dbc->attr.login_timeout;
    +
            if (dbc->attr.mars_enabled != SQL_MARS_ENABLED_NO)
                    login->mars = 1;
            if (dbc->attr.bulk_enabled != SQL_BCP_OFF)

**Comment by freddy77** [comment]
Doing some test using login and connection timeut. Looks like the login timeout is affected by just the login timeout, not sure what the connection timeout is for. The fix seems good, can you provide a comment for the commit message?

**Comment by jerrycl** [comment]
Reading the documentation on ODBC, I think the login timeout is for logins, the statement timeout is for statement execution, and the connection timeout is for everything else - there are lots of connections made for other purposes.

But, I'm assuming that a lot of developers misunderstood the meaning of  the connection timeout, confusing it with the login timeout, and there's probably a lot of code out there depending on the connection timeout to act like the login timeout, so I think it's best to leave it as is.

A possible commit comment:
"Use the SQL_ATTR_LOGIN_TIMEOUT value to time out login connections"

BTW, thanks for maintaining this driver.  Without it, a lot of shops would be unable to use Linux on their Web servers.

-Jerry

**Comment by freddy77** [comment]
Last question. If you pass me the full name and e-mail I can put as author of the commit

**Comment by jerrycl** [comment]
Jerry Clabaugh  jerrycl@tutanota.com

**Comment by freddy77** [comment]
Done, thanks
