### ISSUE TITLE
request subscription please to FreeTDS 

### ISSUE THREAD

**Issue by slingonce** [FreeTDS/freetds#201]
Hello
please add me (MALCOLM B WEAVER JR, SAP / Sybase Product Support Engineer dating back to orig hire date of 1994_07_24) with email address of slingonce@gmail.com to registered subscribers list.

today was able to get the 32bit FreeTDS ODBC driver on rhel 7.4 working with a legacy SAP Sybase middleware server product name DirectConnect for ODBC or the official marketing name is Enterprise Data Connect Access (ECDA) . . . presently only a 32bit app on linux . . . working.  ECDA is middleware that looks like a Sybase SQL SRVR or ASE from the client application perspective but then retrieves the data out the backend from heterogeneous data sources like DB2 z/OS, DB2 LUW, Oracle, MSSQL, and any other ODBC data source.

thank you to all the following persons
Greg Thain . . . converter a.out-based app to ELF library with only the newer CT-Library API
Brian Bruns . . . Sybase DBA with linux DB-Library apps
Craig Spannring . . . author of FreeTDS/JDBC
Frediano Ziglio . . . expanded FeeTDS ODBC driver
Bill Thompson . . . author of BCP system added cursors to FreeTDS CT-Library
James K. Lowden . . . maintainer and author/added doc 

Sincerely,
Malcolm

**Comment by freddy77** [comment]
Done,
Thanks.
