### ISSUE TITLE
Suggest add API to get the size of data which was transfered to bind host var.

### ISSUE THREAD

**Issue by hex2tan** [FreeTDS/freetds#202]
Function dbdatlen() return the original size(colinfo->column_cur_size) from the database. Suggest add API to get the size of data which was transfered to bind host var.

eg: A datetime column, dbdatlen will return 8. If we call dbbind to bind the type to STRINGBIND and specified a buffer to store the data. When we call dbnextrow() to fetch the row, the result was written to the buffer which we setted. But it seems there is no any API to get the effective length of the data.
Although the copy_data_to_host_var() do this transfer work and the tds_convert() return the effective length, but don't save it any where.

**Comment by freddy77** [comment]
I think what do you want is dbnullbind. With that function you can add a variable pointer to the bind so when dbnextrow run it set your variable with the value you want.

**Comment by freddy77** [comment]
Closing, no replies in months
