### ISSUE TITLE
Cannot login via domain account

### ISSUE THREAD

**Issue by Areso** [FreeTDS/freetds#206]
RHEL 7.4, freetds-0.95.81-1.el7.x86_64 (client), MSSQLServer 2014, Windows Server 2012 (server)
Checked RTFM http://www.freetds.org/userguide/domains.htm

**Case1:** 
tsql -S myClasterName -U 'myLocalAccount' -P myPasswordForLocalAccount
-success, console is opened.

**Case2:**
tsql -S myClasterName -U 'domain\domainAccount' -P myPasswordForDomainAccount
Error 20002 (severity 9):
        Adaptive Server connection failed
There was a problem connecting to the server

**Case3:**
tsql -S myClasterName -U 'domainAccount' -P myPasswordForDomainAccount
Msg 18456 (severity 14, state 1) from ClusterServer1\TEST1 Line 1:
        "Login failed for user 'domainAccount'."
Error 20002 (severity 9):
        Adaptive Server connection failed
There was a problem connecting to the server

Kerberos libs installed but not configured properly (somehow), checked it with failed attempts with sqlcmd (but with localAccount all works fine in sqlcmd as well)

krb5-libs-1.15.1-8.el7.i686
krb5-workstation-1.15.1-8.el7.x86_64
kinit done, klist returns my domain user and date of the token expiration

What I should do to connect my database? Case 2 even didn't leave any traces in audit log 
EXEC xp_readerrorlog; returns nothing of Case2 in logs.

tsql -C
Compile-time settings (established with the "configure" script)
Version: freetds v0.95.81
freetds.conf directory: /etc
MS db-lib source compatibility: yes
Sybase binary compatibility: yes
Thread safety: yes
iconv library: yes
TDS version: 4.2
iODBC: no
unixodbc: yes
SSPI "trusted" logins: no
Kerberos: yes
OpenSSL: no
GnuTLS: yes

**Comment by freddy77** [comment]
From **tsql -C** seems that default is TDS 4.2 (which will be disable as default in next version) which don't support login domain (as documented in the page you linked, cfr **Domain logins can be used only with TDS protocol versions 7.0 or above**), try doing a
`export TDSVER=7.1`. Other thing to check in the configuration is NTLMv2, see http://www.freetds.org/userguide/freetdsconf.htm.

**Comment by Areso** [comment]
Thank you, now my config broken somewhere else (on the server side, I suppose, because I see it in MSSQL logs: Login failed. The login is from an untrusted domain and cannot be used with Windows authentication
Also I should notice, that changing global settings to 7.0 was not enough, I additionally create a section for my MSSQL server and pointed in the section tds 7.0 and then it completed the login request (though with the error from above).
Probably your valuable information should be included to http://www.freetds.org/userguide/domains.htm at least as link.

**Comment by freddy77** [comment]
Did you manage to find the issue(s) ?
Have you tried UseNTLMv2 option ?
I thing the global affects other configuration but not connection without a setting in freetds.conf.
By 

> Probably your valuable information should be included to ...

you mean the NTLMv2?

**Comment by Areso** [comment]
@freddy77 Yes, I did.
Should I post somewhere my settings? It's three files I modified to get the whole system work:
odbc.ini, odbcinst.ini, freetds.conf . I spent about week to get it works, playing with those files.

**Comment by freddy77** [comment]
I think would be great to understand how to improve documentation about it.
I follow this project too much, maybe I cannot recognize some configuration issues as I know how to avoid without even recognizing them.
ODBC configuration is written in a way that is possible to avoid using freetds.conf, I won't be surprise if you could use only odbc.ini and odbcinst.ini (unless you use some tools like tsql that is not using ODBC).

**Comment by freddy77** [comment]
Closing, was kept open just as a reminder to turn NTLMv2 on by default for next version

**Comment by iagomez** [comment]
@Areso 
I'm having a very similar issue. I can connect using tsql, but ODBC is giving this error:
> Login failed. The login is from an untrusted domain and cannot be used with Windows authentication

Can you share what configuration settings you used?
