### ISSUE TITLE
Looking for possible size limits with freetds

### ISSUE THREAD

**Issue by markhepburn** [FreeTDS/freetds#207]
I'm trying to isolate a gdal problem with a MSSQL database (2017).  The two main points are:
* the same command, for example ogrinfo, works from Windows but not from Linux
* (for the failing case on Linux) smaller geometries print fine, but larger geometries fail.

So at this point I'm assuming the issue is somewhere in the freetds layer, not gdal.

The error printed is

> ERROR 1: GetNextRawFeature(): Not enough data to deserialize

I've managed to gradually simplify the problem, using the Reduce() geometry simplification method with increasing tolerances; from the original failing POLYGON geometry with 2583 points, I roughly found that 586 points still fails, but 247 was successful.

Is this likely to be an issue with freetds, and can I help further isolate it?

**Comment by freddy77** [comment]
I don't know gdal, which stack is using? In particular which FreeTDS library? dblib, CT-Library or ODBC?
Which protocol version are you using?

**Comment by markhepburn** [comment]
It's using the odbc library (actually, that's an assumption now that I think about it; is there a way to confirm?)

I've tried protocol versions 7.1, 7.2, 7.3 (and not specifying it in freetds.conf)

**Comment by freddy77** [comment]
See http://www.freetds.org/userguide/logging.htm to enable logging. Also see DumpFile in http://www.freetds.org/userguide/odbcconnattr.htm

**Comment by freddy77** [comment]
Closing, no comments in months
