### ISSUE TITLE
VC project files generate failed

### ISSUE THREAD

**Issue by Sniperq2** [FreeTDS/freetds#208]
Using cmake.

Detecting CXX compile features
Detecting CXX compile features - done
CMake Error at CMakeLists.txt:41 (message):
  wrong VERSION format (dev.1.00.365) --> (dev.1.00.365)

**Comment by freddy77** [comment]
Interesting. I suppose AppVeyor compiles the git version fixing the version from configure.ac but not apparently the nightly generated version.

**Comment by freddy77** [comment]
Fixed in master, nightly tarball will be generated tomorrow.
