### ISSUE TITLE
[Feature request] Nightly builds

### ISSUE THREAD

**Issue by Sniperq2** [FreeTDS/freetds#209]
Would be nice if FreeTDS project will provide nightly builds for Win32, Win64.

1. Because of availability of SQL Server 2016
2. More testing, I hope

**Comment by freddy77** [comment]
You can get AppVeyor results from https://ci.appveyor.com/project/FreeTDS/freetds/history

**Comment by freddy77** [comment]
Fixed the build from nightly, do you think there should be something more official than AppVeyor ?

**Comment by freddy77** [comment]
No reply, I suppose current solution is fine
