### ISSUE TITLE
Mailing List Subscription

### ISSUE THREAD

**Issue by AJWID001** [FreeTDS/freetds#210]
Was just advised to open an issue here in order to have email authorised for the mailing list.

I am primarily an Oracle DBA, but I develop PL/SQL code connecting to a variety of respositories (a lot of them SQL Server), for which I use the TDS ODBC Driver; and have done so for about the last several years.

**Comment by freddy77** [comment]
Hi, sure, I just need your email address. You can send it directly to me (you can find my email address easily on the mailing list archive)

**Comment by freddy77** [comment]
Closing, no reply (or I already did I suppose)
