### ISSUE TITLE
Empty strings

### ISSUE THREAD

**Issue by Chris00** [FreeTDS/freetds#212]
For a SQL request such as
```sql
SELECT CAST('' AS VARCHAR(10)) AS vc
```
the value returned by FreeTDS is `' '` (1 space) instead of the empty string.  For this `dbdatlen` returns a length of `1` while the SQL `LEN` clearly says it is `0`.

**Comment by freddy77** [comment]
DB-library was designed with protocol 4.x which does not allow empty strings.
FreeTDS supports however some extensions to allow program to handle empty string correctly.
Use dbdatlen. If this does returns 1 means that you are using still protocol 4.x.
