### ISSUE TITLE
Not able to build with Kerberos support on Ubuntu

### ISSUE THREAD

**Issue by jzwerling** [FreeTDS/freetds#218]
Have tried building from the source here: https://launchpad.net/ubuntu/+source/freetds/1.00.82-1 as well as from git.

Using these flags: `./autogen.sh --enable-krb5 --enable-msdblib --with-gnutls`, have also tried with just `--enable-krb5`, but after I make and install, tsql -C shows:

Version: freetds v1.00.82
freetds.conf directory: /usr/local/etc
MS db-lib source compatibility: yes
Sybase binary compatibility: no
Thread safety: yes
iconv library: yes
TDS version: auto
iODBC: no
unixodbc: yes
SSPI "trusted" logins: no
Kerberos: no
OpenSSL: no
GnuTLS: yes
MARS: no

Am I missing something?   Thank you.

**Comment by ramiro** [comment]
You should be using the nwer version 1.00.82-2  of the Debian/Ubuntu package as a starting base instead. 

Are you sure you've installed the header files, .etc. of depencencies, among them Kerberos (libkrb5-dev package)?: https://salsa.debian.org/vorlon/freetds/blob/master/debian/control#L10-18

Also, the steps the configure and build used to build by the .deb package  could be of help: https://salsa.debian.org/vorlon/freetds/blob/master/debian/rules

PS: IMHO thosissue tracker isnt the right place for these kind of user support questions. The mailing list or, say, StackOverflow would be better choices.

**Comment by freddy77** [comment]
I suppose this was solved with Ramiro answer.
