### ISSUE TITLE
Error 2404 (severity 4): 	Some character(s) could not be converted into client's character set

### ISSUE THREAD

**Issue by EnvyLan** [FreeTDS/freetds#220]
field  qita (varchar)
run   "select qita from fm_order where orderid = 'B630247933800293'"
output in tsql: 
2> go
qita
Error 2404 (severity 4):
	Some character(s) could not be converted into client's character set
... 请发到货信息提醒哈
(1 row affected)

with Java: 
![image](https://user-images.githubusercontent.com/15703555/42616987-bbd7fe7a-85e2-11e8-99f3-38fe1593105f.png)

**Comment by freddy77** [comment]
2018-07-12 7:51 GMT+01:00 Envylan <notifications@github.com>:

> field qita (varchar)
> run "select qita from fm_order where orderid = 'B630247933800293'"
> output in tsql:
> 2> go
> qita
> Error 2404 (severity 4):
> Some character(s) could not be converted into client's character set
> ... 请发到货信息提醒哈
> (1 row affected)
>
> with Java:
> [image: image]
> <https://user-images.githubusercontent.com/15703555/42616987-bbd7fe7a-85e2-11e8-99f3-38fe1593105f.png>
>
>
> Looks like the last character is not converted for some reason.
Can you send a TDSDUMP?
Which OS are you using?
Which iconv library are you using?
Is qita really varchar or nvarchar? Which collation?

Frediano

**Comment by EnvyLan** [comment]
TDSDUMP:
mem.c:651:tds_free_all_results()
util.c:165:Changed query state from IDLE to WRITING
util.c:165:Changed query state from WRITING to PENDING
packet.c:742:Sending packet
0000 01 01 00 98 00 00 01 00-16 00 00 00 12 00 00 00 |........ ........|
0010 02 00 00 00 00 00 00 00-00 00 01 00 00 00 53 00 |........ ......S.|
0020 45 00 4c 00 45 00 43 00-54 00 20 00 71 00 69 00 |E.L.E.C. T. .q.i.|
0030 74 00 61 00 20 00 66 00-72 00 6f 00 6d 00 20 00 |t.a. .f. r.o.m. .|
0040 46 00 4d 00 5f 00 4f 00-52 00 44 00 45 00 52 00 |F.M._.O. R.D.E.R.|
0050 20 00 77 00 68 00 65 00-72 00 65 00 20 00 6f 00 | .w.h.e. r.e. .o.|
0060 72 00 64 00 65 00 72 00-69 00 64 00 20 00 3d 00 |r.d.e.r. i.d. .=.|
0070 20 00 27 00 42 00 36 00-31 00 31 00 30 00 38 00 | .'.B.6. 1.1.0.8.|
0080 34 00 38 00 39 00 32 00-31 00 35 00 33 00 38 00 |4.8.9.2. 1.5.3.8.|
0090 33 00 35 00 27 00 0a 00-                        |3.5.'...|

token.c:532:tds_process_tokens(0x1ad98a0, 0x7ffec18d6b6c, (nil), 0x6914)
util.c:165:Changed query state from PENDING to READING
packet.c:640:Received packet
0000 04 01 00 42 00 7c 01 00-81 01 00 00 00 00 00 09 |...B.|.. ........|
0010 00 a7 00 04 04 08 d0 00-00 04 71 00 69 00 74 00 |........ ..q.i.t.|
0020 61 00 d1 10 00 c7 eb bc-b4 b7 a2 bb f5 3a d0 bb |a....... .....:..|
0030 d0 bb aa f7 20 fd 10 00-c1 00 01 00 00 00 00 00 |.... ... ........|
0040 00 00                  -                        |..|

token.c:547:processing result tokens.  marker is  81(TDS7_RESULT)
token.c:1554:processing TDS7 result metadata.
mem.c:651:tds_free_all_results()
token.c:1579:set current_results (1 column) to tds->res_info
token.c:1586:setting up 1 columns
token.c:3188:adjust_character_column_size:
	Server charset: CP936
	Server column_size: 1024
	Client charset: UTF-8
	Client column_size: 4096
token.c:1523:tds7_get_data_info: 
	colname = qita
	type = 39 (varchar)
	server's type = 167 (xvarchar)
	column_varint_size = 2
	column_size = 4096 (1024 on server)
token.c:1597: name                 size/wsize      type/wtype      utype  
token.c:1598: -------------------- --------------- --------------- -------
token.c:1603: qita                    4096/1024         39/167           0
util.c:165:Changed query state from READING to PENDING
token.c:532:tds_process_tokens(0x1ad98a0, 0x7ffec18d6b6c, (nil), 0x6914)
util.c:165:Changed query state from PENDING to READING
token.c:547:processing result tokens.  marker is  d1(ROW)
token.c:653:tds_process_tokens::SET_RETURN stopping on current token
util.c:165:Changed query state from READING to PENDING
token.c:532:tds_process_tokens(0x1ad98a0, 0x7ffec18d6b6c, (nil), 0x1508)
util.c:165:Changed query state from PENDING to READING
token.c:547:processing result tokens.  marker is  d1(ROW)
token.c:1935:tds_process_row(): reading column 0 
data.c:706:tds_get_data: type 39, varint size 2
data.c:750:tds_get_data(): wire column size is 16 
util.c:322:tdserror(0x1ad9740, 0x1ad98a0, 2404, 0)
util.c:352:tdserror: client library returned TDS_INT_CANCEL(2)
util.c:375:tdserror: returning TDS_INT_CANCEL(2)
stream.c:125:Error: tds_convert_stream: tds_iconv returned errno 84, conv_errno 84
stream.c:125:Error: tds_convert_stream: tds_iconv returned errno 84, conv_errno 84
stream.c:136:No conversion possible: some bytes left.
util.c:165:Changed query state from READING to PENDING
token.c:532:tds_process_tokens(0x1ad98a0, 0x7ffec18d6b6c, (nil), 0x1508)
util.c:165:Changed query state from PENDING to READING
token.c:547:processing result tokens.  marker is  fd(DONE)
token.c:2082:tds_process_end: more_results = 0
		was_cancelled = 0
		error = 0
		done_count_valid = 1
token.c:2099:                rows_affected = 1
token.c:2102:tds_process_end() state set to TDS_IDLE
util.c:165:Changed query state from READING to IDLE
util.c:83:logic error: cannot change query state from IDLE to PENDING
util.c:165:Changed query state from IDLE to IDLE
token.c:532:tds_process_tokens(0x1ad98a0, 0x7ffec18d6b6c, (nil), 0x6914)
token.c:535:tds_process_tokens() state is COMPLETED

OS: ubuntu 18.04

iconv:  iconv (Ubuntu GLIBC 2.27-3ubuntu1) 2.27

qita: varchar 

collation:  Chinese_PRC_CI_AS

tsql:

tsql -C                                                                                                                                                                               ~
Compile-time settings (established with the "configure" script)
                            Version: freetds v1.00.59
             freetds.conf directory: /usr/local/etc
     MS db-lib source compatibility: no
        Sybase binary compatibility: no
                      Thread safety: yes
                      iconv library: yes
                        TDS version: auto
                              iODBC: no
                           unixodbc: yes
              SSPI "trusted" logins: no
                           Kerberos: no
                            OpenSSL: yes
                             GnuTLS: no
                               MARS: no

**Comment by freddy77** [comment]
2018-07-20 7:22 GMT+01:00 Envylan <notifications@github.com>:

> TDSDUMP:
> mem.c:651:tds_free_all_results()
> util.c:165:Changed query state from IDLE to WRITING
> util.c:165:Changed query state from WRITING to PENDING
> packet.c:742:Sending packet
> 0000 01 01 00 98 00 00 01 00-16 00 00 00 12 00 00 00 |........ ........|
> 0010 02 00 00 00 00 00 00 00-00 00 01 00 00 00 53 00 |........ ......S.|
> 0020 45 00 4c 00 45 00 43 00-54 00 20 00 71 00 69 00 |E.L.E.C. T. .q.i.|
> 0030 74 00 61 00 20 00 66 00-72 00 6f 00 6d 00 20 00 |t.a. .f. r.o.m. .|
> 0040 46 00 4d 00 5f 00 4f 00-52 00 44 00 45 00 52 00 |F.M._.O. R.D.E.R.|
> 0050 20 00 77 00 68 00 65 00-72 00 65 00 20 00 6f 00 | .w.h.e. r.e. .o.|
> 0060 72 00 64 00 65 00 72 00-69 00 64 00 20 00 3d 00 |r.d.e.r. i.d. .=.|
> 0070 20 00 27 00 42 00 36 00-31 00 31 00 30 00 38 00 | .'.B.6. 1.1.0.8.|
> 0080 34 00 38 00 39 00 32 00-31 00 35 00 33 00 38 00 |4.8.9.2. 1.5.3.8.|
> 0090 33 00 35 00 27 00 0a 00- |3.5.'...|
>
> token.c:532:tds_process_tokens(0x1ad98a0, 0x7ffec18d6b6c, (nil), 0x6914)
> util.c:165:Changed query state from PENDING to READING
> packet.c:640:Received packet
> 0000 04 01 00 42 00 7c 01 00-81 01 00 00 00 00 00 09 |...B.|.. ........|
> 0010 00 a7 00 04 04 08 d0 00-00 04 71 00 69 00 74 00 |........ ..q.i.t.|
> 0020 61 00 d1 10 00 c7 eb bc-b4 b7 a2 bb f5 3a d0 bb |a....... .....:..|
> 0030 d0 bb aa f7 20 fd 10 00-c1 00 01 00 00 00 00 00 |.... ... ........|
> 0040 00 00 - |..|
>
> token.c:547:processing result tokens. marker is 81(TDS7_RESULT)
> token.c:1554:processing TDS7 result metadata.
> mem.c:651:tds_free_all_results()
> token.c:1579:set current_results (1 column) to tds->res_info
> token.c:1586:setting up 1 columns
> token.c:3188:adjust_character_column_size:
> Server charset: CP936
> Server column_size: 1024
> Client charset: UTF-8
> Client column_size: 4096
> token.c:1523:tds7_get_data_info:
> colname = qita
> type = 39 (varchar)
> server's type = 167 (xvarchar)
> column_varint_size = 2
> column_size = 4096 (1024 on server)
> token.c:1597: name size/wsize type/wtype utype
> token.c:1598: -------------------- --------------- --------------- -------
> token.c:1603: qita 4096/1024 39/167 0
> util.c:165:Changed query state from READING to PENDING
> token.c:532:tds_process_tokens(0x1ad98a0, 0x7ffec18d6b6c, (nil), 0x6914)
> util.c:165:Changed query state from PENDING to READING
> token.c:547:processing result tokens. marker is d1(ROW)
> token.c:653:tds_process_tokens::SET_RETURN stopping on current token
> util.c:165:Changed query state from READING to PENDING
> token.c:532:tds_process_tokens(0x1ad98a0, 0x7ffec18d6b6c, (nil), 0x1508)
> util.c:165:Changed query state from PENDING to READING
> token.c:547:processing result tokens. marker is d1(ROW)
> token.c:1935:tds_process_row(): reading column 0
> data.c:706:tds_get_data: type 39, varint size 2
> data.c:750:tds_get_data(): wire column size is 16
> util.c:322:tdserror(0x1ad9740, 0x1ad98a0, 2404, 0)
> util.c:352:tdserror: client library returned TDS_INT_CANCEL(2)
> util.c:375:tdserror: returning TDS_INT_CANCEL(2)
> stream.c:125:Error: tds_convert_stream: tds_iconv returned errno 84,
> conv_errno 84
> stream.c:125:Error: tds_convert_stream: tds_iconv returned errno 84,
> conv_errno 84
> stream.c:136:No conversion possible: some bytes left.
> util.c:165:Changed query state from READING to PENDING
> token.c:532:tds_process_tokens(0x1ad98a0, 0x7ffec18d6b6c, (nil), 0x1508)
> util.c:165:Changed query state from PENDING to READING
> token.c:547:processing result tokens. marker is fd(DONE)
> token.c:2082:tds_process_end: more_results = 0
> was_cancelled = 0
> error = 0
> done_count_valid = 1
> token.c:2099: rows_affected = 1
> token.c:2102:tds_process_end() state set to TDS_IDLE
> util.c:165:Changed query state from READING to IDLE
> util.c:83:logic error: cannot change query state from IDLE to PENDING
> util.c:165:Changed query state from IDLE to IDLE
> token.c:532:tds_process_tokens(0x1ad98a0, 0x7ffec18d6b6c, (nil), 0x6914)
> token.c:535:tds_process_tokens() state is COMPLETED
>
> OS: ubuntu 18.04
>
> iconv: iconv (Ubuntu GLIBC 2.27-3ubuntu1) 2.27
>
> qita: varchar
>
> collation: Chinese_PRC_CI_AS
>
> tsql:
>
> tsql -C ~
> Compile-time settings (established with the "configure" script)
> Version: freetds v1.00.59
> freetds.conf directory: /usr/local/etc
> MS db-lib source compatibility: no
> Sybase binary compatibility: no
> Thread safety: yes
> iconv library: yes
> TDS version: auto
> iODBC: no
> unixodbc: yes
> SSPI "trusted" logins: no
> Kerberos: no
> OpenSSL: yes
> GnuTLS: no
> MARS: no
>

That was really helpful.

Doing some tests with tsql o nmy machine:

1> create table #tmp2 (v varchar(100) collate Chinese_PRC_CI_AS)
2> insert into #tmp2 values(0xc7ebbcb4b7a2bbf53ad0bbd0bbaaf720)
3> go

1> select v from #tmp2
2> go
v
Error 2404 (severity 4):
        Some character(s) could not be converted into client's character set
请即发货:谢谢
(1 row affected)
1> select convert(nvarchar(100), v) from #tmp2
2> go

请即发货:谢谢
(1 row affected)



$ echo -n 'c7 eb bc b4 b7 a2 bb f5 3a d0 bb d0 bb aa f7 20 ' | perl -pe 's/
//g; $_ = pack("H*", $_)' | iconv -f cp936 -t utf8
请即发货:谢谢iconv: illegal input sequence at position 13


$ echo -n 'c7 eb bc b4 b7 a2 bb f5 3a d0 bb d0 bb aa f7 20 ' | perl -pe 's/
//g; $_ = pack("H*", $_)' | iconv -f GB18030 -t utf8
请即发货:谢谢

Apparently Windows moved from cp936 to gb18030 despite on many
documentation like
https://docs.microsoft.com/en-us/previous-versions/windows/embedded/ms930130(v=msdn.10)
they still say they use cp936.

As far as I read gb18030 (https://en.wikipedia.org/wiki/GB_18030) this
encoding is compatible
with former one so should not a problem to change to this new encoding.
The only concern is the support by the different iconv implementations.

This should fix your issue (surely Linux iconv support this encoding!):

--- a/src/tds/iconv.c
+++ b/src/tds/iconv.c
@@ -1182,7 +1182,7 @@ collate2charset(int sql_collate, int lcid)
                break;
        case 0x1004:
        case 0x804:             /* 0x20804 */
-               cp = TDS_CHARSET_CP936;
+               cp = TDS_CHARSET_GB18030;
                break;
        case 0x412:             /* 0x10412 */
                cp = TDS_CHARSET_CP949;


Frediano

**Comment by freddy77** [comment]
>
> This should fix your issue (surely Linux iconv support this encoding!):
>
> --- a/src/tds/iconv.c
> +++ b/src/tds/iconv.c
> @@ -1182,7 +1182,7 @@ collate2charset(int sql_collate, int lcid)
>                 break;
>         case 0x1004:
>         case 0x804:             /* 0x20804 */
> -               cp = TDS_CHARSET_CP936;
> +               cp = TDS_CHARSET_GB18030;
>                 break;
>         case 0x412:             /* 0x10412 */
>                 cp = TDS_CHARSET_CP949;
>
>

In master and Branch-1_00, enjoy

Frediano
