### ISSUE TITLE
Ensuring NTLMv2 protocol is used

### ISSUE THREAD

**Issue by rpyzh** [FreeTDS/freetds#221]
I am having hard time getting a successful authentication using NTLMv2 while connecting to SQL Sever instance (version 11.0.7462.6) from MacOSX (10.11.6).

It's related to issue #206 since I am trying to connect using a domain account, but I am not using Kerberos. Instead, I am simply providing both username (in 'domain-name\username' format) and password. I am able to successfully connect to the same SQL Server instance using jTDS driver, so I know that authentication using NTLMv2 works. In jTDS, all I have to do is set UseNTLMv2 to true and specify the domain for the user. My understanding is that FreeTDS does not have a separate configuration parameter for user domain specification and instead relies on DOMAIN\USERNAME convention to detect domain user logins.

I bumped debug flags in `freetds.conf` file to `0xffff` to see if I can get a confirmation that NTLMv2 is actually taking place, but I didn't see anything in the dump file that would unequivocally confirm that.

I thought that somehow driver version may play a role (got mine through a fairly recent `brew` recipe though), so I built the freetds v1.1.dev.2018.0724 to see if the bleeding edge would solve my problem. Alas, that didn't work nether. Still getting the following error:

```
Msg 18452 (severity 14, state 1) from <my sever info> Line 1:
     "Login failed. The login is form an untrusted domain and cannot be used with Windows authentication."
Error 20002 (severity 9):
      Adaptive Server connection failed
There was a problem connecting to the server
```
What would be a sure way to make FreeTDS use NTLMv2 protocol? Also, any way to make it visible in the dump file?

Thanks in advance for your help!

**Comment by freddy77** [comment]
2018-07-24 22:36 GMT+01:00 rpyzh <notifications@github.com>:

> I am having hard time getting a successful authentication using NTLMv2
> while connecting to SQL Sever instance (version 11.0.7462.6) from MacOSX
> (10.11.6).
>
> It's related to issue #206 <https://github.com/FreeTDS/freetds/issues/206>
> since I am trying to connect using a domain account, but I am not using
> Kerberos. Instead, I am simply providing both username (in
> 'domain-name\username' format) and password. I am able to successfully
> connect to the same SQL Server instance using jTDS driver, so I know that
> authentication using NTLMv2 works. In jTDS, all I have to do is set
> UseNTLMv2 to true and specify the domain for the user. My understanding is
> that FreeTDS does not have a separate configuration parameter for user
> domain specification and instead relies on DOMAIN\USERNAME convention to
> detect domain user logins.
>
> I bumped debug flags in freetds.conf file to 0xffff to see if I can get a
> confirmation that NTLMv2 is actually taking place, but I didn't see
> anything in the dump file that would unequivocally confirm that.
>
> I thought that somehow driver version may play a role (got mine through a
> fairly recent brew recipe though), so I built the freetds
> v1.1.dev.2018.0724 to see if the bleeding edge would solve my problem.
> Alas, that didn't work nether. Still getting the following error:
>
> Msg 18452 (severity 14, state 1) from <my sever info> Line 1:
>      "Login failed. The login is form an untrusted domain and cannot be used with Windows authentication."
> Error 20002 (severity 9):
>       Adaptive Server connection failed
> There was a problem connecting to the server
>
> What would be a sure way to make FreeTDS use NTLMv2 protocol? Also, any
> way to make it visible in the dump file?
>
> Thanks in advance for your help!
>
http://www.freetds.org/userguide/freetdsconf.htm, see "use ntlmv2",
http://www.freetds.org/userguide/odbcconnattr.htm see UseNTLMv2.
Not sure how to make visible in the dump, from a quick look is not
possible. Even raw data are omitted from the log for security reasons.

Frediano

**Comment by rpyzh** [comment]
Thanks for looking into it, Frediano.

I failed to mention on my original post that I have checked the manual and have tried adding `use ntlmv2 = yes` in `freetds.conf` as well as `UseNTLMv2 = Yes` in `odbc.ini`. I also made sure that I ran `odbcinst -i -s -f /etc/odbc.ini` for changes in `odbc.ini` to take effect.

Once I added source level info mask to `debug flag`, the dump file actually does show for `login.c` that it's using NTLM authentication, but I am not sure it fails to use NTLMv2 or not. What would the message look like if NTLMv2 was truly used?

**Comment by freddy77** [comment]
Can you try this patch:
```
diff --git a/src/tds/config.c b/src/tds/config.c
index 1ff3ad6c..1ec50e99 100644
--- a/src/tds/config.c
+++ b/src/tds/config.c
@@ -662,6 +662,7 @@ tds_parse_conf_section(const char *option, const char *value, void *param)
                s = tds_dstr_copy(&login->server_name, value);
        } else if (!strcmp(option, TDS_STR_USENTLMV2)) {
                login->use_ntlmv2 = tds_config_boolean(option, value, login);
+               login->use_ntlmv2_specified = 1;
        } else if (!strcmp(option, TDS_STR_USELANMAN)) {
                login->use_lanman = tds_config_boolean(option, value, login);
        } else if (!strcmp(option, TDS_STR_REALM)) {
```
?

**Comment by rpyzh** [comment]
Built freetds `v1.1.dev.20180726`, added the line from your patch, built again, installed. Still getting the same kind of error:
```
Msg 18452 (severity 14, state 1) from <server> Line 1:
       "Login failed. The login is from an untrusted domain and cannot be used with Windows authentication."
Error 20002 (severity 9):
       Adaptive Server connection failed
```

**Comment by freddy77** [comment]
To see the raw login packet try to comment out or remove the line
`        tdsdump_off();
`
in src/tds/login.c (you can also define `TDS_DEBUG_LOGIN` but maybe is not so easy and sure). In the log you should see NTLMSSP structure.

**Comment by rpyzh** [comment]
I just realized that that in my `tsql` testing command I have an unescaped special character. After properly escaping it, freeTDS was able to connect just fine, even without the patch above. My cross validation tool was not CLI, so I didn't catch a possible issue with the password.

Having said that, having the same `Login failed. The login is from an untrusted domain and cannot be used with Windows authentication.` message for locked out AD account, bad password, AND improper NTLM setting makes debugging very tricky. Any way to improve error messaging here?

**Comment by freddy77** [comment]
> Having said that, having the same `Login failed. The login is from an untrusted domain and cannot be used with Windows authentication.` message for locked out AD account, bad password, AND improper NTLM setting makes debugging very tricky. Any way to improve error messaging here?

You should ask Microsoft or Sybase but I think the reply is security. Imagine if an invalid user name would tell you "user name invalid", now you can test common user names or names of people or company group names. Now imagine you know if an account is locked or not, now you can test account locking policy and know if the password you are trying is wrong or just you locked out the account with too many attempts, hacker could use this to test passwords during the night so real people won't notice the attempts.

**Comment by ecki** [comment]
> You should ask Microsoft or Sybase 

in that case the "The login is from an untrusted domain and cannot be used with Windows authentication." part is probably missleading if it is not based on a specific error code.

**Comment by freddy77** [comment]
That error came from the server. I think is kind of wanted to avoid to tell the specific issue to avoid malicious users to get information from the attempts.
