### ISSUE TITLE
Numeric Value out of range when sending floats and numeric types to Sybase ASE 16

### ISSUE THREAD

**Issue by torrcm** [FreeTDS/freetds#223]
I have set up unixODBC and FreeTDS and always get the following when sending floats to an instance of Sybase ASE v 16 from the freetds.log file

prepare_query.c:198:parsing 0 parameters
sql2tds.c:174:type=3
sql2tds.c:182:trace
error.c:414:odbc_errs_add: "Numeric value out of range"

When I send values with a more than 2 digits on the right of the decimal place I receive the error above. When I send values with 1 digit everythign works. The scale of the values is registered as 7 in the odbc.log. when it is not defined as 7 in any of the data-types that are used. E.g numeric(3,2).

**Comment by torrcm** [comment]
In odbc.cpp->Parameter* ODBC::GetParametersFromArray (Local<Array> values, int *paramCount)  -> around line 732 ( in master ) see this section:

else if (value->IsNumber()) {
      double *number   = new double(value->NumberValue());
      
      params[i].ValueType         = SQL_C_DOUBLE;
      params[i].ParameterType     = SQL_DECIMAL;
      params[i].ParameterValuePtr = number;
      params[i].BufferLength      = sizeof(double);
      params[i].StrLen_or_IndPtr  = params[i].BufferLength;
      params[i].DecimalDigits     = 7;
      *params[i].ColumnSize        = sizeof(double);           //valid range is precision = 8, scale = 7 ie 2.1 etc is good
      **params[i].ColumnSize        = sizeof(double) + 1;     //valid range is precision = 9, scale = 7 ie 22.1 etc is good

The first "*" line maps to the precision in unixODBC which causes numbers with more than one digit on the left (eg 22.1) to be invalid which cause FreeTDS to throw a numeric scale error. I have rebuilt your project and run it again and confirmed that if the second "**" line is used then I can use numbers with two digits on the left of the decimal place ( precision = 9, scale = 7).

**Comment by qlecler** [comment]
Hey

Is it fixed ? I've the same issue.
