### ISSUE TITLE
Text is truncated due to multiple trailing zeros in buffer

### ISSUE THREAD

**Issue by renkun-ken** [FreeTDS/freetds#224]
For SQL Server, it is possible that when fetching a `text` field, the char buffer is not guaranteed to be fully filled and only the last char is `0`  before returning `SQL_NO_TOTAL` so that there are trailing zeros in the buffer in each iteration. The trailing zeros in the first buffer terminate the string so that the resulted text is truncated. 

See https://github.com/nanodbc/nanodbc/issues/174, https://github.com/r-dbi/odbc/issues/171.

**Comment by freddy77** [comment]
Confirmed a bug in FreeTDS

**Comment by freddy77** [comment]
Fixed in FreeTDS 1.00.103.
