### ISSUE TITLE
Infinite loop fetching text into buffer

### ISSUE THREAD

**Issue by renkun-ken** [FreeTDS/freetds#225]
For SQL Server, it is possible that fetching text into buffer may end up in an infinite loop where `SQL_SUCCESS_WITH_INFO` is always returned, indicating that there's always more texts to be fetched. However, when all texts are fetched, the subsequent iteration always leaves the empty buffer unchanged.

See https://github.com/nanodbc/nanodbc/issues/175, https://github.com/r-dbi/odbc/issues/171.

**Comment by freddy77** [comment]
Fixed in FreeTDS 1.00.103.
