### ISSUE TITLE
ODBC not rounding fractional seconds for DATETIME columns

### ISSUE THREAD

**Issue by gordthompson** [FreeTDS/freetds#228]
( prompted by https://github.com/mkleehammer/pyodbc/issues/448 )

FreeTDS ODBC version (dev): 01.00.0411

Test code (python 3.6 + pyodbc):

```python
s = '1900-01-01 00:00:00.007'
result = crsr.execute(f"SELECT CAST('{s}' AS DATETIME)").fetchval()
print(result)
```

When run using "ODBC Driver 17 for SQL Server" the code prints the correct result

```
1900-01-01 00:00:00.007000
```

However, when run using FreeTDS ODBC the fractional seconds are not rounded as required by the DATETIME data type

```
1900-01-01 00:00:00.006666
```

ODBC is aware of how many "Decimal Digits" the seconds should have ...

```
[ODBC][13496][1535041175.535408][SQLDescribeColW.c][467]
        Exit:[SQL_SUCCESS]                
            Column Name = [dt](unicode)                
            Data Type = 0x7fff85d90392 -> 93                
            Column Size = 0x7fff85d90398 -> 23                
            Decimal Digits = 0x7fff85d90394 -> 3                
            Nullable = 0x7fff85d90396 -> 1
...
[ODBC][13496][1535041175.535525][SQLGetData.c][237]
        Entry:
            Statement = 0x13c5e20
            Column Number = 1
            Target Type = 93 SQL_TYPE_TIMESTAMP
            Buffer Length = 16
            Target Value = 0x7fff85d90590
            StrLen Or Ind = 0x7fff85d90588
```

... so the driver should do the rounding to ensure the value returned matches the "actual" value in the database (i.e., millisecond precision, "rounded to increments of .000, .003, or .007 seconds", ref: [here](https://docs.microsoft.com/en-us/sql/t-sql/data-types/datetime-transact-sql)).

**Comment by freddy77** [comment]
No exactly wrong, I think Pyhon should round to the expected precision, "1900-01-01 00:00:00.007000" is technically wrong too. By the way, fixed in both branches (master and Branch-1_00)
