### ISSUE TITLE
dbbind returning garbage (octal bit patterns?) from mssql 2017 (C++ & Linux)

### ISSUE THREAD

**Issue by doctorzeus1aonly** [FreeTDS/freetds#235]
Hi,

I am currently creating a test application on Linux however currently I don't seem to be able to get the "dbbind" function to work after using the sample code from the user guide (http://www.freetds.org/userguide/samplecode.htm#SAMPLECODE.QUERY).

I am getting the column names, type etc back successfully however when returning the example column (JobID) I am getting "\020\355'UUU" instead of "1" as expected.

I am guessing this is probably something to do with encoding (currently locale is set to en_GB.UTF-8) however I am still having no luck even after setting "client charset = UTF-8" under freetds.conf.

I notice that 020 and 355 in octal is "DATA LINK ESCAPE" and "CARRIAGE RETURN" so don't know if this has anything to do with it?

Calling from dbadata lets me return text fields successfully but similar problem/s with other ones.

I am happy to provide code if needed.

Many Thanks.

**Comment by freddy77** [comment]
Probably depends on the type you bind to. If you expect a string you should bind with CHARBIND, STRINGBIND or something similar.
Send the code, should shed some light.

**Comment by freddy77** [comment]
Tried to compile the sample and did a simple "select * from sysobjects", the result is fine. What kind of binding are you using and what type is "JobID" column?

**Comment by freddy77** [comment]
Closing the issue, no replies in a month and is working for me.
