### ISSUE TITLE
Error while trying to execute data migration.

### ISSUE THREAD

**Issue by OsnielLopes** [FreeTDS/freetds#236]
Hi.

I'm using Django (1.6.8) and FreeTDS in a Mac to connect to an MSSQL server. While trying to run a Django migration I got the following error:

django.db.utils.ProgrammingError: ('25000', u'[25000] [FreeTDS][SQL Server]The ROLLBACK TRANSACTION request has no corresponding BEGIN TRANSACTION. (3903) (SQLEndTran)').

**Comment by freddy77** [comment]
Looks like Django forgot to start the transaction.
Which library (dblib/ctlib/odbc) is Django using?
Logs (see http://www.freetds.org/userguide/logging.htm or odbc tracing help) should help understand what went wrong.

**Comment by OsnielLopes** [comment]
I'm using ODBC.

Here's the configuration file.
<img width="570" alt="screen shot 2018-09-25 at 11 10 41" src="https://user-images.githubusercontent.com/22840423/46020482-e2695400-c0b4-11e8-86e3-6c2442f5172a.png">

I set up the environment variables of FreeTDS for logging, but nothing is generated.
![screen shot 2018-09-25 at 11 16 48](https://user-images.githubusercontent.com/22840423/46020489-e6957180-c0b4-11e8-8935-60282be11611.png)

**Comment by freddy77** [comment]
I remember sometimes with unixODBC I had to change system odbdinst.ini in order to get the trace.
For FreeTDS logging, does /temp/freetds directory exist?

**Comment by OsnielLopes** [comment]
Sorry for the delay.

Here are the logs:
[freetds.log](https://github.com/FreeTDS/freetds/files/2561801/freetds.log)
[traceodbc.txt](https://github.com/FreeTDS/freetds/files/2561809/traceodbc.txt)

And the execution output in terminal:
<img width="1486" alt="screen shot 2018-11-08 at 11 01 33" src="https://user-images.githubusercontent.com/22840423/48200239-a973fe80-e345-11e8-8bf2-e0891ba864cc.png">

**Comment by freddy77** [comment]
Mumble, from the log the error from FreeTDS seems correct. Django never set autocommit off so odbc does not start a transaction and complains when the caller attempt a rollback.
I'll check documentation and MS behaviour to see what should happen in such cases.

**Comment by freddy77** [comment]
Small update, I found this comment on Microsoft documentation helps:
"When a driver is in autocommit mode, the Driver Manager does not call SQLEndTran in the driver. SQLEndTran always returns SQL_SUCCESS regardless of whether it is called with a CompletionType of SQL_COMMIT or SQL_ROLLBACK. "
So it seems the DM should filter these calls. I'll check, just in case.

**Comment by freddy77** [comment]
Yes, tested under Windows, the DM doesn't even call SQLEndTran. Probably Unix/Linux DM instead calls the drivers but for compatibility the driver then should ignore the call. I already wrote a test.

**Comment by freddy77** [comment]
Fixed. Still convinced that Django should not issue a ROLLBACK if there's no transaction running.
