### ISSUE TITLE
SQL Server money precision must be 4

### ISSUE THREAD

**Issue by studentiks** [FreeTDS/freetds#237]
- FreeTDS: 1.00.96
- Unixodbc 2.3.7
- Python: 3.7.0
- pyodbc: 4.0.24
- OS: Linux
- DB: Microsoft SQL Server 2008 R2 (SP3) - 10.50.6220.0 (X64) 
- driver: FreeTDS

```python
db = pyodbc.connect(my_connection_string)
sql = 'SELECT CAST(0.1234 AS money)'
print(db.execute(sql).fetchall()[0]) 

# outputs (Decimal('0.12'), )
# expected (Decimal('0.1234'), )
```

All MSSQL versions should have [4-digits precision for money type](https://docs.microsoft.com/en-us/sql/t-sql/data-types/money-and-smallmoney-transact-sql?view=sql-server-2017)

Trace and very helpful guidelines were provided here: https://github.com/mkleehammer/pyodbc/issues/463

Is this configurable maybe? Thank you!

**Comment by freddy77** [comment]
Merged ODBC setting.
