### ISSUE TITLE
SQL Server 2016 Support

### ISSUE THREAD

**Issue by hmrc87** [FreeTDS/freetds#240]
Hi, whenever I connect to a SQL Server 2016 SQL Server tells me that the password does not match. Is this because the FreeTDS Library does not support 2016 yet?

**Comment by freddy77** [comment]
No, servers are backward compatible. FreeTDS is tested to work correctly with MSSQL 2017.
Common problems are quoting on shell if password contains uncommon characters, UseNTLMv2 flag or wrong domain for domain accounts.

**Comment by hmrc87** [comment]
I found the issue: The password was 32 characters long. Apparently this was an issue for the TSQL command

**Comment by freddy77** [comment]
That means that you are using an old protocol version which does not support long password!
I think the limit was lifted to 128 characters in SQL Server 7.0 (which was more than 20 years ago!)
