### ISSUE TITLE
Core dump in tds_socket_read

### ISSUE THREAD

**Issue by caohunan** [FreeTDS/freetds#241]
Hi Team,

I came across the following core dump a few times in a Ruby on Rails application that uses freetds to connect to a SQLServer database.
FreeTDSversion: freetds-1.00.21
OS: Ubuntu
Backtrace:
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ruby...done.
[New LWP 65303]
[New LWP 23]
[New LWP 25]
[New LWP 26]
[New LWP 31]
[New LWP 33]
[New LWP 34]
[New LWP 35]
[New LWP 36]
[New LWP 65314]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `puma: cluster worker 0: 16 [orderingportal]      '.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7fb21d43b700 (LWP 65303))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007fb22872042a in __GI_abort () at abort.c:89
#2  0x00007fb229492811 in die () at error.c:552
#3  rb_bug_context (ctx=ctx@entry=0x7fb20400ae40, 
    fmt=fmt@entry=0x7fb22964c33f "Segmentation fault at %p") at error.c:582
#4  0x00007fb229588902 in sigsegv (sig=11, info=0x7fb20400af70, ctx=0x7fb20400ae40) at signal.c:928
#5  <signal handler called>
#6  0x00007fb222292e7e in dbperror () from /usr/local/lib/libsybdb.so.5
#7  0x00007fb22229353b in _dblib_handle_err_message () from /usr/local/lib/libsybdb.so.5
#8  0x00007fb2222a8d7f in tdserror () from /usr/local/lib/libsybdb.so.5
#9  0x00007fb2222c7aa6 in tds_socket_read () from /usr/local/lib/libsybdb.so.5
#10 0x00007fb2222c7e0f in tds_goodread () from /usr/local/lib/libsybdb.so.5
#11 0x00007fb2222c7f22 in tds_connection_read () from /usr/local/lib/libsybdb.so.5
#12 0x00007fb2222cd30d in tds_read_packet () from /usr/local/lib/libsybdb.so.5
#13 0x00007fb2222abd3b in tds_get_byte () from /usr/local/lib/libsybdb.so.5
#14 0x00007fb2222a25de in tds_process_tokens () from /usr/local/lib/libsybdb.so.5
#15 0x00007fb22228d133 in dbsqlok () from /usr/local/lib/libsybdb.so.5
#16 0x00007fb2295ca629 in call_without_gvl (fail_if_interrupted=0, data2=<optimized out>, 
    ubf=<optimized out>, data1=0x7fb1fd687630, func=0x7fb22228cffd <dbsqlok>) at thread.c:1353
#17 rb_thread_call_without_gvl (func=0x7fb22228cffd <dbsqlok>, data1=data1@entry=0x7fb1fd687630, 
    ubf=ubf@entry=0x7fb2224f90e0 <dbcancel_ubf>, data2=data2@entry=0x7fb1fd687630) at thread.c:1463
#18 0x00007fb2224fa7ef in nogvl_dbsqlok (client=0x7fb1fd687630) at result.c:115
#19 rb_tinytds_result_ok_helper (client=0x7fb1fd687630) at result.c:165
#20 rb_tinytds_result_each (argc=1, argv=<optimized out>, self=140401415134160) at result.c:438
#21 0x00007fb2295f8bef in vm_call_cfunc_with_frame (ci=0x5630357c65d0, cc=<optimized out>, 
    calling=<optimized out>, reg_cfp=0x7fb1fecaa8a0, ec=0x7fb204015238) at vm_insnhelper.c:1918
#22 vm_call_cfunc (ec=0x7fb204015238, reg_cfp=0x7fb1fecaa8a0, calling=<optimized out>, 
    ci=0x5630357c65d0, cc=<optimized out>) at vm_insnhelper.c:1934
#23 0x00007fb229604549 in vm_exec_core (ec=ec@entry=0x7fb204015238, initial=initial@entry=0)
    at insns.def:915
#24 0x00007fb229608a80 in vm_exec (ec=ec@entry=0x7fb204015238) at vm.c:1778
#25 0x00007fb2296097bc in invoke_block (captured=0x7fb1fefad8e0, opt_pc=<optimized out>, 
    type=<optimized out>, cref=0x0, self=140401415003920, iseq=<optimized out>, ec=0x7fb204015238)
    at vm.c:979
#26 invoke_iseq_block_from_c (ec=0x7fb204015238, captured=0x7fb1fefad8e0, self=140401415003920, 
    argc=<optimized out>, argv=<optimized out>, passed_block_handler=0, cref=0x0, is_lambda=0)
    at vm.c:1031
#27 0x00007fb229609954 in invoke_block_from_c_proc (ec=0x7fb204015238, proc=<optimized out>, 
    self=<optimized out>, argc=0, argv=0x7fb21d436020, passed_block_handler=<optimized out>, 
    is_lambda=<optimized out>) at vm.c:1124
#28 0x00007fb229609a59 in vm_invoke_proc (ec=0x7fb204015238, proc=0x7fb1fefad8e0, self=140401415003920, 
    argc=argc@entry=0, argv=0x7fb21d436020, passed_block_handler=0) at vm.c:1149
#29 0x00007fb229609b04 in rb_vm_invoke_proc (ec=ec@entry=0x7fb204015238, proc=proc@entry=0x7fb1fefad8e0, 
    argc=argc@entry=0, argv=<optimized out>, passed_block_handler=<optimized out>) at vm.c:1179
#30 0x00007fb229609bd2 in vm_call_opt_call (ec=0x7fb204015238, cfp=0x7fb1fecaad20, 
    calling=0x7fb21d436120, ci=<optimized out>, cc=<optimized out>) at vm_insnhelper.c:2065
#31 0x00007fb229604549 in vm_exec_core (ec=ec@entry=0x7fb204015238, initial=initial@entry=0)
    at insns.def:915
#32 0x00007fb229608a80 in vm_exec (ec=ec@entry=0x7fb204015238) at vm.c:1778
#33 0x00007fb2296097bc in invoke_block (captured=0x7fb1fc595420, opt_pc=<optimized out>, 
    type=<optimized out>, cref=0x0, self=94765052935800, iseq=<optimized out>, ec=0x7fb204015238)
    at vm.c:979
#34 invoke_iseq_block_from_c (ec=0x7fb204015238, captured=0x7fb1fc595420, self=94765052935800, 
    argc=<optimized out>, argv=<optimized out>, passed_block_handler=0, cref=0x0, is_lambda=0)
    at vm.c:1031
#35 0x00007fb229609954 in invoke_block_from_c_proc (ec=0x7fb204015238, proc=<optimized out>, 
    self=<optimized out>, argc=1, argv=0x7fb21d436900, passed_block_handler=<optimized out>, 
    is_lambda=<optimized out>) at vm.c:1124
#36 0x00007fb229609a59 in vm_invoke_proc (ec=0x7fb204015238, proc=0x7fb1fc595420, self=94765052935800, 
    argc=argc@entry=1, argv=0x7fb21d436900, passed_block_handler=0) at vm.c:1149
#37 0x00007fb229609b04 in rb_vm_invoke_proc (ec=ec@entry=0x7fb204015238, proc=proc@entry=0x7fb1fc595420, 
    argc=argc@entry=1, argv=<optimized out>, passed_block_handler=<optimized out>) at vm.c:1179
#38 0x00007fb229609bd2 in vm_call_opt_call (ec=0x7fb204015238, cfp=0x7fb1fecaad80, 
    calling=0x7fb21d436a10, ci=<optimized out>, cc=<optimized out>) at vm_insnhelper.c:2065
#39 0x00007fb229604549 in vm_exec_core (ec=ec@entry=0x7fb204015238, initial=initial@entry=0)
    at insns.def:915

I cannot find any existing bugs in related to this stacktrace. By looking at the source code of freetds, it can be caused by the underling network flapping? 

Can you please share any insights which can be the root cause?

Thanks,
Frank

**Comment by freddy77** [comment]
I suppose you compiled FreeTDS by your own from the path.
Which Ubuntu version did you use?
Would be helpful to have /usr/local/lib/libsybdb.so.5 executable (even better with debug information).

**Comment by caohunan** [comment]
Hi @freddy77 

Thanks for the reply.

We did compile it from source code inside a Dockerfile (sorry I didn't know the reason that why we don't install from apt because I was not the original author of the application). The docker base image is ruby:2.5. Sorry I provided the misleading information saying the OS is Ubuntu because I saw the Dockerfile uses apt-get to install packages. I don't know the exact OS for the docker image ruby:2.5.

Dockerfile:
 ```
FROM ruby:2.5
 
 RUN mkdir /xxx
 RUN apt-get update && apt-get install -y build-essential libc6-dev sqlite3 libsqlite3-dev unixodbc-dev ruby-dev freetds-dev git mysql-client vim wget
 RUN apt-get install -y libssl1.0-dev
 
 WORKDIR /tmp
 RUN wget http://www.freetds.org/files/stable/freetds-1.00.21.tar.gz
 RUN tar -xzf freetds-1.00.21.tar.gz
 WORKDIR /tmp/freetds-1.00.21
 RUN ./configure CFLAGS='-Wswitch' --prefix=/usr/local --with-tdsver=7.1 && make && make install
 
 WORKDIR /xxx
 
 RUN gem install bundler
 COPY Gemfile Gemfile.lock /xxx/
 RUN bundle install
 COPY . /xxx/
 
 ENV RAILS_ENV=production
 ENV RACK_ENV=production
 RUN bundle exec rake assets:clobber assets:precompile
 
 VOLUME /xxx
 VOLUME /db
 EXPOSE 3000
 
 CMD [ "rails", "server", "-d", "-b", "0.0.0.0" ]
```

**Comment by freddy77** [comment]
No problems, but without executables is not easy to pinpoint the exact source lines so the stack trace that you sent is not really useful. Just the unstripped shared libraries would help.

**Comment by caohunan** [comment]
Thanks a lot. I have added --enable-debug option to ./configure. Hopefully, as the crash is not very often (once every 7-10 days), and we are still unclear the trigger of this problem. We will monitor it until it is recreated.

**Comment by freddy77** [comment]
Can I close this issue?

**Comment by freddy77** [comment]
Closing
