### ISSUE TITLE
freetds getting a tds_cancelled error

### ISSUE THREAD

**Issue by jpweins** [FreeTDS/freetds#247]
I'm new to freetds and I'm trying to execute a query from a Linux 4.14(A McAfee kernel) box to a mssql server.  

tds_version = 1796, product_version = 2318535108, product_name = 0x7fffd8001030 "Microsoft SQL Server"

I see the following message in gdb when I execute 
p *(TDSCOLUMN *)tds->res_info->columns  in tds_process_end().
.
.
bcp_terminator = 0x7ffff7172958 "Error converting characters into server's character set. Some character(s) could not be converted"}
.
.

ct_fetch() is returning a _FAIL.

As best I can determine the code is setting the error flag in tds_process_end in token.c line 2072.

What's really strange is this used to work when we used tls 1.0 and now breaks with tls 1.2.

Thanks is advance for any help.

Jay

**Comment by freddy77** [comment]
The error is not related to encryption but to character encoding.
Instead of using gdb try to use FreeTDS logging, see http://www.freetds.org/userguide/logging.htm.

**Comment by jpweins** [comment]
Thanks,

I forget to paste the freetds.log output.  Here's the tail end of it:

18:41:27.482667 18042 (data.c:706):tds_get_data: type 39, varint size 2
18:41:27.482672 18042 (data.c:750):tds_get_data(): wire column size is 24 
18:41:27.482678 18042 (token.c:1964):tds_process_nbcrow(): reading column 24 
18:41:27.482683 18042 (token.c:1964):tds_process_nbcrow(): reading column 25 
18:41:27.482688 18042 (data.c:706):tds_get_data: type 45, varint size 2
18:41:27.482693 18042 (data.c:750):tds_get_data(): wire column size is 8 
18:41:27.482697 18042 (token.c:1964):tds_process_nbcrow(): reading column 26 
18:41:27.482702 18042 (data.c:706):tds_get_data: type 39, varint size 2
18:41:27.482707 18042 (data.c:750):tds_get_data(): wire column size is 38 
18:41:27.482718 18042 (packet.c:640):Received packet
0000 04 01 00 35 00 5b 8d 00-20 00 43 00 6f 00 6c 00 |...5.[..  .C.o.l.|
0010 6c 00 65 00 63 00 74 00-69 00 6f 00 6e 00 00 00 |l.e.c.t. i.o.n...|
0020 00 00 00 00 00 00 00 00-fd 02 00 c1 00 00 00 00 |........ ........|
0030 00 00 00 00 00         -                        |.....|

18:41:27.482745 18042 (token.c:1964):tds_process_nbcrow(): reading column 27 
18:41:27.482752 18042 (data.c:706):tds_get_data: type 56, varint size 0
18:41:27.482770 18042 (data.c:750):tds_get_data(): wire column size is 4 
18:41:27.482775 18042 (token.c:1964):tds_process_nbcrow(): reading column 28 
18:41:27.482780 18042 (data.c:706):tds_get_data: type 56, varint size 0
18:41:27.482785 18042 (data.c:750):tds_get_data(): wire column size is 4 
18:41:27.482789 18042 (token.c:1964):tds_process_nbcrow(): reading column 29 
18:41:27.482794 18042 (data.c:706):tds_get_data: type 39, varint size 2
18:41:27.482799 18042 (data.c:750):tds_get_data(): wire column size is 0 
18:41:27.482803 18042 (token.c:547):processing result tokens.  marker is  fd(DONE)
18:41:27.482809 18042 (token.c:2082):tds_process_end: more_results = 0
		was_cancelled = 0
		error = 1
		done_count_valid = 0
18:41:27.482819 18042 (token.c:2101):                rows_affected = 0
18:41:27.482833 18042 (packet.c:640):Received packet
0000 04 01 00 15 00 5b 01 00-fd 20 00 fd 00 00 00 00 |.....[.. . ......|
0010 00 00 00 00 00         -                        |.....|

18:41:27.482847 18042 (token.c:547):processing result tokens.  marker is  fd(DONE)
18:41:27.482852 18042 (token.c:2082):tds_process_end: more_results = 0
		was_cancelled = 1
		error = 0
		done_count_valid = 0
18:41:27.482857 18042 (token.c:2101):                rows_affected = 0
18:41:27.482862 18042 (token.c:2104):tds_process_end() state set to TDS_IDLE
18:41:27.482866 18042 (util.c:165):Changed query state from READING to IDLE
18:41:27.482872 18042 (util.c:83):logic error: cannot change query state from IDLE to PENDING
18:41:27.482877 18042 (util.c:165):Changed query state from IDLE to IDLE
18:41:27.482882 18042 (ct.c:864):_ct_initialise_cmd(0x7fffd8000f70)
18:41:27.482888 18042 (ct.c:236):ct_describe_cmd_state(3)
18:41:27.482893 18042 (ct.c:236):ct_describe_cmd_state(0)
18:41:27.482897 18042 (ct.c:224):setting command state to IDLE (from SENT)
18:41:27.482902 18042 (ct.c:4085):rpc_clear((nil))
18:41:27.483003 18042 (ct.c:1850):ct_cmd_drop(0x7fffd8000f70)
18:41:27.483016 18042 (ct.c:1890):ct_close(0x6529e0, -99999)
18:41:27.483022 18042 (query.c:3797):tds_disconnect() 
18:41:27.483064 18042 (util.c:165):Changed query state from IDLE to DEAD
18:41:27.483075 18042 (mem.c:653):tds_free_all_results()

**Comment by jpweins** [comment]
Tried adding  client charset = UTF-8 and UTF-16 to freetds.conf without success.    Any suggestions?

Thanks

**Comment by jpweins** [comment]
[freetds.log.tar.gz](https://github.com/FreeTDS/freetds/files/2697041/freetds.log.tar.gz)

Attached is the freetds log file.   Thanks in advance for your help.

**Comment by freddy77** [comment]
Can I close the issue?

**Comment by jpweins** [comment]
Yes.   Thanks again for the help.

Jay
