### ISSUE TITLE
Changes in tds_willconvert.h

### ISSUE THREAD

**Issue by veprbl** [FreeTDS/freetds#251]
I was looking at the diff between the released tarballs freetds-1.00.109.tar.bz2 and freetds-1.00.110.tar.bz2. I see that the intentional change here is 05ec80fc3633e3cc2f62c346568951ec5836f138. And then there is a change to the generated "tds_willconvert.h" file:
https://gist.github.com/veprbl/38e57d17ad3e7e647627ddc8ee98f4da#file-freetds-diff-L447-L607
Maybe it happened because you used a different Perl version when releasing the tarball this time. This is probably fine, but I though I would report this just in case you want to know. Feel free to close this if you think that the script worked as you intended.

**Comment by freddy77** [comment]
Good catch!
But don't worry, is not a problem! It's just that when category indexes are generated inside the script the array (built from hash table values) they are not sorted so the order will change based on the hash order. But as they will be consistent with all table they work exactly the same way.
Nevertheless I'll update the script to avoid these changes in the future.

**Comment by veprbl** [comment]
@freddy77 Thank you for looking at this!
