### ISSUE TITLE
Availability group support exists in master branch but not Branch-1_00

### ISSUE THREAD

**Issue by JonSchuff** [FreeTDS/freetds#253]
Hello,

I've attempted to enable multi-subnet listeners for a SQL Server cluster using the freetds 1.0 release series, though it seems that the original commit, which added availability group support, only exists in the master branch (https://github.com/FreeTDS/freetds/commit/a98ba31b78ca1190987f33a22422f720cab801ef). Sample git log for context:

> freetds$ grep hist ~/.gitconfig
>	hist = log --pretty=format:\"%C(auto)%h %ad | %s%d [%an]\" --graph --date=short

> freetds$ git hist | grep -C 3 'attempt multiple connections if availability groups'
> * c76aea94 2016-07-22 | pool: Avoid to overwrite packet if not entirely written [Frediano Ziglio]
> * 54d45ec2 2016-07-18 | Extends cs_dt_crack to support newer types [Frediano Ziglio]
> * 51a6cf62 2016-07-18 | Make AppVeyor build with OpenSSL enabled [Frediano Ziglio]
> * a98ba31b 2016-06-21 | attempt multiple connections if availability groups are detected [Frediano Ziglio]
> * eb0c8c8d 2016-06-27 | Fix NUMERIC column for bcp native format [Frediano Ziglio]
> * c5663a27 2016-06-26 | Fix freebcp -E (identity columns) [Frediano Ziglio]
> * a848f9be 2016-06-22 | Fix build error on AIX 6.1 / 7.1 / 7.2 [Manfroi Fabrice]

> freetds$ git checkout Branch-1_00
> git Switched to branch 'Branch-1_00'
> Your branch is up to date with 'origin/Branch-1_00'.

> freetds$ git hist | grep -C 3 '2016-06-21'
> freetds$ git hist | grep -C 3 '2016-06-2'
> * 996900a2 2016-07-22 | pool: Avoid to overwrite packet if not entirely written [Frediano Ziglio]
> * 4393768c 2016-07-18 | Extends cs_dt_crack to support newer types [Frediano Ziglio]
> * 036e2830 2016-07-18 | Make AppVeyor build with OpenSSL enabled [Frediano Ziglio]
> * f9fec430 2016-06-27 | Fix NUMERIC column for bcp native format [Frediano Ziglio]
> * 407c41bf 2016-06-26 | Fix freebcp -E (identity columns) output [Frediano Ziglio]
> * 9a07a55c 2016-06-22 | Fix build error on AIX 6.1 / 7.1 / 7.2 [Manfroi Fabrice]
> * 94283044 2016-06-18 | Fix internal result state in dbcanquery [Frediano Ziglio]
> * d7dea73d 2016-06-18 | Avoid to strip spaces from procedure text. [Frediano Ziglio]
> * c56619d6 2016-06-17 | Avoid crash on connection error and report an error instead [Nem W Schlecht]

The underlying code has changed quite a bit since that feature was added on the master branch, or else I'd create a PR for it myself (I'm not very fluent in C). Any chance you'd be able to port that commit into the 1.x release series? I could give it a go as well if you prefer.

Thanks,
Jon

**Comment by freddy77** [comment]
Nope, but I hope to get a new release.

**Comment by JonSchuff** [comment]
Oh sweet, even better! Thx @freddy77

I could definitely deploy a RC build onto a canary node at my work if that'd help. Might not be a full breadth of testing, but I'd be able to perform a sanity check and see how it functions under production-level loads for all of our current uses cases (stack: python 3, pymssql)

**Comment by freddy77** [comment]
Just packaged a new RC and posted on ML (website already updated).
Have fun!

**Comment by freddy77** [comment]
Closed, 1.1 released! Enjoy.
