### ISSUE TITLE
Sybase large identifier support

### ISSUE THREAD

**Issue by boekhold** [FreeTDS/freetds#254]
Hi all,

Referencing an earlier discussion from 2011: https://lists.ibiblio.org/pipermail/freetds/2011q4/027480.html

Has support for large identifiers been integrated into FreeTDS? Searching the current source code, I can only find mention of TDS_REQ_LARGEIDENT in enum_cap.h, and nowhere else. Connecting with sqsh built against current FreeTDS to a Sybase ASE 16 dataserver, I am also not able to use large identifiers.

Since apparently patches for this where provided before (https://lists.ibiblio.org/pipermail/freetds/2011q4/027587.html), maybe this would not require too much effort?

Maarten

**Comment by freddy77** [comment]
Weird that I loss it. But in SUPPORTED_REQ_CAP there's LARGEIDENT so should be supported.
Maybe some other bits are missing?

**Comment by boekhold** [comment]
Actually seems I'm not using the latest FreeTDS version, I installed FreeTDS from the CentOS (EPEL?) repository on CentOS 7, and it's 0.95. Nevertheless, I cloned the git repo and checked out Branch-0_95, and I see this LARGEIDENT in the SUPPORTED_REQ_CAP...

Is there any way I can debug this capabilities negotiation to help figure out what's going on?

**Comment by boekhold** [comment]
OK, figured it out. My freetds,conf file had "8" as TDS version, which isn't recognized, so it falls back to 4.2, which I guess is "pre-large identifiers". Changed it to "tds version = 5.0" and it's working as expected now.

Closing this issue...
