### ISSUE TITLE
ftp.freetds.org is down

### ISSUE THREAD

**Issue by karen-phang** [FreeTDS/freetds#263]
Not sure where to escalate this, the FTP is down on a Friday evening. Hope it get address if that's possible

**Comment by freddy77** [comment]
You can use http://www.freetds.org/files/ in the meanwhile, I'll contact the admin

**Comment by januszm** [comment]
Systems that rely on libraries that use this FTP source may fail in catastrophic way when this server is down. E.g. systems using Ruby Gem https://github.com/rails-sqlserver/tiny_tds in versions 1.x.

**Comment by freddy77** [comment]
Is there a way to specify multiple URLs so other systems can fallback somehow?
