### ISSUE TITLE
Subscription request

### ISSUE THREAD

**Issue by tillea** [FreeTDS/freetds#264]
Hi,
as suggested on the mailing list page I'm hereby requesting subscription for the freetds mailing list to be able to post to freetds@lists.ibiblio.org.  Please subscribe me with the address
         tillea@rki.de
(not my github address which I use for Debian work only).
Please note that I'm sitting behind a firewall that does not even enable access to any page at https://lists.ibiblio.org - so I hope that I got things right here at Github.
Thank you, Andreas.

**Comment by freddy77** [comment]
Done, thanks

**Comment by tillea** [comment]
On Tue, Feb 26, 2019 at 03:27:22AM -0800, freddy77 wrote:
> Closed #264.
Extremely fast - thanks a lot!
