### ISSUE TITLE
Datacopy issue: Sybase Numeric vs MSSQL Numeric

### ISSUE THREAD

**Issue by tfishco** [FreeTDS/freetds#265]
Version: freetds-1.00.111

When performing a _datacopy_ from a Sybase database to an MSSQL database I am running into the following error:

```
COLUMN TYPE MISMATCH: column 2
source: type 62, length 8
dest : type 108, length 17
datacopy: table structures do not match. terminating
```

The above example occurred when copying Sybase numeric(10,0) to MSSQL numeric(10,0), but actually happens with any Sybase numeric to MSSQL numeric copy.

Sybase int to MSSQL int works as expected.

**Comment by freddy77** [comment]
Weird, looks like Sybase returns these numeric using DOUBLE (floating point) on network.
I'll check, maybe the solution should be more conversion during the copy.

**Comment by freddy77** [comment]
I tried multiple times to reproduce without success.
My servers return the number as `NUMERIC`, never `DOUBLE`.
