### ISSUE TITLE
Possible to make libtdsodbc.dylib on mac?

### ISSUE THREAD

**Issue by unhammer** [FreeTDS/freetds#267]
We're trying to link to freetds from Haskell on macos, but are getting 

```
ld: can't link with bundle (MH_BUNDLE) only dylibs (MH_DYLIB) file                             
'/Users/unhammer/src/tds/lib/libtdsodbc.so' for architecture x86_64                                                            
clang: error: linker command failed with exit code 1 (use -v to see                                                                                                           
invocation)                                              
/usr/bin/gcc -fno-stack-protector /var/folders/bq/4xy9knvx413dwltf9c6ngvvm0000gt/T/29815-10.c -o /var/folders/bq/4xy9knvx413dwltf9c6ngvvm0000gt/T/29815-11 -c '-D__GLASGOW_HAS
KELL__=804' '-Ddarwin_BUILD_OS=1' '-Dx86_64_BUILD_ARCH=1' '-Ddarwin_HOST_OS=1' '-Dx86_64_HOST_ARCH=1' -I.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/autogen -I. -I/Users/u
nhammer/.stack/programs/x86_64-osx/ghc-8.4.3/lib/ghc-8.4.3/base-4.11.1.0/include -I/Users/unhammer/.stack/programs/x86_64-osx/ghc-8.4.3/lib/ghc-8.4.3/integer-gmp-1.0.2.0/incl
ude -I/Users/unhammer/.stack/programs/x86_64-osx/ghc-8.4.3/lib/ghc-8.4.3/include                                                                                              
```

which I interpret (perhaps wrongly?) as ld not being able to link to .so, but preferring .dylib. 

Is it possible to create a dylib of libtdsodbc? I haven't been able to figure out this from the configure options.

**Comment by unhammer** [comment]
https://stackoverflow.com/a/2339910/69663 says you should add `-dynamiclib` to the linker on darwin.

https://github.com/google/zopfli/issues/82#issue-124615622 however shows a change to the `$(CC)` command in a makefile that changes 
`-Wl,-soname,libNAME.so.1 -o libNAME.so.1.0.1`
 to
 `-Wl,-install_name,libNAME.1.dylib -o libNAME.1.0.1.dylib`

**Comment by unhammer** [comment]
Actually, it seems we only need symbols from unixodbc for now, so I'll close this (though the above comment may be helpful if anyone in the future needs the whole tds too)

**Comment by freddy77** [comment]
Sorry, it's not clear. Were you trying to link directly to FreeTDS? Normally FreeTDS ODBC driver should be loaded from the DM (not sure if it's unixODBC for Mac), you are supposed to link FreeTDS directly in case you used `--with-odbc-nodm`, not sure if this works as you expect for Mac.

**Comment by unhammer** [comment]
Yes, I think I understand a bit more about how it works now. So in our case, we link into unixodbc.dylib compile-time, and that sees `FreeTDS` in the connection string, then loads the FreeTDS driver (dylib on mac) dynamically by looking up its path in `/etc/odbcinst.ini`. This seems to work for us :) 

On Linux, it doesn't seem to make a difference if I link to tdsodbc.so or odbc.so, but I suppose it worked the same way without me knowing why.
