### ISSUE TITLE
cs_will_convert not working for CS_DATE_TYPE and CS_TIME_TYPE

### ISSUE THREAD

**Issue by chitownhart** [FreeTDS/freetds#268]
The cs_will_convert doesn't seem to support the newer CS_DATE_TYPE and CS_TIME_TYPE values. This is even the case when both the source and target are the same type. The function succeeds but reports the conversion isn't possible. But, if I go ahead and call cs_convert anyway the conversion actually succeeds. I was glancing at the source and it looks like the tds_convert handler is generated from a Perl script and looks to be missing these types in the conversion matrix.

**Comment by freddy77** [comment]
Looks like cs_will_convert is completely broken!
It should accept CTLibrary types but pass them to tds_willconvert which is expected to accept TDS types so the issue.

**Comment by freddy77** [comment]
Fixed. Both Branch-1_1 and master
