### ISSUE TITLE
tdspool segmentation fault 

### ISSUE THREAD

**Issue by vstaf** [FreeTDS/freetds#27]
Hi all!
I try to launch tdspool (with default config files) but got segfault after it starts 

#/opt/freetds/bin/tdspool global
Found conf file in /opt/freetds/etc/pool.conf reading sections
Segmentation fault (core dumped)

https://www.dropbox.com/s/v543q33c3mgli03/core.4620?dl=0 coredump here

Linux 2.6.32-431.11.2.el6.i686 #1 SMP Tue Mar 25 17:17:46 UTC 2014 i686 i686 i386 GNU/Linux
(got same result on x64 server).
I'm pull freetds from master (same error with r95)
./configure --prefix=/opt/freetds
glibc-2.12-1.149.el6_6.9.i686

**Comment by freddy77** [comment]
Hi, which FreeTDS version are you trying? Actually tdspool is not in a good state. If you don't use master (last development version) is not expected to work.
A core without the executable is not that helpful.

**Comment by vstaf** [comment]
Hi!
I'm trying code from master.
https://www.dropbox.com/s/trcx5qvmfpi4bpc/freetds.zip?dl=0 here is archive with tdspool binary file and "fresh" crashdump

**Comment by freddy77** [comment]
There were no validation for pool configuration.
