### ISSUE TITLE
SQL Server and QUOTED_IDENTIFIER

### ISSUE THREAD

**Issue by JakeRuss** [FreeTDS/freetds#271]
Hello FreeTDS crew, 

Is it possible to change the default behavior of FreeTDS to `SET QUOTED_IDENTIFIER ON` when connecting to SQL Server? Or making it possible to set this parameter in the connection string? (I ask after searching through open and closed issues in this repository and not finding any comments on this topic.)

I ran into an issue with SQL Server and the R `odbc` library (see: https://github.com/r-dbi/odbc/issues/209, and https://github.com/tidyverse/dbplyr/issues/246) and the maintainers there think that FreeTDS is not consistent with other odbc drivers in this regard. I don't know much about odbc drivers, so I admit this claim may not be true, but I figured it was worth making this feature request. Thank you.

**Comment by freddy77** [comment]
Hi,
  it's not that FreeTDS is not consistent with other drivers, it that all drivers are not consistent.
Surely it's not good changing the default. Usually we follow MS default setting and I think we do (I'll check just in case). Surely is possible to add an option to connection string.

**Comment by JakeRuss** [comment]
The connection string option would be greatly appreciated.

**Comment by freddy77** [comment]
How to setup these R libraries? (I never used R in my life).
I checked and our ODBC correctly set the flag during connection and has that option on.
Maybe R is using DB-Library which set this option off ?

**Comment by JakeRuss** [comment]
I'm out of my depth on this one, but perhaps @jimhester will comment. I believe he is the right person to ask.

**Comment by freddy77** [comment]
FreeTDS ODBC driver turns on by default the `QUOTED_IDENTIFIER` setting connecting to MS server.
Exceptions are DB-library (which is not ODBC) and a TDS protocol < 7.0.
Can you use TDSDUMP to confirm which setting issue you are having?

**Comment by JakeRuss** [comment]
````
XXXXX$ tsql -C
Compile-time settings (established with the "configure" script)
                            Version: freetds v1.00.111
             freetds.conf directory: /usr/local/etc
     MS db-lib source compatibility: no
        Sybase binary compatibility: no
                      Thread safety: yes
                      iconv library: yes
                        TDS version: 7.3
                              iODBC: no
                           unixodbc: yes
              SSPI "trusted" logins: no
                           Kerberos: no
                            OpenSSL: yes
                             GnuTLS: no
                               MARS: no

**Comment by JakeRuss** [comment]
I appreciate your thoughts on this @freddy77. It appears the whole thing was caused by my specifying an old TDS driver in the `odbcinst.ini` file, which defaulted my R session to TDS 4.2. Once I referenced the updated driver, the 7.3 TDS protocol set `QUOTED_IDENTIFIER` correctly and the issue went away. Closing.

**Comment by jimhester** [comment]
Glad you figured out the cause!
