### ISSUE TITLE
CMake build fails with 'VERSION not found or wrong format'

### ISSUE THREAD

**Issue by warped-rudi** [FreeTDS/freetds#273]
This happened here on Windows with a freshly downloaded tarball. The problem seems to be line 19 of CMakeLists.txt, which checks for 'VERSION' instead of 'PACKAGE_VERSION'.

**Comment by freddy77** [comment]
Looks like a long standing issue in CMakeLists.txt!
Fixed, you should get an updated package tomorrow.
