### ISSUE TITLE
unable to connect with non-admin Azure sql server account

### ISSUE THREAD

**Issue by ahmettahasakar** [FreeTDS/freetds#274]
I have an Azure Sql server. If I try to add a sql server data source with the default admin account. Everything works. However, if I use the following commands to create a non-admin account, I'm unable to connect. I get 20018 and 20002 Adaptive Server errors. However, with any other client is just works. Is there something I'm missing?

```
CREATE LOGIN redash WITH PASSWORD = 'jksa34343hkjw232asd!';
CREATE USER redash FROM LOGIN redash;
ALTER ROLE db_datareader ADD MEMBER redash;
```

**Comment by freddy77** [comment]
Weird. SQL passwords are not special. The first thing I would check is that you are passing the exclamation point correctly, shells threat it specially.
Second check protocol version but being ASCII and not that long I don't think it's a problem.

**Comment by cmdrf** [comment]
Hey, which version of FreeTDS do you use? I also get inexplicable 20002 and 20018 errors with FreeTDS 1.1, but it  works with 1.0. Even better: 1.1 works on some compilers/kernels, but not on others. Really strange...

**Comment by freddy77** [comment]
Fixed.
