### ISSUE TITLE
[08S01][FreeTDS][SQL Server]Read from the server failed

### ISSUE THREAD

**Issue by njudd** [FreeTDS/freetds#278]
Hello everyone I am pretty new to SQL so apologies ahead of time.

I am receiving Read from the server failed, with an SQL statement that is nested.
This one works.
```select * from problems where phase_id in (select id from phases where account_id IN (SELECT account_id FROM accounts_groups WHERE group_id IN (SELECT id FROM groups WHERE name IN ( '_ages 5-6', '_ages 6-7', '_ages 7-8')) AND account_id IN (SELECT id FROM accounts WHERE created_at > '2018-08-01')))```

I redo the connection because I also get a Invalid cursor error.

This one does not work.
```select * from answers where problem_id in (select id from problems where phase_id IN (select id from phases where account_id IN (SELECT account_id FROM accounts_groups WHERE group_id IN (SELECT id FROM groups WHERE name IN ( '_ages 5-6', '_ages 6-7', '_ages 7-8')) AND account_id IN (SELECT id FROM accounts WHERE created_at > '2018-08-01'))))```

I don't understand why one would work yet one step further fails.

Thanks for your help

**Comment by freddy77** [comment]
Pretty complicated query and weird without joins. Beside that the "Read from the server failed" looks like something really wrong. Can happen if the client sent some weird command not recognized by the server or if the server sent back a reply which the client interpreted badly loosing the sync with the server.
A TDSDUMP would shed possibly the reason (or looking at server logs).
You could also try to replace the "*" in the selects with a "1" to remove possible unrecognised replies from server.
Some more information would help, like the various versions (mssql, FreeTDS, OS, TDS protocol).
Is it Sybase or Microsoft?

**Comment by njudd** [comment]
Apologies, I gave up on solving my issue and used a preconfigued microsoft centos data science server. I might come back to this when I have the time, thanks for your help.
