### ISSUE TITLE
Invalid severity level for "DBPROCESS is dead or not enabled"

### ISSUE THREAD

**Issue by rayrapetyan** [FreeTDS/freetds#283]
As per info googled in Internets, "DBPROCESS is dead or not enabled" is a connectivity issue on the client side, severity level should be EXCOMM at least (currently it's EXINFO).
It makes e.g. https://github.com/pymssql/pymssql/blob/fda5fd38f30eaeeb40a911235692144493d69864/src/_mssql.pyx#L1168 to spin infinitely, never raising StopIteration (in case issue occurred in the middle of fetching process). So would you accept a PR changing severity for that error? Thanks.

**Comment by freddy77** [comment]
Merged PR
