### ISSUE TITLE
Changed query state from IDLE to DEAD

### ISSUE THREAD

**Issue by LinLorry** [FreeTDS/freetds#288]
Hi, i get some problem when i use pymssql.
And then I try to use tsql,  but it doesn't work either.
Look like it down when login, but when change tds version to 5.0, log message change.
Server power by Ubuntu 16.94.5 LTS and freetds i clone it by git, so i think it is latest.

When i try 

`TDSVER=7.3 tsql -H host -p port -U user -p password`

Got following error:
>locale is "en_US.UTF-8"
>locale charset is "UTF-8"
>using default charset "UTF-8"
>Error 20017 (severity 9):
>	Unexpected EOF from the server
>Error 20002 (severity 9):
>	Adaptive Server connection failed
>There was a problem connecting to the server

And log:

>15:05:23.660309 21988 (packet.c:797):Sending packet
>0000 12 01 00 3a 00 00 00 00-00 00 1a 00 06 01 00 20 |...:.... ....... |
>0010 00 01 02 00 21 00 0c 03-00 2d 00 04 04 00 31 00 |....!... .-....1.|
>0020 01 ff 09 00 00 00 00 00-00 4d 53 53 51 4c 53 65 |........ .MSSQLSe|
>0030 72 76 65 72 00 e4 55 00-00 00                   |rver..U. ..|
>
>15:05:23.694318 21988 (util.c:165):Changed query state from IDLE to DEAD
>15:05:23.694357 21988 (util.c:319):tdserror(0x259d130, 0x259d650, 20017, 0)
>15:05:23.694430 21988 (util.c:349):tdserror: client library returned TDS_INT_CANCEL(2)
>15:05:23.694443 21988 (util.c:372):tdserror: returning TDS_INT_CANCEL(2)
>15:05:23.694451 21988 (packet.c:542):Read attempt when state is TDS_DEAD
>15:05:23.694458 21988 (login.c:569):login packet rejected
>15:05:23.694463 21988 (util.c:319):tdserror(0x259d130, 0x259d650, 20002, 0)
>15:05:23.694483 21988 (util.c:349):tdserror: client library returned TDS_INT_CANCEL(2)
>15:05:23.694490 21988 (util.c:372):tdserror: returning TDS_INT_CANCEL(2)
>15:05:23.694497 21988 (mem.c:656):tds_free_all_results()

When i try 

`TDSVER=5.0  tsql -H host -p port -U user -p password`

log:
>15:08:14.481229 22355 (net.c:528):tds_open_socket() succeeded`
and
>15:08:14.481422 22355 (token.c:416):tds_process_login_tokens()
15:08:14.515480 22355 (util.c:165):Changed query state from IDLE to DEAD
15:08:14.515538 22355 (util.c:319):tdserror(0x189b130, 0x189b650, 20017, 0)
15:08:14.515576 22355 (util.c:349):tdserror: client library returned TDS_INT_CANCEL(2)
15:08:14.515585 22355 (util.c:372):tdserror: returning TDS_INT_CANCEL(2)
15:08:14.515592 22355 (packet.c:542):Read attempt when state is TDS_DEAD
15:08:14.515598 22355 (token.c:420):looking for login token, got  0()
15:08:14.515605 22355 (token.c:129):tds_process_default_tokens() marker is 0()
15:08:14.515611 22355 (token.c:132):leaving tds_process_default_tokens() connection dead
15:08:14.515616 22355 (login.c:569):login packet accepted
15:08:14.515621 22355 (util.c:319):tdserror(0x189b130, 0x189b650, 20002, 0)
15:08:14.516393 22355 (util.c:349):tdserror: client library returned TDS_INT_CANCEL(2)
15:08:14.516411 22355 (util.c:372):tdserror: returning TDS_INT_CANCEL(2)
>15:08:14.516417 22355 (mem.c:656):tds_free_all_results()

Thanks for your attention.

**Comment by freddy77** [comment]
If you are not decided between 5.0 and 7.3 you should read some documentation (http://www.freetds.org/userguide/).
5.0 is only Sybase, 7.x are only Microsoft. Which server type do you have? (http://www.freetds.org/userguide/choosingtdsprotocol.htm)
If you are not sure about which FreeTDS version you are using try `tsql -C` (http://www.freetds.org/userguide/help.htm).

**Comment by LinLorry** [comment]
@freddy77 Thanks for your response.
My sever is Microsoft SQL Server 2008 R2. I will use tds 7.3 follow your advice.
This is my tsql -C
>                            Version: freetds v1.2.dev.20190507
>             freetds.conf directory: /usr/local/etc
>     MS db-lib source compatibility: yes
>        Sybase binary compatibility: no
>                      Thread safety: yes
>                      iconv library: yes
>                        TDS version: auto
>                              iODBC: no
>                           unixodbc: no
>              SSPI "trusted" logins: no
>                           Kerberos: no
>                            OpenSSL: yes
>                             GnuTLS: no
>                               MARS: yes

**Comment by LinLorry** [comment]
I can connect the same database by other server (tds version 7.3).
I don't think there is a problem with the configuration of the I database.
I have not idea to provide other message.

**Comment by freddy77** [comment]
Sure is not a firewall issue? The data sent seems fine, is not even attempting to send the login, looks like the server just closes the connection. Are you sure the port used is correct?

**Comment by LinLorry** [comment]
@freddy77 Thanks for your response.
This is my problem, i found i have other server on the port 8090, i stop it and connect success.
Sorry for the trouble.
