### ISSUE TITLE
Move TDS Connection Pooling to separate repository 

### ISSUE THREAD

**Issue by misterion** [FreeTDS/freetds#29]
FreeTDS is an big product with large history. And  TDS Connection Pooling obe thet things which should be important feature in it.

I propose to move TDS Connection Pooling to separate repository under FreeTDS organization. And If need it - add it as a submodule in the main project. This change allow us use separate release pipeline and faster development this project.

**Comment by freddy77** [comment]
I would prefer to increase release frequency. pool is currently quite bound to libTDS library which has no ABI (and don't want to have one).

**Comment by freddy77** [comment]
No replies in 2 weeks, I'll close the issue.
