### ISSUE TITLE
db-lib problem with VARYBINBIND

### ISSUE THREAD

**Issue by eranamitai** [FreeTDS/freetds#291]
We are new to FreeTDS, using db-lib functions against MS SQL Server. We execute a simple select to a varbinary column and bind the result back as follows:
```
DBVARYBIN varBinary;
dbbind(dbproc, 1, VARYBINBIND  , 0 , (BYTE *)&varBinary);
dbnextrow (dbproc);
```

But the value is not fetched. When I step through, I find that the `copy_data_to_host_var` function (dblib.c) has a specific section for dealing with matching source and destination types (direct copy, no conversion required) but the section doesn't code for a TDS_SERVER_TYPE of SYBVARBINARY, which is the type of both source and destinations.

Can anybody advise whether we are we doing it incorrectly or it's a hole in the dblib implementation?

Thanks,
Eran

**Comment by freddy77** [comment]
Merged, thanks, will be in tomorrow snapshot, both 1.1 and master,
