### ISSUE TITLE
Strings in TDS7 Login Packet Encoded As ASCII Instead of UCS-2

### ISSUE THREAD

**Issue by cmdrf** [FreeTDS/freetds#293]
I have a strange problem with the same program compiled on different environments. On Debian 9 it works. I used tcpdump to capture the login packet:

```
0000   08 00 27 ed b0 7b 00 e0 4c 68 41 50 08 00 45 00   ..'í°{.àLhAP..E.
0010   00 f8 c3 5f 40 00 40 06 ca 1a c0 a8 15 b4 c0 a8   .øÃ_@.@.Ê.À¨.´À¨
0020   15 81 a3 5e 05 99 10 52 94 b6 99 c3 28 5e 80 18   ..£^...R.¶.Ã(^..
0030   00 e5 58 4b 00 00 01 01 08 0a 00 44 57 20 00 1a   .åXK.......DW ..
0040   e0 a9 10 01 00 c4 00 00 00 00 bc 00 00 00 04 00   à©...Ä....¼.....
0050   00 74 00 10 00 00 06 83 f2 f8 86 7e 00 00 00 00   .t......òø.~....
0060   00 00 e0 01 00 08 88 ff ff ff 36 04 00 00 5e 00   ..à....ÿÿÿ6...^.
0070   07 00 6c 00 03 00 72 00 03 00 78 00 00 00 78 00   ..l...r...x...x.
0080   0e 00 00 00 00 00 94 00 0a 00 a8 00 0a 00 bc 00   ..........¨...¼.
0090   00 00 00 e0 4c 68 41 50 bc 00 00 00 bc 00 00 00   ...àLhAP¼...¼...
00a0   bc 00 00 00 00 00 00 00 67 00 72 00 6f 00 6c 00   ¼.......g.r.o.l.
00b0   73 00 63 00 68 00 74 00 73 00 74 00 e2 a5 92 a5   s.c.h.t.s.t.â¥.¥
00c0   e2 a5 31 00 39 00 32 00 2e 00 31 00 36 00 38 00   â¥1.9.2...1.6.8.
00d0   2e 00 32 00 31 00 2e 00 31 00 32 00 39 00 44 00   ..2.1...1.2.9.D.
00e0   42 00 2d 00 4c 00 69 00 62 00 72 00 61 00 72 00   B.-.L.i.b.r.a.r.
00f0   79 00 75 00 73 00 5f 00 65 00 6e 00 67 00 6c 00   y.u.s._.e.n.g.l.
0100   69 00 73 00 68 00                                 i.s.h.
```

Note that in the string section at the end, every character has two bytes.

The login to the same server from a different machine with a different Linux distro:

```
0000   08 00 27 ed b0 7b 22 e1 80 a5 10 21 08 00 45 00   ..'í°{"á.¥.!..E.
0010   00 ce f6 90 40 00 40 06 97 c6 c0 a8 15 01 c0 a8   .Îö.@.@..ÆÀ¨..À¨
0020   15 81 ea f8 05 99 64 33 eb 36 24 c3 c3 65 80 18   ..êø..d3ë6$ÃÃe..
0030   00 e5 53 11 00 00 01 01 08 0a ff ff 1c 77 00 1a   .åS.......ÿÿ.w..
0040   70 4c 10 01 00 9a 00 00 00 00 92 00 00 00 04 00   pL..............
0050   00 74 00 10 00 00 06 83 f2 f8 11 02 00 00 00 00   .t......òø......
0060   00 00 e0 01 00 08 88 ff ff ff 36 04 00 00 5e 00   ..à....ÿÿÿ6...^.
0070   06 00 6a 00 01 00 6d 00 01 00 70 00 00 00 70 00   ..j...m...p...p.
0080   07 00 00 00 00 00 7e 00 05 00 88 00 05 00 92 00   ......~.........
0090   00 00 22 e1 80 a5 10 21 92 00 00 00 92 00 00 00   .."á.¥.!........
00a0   92 00 00 00 00 00 00 00 6f 74 68 65 72 6d 61 63   ........othermac
00b0   68 69 6e 65 74 73 74 e2 92 e2 31 39 32 2e 31 36   hinetstâ.â192.16
00c0   38 2e 32 31 2e 31 32 39 44 42 2d 4c 69 62 72 61   8.21.129DB-Libra
00d0   72 79 75 73 5f 65 6e 67 6c 69 73 68               ryus_english

```

The server then complains it cannot find a user whose name is a chinese looking character. The lengths and offset in the packet body also don't match up.

![grafik](https://user-images.githubusercontent.com/12779694/59875735-d4c1d000-93a1-11e9-94a0-51dd40703c97.png)

First machine is Debian 9 on amd64 with gcc 6.3.0. Second machine is a OpenEmbedded-derived distro with gcc 7.2.0, also running on amd64. FreeTDS was cross-compiled with `./configure --build=x86_64-linux-gnu --host=x86_64-bogus-gnu --target=x86_64-bogus-gnu`. `iconv -l` gives the same output on both machines which includes UCS-2LE and UCS-2BE.

I also tried an older version of the OpenEmbedded-derived distro with gcc 5.2.0. Login fails with some out-of-memory error.

I tried FreeTDS 1.1.6 and today's nightly. FreeTDS 1.0 works after some tries, because it seems to fall back to TDS4/5 login packets.

I will further investigate this, but any help is appreciated!

[login-debian9.pcap.gz](https://github.com/FreeTDS/freetds/files/3311790/login-debian9.pcap.gz)
[login-othermachine.pcap.gz](https://github.com/FreeTDS/freetds/files/3311792/login-othermachine.pcap.gz)

**Comment by freddy77** [comment]
Il giorno gio 20 giu 2019 alle ore 20:26 Fabian <notifications@github.com>
ha scritto:

> I have a strange problem with the same program compiled on different
> environments. On Debian 9 it works. I used tcpdump to capture the login
> packet:
>
> 0000   08 00 27 ed b0 7b 00 e0 4c 68 41 50 08 00 45 00   ..'í°{.àLhAP..E.
>
> 0010   00 f8 c3 5f 40 00 40 06 ca 1a c0 a8 15 b4 c0 a8   .øÃ_@.@.Ê.À¨.´À¨
>
> 0020   15 81 a3 5e 05 99 10 52 94 b6 99 c3 28 5e 80 18   ..£^...R.¶.Ã(^..
>
> 0030   00 e5 58 4b 00 00 01 01 08 0a 00 44 57 20 00 1a   .åXK.......DW ..
>
> 0040   e0 a9 10 01 00 c4 00 00 00 00 bc 00 00 00 04 00   à©...Ä....¼.....
>
> 0050   00 74 00 10 00 00 06 83 f2 f8 86 7e 00 00 00 00   .t......òø.~....
>
> 0060   00 00 e0 01 00 08 88 ff ff ff 36 04 00 00 5e 00   ..à....ÿÿÿ6...^.
>
> 0070   07 00 6c 00 03 00 72 00 03 00 78 00 00 00 78 00   ..l...r...x...x.
>
> 0080   0e 00 00 00 00 00 94 00 0a 00 a8 00 0a 00 bc 00   ..........¨...¼.
>
> 0090   00 00 00 e0 4c 68 41 50 bc 00 00 00 bc 00 00 00   ...àLhAP¼...¼...
>
> 00a0   bc 00 00 00 00 00 00 00 67 00 72 00 6f 00 6c 00   ¼.......g.r.o.l.
>
> 00b0   73 00 63 00 68 00 74 00 73 00 74 00 e2 a5 92 a5   s.c.h.t.s.t.â¥.¥
>
> 00c0   e2 a5 31 00 39 00 32 00 2e 00 31 00 36 00 38 00   â¥1.9.2...1.6.8.
>
> 00d0   2e 00 32 00 31 00 2e 00 31 00 32 00 39 00 44 00   ..2.1...1.2.9.D.
>
> 00e0   42 00 2d 00 4c 00 69 00 62 00 72 00 61 00 72 00   B.-.L.i.b.r.a.r.
>
> 00f0   79 00 75 00 73 00 5f 00 65 00 6e 00 67 00 6c 00   y.u.s._.e.n.g.l.
>
> 0100   69 00 73 00 68 00                                 i.s.h.
>
>
> Note that in the string section at the end, every character has two bytes.
>
> The login to the same server from a different machine with a different
> Linux distro:
>
> 0000   08 00 27 ed b0 7b 22 e1 80 a5 10 21 08 00 45 00   ..'í°{"á.¥.!..E.
>
> 0010   00 ce f6 90 40 00 40 06 97 c6 c0 a8 15 01 c0 a8   .Îö.@.@..ÆÀ¨..À¨
>
> 0020   15 81 ea f8 05 99 64 33 eb 36 24 c3 c3 65 80 18   ..êø..d3ë6$ÃÃe..
>
> 0030   00 e5 53 11 00 00 01 01 08 0a ff ff 1c 77 00 1a   .åS.......ÿÿ.w..
>
> 0040   70 4c 10 01 00 9a 00 00 00 00 92 00 00 00 04 00   pL..............
>
> 0050   00 74 00 10 00 00 06 83 f2 f8 11 02 00 00 00 00   .t......òø......
>
> 0060   00 00 e0 01 00 08 88 ff ff ff 36 04 00 00 5e 00   ..à....ÿÿÿ6...^.
>
> 0070   06 00 6a 00 01 00 6d 00 01 00 70 00 00 00 70 00   ..j...m...p...p.
>
> 0080   07 00 00 00 00 00 7e 00 05 00 88 00 05 00 92 00   ......~.........
>
> 0090   00 00 22 e1 80 a5 10 21 92 00 00 00 92 00 00 00   .."á.¥.!........
>
> 00a0   92 00 00 00 00 00 00 00 6f 74 68 65 72 6d 61 63   ........othermac
>
> 00b0   68 69 6e 65 74 73 74 e2 92 e2 31 39 32 2e 31 36   hinetstâ.â192.16
>
> 00c0   38 2e 32 31 2e 31 32 39 44 42 2d 4c 69 62 72 61   8.21.129DB-Libra
>
> 00d0   72 79 75 73 5f 65 6e 67 6c 69 73 68               ryus_english
>
>
>
>
> The server then complains it cannot find a user whose name is a chinese
> looking character. The lengths and offset in the packet body also don't
> match up.
>
> [image: grafik]
> <https://user-images.githubusercontent.com/12779694/59875735-d4c1d000-93a1-11e9-94a0-51dd40703c97.png>
>
> First machine is Debian 9 on amd64 with gcc 6.3.0. Second machine is a
> OpenEmbedded-derived distro with gcc 7.2.0, also running on amd64. FreeTDS
> was cross-compiled with ./configure --build=x86_64-linux-gnu
> --host=x86_64-bogus-gnu --target=x86_64-bogus-gnu. iconv -l gives the
> same output on both machines which includes UCS-2LE and UCS-2BE.
>
> I also tried an older version of the OpenEmbedded-derived distro with gcc
> 5.2.0. Login fails with some out-of-memory error.
>
> I tried FreeTDS 1.1.6 and today's nightly. FreeTDS 1.0 works after some
> tries, because it seems to fall back to TDS4/5 login packets.
>
> I will further investigate this, but any help is appreciated!
>
> login-debian9.pcap.gz
> <https://github.com/FreeTDS/freetds/files/3311790/login-debian9.pcap.gz>
> login-othermachine.pcap.gz
> <https://github.com/FreeTDS/freetds/files/3311792/login-othermachine.pcap.gz>
>
> Hi,
  it looks like for some reasons FreeTDS is using an invalid encode name
for UTF16 (Microsoft moved to UTF16 from UCS2 time ago).
I think would be worth seeing config.h and configure log. Maybe it's a
problem with cross compilation.
Did you try TDSDUMP ? First lines should log the encodings used.
Maybe iconv command is not using same iconv implementation on the 2
machines.

Frediano

**Comment by cmdrf** [comment]
Hey Frediano,

thanks for the reply! Here's a diff of confg.h on the two setups (left is Debian):
```diff
67c67
< /* #undef HAVE_COM_ERR_H */
---
> #define HAVE_COM_ERR_H 1
213c213
< /* #undef HAVE_GNUTLS_ABSTRACT_H */
---
> #define HAVE_GNUTLS_ABSTRACT_H 1
365c365
< #define HAVE_SQLGETPRIVATEPROFILESTRING 1
---
> /* #undef HAVE_SQLGETPRIVATEPROFILESTRING */
368c368
< #define HAVE_SQLLEN 1
---
> /* #undef HAVE_SQLLEN */
377c377
< #define HAVE_SQLSETPOSIROW 1
---
> /* #undef HAVE_SQLSETPOSIROW */
380c380
< #define HAVE_SQL_H 1
---
> /* #undef HAVE_SQL_H */
469c469
< #define HAVE_VALGRIND_MEMCHECK_H 1
---
> /* #undef HAVE_VALGRIND_MEMCHECK_H */
600c600
< #define SIZEOF_SQLWCHAR 2
---
> #define SIZEOF_SQLWCHAR 0
656c656
< #define TDS_SQLCOLATTRIBUTE_SQLLEN 1
---
> /* #undef TDS_SQLCOLATTRIBUTE_SQLLEN */
659c659
< #define TDS_SQLPARAMOPTIONS_SQLLEN 1
---
> /* #undef TDS_SQLPARAMOPTIONS_SQLLEN */
```

`#define SIZEOF_SQLWCHAR 0` doesn't seem right. But it seems to be only used in odbc.h, and there it should report an `#error`. I don't use ODBC.

I'd prefer CMake to `configure` anyway, but that fails on both setups.

**Comment by cmdrf** [comment]
> Did you try TDSDUMP ? First lines should log the encodings used.

Debian says:
```
iconv.c:326:tds_iconv_open(0x7f81d0004800, UTF-8)
iconv.c:348:setting up conversions for client charset "UTF-8"
iconv.c:350:preparing iconv for "UTF-8" <-> "UCS-2LE" conversion
iconv.c:389:tds_iconv_open: done
```

Other machine says:
```
iconv.c:326:tds_iconv_open(0x7f29a8037170, ISO-8859-1)
iconv.c:348:setting up conversions for client charset "ISO-8859-1"
iconv.c:350:preparing iconv for "ISO-8859-1" <-> "UCS-2LE" conversion
iconv.c:389:tds_iconv_open: done
```

**Comment by freddy77** [comment]
Il giorno mer 26 giu 2019 alle ore 10:34 Fabian <notifications@github.com>
ha scritto:

> Hey Frediano,
>
> thanks for the reply! Here's a diff of confg.h on the two setups (left is
> Debian):
>
> 67c67< /* #undef HAVE_COM_ERR_H */---> #define HAVE_COM_ERR_H 1213c213< /* #undef HAVE_GNUTLS_ABSTRACT_H */---> #define HAVE_GNUTLS_ABSTRACT_H 1365c365< #define HAVE_SQLGETPRIVATEPROFILESTRING 1---> /* #undef HAVE_SQLGETPRIVATEPROFILESTRING */368c368< #define HAVE_SQLLEN 1---> /* #undef HAVE_SQLLEN */377c377< #define HAVE_SQLSETPOSIROW 1---> /* #undef HAVE_SQLSETPOSIROW */380c380< #define HAVE_SQL_H 1---> /* #undef HAVE_SQL_H */469c469< #define HAVE_VALGRIND_MEMCHECK_H 1---> /* #undef HAVE_VALGRIND_MEMCHECK_H */600c600< #define SIZEOF_SQLWCHAR 2---> #define SIZEOF_SQLWCHAR 0656c656< #define TDS_SQLCOLATTRIBUTE_SQLLEN 1---> /* #undef TDS_SQLCOLATTRIBUTE_SQLLEN */659c659< #define TDS_SQLPARAMOPTIONS_SQLLEN 1---> /* #undef TDS_SQLPARAMOPTIONS_SQLLEN */
>
> #define SIZEOF_SQLWCHAR 0 doesn't seem right. But it seems to be only
> used in odbc.h, and there it should report an #error. I don't use ODBC.
>

Normal if ODBC is not compiled, not a problem.
I cannot find anything specific to iconv.

> I'd prefer CMake to configure anyway, but that fails on both setups.
>
Currently CMake is more for Windows, it misses a lot of tests present in
autoconf. The rule is simply CMake for Windows, autoconf for everything
else.

Frediano

**Comment by freddy77** [comment]
Il giorno mer 26 giu 2019 alle ore 14:18 Fabian <notifications@github.com>
ha scritto:

> Did you try TDSDUMP ? First lines should log the encodings used.
>
> Debian says:
>
> iconv.c:326:tds_iconv_open(0x7f81d0004800, UTF-8)
> iconv.c:348:setting up conversions for client charset "UTF-8"
> iconv.c:350:preparing iconv for "UTF-8" <-> "UCS-2LE" conversion
> iconv.c:389:tds_iconv_open: done
>
> Other machine says:
>
> iconv.c:326:tds_iconv_open(0x7f29a8037170, ISO-8859-1)
> iconv.c:348:setting up conversions for client charset "ISO-8859-1"
> iconv.c:350:preparing iconv for "ISO-8859-1" <-> "UCS-2LE" conversion
> iconv.c:389:tds_iconv_open: done
>
> Broken iconv implementation?

Can you try with --disable-libiconv? It's not a recommended setup but for
testing connection it's fine.

I would also try GNU iconv library. See --with-libiconv-prefix option (
https://www.freetds.org/userguide/config.htm) and obviously iconv (
https://www.gnu.org/software/libiconv/).

Frediano

**Comment by cmdrf** [comment]
I made my own CMakeLists.txt (which basically just adds all the source files), copied the config.h from my Debian machine, and still had the same results on the target machine. Then I set `HAVE_ICONV` to 0 to force the usage of the functions in `replacements/iconv.c` (this is probably what `--disable-libiconv` does). Now it works!

So it seems to be a problem with the iconv implementation on the target machine, and FreeTDS is not detecting this problem.

**Comment by freddy77** [comment]
Well, detecting a runtime issue while cross compiling is kind of magic. Also is not responsibility of a library to check that dependencies are not buggy, unless you want to implement specific workaround for specific bugs.
Said that I would try to understand what is the specific iconv implementation this OpenEmbedded Linux is using and trying to understand the bug in order to report and have it fixed.

**Comment by freddy77** [comment]
Should I close his bug here? Look like a distro issue.

**Comment by cmdrf** [comment]
It might be a  distro issue, but maybe there is a way to catch this? Maybe an `assert` about the length of the converted strings. We know it should be two bytes per character. If we get one byte per character, something is fishy.

**Comment by freddy77** [comment]
> It might be a distro issue, but maybe there is a way to catch this? Maybe an `assert` about the length of the converted strings. We know it should be two bytes per character. If we get one byte per character, something is fishy.

This was true 20 years ago. But I can try to convert an ASCII string and check the result in tds_iconv_init, just to make sure the base of UTF-8, UCS-2/UTF16 (or at least the base expected encodings).

**Comment by freddy77** [comment]
Add a check in master
