### ISSUE TITLE
Newer (1.1.6) FreeTDS rpm's for CentOS 7 to solve encoding issues with version 0.95 version available in EPEL

### ISSUE THREAD

**Issue by DrLove73** [FreeTDS/freetds#295]
Hi.
I had an issue using tds_fdw with freetds 0.95 on CentOS 7 with regards to encodings. I connect to MSSQL 2008R2 from PostgreSQL 10 server via Foreign data wrapper (Foreign tables) and since MSSQL database uses Serbian_Latin encoding, Serbian letters were not properly converted.
I reported it in tds_fdw here: https://github.com/tds-fdw/tds_fdw/issues/111#issuecomment-503175971 and came to conclusion Serbian_latin is not supported by freetds 0.95 so I ventured to create/rebuild rpms provided by EPEL to version 1.1.6.

I fired up my rpm rebuilding skills and I managed to update EPEL's src.rpm to version 1.1.6 (replaced tar.bz2, and in spec file changed version number and --with-tdsver="7.3" from --with-tdsver="4.2" ).
Since there are no rpm's for CentOS 7, I am publishing rpm and src.rpm files in my old repo: http://centos.plnet.rs/mrepo/plnet-centos7-x86_64/RPMS.plnet-compiled/ and http://centos.plnet.rs/mrepo/plnet-centos7-srpms-srpms/RPMS.plnet-compiled/

BE aware that files are NOT YET SIGNED! I have yet to find my old keys and even see if they are still valid. I will do this at later time.
Serbian letters are properly shown in PgAdmin4 and Lazarus via ZEOS components.
If anyone can provide further testing, if everything looks good I will contact EPEL maintainer to upgrade freetds to 1.1.6.

Who wants to rebuild them them self, use my spec file: 
[freetds.spec.txt](https://github.com/FreeTDS/freetds/files/3330271/freetds.spec.txt) and put this file
[freetds-tds_sysdep_public.h.txt](https://github.com/FreeTDS/freetds/files/3330278/freetds-tds_sysdep_public.h.txt) (remove .txt from names)  and 1.1.6 tar: ftp://ftp.freetds.org/pub/freetds/stable/freetds-1.1.6.tar.bz2 into SOURCE directory. To be able to build them you also need to run this: `yum install readline-devel gnutls-devel krb5-devel libgcrypt-devel doxygen rpmdevtools docbook-style-dsssl automake autoconf libtool make gcc perl redhat-rpm-config rpm-build -y`

FreeTDS Developers: If providing link to binary packages is against some rules, you may remove them, or I will if you say so. I am long-time CentOS contributor (in mailing lists since ~2009) and I am admin of CentOS Facebook group so rpm's are clean of malware, built from unchanged sources.

**Comment by freddy77** [comment]
Il giorno mer 26 giu 2019 alle ore 14:48 Ljubomir Ljubojevic <
notifications@github.com> ha scritto:

> Hi.
> I had an issue using tds_fdw with freetds 0.95 on CentOS 7 with regards to
> encodings. I connect to MSSQL 2008R2 from PostgreSQL 10 server via Foreign
> data wrapper (Foreign tables) and since MSSQL database uses Serbian_Latin
> encoding, Serbian letters were not properly converted.
> I reported it in tds_fdw here: tds-fdw/tds_fdw#111 (comment)
> <https://github.com/tds-fdw/tds_fdw/issues/111#issuecomment-503175971>
> and came to conclusion Serbian_latin is not supported by freetds 0.95 so I
> ventured to create/rebuild rpms provided by EPEL to version 1.1.6.
>
> I fired up my rpm rebuilding skills and I managed to update EPEL's src.rpm
> to version 1.1.6 (replaced tar.bz2, and in spec file changed version number
> and --with-tdsver="7.3" from --with-tdsver="4.2" ).
> Since there are no rpm's for CentOS 7, I am publishing rpm and src.rpm
> files in my old repo:
> http://centos.plnet.rs/mrepo/plnet-centos7-x86_64/RPMS.plnet-compiled/
> and
> http://centos.plnet.rs/mrepo/plnet-centos7-srpms-srpms/RPMS.plnet-compiled/
>
> BE aware that files are NOT YET SIGNED! I have yet to find my old keys and
> even see if they are still valid. I will do this at later time.
> Serbian letters are properly shown in PgAdmin4 and Lazarus via ZEOS
> components.
> If anyone can provide further testing, if everything looks good I will
> contact EPEL maintainer to upgrade freetds to 1.1.6.
>
> Who wants to rebuild them them self, use my spec file:
> freetds.spec.txt
> <https://github.com/FreeTDS/freetds/files/3330271/freetds.spec.txt> and
> put this file
> freetds-tds_sysdep_public.h.txt
> <https://github.com/FreeTDS/freetds/files/3330278/freetds-tds_sysdep_public.h.txt>
> (remove .txt from names) and 1.1.6 tar:
> ftp://ftp.freetds.org/pub/freetds/stable/freetds-1.1.6.tar.bz2 into
> SOURCE directory. To be able to build them you also need to run this: yum
> install readline-devel gnutls-devel krb5-devel libgcrypt-devel doxygen
> rpmdevtools docbook-style-dsssl automake autoconf libtool make gcc perl
> redhat-rpm-config rpm-build -y
>
> FreeTDS Developers: If providing link to binary packages is against some
> rules, you may remove them, or I will if you say so.
>
Hi,
  please read https://www.freetds.org/userguide/osissues.htm#RPM.

Just:

rpmbuild -ta freetds-1.1.9.tar.bz2

Or

rpmbuild -ts freetds-1.1.9.tar.bz2
mock -r epel-7-x86_64 freetds-1.1.9-1.src.rpm

I agree that on the long term better to contact EPEL maintainer and make it
update the package.

Frediano

**Comment by DrLove73** [comment]
Hi Frediano,
thanks for examples how to build rpm's from freetds tar, it has been several years since I seriously worked on rebuilding packages.

But, since I am exclusivity using CentOS, I came to distrust rpm's (spec files) that are made by package developers. There seams to always be some small thing or other that does not work just right, so I trust more to src.rpm's made specifically for CentOS packages.  It is nothing personal, it is just strong belief of paranoid system admin :)

**Comment by mckaygerhard** [comment]
that's it's the most funny thing i never read! epel rpm's are not "special" for centos.. it's just take original spec's files and ajust the depends that's all.. no so much work..  

that's why most vendors uses debian so much!

**Comment by freddy77** [comment]
Epel updated to 1.1.11. Closing this issue
