### ISSUE TITLE
Log level for query state change

### ISSUE THREAD

**Issue by zanardigit** [FreeTDS/freetds#300]
Shortly: why is a query state change logged as error? See https://github.com/FreeTDS/freetds/blob/89a74da5a812e152fbdae8ee8ccbcacac7fb9595/src/tds/util.c#L165

DETAILS
I set my local configuration to only log errors, and since the system is working fine I did not expect to see many rows written into the logs. I found that I get lots of and lots of `Changed query state ...`.
That does not look like an error to me, yet I am a complete newbie on this project so thank you to anyone who will provide some additional info.

**Comment by freddy77** [comment]
Surely a copy&paste mistake, it's just information, I would say change to `TDS_DBG_INFO1`, I'll do it

**Comment by freddy77** [comment]
Merged, expect a snapshot tomorrow, stable version 1.1.12.
Looks like AppVeyor is having some issues, but looks like the VM changed, nothing to worry.

**Comment by zanardigit** [comment]
@freddy77 thank you so much for your quick reply and fix!
