### ISSUE TITLE
CTLib unusable with Microsoft Azure

### ISSUE THREAD

**Issue by evanmiller** [FreeTDS/freetds#303]
Similar to #160, the C library in its current form cannot be used with Microsoft Azure databases. By default CTLib will connect to the "master" database, and attempts to switch to another database yield the error:

> USE statement is not supported to switch between databases. Use a new connection to connect to a different database.

I have worked around the issue by defining a new `CS_DATABASE` property that calls `tds_dstr_copy(&tds_login->database, set_buffer)` inside of `ct_con_props`, so that the database can be defined before the initial connection. I can contribute this code if desired.

**Comment by freddy77** [comment]
sure, makes sense, feel free to send a proposal

**Comment by evanmiller** [comment]
@freddy okay, PR #304 opened using the 9302 convention.

**Comment by freddy77** [comment]
Merged proposed patch. Nightly/updates expected tomorrow
