### ISSUE TITLE
freebcp -F option no longer entirely skips lines (syntax error in source field)

### ISSUE THREAD

**Issue by epa** [FreeTDS/freetds#306]
The `-F` option to freebcp is to start with a first row other than 1; for example `-F 2` will skip over an initial header line and start from the second line of the input file.  In freetds 0.95.81 this worked fine.  But with 1.1.11, the line which is meant to be skipped gets parsed anyway, giving syntax errors if it wasn't a line of data to be uploaded.  So for example given

`create table test_table (a int not null)`

the following works okay, uploading only the second line in the input file:

````
% echo 1 >f; echo 2 >>f; freebcp test_table in f -S myserver -D mydb -U myuser -P mypass -c -t , -F 2

Starting copy...
1 rows copied.
````

But if the first line of the file isn't in numeric format then it fails, even though that line was meant to be skipped:

````
% echo hello >f; echo 2 >>f;  freebcp test_table in f -S myserver -D mydb -U myuser -P mypass -c -t , -F 2

Starting copy...
Msg 20050, Level 4
Attempt to convert data stopped by syntax error in source field

1 rows copied.
````

This means you can no longer use freebcp to upload files that have one or more header lines followed by some data lines to upload.  Please can you restore the old behaviour of skipping lines entirely if `-F` is given, not even attempting to parse them?

**Comment by freddy77** [comment]
I don't remember specifically this change, maybe was due to something else and now potentially the parsing is more picky. For instance one reason that came into my mind is a quoted string having newlines in the middle detected as 2 records. I'll have a look.

**Comment by epa** [comment]
Thanks.  The manual page does say that -F sets the first *row*, not the first *line*.  But the behaviour in the past has always been to skip lines.  That's also what the `bcp` program provided with Microsoft SQL Server does, and most likely Sybase's version too.

Some compromise might be to check for double quotes and stuff, but not type-check the values or check for the right number of columns when a row is being skipped.

**Comment by epa** [comment]
Could I ask the freetds developers to have another look at this?  It is still broken in 1.1.36.  Can the earlier more useful behaviour be reinstated?

**Comment by freddy77** [comment]
I sorry for the delay. I just tested and both 0.95.81 and last 1.1 behave the same, they reports error but as freebcp has a `MAXERRS` default of 10 it ignore them. Is it possible I did some mistakes but even looking at code this seems correct. But I don't think a change that will avoid the conversion in case rows are skipped would be sensible. Is a bit different than skipping lines, you still parse terminators or, for binary files, rows. Just don't do the conversion if the line is going to be skipped.

**Comment by epa** [comment]
Thanks for investigating.  I am sure it used to work with an older version since I have application code passing -F 1 to skip the first line in a CSV file, which worked fine, until upgrading to a newer freetds broke it.

But anyway, either alternative works for me: either make -F skip lines (which is fine for CSV but as you say might not work so well for binary formats), or keep it as skipping rows but don't do the type conversion if the row is to be skipped.

I think one of the most common uses for -F is to load a text file skipping an initial header line.  That works with Microsoft's bcp implementation and it would be great for freebcp to support it once again.

**Comment by freddy77** [comment]
Tested more Microsoft bcp utility. Rows are skipped, not lines, so implementing this. I also tried, mainly out of curiosity, FreeTDS 0.91 but still conversion is done. Maybe a very old version not doing much errors. Currently implemented this and some other minor fixes, currently testing.

**Comment by epa** [comment]
Thank you for fixing this.  I can confirm it's all working again now.
