### ISSUE TITLE
Cross domain AD authentication fails after successful authentication

### ISSUE THREAD

**Issue by anupinder** [FreeTDS/freetds#307]
Cross domain AD authentication fails after successful authentication 

Here is snippet from TDS Dump 

tls.c:110:in tds_pull_func_login
tls.c:110:in tds_pull_func_login
tls.c:110:in tds_pull_func_login
tls.c:960:handshake succeeded!!
login.c:866:using GSS authentication
gssapi.c:221:using kerberos name MSSQLSvc/<servername>:1433
gssapi.c:233:gss_import_name: GSS_S_COMPLETE: gss_import_name completed successfully.
gssapi.c:321:gss_init_sec_context: actual mechanism at 0x0
gssapi.c:337:gss_init_sec_context: min_stat 2529638919 "Unknown error"
gssapi.c:377:gss_init_sec_context: GSS_S_FAILURE: The routine failed for reasons that are not defined at the GSS level.
login.c:532:login packet rejected
query.c:3796:tds_disconnect()
util.c:165:Changed query state from IDLE to DEAD
util.c:322:tdserror(100188bb0, 100188d70, 20002, 0)
ctutil.c:86:_ct_handle_client_message(100188bb0, 100188d70, ffffffff7fffe290)
util.c:352:tdserror: client library returned TDS_INT_CANCEL(2)
util.c:375:tdserror: returning TDS_INT_CANCEL(2)
mem.c:651:tds_free_all_results()

**Comment by freddy77** [comment]
Why are you saying

> fails after successful authentication

? If you refer to `handshake succeeded!!` this refers to TLS. It's weird the `MSSQLSvc/:1433`, there should be an host name (a FQDN like `myhost.domain.org`).

**Comment by anupinder** [comment]
Hi,
     I am talking about this error
gssapi.c:337:gss_init_sec_context: min_stat 2529638919 "Unknown error"
gssapi.c:377:gss_init_sec_context: GSS_S_FAILURE: The routine failed for reasons that are not defined at the GSS level.

**Comment by freddy77** [comment]
Can you try to set a FQDN as host name? Check if ping is able to resolve the full name.

**Comment by anupinder** [comment]
I have found fix for issue.I had to specify realm explicitly in freetds.conf and that resolved issue.

Thanks Freddy.

**Comment by chiragthakar73** [comment]
I am also facing the same issue as mentioned in the post. I was interested in knowing what to specify in the freetds.conf file as realm.
I am trying to connect to Azure sql database so my specific realm will be like **azure.com** or something else. I have very little knowledge about the networking terminologies and getting confused. Kindly state what I should write as specific realm. @anupinder @freddy77

**Comment by freddy77** [comment]
For how to specify the realm in `freetds.conf` see https://www.freetds.org/userguide/freetdsconf.html.
You could also use (if you are using ODBC) the `REALM` attribute (either `odbc.ini` or using `SQLDriverConnect`), see https://www.freetds.org/userguide/OdbcConnAttr.html.
