### ISSUE TITLE
Can't connect from Azure VM to Azure SQL database

### ISSUE THREAD

**Issue by hobbsenigma** [FreeTDS/freetds#308]
Attempting to connect from Azure Redhat 7 VM to Azure sql database.  I am able to make the connection using telnet and via mssql-cli, but not with tsql, so this appears to be an issue with my freetds configuration or a freetds dependency.  I did have to increase the timeout for mssql-cli in order to make the connection.  I set the freetds command and connection timeouts to 60, but did not see any change.

I am able to connect from machines outside of Azure using tsql, though they are running Ubuntu, and use different versions of openssl.  

tsql output and partial log file below (I will include packet contents if this can be done securely).  Comparing with one of my Ubuntu machines, it appears the problem is somewhere between "quietly sending TDS 7+ login packet" and "Received packet".  The received packet is much smaller than that received by the Ubuntu machines.  Advice / suggestions welcome!

OpenSSL 1.0.2k-fips  26 Jan 2017

> tsql -C
Compile-time settings (established with the "configure" script)
                            Version: freetds v1.1.11
             freetds.conf directory: /usr/local/etc
     MS db-lib source compatibility: no
        Sybase binary compatibility: no
                      Thread safety: yes
                      iconv library: yes
                        TDS version: auto
                              iODBC: no
                           unixodbc: no
              SSPI "trusted" logins: no
                           Kerberos: no
                            OpenSSL: yes
                             GnuTLS: no
                               MARS: yes

> tsql -S servername.database.windows.net -U username
Password:
locale is "en_US.UTF-8"
locale charset is "UTF-8"
using default charset "UTF-8"
17Error 20002 (severity 9):
        Adaptive Server connection failed
Error 20002 (severity 9):
        Adaptive Server connection failed
There was a problem connecting to the server

> cat /tmp/freetds.log
02:09:12.012078 42900 (log.c:168):Starting log file for FreeTDS 1.1.11
        on 2019-09-28 02:09:12 with debug flags 0xffff.
02:09:12.012777 42900 (iconv.c:326):tds_iconv_open(0xbb73f0, UTF-8)
02:09:12.013072 42900 (iconv.c:186):local name for ISO-8859-1 is ISO-8859-1
02:09:12.013079 42900 (iconv.c:186):local name for UTF-8 is UTF-8
02:09:12.013081 42900 (iconv.c:186):local name for UCS-2LE is UCS-2LE
02:09:12.013083 42900 (iconv.c:186):local name for UCS-2BE is UCS-2BE
02:09:12.013085 42900 (iconv.c:348):setting up conversions for client charset "UTF-8"
02:09:12.013087 42900 (iconv.c:350):preparing iconv for "UTF-8" <-> "UCS-2LE" conversion
02:09:12.013143 42900 (iconv.c:389):tds_iconv_open: done
02:09:12.013150 42900 (net.c:391):Connecting with protocol version 7.4
02:09:12.014553 42900 (net.c:318):Connecting to xx.xx.xx.xx port 1433
02:09:12.014955 42900 (net.c:340):tds_setup_socket: connect(2) returned "Operation now in progress"
02:09:12.017170 42900 (net.c:528):tds_open_socket() succeeded
02:09:12.017231 42900 (packet.c:801):Sending packet

02:09:12.019298 42900 (packet.c:435):Received packet

02:09:12.019338 42900 (login.c:1254):detected flag 3
02:09:12.019898 42900 (tls.c:1012):setting default openssl cipher to:HIGH:!SSLv2:!aNULL:-DH
02:09:12.020007 42900 (tls.c:147):in tds_push_func_login
02:09:12.020014 42900 (tls.c:117):in tds_pull_func_login
02:09:12.020019 42900 (packet.c:801):Sending packet

02:09:12.023693 42900 (packet.c:435):Received packet

02:09:12.024675 42900 (tls.c:117):in tds_pull_func_login
02:09:12.024685 42900 (tls.c:117):in tds_pull_func_login
02:09:12.024695 42900 (packet.c:435):Received packet

02:09:12.025682 42900 (tls.c:147):in tds_push_func_login
02:09:12.025696 42900 (tls.c:117):in tds_pull_func_login
02:09:12.025703 42900 (packet.c:801):Sending packet

02:09:12.028507 42900 (packet.c:435):Received packet

02:09:12.028537 42900 (tls.c:117):in tds_pull_func_login
02:09:12.028563 42900 (tls.c:117):in tds_pull_func_login
02:09:12.028567 42900 (tls.c:117):in tds_pull_func_login
02:09:12.028611 42900 (tls.c:1048):handshake succeeded!!
02:09:12.028632 42900 (login.c:976):quietly sending TDS 7+ login packet
02:09:12.028683 42900 (token.c:416):tds_process_login_tokens()
02:09:12.030000 42900 (tls.c:160):in tds_pull_func
02:09:12.030017 42900 (tls.c:160):in tds_pull_func
02:09:12.030025 42900 (packet.c:435):Received packet

02:09:12.030092 42900 (token.c:420):looking for login token, got  ad(LOGINACK)
02:09:12.030097 42900 (token.c:346):server reports TDS version 74.0.0.4
02:09:12.030099 42900 (token.c:348):Product name for 0x74000004 is 2012-2017
02:09:12.030108 42900 (token.c:382):Product version 8C000640
02:09:12.030111 42900 (token.c:420):looking for login token, got  e3(ENVCHANGE)
02:09:12.030113 42900 (token.c:129):tds_process_default_tokens() marker is e3(ENVCHANGE)
02:09:12.030117 42900 (token.c:420):looking for login token, got  e3(ENVCHANGE)
02:09:12.030119 42900 (token.c:129):tds_process_default_tokens() marker is e3(ENVCHANGE)
02:09:12.030122 42900 (token.c:2285):changing block size from 4096 to 4096
02:09:12.030126 42900 (token.c:420):looking for login token, got  fd(DONE)
02:09:12.030128 42900 (token.c:129):tds_process_default_tokens() marker is fd(DONE)
02:09:12.030131 42900 (token.c:2094):tds_process_end: more_results = 0
                was_cancelled = 0
                error = 0
                done_count_valid = 0
02:09:12.030134 42900 (token.c:2113):                rows_affected = 0
02:09:12.030136 42900 (token.c:2116):tds_process_end() state set to TDS_IDLE
02:09:12.030138 42900 (token.c:443):tds_process_login_tokens() returning TDS_SUCCESS
02:09:12.030141 42900 (query.c:3783):tds_disconnect()
02:09:12.030160 42900 (util.c:165):Changed query state from IDLE to DEAD
02:09:23.804655 42900 (net.c:391):Connecting with protocol version 7.4
02:09:23.804756 42900 (net.c:318):Connecting to yy.yy.yy.yy port 11048
02:09:23.805040 42900 (net.c:340):tds_setup_socket: connect(2) returned "Operation now in progress"
02:09:23.806646 42900 (net.c:528):tds_open_socket() succeeded
02:09:23.806682 42900 (packet.c:801):Sending packet

02:09:23.806723 42900 (tls.c:183):in tds_push_func
02:09:29.223117 42900 (util.c:165):Changed query state from IDLE to DEAD
02:09:29.223169 42900 (packet.c:542):Read attempt when state is TDS_DEAD
02:09:29.223173 42900 (login.c:582):login packet rejected
02:09:29.223176 42900 (util.c:319):tdserror(0x7ffd12a838d0, 0xbb7730, 20002, 0)
02:09:29.223181 42900 (util.c:349):tdserror: client library returned TDS_INT_CANCEL(2)
02:09:29.223184 42900 (util.c:372):tdserror: returning TDS_INT_CANCEL(2)
02:09:29.223201 42900 (util.c:319):tdserror(0xbb7150, 0xbb7730, 20002, 0)
02:09:29.223227 42900 (util.c:349):tdserror: client library returned TDS_INT_CANCEL(2)
02:09:29.223230 42900 (util.c:372):tdserror: returning TDS_INT_CANCEL(2)
02:09:29.223246 42900 (mem.c:656):tds_free_all_results()

**Comment by freddy77** [comment]
Pretty weird. The only explanation that come into my mind is that server is rerouting to another server. But should not wait 11 seconds to attempt the connection to the routed server. Can you send my (privately if you prefer) the logs with network data?
The `tds_process_login_tokens() returning TDS_SUCCESS` line and other lines seems to indicate that server accepted the login.

**Comment by hobbsenigma** [comment]
Freddy, I emailed you the log file.  I did add the database to the tsql command, in case that matters, but I think the response looks the same.
tsql -S servername.database.windows.net -U username -D database
