### ISSUE TITLE
freetds doesn't compile on Solaris 10 32 bit

### ISSUE THREAD

**Issue by JUNGROL** [FreeTDS/freetds#309]
./configure --prefix=/export/home/jungrol/freetds_stuff --with-unixodbc=/opt/csw/
runs without problems

compile failed with error:

Making all in include
make[1]: Entering directory `/export/home/jungrol/freetds-dev.1.1.57/include'
make  all-recursive
make[2]: Entering directory `/export/home/jungrol/freetds-dev.1.1.57/include'
Making all in freetds
make[3]: Entering directory `/export/home/jungrol/freetds-dev.1.1.57/include/freetds'
echo '#define FREETDS_SYSCONFDIR "/export/home/jungrol/freetds_stuff/etc"' >sysconfdir.h
make[3]: Leaving directory `/export/home/jungrol/freetds-dev.1.1.57/include/freetds'
make[3]: Entering directory `/export/home/jungrol/freetds-dev.1.1.57/include'
make[3]: Leaving directory `/export/home/jungrol/freetds-dev.1.1.57/include'
make[2]: Leaving directory `/export/home/jungrol/freetds-dev.1.1.57/include'
make[1]: Leaving directory `/export/home/jungrol/freetds-dev.1.1.57/include'
Making all in src
make[1]: Entering directory `/export/home/jungrol/freetds-dev.1.1.57/src'
Making all in utils
make[2]: Entering directory `/export/home/jungrol/freetds-dev.1.1.57/src/utils'
Making all in .
make[3]: Entering directory `/export/home/jungrol/freetds-dev.1.1.57/src/utils'
  CC       md4.lo
  CC       md5.lo
  CC       des.lo
  CC       hmac_md5.lo
In file included from /usr/sfw/lib/gcc/i386-pc-solaris2.10/3.4.3/include/sys/types.h:44,
                 from /usr/include/memory.h:13,
                 from hmac_md5.c:29:
/usr/include/sys/int_types.h:54: error: conflicting types for 'int8_t'
../../include/tds_sysdep_public.h:31: error: previous declaration of 'int8_t' was here
make[3]: *** [hmac_md5.lo] Error 1
make[3]: Leaving directory `/export/home/jungrol/freetds-dev.1.1.57/src/utils'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/export/home/jungrol/freetds-dev.1.1.57/src/utils'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/export/home/jungrol/freetds-dev.1.1.57/src'
make: *** [all-recursive] Error 1

Any workaround?
or isn't it possible to run freetds on Solaris?

Thank you in advance for your response.

**Comment by freddy77** [comment]
Should be. Similar issue at https://github.com/libexpat/libexpat/issues/234

**Comment by freddy77** [comment]
Can you try this:

```diff
diff --git a/include/tds_sysdep_public.h.in b/include/tds_sysdep_public.h.in
index c5bdd9d2..d6eb4676 100644
--- a/include/tds_sysdep_public.h.in
+++ b/include/tds_sysdep_public.h.in
@@ -27,6 +27,8 @@
 
 #if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L
 #  include <stdint.h>
+#elif defined(__sun) && defined(__SVR4)
+#  include <inttypes.h>
 #else
 typedef   signed char      int8_t;     /* 8-bit int */
 typedef unsigned char     uint8_t;     /* 8-bit int */
```

**Comment by JUNGROL** [comment]
Thank you for the quick response.

 

I applied the patch and the code compiles with a few warnings.

 

Now i can access MS-SQL from Solaris 10

 

 

Von: freddy77 <notifications@github.com> 
Gesendet: Sonntag, 6. Oktober 2019 19:05
An: FreeTDS/freetds <freetds@noreply.github.com>
Cc: JUNGROL <sbjung@t-online.de>; Author <author@noreply.github.com>
Betreff: Re: [FreeTDS/freetds] freetds doesn't compile on Solaris 10 32 bit (#309)

 

Can you try this:

diff --git a/include/tds_sysdep_public.h.in b/include/tds_sysdep_public.h.in
index c5bdd9d2..d6eb4676 100644
--- a/include/tds_sysdep_public.h.in
+++ b/include/tds_sysdep_public.h.in
@@ -27,6 +27,8 @@
 
 #if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L
 #  include <stdint.h>
+#elif defined(__sun) && defined(__SVR4)
+#  include <inttypes.h>
 #else
 typedef   signed char      int8_t;     /* 8-bit int */
 typedef unsigned char     uint8_t;     /* 8-bit int */

**Comment by freddy77** [comment]
Merged
