### ISSUE TITLE
freetds.org is down

### ISSUE THREAD

**Issue by bugg2844** [FreeTDS/freetds#314]
Not sure how else to report this...
Thanks.

**Comment by robotfelix** [comment]
To expand on this, it's not just the front end website that is down. The FTP repository (ftp://ftp.freetds.org/pub/freetds) is down too.

**Comment by robotfelix** [comment]
I was hunting in the Wayback Machine for any other support methods and the site has come back up just a moment ago!

To prevent future issues, it feels like some sort of mirror could be useful?

**Comment by aharpervc** [comment]
> Somebody knows a free mirror service? FreeTDS website is static, won't be difficult to replicate it.

I wonder if [Github Pages](https://pages.github.com/) hosted right would be a good fit? It could probably be it's own repo in this same org

**Comment by robotfelix** [comment]
The website and FTP server are down again.

They seemed to be rock solid last year and the first half of this year, but they seem to be happening at least once a month at the moment (@bugg2844's opening of this issue was definitely not the first occurrence).

Do we know what has changed?
