### ISSUE TITLE
SQLGetData performance

### ISSUE THREAD

**Issue by osidorkin** [FreeTDS/freetds#315]
It seems SQLGetData spent 65% of time in tds_canonical_charset doing charset lookup over and over on every call. Is there a way to cache and reuse lookup results?

Here is a flame chart:
https://www.dropbox.com/s/u1d8pvctygbw9dn/Screenshot%202019-10-27%2017.09.46.png?dl=0

**Comment by osidorkin** [comment]
The main reason to call SQLGetData often (after every SQLFetch) is to fetch varchar and varbinary columns with confidence as there is no way to known in advance and preallocate enough buffer for SQLBindCol.

**Comment by osidorkin** [comment]
Use of SQLGetData to fetch the remaining part, not fitted to a buffer assigned to SQLBindCol, is well supported by FreeTDS, and can help to reduce numbers of extra SQLGetData calls to overflow cases only. Unfortunately this patterns fails with "invalid cursor state" for native Microsoft ODBC drivers. So the least common denominator approach is to move all var length columns to the end of a query and use SQLBindCol for fixed length columns and SQLGetData for the remaining variable length ones. Unfortunately this pattern hits a performance issue wit linear charset lookup on every SQLGetData call.

**Comment by osidorkin** [comment]
Thank you for the change above! Will test is shortly and post the results.

**Comment by osidorkin** [comment]
It's much better with change. Actual icon conversion now takes more time than charset lookup:
https://www.dropbox.com/s/e69l710o6nep7p1/Screenshot%202019-11-01%2017.28.19.png?dl=0

However it's still responsible for ~16% of SQLGetData footprint. Perhaps a tiny LRU cache `(client charset, server charset) -> TDSICONV*` could eliminate it completely.

**Comment by osidorkin** [comment]
I guess even 1 element LRU cache in TDSCONNECTION will do a trick.

**Comment by freddy77** [comment]
I wrote also optimization 2), see https://github.com/FreeTDS/freetds/commit/dc7b45efcbe83a1189d6982081564241d08009cf and https://github.com/FreeTDS/freetds/commit/b1da10a62ce2b32107e82a8aea73d7ed49f26c9f (on branch https://github.com/FreeTDS/freetds/tree/appveyor).
About `SQLGetData` usage programs could attempt to resize the buffer using exponential algorithm instead of linear and do not reallocate for every row, this would reduce `SQLGetData` calls.

**Comment by freddy77** [comment]
Merged
