### ISSUE TITLE
Make fails after latest commit

### ISSUE THREAD

**Issue by eclipsehm** [FreeTDS/freetds#316]
On the debian jessie, make fails after latest commits.
It works with commit hash "f75e09e3e2f83741b0a9cf37b9809e47a6658043".

`perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
mv tds_willconvert.h.tmp tds_willconvert.h
perl ./encodings.pl . gperf > encodings.h.tmp 2> /dev/null
Makefile:844: recipe for target 'encodings.h' failed
make[2]: *** [encodings.h] Error 2
make[2]: Leaving directory '/tmp/testing/freetds/src/tds'
Makefile:411: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/testing/freetds/src'
Makefile:449: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
`

**Comment by freddy77** [comment]
There's an additional requirement which is gperf.
I think I'll update the autoconf scripts to detect and better signal this requirement.
Potentially you should be able to use the snapshot you can find at https://www.freetds.org/files/current/ that already distribute processed files.

**Comment by freddy77** [comment]
Updated autoconf script to check for gperf program.
