### ISSUE TITLE
v0.95.67 Corrupt Packets After - Error converting characters into server's character set

### ISSUE THREAD

**Issue by metaskills** [FreeTDS/freetds#32]
Cross post from the [mailing list](http://lists.ibiblio.org/pipermail/freetds/2015q4/029627.html). 

When testing the Ruby C-extensions, TinyTDS, FreeTDS 0.95. We have a test that checks usage of the client after inserting invalid characters. The following insert is done when the client encoding is set to 'ASCII'.

```sql
INSERT INTO [datatypes] ([nvarchar_50]) VALUES ('Test ✓')
```

After handling the message, the followup `SELECT 1 AS [one]` test query returns

```
Incorrect syntax near '3'
```

When examining the TDSDUMP file, it seems there is some garbage in the packets. Thoughts?

```
dblib.c:1338:dbcmd(0x7fca058a4f60, INSERT INTO [datatypes] ([nvarchar_50]) VALUES ('Test âœ“'))
dblib.c:1344:dbcmd() bufsz = 56
dblib.c:5845:dbfreebuf(0x7fca058a4f60)
dblib.c:6817:dbsqlsend(0x7fca058a4f60)
mem.c:648:tds_free_all_results()
util.c:165:Changed query state from IDLE to WRITING
util.c:322:tdserror(0x7fca046f4a80, 0x7fca044b0240, 2402, 0)
dblib.c:7897:dbperror(0x7fca058a4f60, 2402, 0)
dblib.c:7965:dbperror: Calling dblib_err_handler with msgno = 2402; msg->msgtext = "Error converting characters into server's character set. Some character(s) could not be converted"
dblib.c:5743:dbgetuserdata(0x7fca058a4f60)
dblib.c:5845:dbfreebuf(0x7fca058a4f60)
dblib.c:5743:dbgetuserdata(0x7fca058a4f60)
dblib.c:1338:dbcmd(0x7fca058a4f60, SELECT 1 AS [one])
dblib.c:1344:dbcmd() bufsz = 0
dblib.c:6817:dbsqlsend(0x7fca058a4f60)
util.c:165:Changed query state from WRITING to PENDING
packet.c:740:Sending packet
0000 01 01 00 56 00 00 01 00-16 00 00 00 12 00 00 00 |...V.... ........|
0010 02 00 01 00 00 00 33 00-00 00 01 00 00 00 16 00 |......3. ........|
0020 00 00 12 00 00 00 02 00-01 00 00 00 33 00 00 00 |........ ....3...|
0030 01 00 00 00 53 00 45 00-4c 00 45 00 43 00 54 00 |....S.E. L.E.C.T.|
0040 20 00 31 00 20 00 41 00-53 00 20 00 5b 00 6f 00 | .1. .A. S. .[.o.|
0050 6e 00 65 00 5d 00      -                        |n.e.].|

dblib.c:5743:dbgetuserdata(0x7fca058a4f60)
dblib.c:5743:dbgetuserdata(0x7fca058a4f60)
dblib.c:5743:dbgetuserdata(0x7fca058a4f60)
dblib.c:5743:dbgetuserdata(0x7fca058a4f60)
dblib.c:4625:dbsqlok(0x7fca058a4f60)
dblib.c:4654:dbsqlok() not done, calling tds_process_tokens()
token.c:549:tds_process_tokens(0x7fca044b0240, 0x7fff5b414fd4, 0x7fff5b414fd0, 0x6914)
util.c:165:Changed query state from PENDING to READING
packet.c:639:Received packet
0000 04 01 00 66 00 33 01 00-aa 4e 00 66 00 00 00 01 |...f.3.. ªN.f....|
0010 0f 1a 00 49 00 6e 00 63-00 6f 00 72 00 72 00 65 |...I.n.c .o.r.r.e|
0020 00 63 00 74 00 20 00 73-00 79 00 6e 00 74 00 61 |.c.t. .s .y.n.t.a|
0030 00 78 00 20 00 6e 00 65-00 61 00 72 00 20 00 27 |.x. .n.e .a.r. .'|
0040 00 33 00 27 00 2e 00 06-53 00 53 00 32 00 30 00 |.3.'.... S.S.2.0.|
0050 31 00 34 00 00 01 00 00-00 fd 02 00 fd 00 00 00 |1.4..... .ý..ý...|
0060 00 00 00 00 00 00      -                        |......|
```

**Comment by freddy77** [comment]
Two packet extension are sent but the second is interpreted as a sql query.
We should discard the extension on query problems or cancel the partial sent query.

**Comment by metaskills** [comment]
Thanks for the reply, so this means there is a bug in 0.95 that needs to be fixed here? If so, can I help coordinate a pull request?

**Comment by freddy77** [comment]
well, if you have a fix you can post a pull request. The easy solution is to send a cancel if you detect such event.

**Comment by metaskills** [comment]
I will test that later today and report back! Thanks.

**Comment by freddy77** [comment]
Looking again at the log... is it the full log or did you cut something in the middle?
I can see the call to the error handler ("dbperror: Calling dblib_err_handler with ms"...) but not the return ("dbperror: dblib_err_handler for msgno = "...).

**Comment by metaskills** [comment]
The log does not have anything cut from the middle, but there is more above and below that is mostly setup and teardown test code. I did put a a cancel in my code, but it did not work. It adds this first line right before the dbcmd for the followup query.

```
dblib.c:3203:dbcancel(0x7fc3fe040db0)
dblib.c:1338:dbcmd(0x7fc3fe040db0, SELECT 1 AS [one])
```

**Comment by metaskills** [comment]
@freddy77 Been trying to find out more as well as if this test is really important or not. I've not been able to reproduce this with `tsql` and passing various `-J` options. In our test, we pass `ASCII` as the charset which is passed to `DBSETLCHARSET`. The test then basically does the SQL mentioned above. I have noticed that if I try to set the charset to `ISO-8859-1`, the test passes. Which I did not expect. This test was written for us and worked in 0.91. The purpose was to make sure when `SYBEICONVO/2402` happened, our next SQL batch would work. I still think something is amiss.

One reason you likely do not see the message handler is due to how our code works or maybe how this test is exercising FreeTDS. The Ruby bindings will store error and messagesing  (above 10 severity) in a struct that is processed after the command batch. When errors are present, we raise a Ruby exception which pops the stack. Maybe that keeps the messages from being processed. Here is the full DUMP if you are interested. https://gist.github.com/metaskills/761f9c5cbc6cf91e8fb3

**Comment by freddy77** [comment]
I think there are two problems:
1- libTDS should return TDS_FAIL if string failed to convert so caller can handle it calling dbcancel;
2-your library discard the stack not making possible to libTDS to bring state back to stable.

I can fix the point 1 (I don't know in 0.95) but you have to fix point 2.

**Comment by metaskills** [comment]
Thanks, I am pretty sure I can fix point 2.

**Comment by metaskills** [comment]
OK, I think this takes care of point 2 for me. https://github.com/rails-sqlserver/tiny_tds/commit/1957e459bed62e02fd4e8092aaac8f4819aa89a5

I think this makes point 1 a lower priority, but interested in your feedback.

**Comment by metaskills** [comment]
Gonna close this issue. I think I have this well solved in our end.
