### ISSUE TITLE
Double quote escaping a table or view not accepted

### ISSUE THREAD

**Issue by khalyomede** [FreeTDS/freetds#321]
## Version

Compile-time settings (established with the "configure" script)
                            Version: freetds v1.00.82
             freetds.conf directory: /etc/freetds
     MS db-lib source compatibility: no
        Sybase binary compatibility: yes
                      Thread safety: yes
                      iconv library: yes
                        TDS version: 4.2
                              iODBC: no
                           unixodbc: yes
              SSPI "trusted" logins: no
                           Kerberos: yes
                            OpenSSL: no
                             GnuTLS: yes
                               MARS: no

OS: Ubuntu 18.04.3 LTS

## Description of the issue

It seems I cannot use double quotes to escape my table or view names in my queries.

## Reproduce the issue

1. Connect to your SQL Server using `tsql`

```bash
isql -v YourServer User Password
```

2. Run this query (adapt with an existing view or table)

```
SQL> SELECT * FROM "your_table";
```

3. See this error message

> [37000][FreeTDS][SQL Server]Incorrect syntax near 'your_table'.
> [ISQL]ERROR: Could not SQLExecute

4. Run the fixed query

```
SQL> SELECT * FROM [your_table];
```

5. See the columns and their value correctly displayed

## Expected result

I expected I could use double quotes to escape my view or table name.

## Notes
Is this a legit bug?

Also, It seems there is a pending PR fixing some issues regarding escaping columns, is it related? https://github.com/FreeTDS/freetds/pull/276

It is said in one of the comments:

> Patch make sense, some consideration:
> - would be good to also support possible ']' in names;
>  - what would happen if a column name contain a comma ?
>  - **not all servers support [] for quoting, old ASE ones only support "";**
>  - (OT?) maybe for these utility some more relax "abort on memory error" should be considered.

**Comment by srutzky** [comment]
Since this is regarding SQL Server, have you tried:

```
SQL> SET QUOTED_IDENTIFIER ON;
```

and then using `"` to delimit object names?
