### ISSUE TITLE
Request subscribing to list in order to post messages

### ISSUE THREAD

**Issue by debrote** [FreeTDS/freetds#322]
I work with the freetds library in order to port our application from using Sybase ASE over to using Microsoft SQL Server.

We've used Sybase ASE and ct-lib for years. We've accomplished most of our port to SQL Server but have some remaining sticking points. I'd like to subscribe in order that I may post regarding questions on some remaining issues.

-ed debrot

**Comment by freddy77** [comment]
Can you send me your e-mail address? Even privately if you prefer.

**Comment by debrote** [comment]
My e-mail address is;

debrot@addsys.com<mailto:debrot@addsys.com>

thanks!

Ed Debrot | VP of Engineering - Mobile Development
ADD Systems<http://www.addsys.com> | (973) 584-4026 | mobile (862) 881-7582

**Comment by freddy77** [comment]
done
