### ISSUE TITLE
Problemas de conexión SQLSERVER 2012 desde postgresql 9.5

### ISSUE THREAD

**Issue by fabiolahorasstevenson** [FreeTDS/freetds#324]
Hola, hace una semana estoy tratando de resolver el problema para conectarme a una base de datos en SQL SERVER 2012, desde un postgresql 9.5 instalado en un ubuntu server 16.04, instalé el protocolo freetds versión 1.0 ahora adjunto lo que arroja tsql -C

root@testing:~# tsql -C
Compile-time settings (established with the "configure" script)
                            Version: freetds v1.00.92
             freetds.conf directory: /usr/local/etc
     MS db-lib source compatibility: no
        Sybase binary compatibility: no
                      Thread safety: yes
                      iconv library: yes
                        TDS version: 7.3
                              iODBC: no
                           unixodbc: yes
              SSPI "trusted" logins: no
                           Kerberos: no
                            OpenSSL: yes
                             GnuTLS: no
                               MARS: no
Por otro lado he añadido en odbc.ini lo siguiente:

[SQLEXPRESS]
Description=SQLEXPRESS
Driver=freetds
Server=SQLEXPRESS
TDS_Version=7.3

He revisado los espacios, según uno de los tantos foros que consulté, pero nada.
También configuré odbcinst.ini de la siguiente manera:

[ODBC Driver 17 for SQL Server]
Description=Microsoft ODBC Driver 17 for SQL Server
Driver=/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.4.so.2.1
UsageCount=1

[ODBC]
Trace=yes
TraceFile=/tmp/odbctrace.txt

[FreeTDS]
Description=FreeTDS for connecting to Sybase and SQL Server
Driver=/usr/local/lib/libtdsodbc.so

Además he probado con diversas formas de configuración, no teniendo éxito alguno.

Por otro lado ejecuto el siguiente comando y me arroja el siguiente problema
tsql -S sqlserver -U sa -P xxxx
locale is "es_AR.UTF-8"
locale charset is "UTF-8"
using default charset "UTF-8"

No se conecta.

Además hice:
isql -v SQLEXPRESS
[S1000][unixODBC][FreeTDS][SQL Server]Unable to connect to data source
[01000][unixODBC][FreeTDS][SQL Server]Unknown host machine name.
[ISQL]ERROR: Could not SQLConnect

Ya no se qué más hacer !!! por favor necesito ayuda para resolver este asunto, mil gracias, estaré más que agradecida para resolver este tema que ya no me deja dormir !!!! 
Necesito resolver este asunto para mi tesis, por eso la urgencia y suma necesidad. Gracias

**Comment by freddy77** [comment]
I would try with a

```sh
telnet SQLSERVER 1433
```
from postgres machine

**Comment by fabiolahorasstevenson** [comment]
Acabo de testear y me arroja eso.
usuario@testing:~$ telnet SQLSERVER 1433
telnet: could not resolve SQLSERVER/1433: Name or service not known
usuario@testing:~$ telnet 10.0.0.43\SQLSERVER 1433
telnet: could not resolve 10.0.0.43SQLSERVER/1433: Name or service not known

**Comment by fabiolahorasstevenson** [comment]
Muchas gracias por la pronta respuesta, llevo mucho tiempo tratando de resolverlo

**Comment by freddy77** [comment]
From your tests this should work better

```
[SQLEXPRESS]
Description=SQLEXPRESS
Driver=freetds
Server=10.0.0.43
Port=1433
TDS_Version=7.3
```

(not sure `Port` is necessary)

**Comment by fabiolahorasstevenson** [comment]
usuario@testing:~$ telnet 10.0.0.43 1433
Trying 10.0.0.43...
Connected to 10.0.0.43.
Escape character is '^]'.

Es cierto ! ahora funciona

**Comment by fabiolahorasstevenson** [comment]
pero tengo una duda más ! estoy tan tan agradecida que me ayuden ! no saben cuánto tiempo llevo gogleando todo

**Comment by fabiolahorasstevenson** [comment]
Tengo tres versiones instaladas de tds, entonces quiero dejar la versión 7.4 por defecto, ya que según consulté el siguiente sitio https://www.freetds.org/userguide/choosingtdsprotocol.htm,indica la versión que es compatible con sql server 2012, ya que cuando ejecuto la siguiente línea de código desde el pg_admin 4 para generar el contenedor foráneo me sale lo siguiente:

create server mssql_svr foreign data wrapper tds_fdw options 
(servername 'mssql_freetds', port '1433',  database 'db', tds_version '7.4', msg_handler 'notice' );


Dice:
ERROR:  Unknown tds version: 7.4.
SQL state: 42601

**Comment by freddy77** [comment]
Looks like it's an error from tds_fdw, see https://github.com/tds-fdw/tds_fdw/blob/master/src/tds_fdw.c.

**Comment by fabiolahorasstevenson** [comment]
if (tds_version == DBVERSION_UNKNOWN)
		{
			ereport(ERROR,
				(errcode(ERRCODE_SYNTAX_ERROR),
					errmsg("Unknown tds version: %s.", option_set->tds_version)
				));
		}



Tiene que ver con esa parte de código ? que´no sabe qué versión tiene o que encuentra una versión compatible en las líneas de código previas ?

**Comment by fabiolahorasstevenson** [comment]
Eso lo comprendo, quizás en esta instancia mi confusión radica la configuración y decir en todos lados que la versión sería 7.4 para poder conectarse.

Ya que estamos así termino de entender bien, desde pgAdmin levanta o consulta lo configurado en freetds.conf, en odbc.ini, en odbcinst.ini ?

Gracias ! estoy más que agradecida que me estén respondiendo.

**Comment by fabiolahorasstevenson** [comment]
Estuve examinando el código fuente de tds_fdw.c y tengo unas dudas:

- El valor de PG_VERSION_NUM de donde lo obtiene ? 

- El valor de tds_version de donde lo obtiene, ? 


Entendiendo esto, podré terminar de comprender me parece para poder crear el contenedor foráneo desde pgAdmin 4 y poder crear la tabla foránea que vincula las dos bases.

Muchas gracias

**Comment by freddy77** [comment]
You should ask `tds_fdw` people, I just had a quick look. I think option cames from https://github.com/tds-fdw/tds_fdw/blob/master/src/options.c.
From what I see they are using DB-library, so surely not from `odbc.ini`.
An alternative would be to use FreeTDS ODBC driver, surely there's a ODBC provider for Postgres.

**Comment by fabiolahorasstevenson** [comment]
Si intenté con odbc_fdw pero me arrojaba un error de no ver el servidor, voy a intentar de nuevo en tal caso, agradezco infinitamente tu tiempo.

**Comment by fabiolahorasstevenson** [comment]
CREATE USER MAPPING
     FOR <UsuarioPostgres>
     SERVER <NombreServerDesdePG>
OPTIONS (username '<UsuarioSQLServer>', password '<PassSQLServer>');

Cuando hago esa parte del código y pongo el usuario sa, me dice el siguiente error:

ERROR:  invalid option "username"
HINT:  Valid options in this context are: <none>
SQL state: HV00D

**Comment by fabiolahorasstevenson** [comment]
Al ejecutar todo por odbc_fdw me arroja el siguiente error

ERROR:  Connecting to driver
SQL state: 58000

**Comment by fabiolahorasstevenson** [comment]
El problema acontecido que era que con pgAdmin 4 me rechazaba la conexión, en cambio usando pgAdmin III pude lograr conectarme, comparto esto y cierro el issue, por si a alguien le pasa lo mismo para que no tarde tanto en encontrar la solución.
Muchas gracias por todas las respuestas, me sirvió mucho para aprender.
