### ISSUE TITLE
FreeTDS and international characters

### ISSUE THREAD

**Issue by Davide65** [FreeTDS/freetds#325]
I'm using CodeIgniter 3.1.11 in my Raspberry3 (Raspbian 10 - BUSTER) and it's connected to a Windows server with SQL Server Express 2014 via FreeTDS (v1.00.104)
I'm getting lot of troubles updating and inserting strings in MSSQL because international chars (italian) are transformed. 
For example this string "Pipe 1m Ø30 cm. max. temp 90 °C" is saved as "Pipe 1m ÃƒÂ˜30 cm. max. temp 90 Ã‚Â°C". 
I read a lot on the web, tried to change default_charset in php.ini, set "client dataset" in freetds.conf, also tried iconv() function, but nothing works.

This sample code made in PHP shows the issue.

```
<?php
setlocale(LC_ALL, 'it_IT');    
$odbc=odbc_connect("DRIVER=FreeTDS;SERVER=MyServer\SQLEXPRESS;Database=MyDB;UID=myUser;$PWD=myPWD;TDS_Version= Auto;Port=1433;", "","") or die(odbc_errormsg());
$value = 'string with italian chars: °±Øòàèé?°§ù end string';
$q="UPDATE MYTABLE set MYFIELD = '$value' WHERE ID = 1";
odbc_exec($odbc, $q) or die("<p>".odbc_errormsg());
odbc_close($odbc);
?>
```
the result is: "string with italian chars: Ã‚Â°Ã‚Â±ÃƒÂ˜ÃƒÂ²ÃƒÂ ÃƒÂ¨ÃƒÂ©?Ã‚Â°Ã‚Â§ÃƒÂ¹ end string"

How can I solve it ?

**Comment by freddy77** [comment]
Ciao Davide,
  it's not clear to me which encoding are you using for the .php file, from
your "setlocale" possibly Latin1 or similar.
I would use odbc traces to verify (
http://www.freetds.org/userguide/logging.htm#LOGGING.ODBC) or use FreeTDS
logging
(same page, above, http://www.freetds.org/userguide/logging.htm).
With odbc trace you can also verify if PHP or the DM are converting strings
itself (so calling SQLExecDirectW or other -W functions)
or letting FreeTDS handle the conversion.
As for the encoding I would use ClientCharset in the connection string (
http://www.freetds.org/userguide/odbcconnattr.htm).
Note that the string you are using for odbc connection is called DSN-less (
http://www.freetds.org/userguide/dsnless.htm)
and, not using "Servername" but "Server" is also not using freetds.conf so
setting "client dataset" in freetds.conf is
not really helpful.

Regards,
  Frediano


Il giorno mer 1 apr 2020 alle ore 13:44 Davide65 <notifications@github.com>
ha scritto:

**Comment by Davide65** [comment]
It works!
I modified connection string using SERVERNAME instead of SERVER.
Now I've to solve a new problem because the new connection string doesn't work in CodeIgniter.

$db['MY_MSSQL_DB'] = array(
	'dsn'	=> 'DRIVER=FreeTDS;SERVERNAME=MYSERVER;Database=GALAXYNG_SVILUPPO;UID=myUser;PWD=myPWD;TDS_Version= Auto;Port=1433;',
        'hostname' => '',
	'username' => 'myUser',
	'password' => 'myPWD',
        'database' => 'MY_MSSQL_DB',
	'dbdriver' => 'odbc',
	'dbprefix' => '', 
	'pconnect' => FALSE,
	'db_debug' => (ENVIRONMENT !== 'production'),
	'cache_on' => FALSE
);

**Comment by Davide65** [comment]
It works!
Thanks a lot
