### ISSUE TITLE
Tried to follow the examples of FreeTDS on Windows,but it has issues and I have no idea

### ISSUE THREAD

**Issue by abcdef123ghi** [FreeTDS/freetds#327]
Hi Freetds 
  I followed the example which is link to https://www.freetds.org/userguide/samplecode.htm

everything works fine but 2 statements didn't work and I have no idea

I was on a PC with Windows 8.1 and VS 2019 

in Example 11-7. Sample Code: DB-Library Fetch Results

 if ((columns = calloc(ncols, sizeof(struct col))) == NULL)
has issue :  E0513	a value of type "void *" cannot be assigned to an entity of type "col *"

 if ((pcol->buffer = calloc(1, 20)) == NULL) {

has issue: E0513	a value of type "void *" cannot be assigned to an entity of type "char *"

any idea?

**Comment by freddy77** [comment]
It looks like you are using a C++ compiler with C code

**Comment by abcdef123ghi** [comment]
> It looks like you are using a C++ compiler with C code

thanks for replying,these work for me
modified from
if ((columns = calloc(ncols, sizeof(struct col))) == NULL){
to
if ((columns = (col*)calloc(ncols, sizeof(struct col))) == NULL) {

and modified from 
if ((pcol->buffer = calloc(1, 20)) == NULL) {
to

if ((pcol->buffer = (char *)calloc(1, 20)) == NULL) {

**Comment by abcdef123ghi** [comment]
hopefully you guys just modify the example page as well please

**Comment by freddy77** [comment]
The examples are perfectly fine, as I said you are using the wrong compiler.
