### ISSUE TITLE
I have garbled character issue with freeTDS when I tried to execute a statement of insert with utf-8 characters

### ISSUE THREAD

**Issue by abcdef123ghi** [FreeTDS/freetds#330]
Hi freeTDS
   I tried to execute a statement of insert which was 
 "insert INTO msg(topic,msg) values ('orders/hj123456','Hallå')
the execution was success,but unfortunately I got the garbled character issue,
when I executed the inquery on management studio which was "select * from msg" and I just found the value of msg was
"Hall? ",even I tried to convert the statement of insert into UTF-8 format,it doesn't work 
even I have searched the documents of FreeDTS,I just found the FreeTDS convert text with libiconv and I just have tried to recompile freeTDS with libiconv and what I have done was 
built the libiconv 1.16 and copied the static library files /lib/  to /src/iconv/
modifed the CMakeLists.txt within the freeTDS which meditioned libiconv

set(lib_BASE ${lib_RT} ${CMAKE_THREAD_LIBS_INIT})
if(EXISTS "${CMAKE_SOURCE_DIR}/iconv/lib/libiconv-static.lib")
	set(lib_BASE ${lib_BASE} ${CMAKE_THREAD_LIBS_INIT} "${CMAKE_SOURCE_DIR}/iconv/lib/libiconv-static.lib")
	config_write("#define HAVE_ICONV 1\n\n")
	config_write("#define ICONV_CONST \n\n")
endif() 
then rebuilt the FreeTDS,unfortunately it doesn't work as well
any idea?
I was on Windows 7 + VS 2019,the server side was a Win 2003 with SQL 2000(it was a legacy project),libiconv 1.16 and FreeTDS 1.1

**Comment by abcdef123ghi** [comment]
this was the code which I tried to convert the ANSI code to UTF8 code ,it's not working

std::string iso_8859_1_to_utf8(std::string &str)
{
	string strOut;
	for (std::string::iterator it = str.begin(); it != str.end(); ++it)
	{
		uint8_t ch = *it;
		if (ch < 0x80) {
			strOut.push_back(ch);
		}
		else {
			strOut.push_back(0xc0 | ch >> 6);
			strOut.push_back(0x80 | (ch & 0x3f));
		}
	}
	return strOut;
}

**Comment by freddy77** [comment]
Why don't you use ODBC library?

You have to use as client encoding the one that match your strings.

Note also that for Windows you can find already compiled libraries following AppVeyor link in the main page (www.freetds.org, right bottom corner). They already contain libiconv compiled for Windows.

**Comment by abcdef123ghi** [comment]
> Why don't you use ODBC library?
> 
> You have to use as client encoding the one that match your strings.
> 
> Note also that for Windows you can find already compiled libraries following AppVeyor link in the main page ([www.freetds.org](http://www.freetds.org), right bottom corner). They already contain libiconv compiled for Windows.

Before I tried freetds,I have tried ODBC library,it doesn't work totally,it was not able to connect to MSSQL totally

**Comment by abcdef123ghi** [comment]
I really appreciate you replying

**Comment by abcdef123ghi** [comment]
> Why don't you use ODBC library?
> 
> You have to use as client encoding the one that match your strings.
> 
> Note also that for Windows you can find already compiled libraries following AppVeyor link in the main page ([www.freetds.org](http://www.freetds.org), right bottom corner). They already contain libiconv compiled for Windows.

thank you so much!!!!!!!!
it works until I add to the statements below!!!!

string Charset = "UTF-8";
DBSETLCHARSET(login, Charset.c_str());
