### ISSUE TITLE
Please subscribe me to the FreeTDS mailing list

### ISSUE THREAD

**Issue by toddthomp** [FreeTDS/freetds#334]
My email address is toddthomp@hotmail.com. 
I'd like to subscribe because I'm looking for instruction to install freetds freetds-1.1.20 on HPUX 11.31.
I wasn't able to find any on the freetds.org site or with a Google search.

Thanks,
Todd

**Comment by freddy77** [comment]
Subscribed. I don't have access nowadays to HP-UX, surely used to work. Did you see the UserGuide at http://www.freetds.org/userguide/ ? Continue on ML...
