### ISSUE TITLE
Return SQL_GD_ANY_COLUMN for SQLGetInfo(SQL_GETDATA_EXTENSIONS)?

### ISSUE THREAD

**Issue by krlmlr** [FreeTDS/freetds#335]
From my tests on Linux and Windows (version 1.0 and 1.1), FreeTDS seems to support `SQLGetData()` on columns that come before other bound columns. Can you confirm?

If yes, should this be communicated via `SQLGetInfo()`?

Relevant code:

https://github.com/FreeTDS/freetds/blob/2c9260c6bdc48242e2daa0bfefb6e1b785503f93/src/odbc/odbc.c#L5520-L5523

Downstream: https://github.com/nanodbc/nanodbc/issues/228

Output from a variant of the program from the [ODBC tutorial](https://www.easysoft.com/developer/languages/c/odbc_tutorial.html) on Ubuntu 18.04 with FreeTDS 1.0:

```r
Connected
DBMS Name: Microsoft SQL Server
DBMS Version: 15.00.4033
SQL_MAX_CONCURRENT_ACTIVITIES = 1
SQLGetData - columns must be retrieved in order
SQLGetData - columns must be retrieved after last bound one
```

Source code:

```c
#include <stdio.h>
#include <sql.h>
#include <sqlext.h>

int main() {
  SQLHENV env;
  SQLHDBC dbc;
  SQLRETURN ret; /* ODBC API return status */

  /* Allocate an environment handle */
  SQLAllocHandle(SQL_HANDLE_ENV, SQL_NULL_HANDLE, &env);
  /* We want ODBC 3 support */
  SQLSetEnvAttr(env, SQL_ATTR_ODBC_VERSION, (void *) SQL_OV_ODBC3, 0);
  /* Allocate a connection handle */
  SQLAllocHandle(SQL_HANDLE_DBC, env, &dbc);
  /* Connect to the DSN mydsn */
  ret = SQLDriverConnect(dbc, NULL, "DSN=dsn;", SQL_NTS,
                         NULL, 0, NULL,
                         SQL_DRIVER_COMPLETE);
  if (SQL_SUCCEEDED(ret)) {
    SQLCHAR dbms_name[256], dbms_ver[256];
    SQLUINTEGER getdata_support;
    SQLUSMALLINT max_concur_act;
    SQLSMALLINT string_len;

    printf("Connected\n");
    /*
     *  Find something out about the driver.
     */
    SQLGetInfo(dbc, SQL_DBMS_NAME, (SQLPOINTER)dbms_name,
               sizeof(dbms_name), NULL);
    SQLGetInfo(dbc, SQL_DBMS_VER, (SQLPOINTER)dbms_ver,
               sizeof(dbms_ver), NULL);
    SQLGetInfo(dbc, SQL_GETDATA_EXTENSIONS, (SQLPOINTER)&getdata_support,
               0, 0);
    SQLGetInfo(dbc, SQL_MAX_CONCURRENT_ACTIVITIES, &max_concur_act, 0, 0);

    printf("DBMS Name: %s\n", dbms_name);
    printf("DBMS Version: %s\n", dbms_ver);
    if (max_concur_act == 0) {
      printf("SQL_MAX_CONCURRENT_ACTIVITIES - no limit or undefined\n");
    } else {
      printf("SQL_MAX_CONCURRENT_ACTIVITIES = %u\n", max_concur_act);
    }
    if (getdata_support & SQL_GD_ANY_ORDER)
      printf("SQLGetData - columns can be retrieved in any order\n");
    else
      printf("SQLGetData - columns must be retrieved in order\n");
    if (getdata_support & SQL_GD_ANY_COLUMN)
      printf("SQLGetData - can retrieve columns before last bound one\n");
    else
      printf("SQLGetData - columns must be retrieved after last bound one\n");

    SQLDisconnect(dbc);               /* disconnect from driver */
  } else {
    fprintf(stderr, "Failed to connect\n");

  }
  /* free up allocated handles */
  SQLFreeHandle(SQL_HANDLE_DBC, dbc);
  SQLFreeHandle(SQL_HANDLE_ENV, env);
  return 0;
}
```

**Comment by freddy77** [comment]
Yes, FreeTDS keeps all row so you get fetch whatever column you want. However proprietary drivers have this restriction and I prefer to keep this small "lie" from FreeTDS in order to change in the future.

OT: about SQL_MAX_CONCURRENT_ACTIVITIES maybe should not be 1 if MARS is enabled, but you probably didn't enable MARS (better not unless you strictly need them).

**Comment by krlmlr** [comment]
Thanks. I'm having trouble parsing this. Is FreeTDS intentionally downplaying its capabilities? What are these "proprietary drivers" -- the ODBC drivers for databases other than SQL Server?

I'm running stock versions of FreeTDS, except on Windows where I installed from an AppVeyor `.zip` and really wish there was an `.msi` installer ;-)

**Comment by freddy77** [comment]
> Thanks. I'm having trouble parsing this. Is FreeTDS intentionally downplaying its capabilities? What are these "proprietary drivers" -- the ODBC drivers for databases other than SQL Server?
> 

Sorry for late reply. Yes, like Microsoft ODBC drivers.

> I'm running stock versions of FreeTDS, except on Windows where I installed from an AppVeyor `.zip` and really wish there was an `.msi` installer ;-)

Opened another issue, should not be difficult, just create a Wix file and use it during the build
