### ISSUE TITLE
Use GSS_C_NT_HOSTBASED_SERVICE instead of GSS_KRB5_NT_PRINCIPAL_NAME

### ISSUE THREAD

**Issue by nicowilliams** [FreeTDS/freetds#338]
It would be nice to have a configuration setting, and maybe even make it the default, for using `GSS_C_NT_HOSTBASED_SERVICE` instead of `GSS_KRB5_NT_PRINCIPAL_NAME`.  Using the latter, especially setting the realm to anything other than the empty string, is a recipe for hard-to-debug problems in environments with multiple realms.

**Comment by nicowilliams** [comment]
See https://github.com/dbcli/mssql-cli/issues/474.

**Comment by nicowilliams** [comment]
https://krbdev.mit.edu/rt/Ticket/Display.html?id=8903

**Comment by freddy77** [comment]
It looks like you know much more than me about kerberos. Some code suggestions? Suggestion for a possible option name?

**Comment by freddy77** [comment]
@nicowilliams no replies in months
