### ISSUE TITLE
freebcp fails when copying out empty table

### ISSUE THREAD

**Issue by epa** [FreeTDS/freetds#341]
Create an empty table:
`create table empty_table (a int not null)`
Then writing it out with freebcp fails:
```
% freebcp mydb..empty_table out outfile -c -S myserver -U myuser -P mypass

Starting copy...
Msg 20066, Level 2
The table which bulk copy is attempting to copy to a host file is shorter than the number of rows which bulk copy was instructed to skip

bcp copy out failed
```
This worked in 1.1.36 but fails in 1.1.39.

**Comment by epa** [comment]
I suspect this was broken as an accidental side-effect of the work to make the `-F` option to bcp omit data validation of rows which are to be skipped.  It looks like an off by one error; remember that `-F 1` does not mean skip the first row, but start with the first row, that is, skip nothing.

**Comment by freddy77** [comment]
Yes, indeed a regression. Patch/fix is simple, but I'll do some checks with proprietary tool before. The old code rely on a set/no set check which from proprietary documentation seems to not apply

**Comment by epa** [comment]
Thanks.  I wonder whether copying out an empty table with explicit `-F 1` should also work or is meant to fail.

**Comment by freddy77** [comment]
> Thanks. I wonder whether copying out an empty table with explicit `-F 1` should also work or is meant to fail.

You guessed one of the test I'm going to do :+1:

**Comment by freddy77** [comment]
Currently testing, I don't expect any failure by the way.

**Comment by freddy77** [comment]
Fixed and merged. Expect version 1.1.40 tomorrow (packaging is automatic)
