### ISSUE TITLE
"TDS: cannot resolve datatype 'univarchar'"

### ISSUE THREAD

**Issue by bindt** [FreeTDS/freetds#342]
This issue looks like had been resolved (#88) , however I see it in the latest 
version.

Environment:

Nginx Unit/PHP 7.4 (embed library)/Freetds 1.1.39
SAP SQL Anywhere 17
Table with nvarchar fields.

==========================================
tds version 4.2

have no idea it has relation to problem or not but it is in the log before request.

packet.c:640:Received packet
0000 04 00 00 1f 00 00 00 00-54 44 53 3a 20 75 6e 65 |........ TDS: une|
0010 78 70 65 63 74 65 64 20-74 6f 6b 65 6e 20 30    |xpected  token 0|

on data received from server 

dbutil.c:75:msgno 21: "TDS: cannot resolve datatype 'univarchar'"

and finished with:
SQL Anywhere Err or -85: Communication error

==========================================

tds version 5.0

it looks like data is received correctly, however 

first question: the server has UTf-8 charset but freetds detected 
it as UTF-16LE

next: the request is not finished , the connection is dropped by timeout

packet.c:742:Sending packet
0000 0f 01 00 94 00 00 00 00-21 87 00 00 00 00 53 45 |........ !.....SE|
0010 4c 45 43 54 20 5b 62 5d-2e 2a 20 46 52 4f 4d 20 |LECT [b] .* FROM |

....

dblib.c:4657:dbsqlok(0x55b1e9d30c80)
dblib.c:4686:dbsqlok() not done, calling tds_process_tokens()
token.c:532:tds_process_tokens(0x55b1e9d31460, 0x7ffcc3fbca58, 0x7ffcc3fbca5c, 0x6914)
util.c:165:Changed query state from PENDING to READING

packet.c:640:Received packet
....
01c0 00 64 00 6d 00 69 00 6e-00 69 00 73 00 74 00 72 |.d.m.i.n .i.s.t.r|
01d0 00 61 00 74 00 6f 00 72-00 72 00 72 00 72 00 78 |.a.t.o.r .r.r.r.x|
01e0 00 5a 00 78 00 62 00 62-00 64 00 64 00 64 00 76 |.Z.x.b.b .d.d.d.v|
01f0 00 47 00 58 00 47 00 58-00 45 00 00 00 00 00    |.G.X.G.X .E.....|

token.c:547:processing result tokens.  marker is  61(ROWFMT2)
token.c:1771:tds5_process_result2
mem.c:653:tds_free_all_results()
token.c:1795:num_cols=7
token.c:3193:adjust_character_column_size:
        Server charset: UTF-16LE
        Server column_size: 128
        Client charset: UTF-8
        Client column_size: 256

........

token.c:1862:   column_name=[description]
token.c:1868:   flags=0 utype=36 type=174 varint=4
token.c:1871:   colsize=131068 prec=0 scale=0
packet.c:640:Received packet
0000 04 01 00 36 00 00 00 00-10 87 02 00 00 00 00 00 |...6.... ........|
0010 00 c2 0b 00 00 00 c2 8f-02 00 00 00 00 00 00 00 |........ ........|
0020 00 00 00 00 00 14 b4 dd-5a df 33 58 5c fd 10 00 |........ Z.3X\...|
0030 01 00 01 00 00 00      -                        |......|

==========================================
tds version not specified -> default 7.4

same behavior like for 5.0

**Comment by freddy77** [comment]
Looks like there's some problems. Don't use protocol 4.2, unless you have to deal with some 20/25 years old servers you should not being using anyway. Protocol 7.4 is only MSSQL, won't work for Sybase. If the connection is working probably the client is just set to automatic and is succeeding as reconnecting using protocol 5.0. The logs are partial so I cannot confirm but from `type=174` the server reported a UNITEXT type which, as Sybase documentation states, is encoded always using UTF-16 encoding. If data in the server is not in UTF-16 format it means somebody uploaded wrong data on that column.

To better understand the issue I would need DDL information on the table and raw data for data returned from the server.

**Comment by bindt** [comment]
Actually, I've started with  tds version "auto" and continued to iterate after errors, starting from 4.2 as far as it is stated  "Still works with all products, subject to its limitations. " in documentation.
Anyway version 5.0 is broken as well for my configuration. 
 
Concerning SQL Anywhere, could you point me to the documentation where Sybase is always using UTF-16. I didn't find such info neither for ASE nor for SQLA. Moreover, I have feeling both don't support UTF-16, at least there is 
no option to create database with UTF-16 in SQLA and documentation for 
 ASE16 (SAP Adaptive Server Enterprise 16.0 > Configuration Guide for UNIX Adaptive Server Enterprise 16.0 > Localization Support) has only UTF8.


My server is:
dbinfo -c "uid=dba;pwd=sql"
SQL Anywhere Information Utility Version 17.0.10.6127
Database  : 10d.db
Log file  : 10d.log
Log mirror: none
Page size : 4096
Encrypted : No
Strings padded with blanks for comparisons: Yes
CHAR collation sequence: UTF8BIN(CaseSensitivity=Ignore)
CHAR character set encoding: UTF-8
NCHAR collation sequence: UTF8BIN(CaseSensitivity=Ignore)
NCHAR character set encoding: UTF-8
Database checksums enabled: Yes
Encrypted tables supported: No


DDL

CREATE TABLE "dba"."TblA" (
    "id"                                  integer NOT NULL DEFAULT autoincrement
   ,"name"                            nvarchar(255) NOT NULL
   ,"sort_order"                     integer NOT NULL DEFAULT 0
   ,"archived"                        tinyint NOT NULL DEFAULT 0
   ,"description"                    nvarchar(255) NOT NULL
   ,"location"                         nvarchar(255) NOT NULL   
   ,PRIMARY KEY ("id" ASC)
)


Would you like freetds log or tcpdump?
Btw, in my first post you can see in section for tds version=5 full log starting from select. The log was stopped where you can see.

**Comment by freddy77** [comment]
I tried to do something like:

```
create table \#t1 (description nvarchar(255))
go
insert into \#t1 values('test')
select * from \#t1
```
using Sybase 16 and correctly the column is returned as SYBLONGCHAR.

Both a freetds log or a tcpdump are fine to me. Send me privately if you are worried about possible security content.

**Comment by bindt** [comment]
Found in the documentation, ASE 16 
(SAP Adaptive Server Enterprise 16.0 > System Administration Guide 16.0: Volume 1 > Configuring Character Sets, Sort Orders, and Languages > Selecting the Character Set for Your Server)
...
SAP supported Unicode in the form of three datatypes: unichar, univarchar, and unitext. These datatypes store data in the UTF-16 encoding of Unicode. 

However, it is technical info. As you see it is located in SYSAdm guide. On top they have info about UTF-8. Thus, perhaps it sends UTF-16, as you mentioned.

SQL Anywhere (pls pay attention I'm talking about this server) has no UTF-16 support. 

Perhaps it need to be solved somehow defining UTF-8 for SQL Anywhere or
make it configurable in config file.

It seems to me I found the problem, I have no time to dive in source code,
so it is just guess.


below the freetds log for tds version = 5.0.

table a
description  nvarchar 32000

table b
nv  nvarchar 50

select * from a   never completed, keeps a open connection to server, so ctrl+c 
select * from b   was completed  without any problem.

the size of variable matter.  if it is more then 16kb  the request is hanging. 
SQLA allows nvarchar size 32767.


in freetds it is detected in different way 

(works)   token.c:1882:   flags=2 utype=35 type=35 server type 225 varint=5

(doesn't) token.c:1882:   flags=0 utype=36 type=174 server type 174 varint=4


token.c:3258:adjust_character_column_size:
	Server charset: UTF-16LE
	Server column_size: 65534
	Client charset: UTF-8
	Client column_size: 131068
token.c:1875:col 0:
token.c:1876:	column_name=[description]
token.c:1882:	flags=0 utype=36 type=174 server type 174 varint=4
token.c:1886:	colsize=131068 prec=0 scale=0




token.c:3258:adjust_character_column_size:
        Server charset: UTF-16LE
        Server column_size: 100
        Client charset: UTF-8
        Client column_size: 200
token.c:1875:col 0:
token.c:1876:   column_name=[nv]
token.c:1882:   flags=2 utype=35 type=35 server type 225 varint=5
token.c:1886:   colsize=200 prec=0 scale=0

**Comment by freddy77** [comment]
It seems this http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.help.sqlanywhere.12.0.1/dbadmin/natlang-s-6970658.html is confirming that SQL Anywhere does not support UTF-16 in these types. I did some additional tests on ASE 16 and it support UTF-16.

I think that during login SQL Anywhere is returning some capabilities in order to tell the client that is does not support UTF-16 but "only" UTF-8. Can I have a full network capture? I don't have SQL Anywhere and I would like to understand the different in CAPABILITIES reply.

**Comment by bindt** [comment]
log.c:168:Starting log file for FreeTDS 1.1.39
	on 2020-05-26 15:09:07 with debug flags 0x4fff.
dblib.c:1255:tdsdbopen: Calling tds_connect_and_login(0x2e76f70, 0x2e772c0)
iconv.c:326:tds_iconv_open(0x2e76bb0, UTF-8)
iconv.c:186:local name for ISO-8859-1 is ISO-8859-1
iconv.c:186:local name for UTF-8 is UTF-8
iconv.c:186:local name for UCS-2LE is UCS-2LE
iconv.c:186:local name for UCS-2BE is UCS-2BE
iconv.c:348:setting up conversions for client charset "UTF-8"
iconv.c:350:preparing iconv for "UTF-8" <-> "UCS-2LE" conversion
iconv.c:389:tds_iconv_open: done
net.c:391:Connecting with protocol version 5.0
net.c:318:Connecting to 127.0.0.1 port 2638
net.c:340:tds_setup_socket: connect(2) returned "Operation now in progress"
net.c:528:tds_open_socket() succeeded
packet.c:808:Sending packet
0000 02 00 02 00 00 00 00 00-64 6f 63 78 00 00 00 00 |........ docx....|
0010 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00 |........ ........|
0020 00 00 00 00 00 00 04 64-62 61 00 00 00 00 00 00 |.......d ba......|
0030 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00 |........ ........|
0040 00 00 00 00 00 73 71 6c-00 00 00 00 00 00 00 00 |......sq l.......|
0050 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00 |........ ........|
0060 00 00 00 00 08 32 39 32-38 00 00 00 00 00 00 00 |.....292 8.......|
0070 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00 |........ ........|
0080 00 00 00 04 03 01 06 0a-09 01 00 00 00 00 00 00 |........ ........|
0090 00 00 00 00 50 48 50 20-66 72 65 65 74 64 73 00 |....PHP  freetds.|
00a0 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00 |........ ........|
00b0 00 00 0b 31 32 37 2e 30-2e 30 2e 31 00 00 00 00 |...127.0 .0.1....|
00c0 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00 |........ ........|
00d0 00 09 00 08 73 71 6c 00-00 00 00 00 00 00 00 00 |....sql. ........|
00e0 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00 |........ ........|
00f0 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00 |........ ........|
0100 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00 |........ ........|
0110 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00 |........ ........|
0120 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00 |........ ........|
0130 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00 |........ ........|
0140 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00 |........ ........|
0150 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00 |........ ........|
0160 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00 |........ ........|
0170 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00 |........ ........|
0180 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00 |........ ........|
0190 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00 |........ ........|
01a0 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00 |........ ........|
01b0 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00 |........ ........|
01c0 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00 |........ ........|
01d0 00 0a 05 00 00 00 44 42-2d 4c 69 62 72 61 72 79 |......DB -Library|
01e0 0a 05 00 00 00 00 0d 11-75 73 5f 65 6e 67 6c 69 |........ us_engli|
01f0 73 68 00 00 00 00 00 00-00 00 00 00 00 00 00 00 |sh...... ........|

packet.c:808:Sending packet
0000 02 01 00 6b 00 00 00 00-00 00 00 00 00 00 0a 00 |...k.... ........|
0010 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00 |........ ........|
0020 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00 |........ ........|
0030 00 00 00 00 00 00 00 00-00 00 00 00 01 35 31 32 |........ .....512|
0040 00 00 00 03 00 00 00 00-e2 20 00 01 0e 00 00 60 |........ . .....`|
0050 08 81 81 e8 0f 6d 7f ff-ff ff fe 02 0e 00 00 00 |.....m.. ........|
0060 00 00 00 00 00 00 02 68-00 00 00                |.......h ...|

token.c:416:tds_process_login_tokens()
packet.c:436:Received packet
0000 04 01 00 63 00 00 00 00-e3 07 00 03 04 75 74 66 |...c.... .....utf|
0010 38 00 e3 09 00 04 03 35-31 32 03 35 31 32 ad 16 |8......5 12.512..|
0020 00 05 05 00 00 00 0c 53-51 4c 20 41 6e 79 77 68 |.......S QL Anywh|
0030 65 72 65 11 00 00 00 e2-20 00 01 0e 00 00 60 08 |ere.....  .....`.|
0040 01 81 e8 0e 61 01 ff ff-fe e6 02 0e ff ff 00 00 |....a... ........|
0050 00 01 fe 27 80 e6 68 00-00 0a fd 00 00 01 00 00 |...'..h. ........|
0060 00 00 00               -                        |...|

token.c:420:looking for login token, got  e3(ENVCHANGE)
token.c:129:tds_process_default_tokens() marker is e3(ENVCHANGE)
token.c:2302:server indicated charset change to "utf8"
iconv.c:786:setting server single-byte charset to "UTF-8"
dblib.c:305:db_env_chg(0x2e76f70, 3, , utf8)
token.c:420:looking for login token, got  e3(ENVCHANGE)
token.c:129:tds_process_default_tokens() marker is e3(ENVCHANGE)
token.c:2286:changing block size from 512 to 512
dblib.c:305:db_env_chg(0x2e76f70, 4, 512, 512)
token.c:420:looking for login token, got  ad(LOGINACK)
token.c:346:server reports TDS version 5.0.0.0
token.c:348:Product name for 0x5000000 is unknown
token.c:382:Product version 11000000
token.c:420:looking for login token, got  e2(CAPABILITY)
token.c:129:tds_process_default_tokens() marker is e2(CAPABILITY)
token.c:420:looking for login token, got  fd(DONE)
token.c:129:tds_process_default_tokens() marker is fd(DONE)
token.c:2095:tds_process_end: more_results = 0
		was_cancelled = 0
		error = 0
		done_count_valid = 0
token.c:2114:                rows_affected = 0
token.c:2117:tds_process_end() state set to TDS_IDLE
token.c:443:tds_process_login_tokens() returning TDS_SUCCESS
mem.c:656:tds_free_all_results()
util.c:165:Changed query state from IDLE to WRITING
packet.c:808:Sending packet
0000 0f 01 00 2f 00 00 00 00-21 22 00 00 00 00 73 65 |.../.... !"....se|
0010 74 20 74 65 78 74 73 69-7a 65 20 36 34 35 31 32 |t textsi ze 64512|
0020 20 73 65 6c 65 63 74 20-40 40 73 70 69 64 20    | select  @@spid |

util.c:165:Changed query state from WRITING to PENDING
token.c:553:tds_process_tokens(0x2e76f70, 0x7ffeea648b58, 0x7ffeea648b5c, 0x500)
util.c:165:Changed query state from PENDING to READING
packet.c:436:Received packet
0000 04 01 00 53 00 00 00 00-fd 01 00 01 00 00 00 00 |...S.... ........|
0010 00 61 1d 00 00 00 01 00-06 40 40 73 70 69 64 00 |.a...... .@@spid.|
0020 00 00 06 40 40 73 70 69-64 00 00 00 00 07 00 00 |...@@spi d.......|
0030 00 38 00 d1 03 00 00 00-fd 11 00 01 00 01 00 00 |.8...... ........|
0040 00 fd 01 00 01 00 00 00-00 00 fd 00 00 01 00 00 |........ ........|
0050 00 00 00               -                        |...|

token.c:568:processing result tokens.  marker is  fd(DONE)
token.c:2095:tds_process_end: more_results = 1
		was_cancelled = 0
		error = 0
		done_count_valid = 0
token.c:2114:                rows_affected = 0
util.c:165:Changed query state from READING to PENDING
token.c:553:tds_process_tokens(0x2e76f70, 0x7ffeea648b58, 0x7ffeea648b5c, 0x500)
util.c:165:Changed query state from PENDING to READING
token.c:568:processing result tokens.  marker is  61(ROWFMT2)
token.c:1785:tds5_process_result2
mem.c:656:tds_free_all_results()
token.c:1809:num_cols=1
token.c:1875:col 0:
token.c:1876:	column_name=[@@spid]
token.c:1882:	flags=0 utype=7 type=56 server type 56 varint=0
token.c:1886:	colsize=4 prec=0 scale=0
token.c:568:processing result tokens.  marker is  d1(ROW)
token.c:1950:tds_process_row(): reading column 0
data.c:720:tds_get_data: type 56, varint size 0
data.c:764:tds_get_data(): wire column size is 4
util.c:165:Changed query state from READING to PENDING
token.c:553:tds_process_tokens(0x2e76f70, 0x7ffeea648b58, 0x7ffeea648b5c, 0x500)
util.c:165:Changed query state from PENDING to READING
token.c:568:processing result tokens.  marker is  fd(DONE)
token.c:2095:tds_process_end: more_results = 1
		was_cancelled = 0
		error = 0
		done_count_valid = 1
token.c:2114:                rows_affected = 1
util.c:165:Changed query state from READING to PENDING
token.c:553:tds_process_tokens(0x2e76f70, 0x7ffeea648b58, 0x7ffeea648b5c, 0x500)
util.c:165:Changed query state from PENDING to READING
token.c:568:processing result tokens.  marker is  fd(DONE)
token.c:2095:tds_process_end: more_results = 1
		was_cancelled = 0
		error = 0
		done_count_valid = 0
token.c:2114:                rows_affected = 0
util.c:165:Changed query state from READING to PENDING
token.c:553:tds_process_tokens(0x2e76f70, 0x7ffeea648b58, 0x7ffeea648b5c, 0x500)
util.c:165:Changed query state from PENDING to READING
token.c:568:processing result tokens.  marker is  fd(DONE)
token.c:2095:tds_process_end: more_results = 0
		was_cancelled = 0
		error = 0
		done_count_valid = 0
token.c:2114:                rows_affected = 0
token.c:2117:tds_process_end() state set to TDS_IDLE
util.c:165:Changed query state from READING to IDLE
util.c:83:logic error: cannot change query state from IDLE to PENDING
util.c:165:Changed query state from IDLE to IDLE
token.c:553:tds_process_tokens(0x2e76f70, 0x7ffeea648b58, 0x7ffeea648b5c, 0x500)
token.c:556:tds_process_tokens() state is COMPLETED
dblib.c:217:dblib_add_connection(0x7f9db8f65840, 0x2e76f70)
dblib.c:1299:tdsdbopen: Returning dbproc = 0x2e762d0
dblib.c:4458:dbsetopt(0x2e762d0, 17, 2147483647, -1)
dblib.c:4458:dbsetopt(0x2e762d0, 35, 1, -1)
dblib.c:5923:dbsetuserdata(0x2e762d0, 0x7f9db0e75108)
dblib.c:3379:dbcancel(0x2e762d0)
query.c:2130:tds_send_cancel: not in_cancel and idle
dblib.c:1359:dbcmd(0x2e762d0, SELECT [b].* FROM [auth_assignment] [a], [auth_item] [b] WHERE ([a].[item_name]=[b].[name]) AND ([a].[user_id]='2') AND ([b].[type]=1))
dblib.c:1365:dbcmd() bufsz = 0
dblib.c:1405:dbsqlexec(0x2e762d0)
dblib.c:7033:dbsqlsend(0x2e762d0)
mem.c:656:tds_free_all_results()
util.c:165:Changed query state from IDLE to WRITING
packet.c:808:Sending packet
0000 0f 01 00 3f 00 00 00 00-21 32 00 00 00 00 73 65 |...?.... !2....se|
0010 74 20 74 65 78 74 73 69-7a 65 20 32 31 34 37 34 |t textsi ze 21474|
0020 38 33 36 34 37 0a 73 65-74 20 71 75 6f 74 65 64 |83647.se t quoted|
0030 5f 69 64 65 6e 74 69 66-69 65 72 20 6f 6e 0a    |_identif ier on.|

util.c:165:Changed query state from WRITING to PENDING
token.c:553:tds_process_tokens(0x2e76f70, 0x7ffeea64937c, (nil), 0x6914)
util.c:165:Changed query state from PENDING to READING
packet.c:436:Received packet
0000 04 01 00 2c 00 00 00 00-fd 01 00 01 00 00 00 00 |...,.... ........|
0010 00 fd 01 00 01 00 00 00-00 00 fd 01 00 01 00 00 |........ ........|
0020 00 00 00 fd 00 00 01 00-00 00 00 00             |........ ....|

token.c:568:processing result tokens.  marker is  fd(DONE)
token.c:2095:tds_process_end: more_results = 1
		was_cancelled = 0
		error = 0
		done_count_valid = 0
token.c:2114:                rows_affected = 0
util.c:165:Changed query state from READING to PENDING
token.c:553:tds_process_tokens(0x2e76f70, 0x7ffeea64937c, (nil), 0x6914)
util.c:165:Changed query state from PENDING to READING
token.c:568:processing result tokens.  marker is  fd(DONE)
token.c:2095:tds_process_end: more_results = 1
		was_cancelled = 0
		error = 0
		done_count_valid = 0
token.c:2114:                rows_affected = 0
util.c:165:Changed query state from READING to PENDING
token.c:553:tds_process_tokens(0x2e76f70, 0x7ffeea64937c, (nil), 0x6914)
util.c:165:Changed query state from PENDING to READING
token.c:568:processing result tokens.  marker is  fd(DONE)
token.c:2095:tds_process_end: more_results = 1
		was_cancelled = 0
		error = 0
		done_count_valid = 0
token.c:2114:                rows_affected = 0
util.c:165:Changed query state from READING to PENDING
token.c:553:tds_process_tokens(0x2e76f70, 0x7ffeea64937c, (nil), 0x6914)
util.c:165:Changed query state from PENDING to READING
token.c:568:processing result tokens.  marker is  fd(DONE)
token.c:2095:tds_process_end: more_results = 0
		was_cancelled = 0
		error = 0
		done_count_valid = 0
token.c:2114:                rows_affected = 0
token.c:2117:tds_process_end() state set to TDS_IDLE
util.c:165:Changed query state from READING to IDLE
util.c:83:logic error: cannot change query state from IDLE to PENDING
util.c:165:Changed query state from IDLE to IDLE
token.c:553:tds_process_tokens(0x2e76f70, 0x7ffeea64937c, (nil), 0x6914)
token.c:556:tds_process_tokens() state is COMPLETED
mem.c:656:tds_free_all_results()
util.c:165:Changed query state from IDLE to WRITING
packet.c:808:Sending packet
0000 0f 01 00 94 00 00 00 00-21 87 00 00 00 00 53 45 |........ !.....SE|
0010 4c 45 43 54 20 5b 62 5d-2e 2a 20 46 52 4f 4d 20 |LECT [b] .* FROM |
0020 5b 61 75 74 68 5f 61 73-73 69 67 6e 6d 65 6e 74 |[auth_as signment|
0030 5d 20 5b 61 5d 2c 20 5b-61 75 74 68 5f 69 74 65 |] [a], [ auth_ite|
0040 6d 5d 20 5b 62 5d 20 57-48 45 52 45 20 28 5b 61 |m] [b] W HERE ([a|
0050 5d 2e 5b 69 74 65 6d 5f-6e 61 6d 65 5d 3d 5b 62 |].[item_ name]=[b|
0060 5d 2e 5b 6e 61 6d 65 5d-29 20 41 4e 44 20 28 5b |].[name] ) AND ([|
0070 61 5d 2e 5b 75 73 65 72-5f 69 64 5d 3d 27 32 27 |a].[user _id]='2'|
0080 29 20 41 4e 44 20 28 5b-62 5d 2e 5b 74 79 70 65 |) AND ([ b].[type|
0090 5d 3d 31 29            -                        |]=1)|

util.c:165:Changed query state from WRITING to PENDING
dblib.c:4801:dbsqlok(0x2e762d0)
dblib.c:4830:dbsqlok() not done, calling tds_process_tokens()
token.c:553:tds_process_tokens(0x2e76f70, 0x7ffeea649478, 0x7ffeea64947c, 0x6914)
util.c:165:Changed query state from PENDING to READING
packet.c:436:Received packet
0000 04 01 01 f9 00 00 00 00-61 84 01 00 00 07 00 04 |........ a.......|
0010 6e 61 6d 65 05 31 30 64-63 63 03 64 62 61 09 61 |name.10d cc.dba.a|
0020 75 74 68 5f 69 74 65 6d-04 6e 61 6d 65 02 00 00 |uth_item .name...|
0030 00 23 00 00 00 e1 80 00-00 00 00 04 74 79 70 65 |.#...... ....type|
0040 05 31 30 64 63 63 03 64-62 61 09 61 75 74 68 5f |.10dcc.d ba.auth_|
0050 69 74 65 6d 04 74 79 70-65 00 00 00 00 06 00 00 |item.typ e.......|
0060 00 34 00 0b 64 65 73 63-72 69 70 74 69 6f 6e 05 |.4..desc ription.|
0070 31 30 64 63 63 03 64 62-61 09 61 75 74 68 5f 69 |10dcc.db a.auth_i|
0080 74 65 6d 0b 64 65 73 63-72 69 70 74 69 6f 6e 00 |tem.desc ription.|
0090 00 00 00 24 00 00 00 ae-fe ff 00 00 13 00 31 30 |...$.... ......10|
00a0 64 63 63 2e 64 62 61 2e-61 75 74 68 5f 69 74 65 |dcc.dba. auth_ite|
00b0 6d 00 09 72 75 6c 65 5f-6e 61 6d 65 05 31 30 64 |m..rule_ name.10d|
00c0 63 63 03 64 62 61 09 61-75 74 68 5f 69 74 65 6d |cc.dba.a uth_item|
00d0 09 72 75 6c 65 5f 6e 61-6d 65 20 00 00 00 23 00 |.rule_na me ...#.|
00e0 00 00 e1 80 00 00 00 00-04 64 61 74 61 05 31 30 |........ .data.10|
00f0 64 63 63 03 64 62 61 09-61 75 74 68 5f 69 74 65 |dcc.dba. auth_ite|
0100 6d 04 64 61 74 61 20 00-00 00 04 00 00 00 22 ff |m.data . ......".|
0110 7f 00 00 13 00 31 30 64-63 63 2e 64 62 61 2e 61 |.....10d cc.dba.a|
0120 75 74 68 5f 69 74 65 6d-00 0a 63 72 65 61 74 65 |uth_item ..create|
0130 64 5f 61 74 05 31 30 64-6f 63 03 64 62 61 09 61 |d_at.10d cc.dba.a|
0140 75 74 68 5f 69 74 65 6d-0a 63 72 65 61 74 65 64 |uth_item .created|
0150 5f 61 74 00 00 00 00 07-00 00 00 38 00 0a 75 70 |_at..... ...8..up|
0160 64 61 74 65 64 5f 61 74-05 31 30 64 63 63 03 64 |dated_at .10dcc.d|
0170 62 61 09 61 75 74 68 5f-69 74 65 6d 0a 75 70 64 |ba.auth_ item.upd|
0180 61 74 65 64 5f 61 74 00-00 00 00 07 00 00 00 38 |ated_at. .......8|
0190 00 d1 0a 00 00 00 61 00-64 00 6d 00 69 00 6e 00 |......a. d.m.i.n.|
01a0 01 00 10 87 02 00 00 00-00 00 00 c2 0b 00 00 00 |........ ........|
01b0 c2 8f 02 00 00 00 00 00-00 00 00 08 00 00 00 74 |........ .......t|
01c0 00 65 00 73 00 74 00 00-00 00 00 10 87 02 00 00 |.e.s.t.. ........|
01d0 00 00 00 00 c2 0b 00 00-00 c2 8f 02 00 00 00 00 |........ ........|
01e0 00 00 00 00 00 00 00 00-14 b4 dd 5a df 33 58 5c |........ ...Z.3X\|
01f0 fd 10 00 01 00 01 00 00-00                      |........ .|

token.c:568:processing result tokens.  marker is  61(ROWFMT2)
token.c:1785:tds5_process_result2
mem.c:656:tds_free_all_results()
token.c:1809:num_cols=7
token.c:3258:adjust_character_column_size:
	Server charset: UTF-16LE
	Server column_size: 128
	Client charset: UTF-8
	Client column_size: 256
token.c:1875:col 0:
token.c:1876:	column_name=[name]
token.c:1882:	flags=2 utype=35 type=35 server type 225 varint=5
token.c:1886:	colsize=256 prec=0 scale=0
token.c:1875:col 1:
token.c:1876:	column_name=[type]
token.c:1882:	flags=0 utype=6 type=52 server type 52 varint=0
token.c:1886:	colsize=2 prec=0 scale=0
token.c:3258:adjust_character_column_size:
	Server charset: UTF-16LE
	Server column_size: 65534
	Client charset: UTF-8
	Client column_size: 131068
token.c:1875:col 2:
token.c:1876:	column_name=[description]
token.c:1882:	flags=0 utype=36 type=174 server type 174 varint=4
token.c:1886:	colsize=131068 prec=0 scale=0

**Comment by freddy77** [comment]
I think the capability is `TDS_RES_IMAGE_NONCHAR`,  bit 47. I'll do some more tests with some other version

**Comment by mckaygerhard** [comment]
> reconnecting using protocol 5.0. The logs are partial so I cannot confirm but from type=174 the server reported a UNITEXT type which, as Sybase documentation states, is encoded always using UTF-16 encoding. If data in the server is not in UTF-16 format it means somebody uploaded wrong 

there's UNITEXT and UNIVARCHAR.. sybase 12 has UNIVARCHAR i cannot confir right now the UNITEXT..  lastes 1.X odbc tds tested by me returns good data.. (proxy table from mysql but consulting using sybase, yeah crazy but incredible)

> NVARCHAR
umm .. this seems does not support utf-16? well NVARCHAR are same as UNIVARCHAR for me!

@freddy77  the @bindt  just use sybase 17 ... and dumps are only for that .. remenber i provide to you dumps from sybase 12 with many dump data.. use them.. to compare.. 

my case was more harder.. a proxy table (something like a cache data from another server) linking a mysql table and consulting that table in sybase.. of course sybase db was latin1 and mysql was utf-8 .. i dont know why return so xtrange NVARCHAR but seems this is the always returned data type for those..

**Comment by freddy77** [comment]
@mckaygerhard, @bindt is right, ASA is pretty different and does not use UTF-16 but UTF-8 (despite TDS Sybase documentation). I was busy with release, it should not be difficult to check the capability I pointed out but it conflicted with the code I was working on before release.

**Comment by freddy77** [comment]
@bindt, can you try https://www.freetds.org/freetds-1.3.dev.20200729.tar.bz2 ? I'm testing with ASE and MSSQL but I don't have an ASA setup.

SHA1 (freetds-1.3.dev.20200729.tar.bz2) = 634420463199173ffb86dc6bd3f5fbf0ebd5d95a
MD5 (freetds-1.3.dev.20200729.tar.bz2) = 09566ddf95e27ebe4597c7c53f319c64

**Comment by freddy77** [comment]
Fixed
