### ISSUE TITLE
tdspool not respecting : max member age = 120

### ISSUE THREAD

**Issue by achix** [FreeTDS/freetds#347]
Hello
I have been trying freetds, via tds_fdw for postgresql in order to be able to access data on a ms sql 2008 server (protocol 7.3) as a foreign table in postgresql, and this has been working just fine. In order to be conservative at the beginning and minimize possibilities to mistreat the ms sql server I thought of accessing it from within tds_fdw via tdspool. And also this has been proven flawless up to now. However I cannot seem to get "max member age" to work as expected. I set min pool conn = 0. I disconnect from the postgresql session , I verify no client connections to the pool, I wait (much) longer than max member age (120) , but the connections to ms sql are not closing.

postgres$ sudo netstat -t -anp | grep 433
tcp        0      0 0.0.0.0:1433            0.0.0.0:*               LISTEN      10581/tdspool   
tcp        0      0 0.0.0.0:2433            0.0.0.0:*               LISTEN      10557/tdspool   
tcp        0      0 thishost.external.ip:57743         mssqlhost.ip:1433          ESTABLISHED 10581/tdspool   
tcp        0      0 thishost.external.ip:57618         mssqlhost.ip:1433          ESTABLISHED 10557/tdspool   
postgres$ 

freetds version : 1.1.40
tds_fdw version : 2.0.1
postgresql version : 10.13
ms sql version : ms sql server 2008

cat /usr/local/etc/freetds.conf
....
[bdynacomServer]
        host = <mssql ip>
        port = 1433
        tds version = 7.3

cat /usr/local/etc/pool.conf
[global]
        min pool conn = 5
        max pool conn = 10
        max member age = 120

[dynacombridgepool]
        user = xx
        password = xx
        database = xx1
        server = bdynacomServer
        port = 2433
        min pool conn = 0
        max pool conn = 5

[bdynacompool]
        user = xx
        password = xx
        database = xx2
        server = bdynacomServer
        port = 1433
        min pool conn = 0 
        max pool conn = 5

so I don't think the max member age = 120 setting works correctly.

Thank you for any help.

**Comment by freddy77** [comment]
I think I tested. Maybe is respecting but it's checking the age only while there's something active, not if perfectly idle.

**Comment by achix** [comment]
So you propose testing out some simple queries under light load and see at least of the connections drop to 1 for each pool? 
Anyways if your theory is correct it means that under momentary heavy load and then no load at all, the connections will stay at "max pool conn".

**Comment by freddy77** [comment]
Not hard, fix at https://github.com/FreeTDS/freetds/commit/faf136a22d73d670b2b07bd7ed9784c26e7742c6, time for minor testing and I'll merge it.

**Comment by achix** [comment]
This is good news, any idea of when will it be incorporated to the next release? Or should I just clone master and use it for production (after you merge it)? Or just apply this patch to 1.1.40 ?

**Comment by freddy77** [comment]
Being considered a bug has been backported. So it's on master, 1.1 (expect a package in a couple of hours, 1.1.41) and 1.2.

**Comment by achix** [comment]
Thank you so much!
