### ISSUE TITLE
Please add me to mail list.

### ISSUE THREAD

**Issue by elenablack** [FreeTDS/freetds#349]

**Comment by elenablack** [comment]
please add me to the mailing list.

**Comment by freddy77** [comment]
I need your e-mail address. You can send it to me privately (but I think it will appear later in the ML anyway).

**Comment by elenablack** [comment]
my account is on my personal email, 

myst.black@hotmail.com

but since this is for my company can we also add,
elena.black@amundipioneer.com?

i’m having trouble with SQL Server and FreeTDS SSL..

Thanks!
Elena

**Comment by freddy77** [comment]
done
