### ISSUE TITLE
Geometry Column

### ISSUE THREAD

**Issue by larsurilch** [FreeTDS/freetds#35]
Hello,

I would like to know how to perform a geometry query. All table data are returned except the geometry .

My settings:

Version: freetds v0.91
freetds.conf directory: /etc/freetds
MS db-lib source compatibility: no
Sybase binary compatibility: yes
Thread safety: yes
iconv library: yes
TDS version: 4.2
iODBC: no
unixodbc: yes
SSPI "trusted" logins: no
Kerberos: yes

Ex: SELECT ogr_geometry.STAsText ( ) FROM regioes_2010

Thanks

**Comment by freddy77** [comment]
Try to upgrade to 0.95 which can read CLR types. However we read as binary data so don't expect to see readable coordinates.

**Comment by larsurilch** [comment]
Thanks
