### ISSUE TITLE
Wide char support cooperate with ODBC function SQLExecDirectW

### ISSUE THREAD

**Issue by liutianchen** [FreeTDS/freetds#352]
ODBC support SQLExecDirectW API to execute wide char SQL string directly, and support SQLExecDirect to execute normal ASCII SQL string as well, does FreeTDS has fixed client charset option of client charset ? I call SQLExecDirectW, and I found ODBC convert my UCS-2 charset SQL string back to ASCII charset. Can I execute UCS2 charset SQL string directly to avoid implicit charset convert in FreeTDS ? Thank you for your answering.

**Comment by freddy77** [comment]
Hi,
  for a proper answer I would need more detail on your setup. ASCII was
NEVER used by ODBC, you are confusing ANSI terminology with ASCII. Last
UCS-2 usage was a decade ago, even FreeTDS uses UTF-16 or UTF-32. Depending
on the DM and configuration, wide encoding can be either UTF-16 or UTF-32,
I suppose UTF-16 in your case from what you are saying. Microsoft uses
UTF-16 on the network so unless you are using a very old TDS protocol
version using SQLExecDirectW should lead to no conversion. In some cases
the server itself does some conversion when moving data to columns,
depending on the column collations. A "N" prefix could help in these cases.

Regards,
  Frediano


Il giorno gio 9 lug 2020 alle ore 07:29 Liu Tianchen <
notifications@github.com> ha scritto:

**Comment by liutianchen** [comment]
Thank you for your immediate reply, and please forgive my inconcrete description, as a matter of fact I am working in the circumstance that only basic charactors appear so I make a mistake, yes it is UTF-8, Actually the "UCS-2LE" charset format is the response of a very old version SQL Server. Anyway, the situation is UTF-8 client (FreeTDS) and UCS2-LE server (SQL Server), I didn't write config key word "ClientCharset" in odbc.ini and according my GDB debug and official document on freetds.org,  there is a default macro in FreeTDS ISO8890-1 inside source code of FreeTDS, and it is covered by a config obtained by ODBC from system environ-variable (when there's no related config in odbc.ini) . I try to add keyword ClientCharset = UCS2-LE in odbc.ini, and ODBC report it is unable to connect to server.  I call the ODBC API "SQLExecDirectW" which accept the wide char SQL string which is pre-converted to UCS-2 by me, and it really confused me that ODBC convert it to UTF-8 and FreeTDS still implicit convert it to UCS-2. (I found it by setting a break point at function tds_iconv in GDB and print out all parameters, the config is identified by "client2ucs" enumeration) .

**Comment by liutianchen** [comment]
All I aimed to is to ommit the implicit the "iconv" in tds because I am trying to find out how fast could the FreeTDS be between I call "SQLExecute" and send a packet out, the time unit is nanosecond (1e-12), although I already find the FreeTDS is really high efficient because of the really charming structure.

**Comment by liutianchen** [comment]
oh sorry, I forget to mention that I am working with FreeTDS 0.9.1 because I found there is would be unpredictable coredump where I use FreeTDS 1.2.0, it is probablely because the SQL Server version is too old and FreeTDS 0.9.1 is enough stable.

**Comment by freddy77** [comment]
0.9.1 is no more supported. If you have issues with 1.2 open an issue about it.

libTDS (lower layer) does not support multiple encoding at the same type so ODBC convert query strings to UTF-8 (from both wide and ansi encodings) and libTDS will convert to server ones (depending on server type and version and protocol used). ODBC use ad-hoc conversion routines if possible. Note that data path does not follow this, using ODBC libTDS does not convert data strings and ODBC will do the conversion only if needed.

**Comment by freddy77** [comment]
Note that `ClientCharset = UCS-2` or any no multi-byte is not supported. There should be a check about it in recent versions.

**Comment by liutianchen** [comment]
Thank you, many help ~
