### ISSUE TITLE
tds5_gss_send not found

### ISSUE THREAD

**Issue by stef-pellegrino** [FreeTDS/freetds#356]
On Windows 10, VC15, last version of FreeTds, I get when compiling (project built with cmake)
ENABLE_KRB5 is on

tds.lib(login.c.obj) : error LNK2019: unresolved external symbol _tds5_gss_send referenced in function _tds_send_login
tds.lib(login.c.obj) : error LNK2019: unresolved external symbol _tds_gss_get_auth referenced in function _tds_send_login

**Comment by freddy77** [comment]
I think something like this could help https://github.com/FreeTDS/freetds/commit/8188fc6f17f1ceaed7f5df50f6a694e158f12756 .

But I'm not sure is entirely fine. In particular maybe under Windows you want to use SSPI for Kerberos too.

**Comment by freddy77** [comment]
By the way, applied, won't hurt, maximum you have a compilation error if you don't have GSSAPI

**Comment by stef-pellegrino** [comment]
YEs my fault, with cmake, I though I had to check "ENABLE_KRB5" to get sspi 👍 
Should have read code first, Thanks for your time...
