### ISSUE TITLE
Sybase error message number not passed to error handler

### ISSUE THREAD

**Issue by bellam-r** [FreeTDS/freetds#361]
DBLIB (dbutil.c:98) doesn't pass Sybase DB error number to error handler and instead is set as a constant SYBESMSG.

**Comment by freddy77** [comment]
I tried to reproduce with Sybase libraries. This is expected behaviour. An error message from the server is send both to message handler (`dbmsghandle`) and error handler (`dberrhandle`). To get the full error use the message handler.
