### ISSUE TITLE
DBLIB allow bcp null values to tables with non-nullable columns

### ISSUE THREAD

**Issue by bellam-r** [FreeTDS/freetds#362]
DBLIB allow BCP null values to Sybase tables with non-nullable columns. 

There are some commented codes in bcp.c and bulk.c, w.r.t error handling on this.

**Comment by freddy77** [comment]
Proposed patches from @bellam-r 

bcp.c.patch

```diff
--- freetds-1.2.5/src/dblib/bcp.c	2020-07-07 17:15:11.000000000 +0900
+++ freetds-1.2.5.patch/src/dblib/bcp.c	2020-10-06 10:02:40.705623698 +0900
@@ -80,6 +80,7 @@
 
 static void _bcp_free_storage(DBPROCESS * dbproc);
 static void _bcp_free_columns(DBPROCESS * dbproc);
+static void _bcp_null_error(TDSBCPINFO *bcpinfo, int index, int offset);
 static TDSRET _bcp_get_col_data(TDSBCPINFO *bcpinfo, TDSCOLUMN *bindcol, int offset);
 static TDSRET _bcp_no_get_col_data(TDSBCPINFO *bcpinfo, TDSCOLUMN *bindcol, int offset);
 
@@ -622,7 +623,7 @@
 {
 	int i;
 	static const char *const hints[] = {
-		"ORDER", "ROWS_PER_BATCH", "KILOBYTES_PER_BATCH", "TABLOCK", "CHECK_CONSTRAINTS", "FIRE_TRIGGERS", NULL
+		"ORDER", "ROWS_PER_BATCH", "KILOBYTES_PER_BATCH", "TABLOCK", "CHECK_CONSTRAINTS", "FIRE_TRIGGERS", "KEEP_NULLS", NULL
 	};
 
 	tdsdump_log(TDS_DBG_FUNC, "bcp_options(%p, %d, %p, %d)\n", dbproc, option, value, valuelen);
@@ -1414,7 +1415,7 @@
 	}
 
 	dbproc->bcpinfo->parent = dbproc;
-	return TDS_FAILED(tds_bcp_send_record(dbproc->tds_socket, dbproc->bcpinfo, _bcp_get_col_data, NULL, 0)) ? FAIL : SUCCEED;
+	return TDS_FAILED(tds_bcp_send_record(dbproc->tds_socket, dbproc->bcpinfo, _bcp_get_col_data, _bcp_null_error, 0)) ? FAIL : SUCCEED;
 }
 
 
@@ -1555,7 +1556,7 @@
 		if (skip)
 			continue;
 
-		if (TDS_SUCCEED(tds_bcp_send_record(dbproc->tds_socket, dbproc->bcpinfo, _bcp_no_get_col_data, NULL, 0))) {
+		if (TDS_SUCCEED(tds_bcp_send_record(dbproc->tds_socket, dbproc->bcpinfo, _bcp_no_get_col_data, _bcp_null_error, 0))) {
 
 			rows_written_so_far++;
 
@@ -2235,7 +2236,7 @@
 	if (bindcol->bcp_term_len > 0) {	/* terminated field */
 		bytes_read = _bcp_get_term_var(dataptr, (BYTE *)bindcol->bcp_terminator, bindcol->bcp_term_len);
 
-		if (collen)
+		if (collen > 0) /* BCP FIX */
 			collen = (bytes_read < collen) ? bytes_read : collen;
 		else
 			collen = bytes_read;
@@ -2382,3 +2383,9 @@
 	dbproc->bcpinfo = NULL;
 }
 
+static void
+_bcp_null_error(TDSBCPINFO *bcpinfo, int index, int offset)
+{
+     DBPROCESS *dbproc = (DBPROCESS *) bcpinfo->parent;
+     dbperror(dbproc, SYBEBCNN, 0);
+}
```

bulk.c.patch

```diff
--- freetds-1.2.5/src/tds/bulk.c	2020-05-31 21:36:24.000000000 +0900
+++ freetds-1.2.5.patch/src/tds/bulk.c	2020-10-06 10:36:39.467706434 +0900
@@ -334,7 +334,7 @@
  * \return TDS_SUCCESS or TDS_FAIL.
  */
 TDSRET
-tds_bcp_send_record(TDSSOCKET *tds, TDSBCPINFO *bcpinfo, tds_bcp_get_col_data get_col_data, tds_bcp_null_error ignored, int offset)
+tds_bcp_send_record(TDSSOCKET *tds, TDSBCPINFO *bcpinfo, tds_bcp_get_col_data get_col_data, tds_bcp_null_error null_error, int offset)
 {
 	TDSCOLUMN  *bindcol;
 	int i;
@@ -414,7 +414,7 @@
 		row_pos = 2;
 
 		rc = TDS_FAIL;
-		if ((row_pos = tds_bcp_add_fixed_columns(bcpinfo, get_col_data, NULL, offset, record, row_pos)) < 0)
+		if ((row_pos = tds_bcp_add_fixed_columns(bcpinfo, get_col_data, null_error, offset, record, row_pos)) < 0)
 			goto cleanup;
 
 		row_sz_pos = row_pos;
@@ -481,7 +481,7 @@
  * \returns new row length or -1 on error.
  */
 static int
-tds_bcp_add_fixed_columns(TDSBCPINFO *bcpinfo, tds_bcp_get_col_data get_col_data, tds_bcp_null_error ignored, 
+tds_bcp_add_fixed_columns(TDSBCPINFO *bcpinfo, tds_bcp_get_col_data get_col_data, tds_bcp_null_error null_error, 
 				int offset, unsigned char * rowbuffer, int start)
 {
 	TDS_NUMERIC *num;
@@ -518,6 +518,12 @@
 			return -1;
 		}
 #endif
+		/* No value or default value available and NULL not allowed. */
+		if (bcpcol->bcp_column_data->is_null) {
+               tdsdump_log(TDS_DBG_FUNC, "tds_bcp_add_fixed_columns column %d is a null column\n", i + 1);
+			null_error(bcpinfo, i, offset); 
+			return TDS_FAIL;
+		}
 
 		if (is_numeric_type(bcpcol->column_type)) {
 			num = (TDS_NUMERIC *) bcpcol->bcp_column_data->data;
@@ -621,6 +627,11 @@
 			return -1;
 		}
 #endif
+	/* No value or default value available and NULL not allowed. */
+		if (!(bcpcol->column_nullable) && bcpcol->bcp_column_data->is_null) {
+			null_error(bcpinfo, i, offset); 
+			return TDS_FAIL;
+		}
 
 		/* move the column buffer into the rowbuffer */
 		if (!bcpcol->bcp_column_data->is_null) {
```

**Comment by freddy77** [comment]
There are also changes in this respect in NCBI pull request.

James changed this years ago mentioning DEFAULT settings and MSSQL. I did some tests with Microsoft tools. Columns are sent always as nullable types (even if column is not nullable) so server can replace with DEFAULT, even if we disable the replacement with DEFAULT. But I think this behaviour is wrong for Sybase servers. That is it needs more automatic testing and fixes in order to make both databases happy.

**Comment by freddy77** [comment]
The key change on history is https://github.com/FreeTDS/freetds/commit/e1a1216a07246d6abe7a42bf71e369e4cf47a0fd.

Note the comment
```
/* 
 * This function can be removed subject to testing with TDS 5.0.  It is currently unused. 
 * The bcp library was raising an error if data were missing for a non-null target column.  
 * However, the server can have a default defined for the column, making the check both unnecessary
 * and unhelpful (because the file actually could be loaded if e.g. freebcp would at least *try*.  
 * 
 * If Sybase works the same way, remove tds_bcp_null_error parameter from 
 *  	tds_bcp_add_fixed_columns, tds_bcp_add_variable_columns, tds.h, tds_bcp_send_record
 * at the same time.  Also remove any code marked by USING_SYBEBCNN.  
 */
```

**Comment by bellam-r** [comment]
> Proposed patches from @bellam-r
> 
> bcp.c.patch
> 
> ```diff
> --- freetds-1.2.5/src/dblib/bcp.c	2020-07-07 17:15:11.000000000 +0900
> +++ freetds-1.2.5.patch/src/dblib/bcp.c	2020-10-06 10:02:40.705623698 +0900
> @@ -80,6 +80,7 @@
>  
>  static void _bcp_free_storage(DBPROCESS * dbproc);
>  static void _bcp_free_columns(DBPROCESS * dbproc);
> +static void _bcp_null_error(TDSBCPINFO *bcpinfo, int index, int offset);
>  static TDSRET _bcp_get_col_data(TDSBCPINFO *bcpinfo, TDSCOLUMN *bindcol, int offset);
>  static TDSRET _bcp_no_get_col_data(TDSBCPINFO *bcpinfo, TDSCOLUMN *bindcol, int offset);
>  
> @@ -622,7 +623,7 @@
>  {
>  	int i;
>  	static const char *const hints[] = {
> -		"ORDER", "ROWS_PER_BATCH", "KILOBYTES_PER_BATCH", "TABLOCK", "CHECK_CONSTRAINTS", "FIRE_TRIGGERS", NULL
> +		"ORDER", "ROWS_PER_BATCH", "KILOBYTES_PER_BATCH", "TABLOCK", "CHECK_CONSTRAINTS", "FIRE_TRIGGERS", "KEEP_NULLS", NULL
>  	};
>  
>  	tdsdump_log(TDS_DBG_FUNC, "bcp_options(%p, %d, %p, %d)\n", dbproc, option, value, valuelen);
> @@ -1414,7 +1415,7 @@
>  	}
>  
>  	dbproc->bcpinfo->parent = dbproc;
> -	return TDS_FAILED(tds_bcp_send_record(dbproc->tds_socket, dbproc->bcpinfo, _bcp_get_col_data, NULL, 0)) ? FAIL : SUCCEED;
> +	return TDS_FAILED(tds_bcp_send_record(dbproc->tds_socket, dbproc->bcpinfo, _bcp_get_col_data, _bcp_null_error, 0)) ? FAIL : SUCCEED;
>  }
>  
>  
> @@ -1555,7 +1556,7 @@
>  		if (skip)
>  			continue;
>  
> -		if (TDS_SUCCEED(tds_bcp_send_record(dbproc->tds_socket, dbproc->bcpinfo, _bcp_no_get_col_data, NULL, 0))) {
> +		if (TDS_SUCCEED(tds_bcp_send_record(dbproc->tds_socket, dbproc->bcpinfo, _bcp_no_get_col_data, _bcp_null_error, 0))) {
>  
>  			rows_written_so_far++;
>  
> @@ -2235,7 +2236,7 @@
>  	if (bindcol->bcp_term_len > 0) {	/* terminated field */
>  		bytes_read = _bcp_get_term_var(dataptr, (BYTE *)bindcol->bcp_terminator, bindcol->bcp_term_len);
>  
> -		if (collen)
> +		if (collen > 0) /* BCP FIX */
>  			collen = (bytes_read < collen) ? bytes_read : collen;
>  		else
>  			collen = bytes_read;
> @@ -2382,3 +2383,9 @@
>  	dbproc->bcpinfo = NULL;
>  }
>  
> +static void
> +_bcp_null_error(TDSBCPINFO *bcpinfo, int index, int offset)
> +{
> +     DBPROCESS *dbproc = (DBPROCESS *) bcpinfo->parent;
> +     dbperror(dbproc, SYBEBCNN, 0);
> +}
> ```
> 
> bulk.c.patch
> 
> ```diff
> --- freetds-1.2.5/src/tds/bulk.c	2020-05-31 21:36:24.000000000 +0900
> +++ freetds-1.2.5.patch/src/tds/bulk.c	2020-10-06 10:36:39.467706434 +0900
> @@ -334,7 +334,7 @@
>   * \return TDS_SUCCESS or TDS_FAIL.
>   */
>  TDSRET
> -tds_bcp_send_record(TDSSOCKET *tds, TDSBCPINFO *bcpinfo, tds_bcp_get_col_data get_col_data, tds_bcp_null_error ignored, int offset)
> +tds_bcp_send_record(TDSSOCKET *tds, TDSBCPINFO *bcpinfo, tds_bcp_get_col_data get_col_data, tds_bcp_null_error null_error, int offset)
>  {
>  	TDSCOLUMN  *bindcol;
>  	int i;
> @@ -414,7 +414,7 @@
>  		row_pos = 2;
>  
>  		rc = TDS_FAIL;
> -		if ((row_pos = tds_bcp_add_fixed_columns(bcpinfo, get_col_data, NULL, offset, record, row_pos)) < 0)
> +		if ((row_pos = tds_bcp_add_fixed_columns(bcpinfo, get_col_data, null_error, offset, record, row_pos)) < 0)
>  			goto cleanup;
>  
>  		row_sz_pos = row_pos;
> @@ -481,7 +481,7 @@
>   * \returns new row length or -1 on error.
>   */
>  static int
> -tds_bcp_add_fixed_columns(TDSBCPINFO *bcpinfo, tds_bcp_get_col_data get_col_data, tds_bcp_null_error ignored, 
> +tds_bcp_add_fixed_columns(TDSBCPINFO *bcpinfo, tds_bcp_get_col_data get_col_data, tds_bcp_null_error null_error, 
>  				int offset, unsigned char * rowbuffer, int start)
>  {
>  	TDS_NUMERIC *num;
> @@ -518,6 +518,12 @@
>  			return -1;
>  		}
>  #endif
> +		/* No value or default value available and NULL not allowed. */
> +		if (bcpcol->bcp_column_data->is_null) {
> +               tdsdump_log(TDS_DBG_FUNC, "tds_bcp_add_fixed_columns column %d is a null column\n", i + 1);
> +			null_error(bcpinfo, i, offset); 
> +			return TDS_FAIL;
> +		}
>  
>  		if (is_numeric_type(bcpcol->column_type)) {
>  			num = (TDS_NUMERIC *) bcpcol->bcp_column_data->data;
> @@ -621,6 +627,11 @@
>  			return -1;
>  		}
>  #endif
> +	/* No value or default value available and NULL not allowed. */
> +		if (!(bcpcol->column_nullable) && bcpcol->bcp_column_data->is_null) {
> +			null_error(bcpinfo, i, offset); 
> +			return TDS_FAIL;
> +		}
>  
>  		/* move the column buffer into the rowbuffer */
>  		if (!bcpcol->bcp_column_data->is_null) {
> ```

@freddy77  Can this be merged into master?

**Comment by freddy77** [comment]
The proposed patches are partially rolling back the change from James. I would like to get more tests and a behaviour that would suite both Sybase and Microsoft ones. For Sybase is impossible to insert NULLs value in not nullable columns. Also if a type is not nullable we can't physically send a NULL. Microsoft libraries, if the column server type is not nullable send a nullable type in any case ; this to support replacing with default value (which is the default, you can change using `bcp_control` which will enable `KEEP_NULLS` hint). Microsoft `bcp` utility always send NULLs, even if columns are not nullable and `KEEP_NULLS` is specified (in this case server will give error, not done in the client). At the moment using not nullable columns and null values can lead to bad asserts which is pretty bad. I would also like to test any possible server types to make sure they all works correctly (even considering different endianess and character conversions as a bonus). Another nice change for Sybase would be to use the information returned by the server issuing the `insert bulk` statement, not the additional `select` statement to make sure to avoid possible race condition (parse these information is partially done by NBI patches).

**Comment by freddy77** [comment]
@bellam-r can you test master branch ?

**Comment by bellam-r** [comment]
> @bellam-r can you test master branch ?

Tested on master - no luck yet. I have sent you debug log.

**Comment by bellam-r** [comment]
> > @bellam-r can you test master branch ?
> 
> Tested on master - no luck yet. I have sent you debug log.

Re-tested on Appveyor branch and confirmed works fine.

**Comment by freddy77** [comment]
Backported to 1.2.17.
