### ISSUE TITLE
freetds.org domain issues

### ISSUE THREAD

**Issue by dushankw** [FreeTDS/freetds#363]
Hi,

It appears your domain name is having some kind of issue, it has the `clientHold` flag set and is not resolving in the public DNS.

There may be some issue with your registrar, you should investigate it ASAP to avoid the risk of the domain being purged and someone else being able to claim it.

```
$ whois freetds.org
Domain Name: FREETDS.ORG
Registry Domain ID: D9447952-LROR
Registrar WHOIS Server:
Registrar URL: http://www.omnis.com
Updated Date: 2020-10-18T14:10:05Z
Creation Date: 1999-08-25T02:32:50Z
Registry Expiry Date: 2021-08-25T02:32:50Z
Registrar Registration Expiration Date:
Registrar: Omnis Network LLC
Registrar IANA ID: 143
Registrar Abuse Contact Email:
Registrar Abuse Contact Phone:
Reseller:
Domain Status: clientHold https://icann.org/epp#clientHold
Registrant Organization: Lowden
Registrant State/Province: ME
Registrant Country: US
Name Server: NS1.OMNIS.COM
Name Server: NS2.OMNIS.COM
Name Server: NS3.OMNIS.COM
DNSSEC: unsigned
URL of the ICANN Whois Inaccuracy Complaint Form https://www.icann.org/wicf/)
>>> Last update of WHOIS database: 2020-10-18T23:20:03Z <<<
```

**Comment by freddy77** [comment]
Checking, thanks

**Comment by alexpinsky** [comment]
Hi, it's still down..
![Screen Shot 2020-10-19 at 14 01 48](https://user-images.githubusercontent.com/3108776/96442332-a4977500-1213-11eb-954d-43f31699651f.png)

**Comment by bugg2844** [comment]
Still down.

**Comment by UltroEdward** [comment]
looks like available on godaddy, https://ru.godaddy.com/domainsearch/find?checkAvail=1&domainToCheck=freetds.com per 4999/year. Pretty sure they was notified many times

**Comment by mason-sharp** [comment]
> looks like available on godaddy, https://ru.godaddy.com/domainsearch/find?checkAvail=1&domainToCheck=freetds.com per 4999/year. Pretty sure they was notified many times

That link is for .com, not .org.

**Comment by alexpinsky** [comment]
If this impacts your Heroku buildpack, use this https://github.com/eligoenergy/heroku-buildpack-freetds repo to compile against Github.

**Comment by kevinchiu** [comment]
This is also not resolving through Cloudflare's DNS at 1.1.1.1
Currently affecting tiny_tds Ruby gem.

**Comment by kevinchiu** [comment]
> If this impacts your Heroku buildpack, use this https://github.com/eligoenergy/heroku-buildpack-freetds repo to compile against Github.

Line 121 still refers to freetds.org 

  FREETDS_URL="https://www.freetds.org/files/stable/${FREETDS_FILE}"

**Comment by alexpinsky** [comment]
Yes but the function isn't used anymore.. see line 184. 
Anyhow, it's not my repo. But I've checked it and it works. You can fork it and clean it.

**Comment by josephbridgwaterrowe** [comment]
This is preventing my builds to complete, does anyone have a solution?

I looked at this image: https://github.com/veracross/circleci-ruby-freetds, but it was using an older version of the library.

I suppose I could find a newer version and build my own image, but that seems a fair amount of work for what hopefully is a brief outage for freetds.org.

**Comment by freddy77** [comment]
Fixed. Trying to understand how it happened

**Comment by bugg2844** [comment]
Still not resolving here.  Possibly DNS caching?

**Comment by kierany5** [comment]
@bugg2844 Possibly.  Checked DNS records on a who-is service and it has an A record now for "www.freetds.org" but not "freetds.org".  Needs an @ A record.  Can get necessary files from http://38.117.134.17/pub/freetds/stable/

**Comment by freddy77** [comment]
> @bugg2844 Possibly. Checked DNS records on a who-is service and it has an A record now for "www.freetds.org" but not "freetds.org". Needs an @ A record. Can get necessary files from http://38.117.134.17/pub/freetds/stable/

Why `freetds.org` need an A record? The website is `www.freetds.org` and better to use https which has `www.freetds.org` as DNS name.

**Comment by kierany5** [comment]
Agreed on HTTPs, but if someone just types `freetds.org` the browser won't necessarily put the `www.` on the front.  IMO there should at least be a redirect from `freetds.org` to `www.freetds.org` just to reduce the change of people getting issues.  But then now it's up, I guess anyone looking for the site will probably go through a search engine anyway.

Anyway, thanks @freddy77 for sorting this issue out.  We got a little worried over here that Free TDS was going to vanish!

**Comment by bugg2844** [comment]
Ok, fair enough, my mistake.  I was testing using https://freetds.org because that's where I thought the website was... perhaps because Chrome now hides the www prefix per https://url.spec.whatwg.org/#url-rendering-simplification.

Thanks for fixing!

**Comment by freddy77** [comment]
> 
> Anyway, thanks @freddy77 for sorting this issue out. We got a little worried over here that Free TDS was going to vanish!

More thanks to James and Christos who did the heavy lifts.
