### ISSUE TITLE
Consider update openssl used by prebuild windows binary in appveyor ci to 1.1.0/1.1.1

### ISSUE THREAD

**Issue by yyjdelete** [FreeTDS/freetds#366]
openssl 1.0.2 is already EOL in 2020 and windows installer is no longer downloadable from http://slproweb.com/products/Win32OpenSSL.html now

https://www.openssl.org/blog/blog/2019/11/07/3.0-update/

Is it ok to update it to 1.1.1 or 1.1.0(1.1.0 is also EOL, but 1.1.1 should be API and ABI compliant with 1.1.0). Seems only needed to update `c:\openssl-win%WIDTH%` in `misc/appveyor.yml` to `C:\OpenSSL-v111-Win%WIDTH%` or `C:\OpenSSL-v11-Win%WIDTH%`
https://www.appveyor.com/docs/windows-images-software/#tools

**Comment by freddy77** [comment]
Like this https://github.com/FreeTDS/freetds/commit/add8d90c0a22fb5dc09f78750ee24309e8370e82 ?
Testing. I though they updated without changing directory.

**Comment by freddy77** [comment]
Apparently just updating the directory is not enough, but if you also delete the old one CMake will find the new.

**Comment by yyjdelete** [comment]
Seems cmake prefer registry data than environment vars, maybe add `-DOPENSSL_ROOT_DIR=%OPENSSL_ROOT_DIR%` directly to cmake commandline also works.

**Comment by freddy77** [comment]
Done
