### ISSUE TITLE
As advised: subscription opening an issue on GitHub - Typedef issues

### ISSUE THREAD

**Issue by LtCdr-FUDGE** [FreeTDS/freetds#367]
Greetings. I would like to both raise an issue and subscribe to the mailing list.

In order to connect to a MS SQL server, I am attempting to install FreeTDS 1.2.5 on HPUX (HP-UX m9u0018c B.11.31 U ia64 3377098838 unlimited-user license). I have already installed unixODBC 2.3.9 in /usr/local/unixODBC (without the QT GUI manager, which I cannot get to compile and install). Everything seems ready to go, but I keep encountering the same issue that a previous user reported to the list back in May (https://lists.ibiblio.org/pipermail/freetds/2020q2/030511.html).

gcc --version:
gcc (GCC) 4.2.3

To start, I used
./configure --prefix=/usr/local

And the configure stage seemed to go ok. But when trying to make, we get:

**# make
No suffix list.
Making all in include
No suffix list.
        make  all-recursive
No suffix list.
Making all in freetds
No suffix list.
        make  all-am
No suffix list.
No suffix list.
Making all in src
No suffix list.
Making all in utils
Making all in .
  CC       md4.lo
In file included from md4.c:42:
../../include/tds_sysdep_public.h:62: error: conflicting types for 'intptr_t'
/usr/include/sys/_inttypes.h:114: error: previous declaration of 'intptr_t' was here
../../include/tds_sysdep_public.h:63: error: conflicting types for 'uintptr_t'
/usr/include/sys/_inttypes.h:115: error: previous declaration of 'uintptr_t' was here
md4.c: In function 'byteReverse':
md4.c:56: warning: implicit declaration of function '__builtin_bswap32'
*** Error exit code 1

Stop.**

After the configure stage, I had already taken the advice in the afore-mentioned thread and changed line 31 of tds_sysdep_public.h from
**#elif defined(__sun) && defined(__SVR4)**
to 
**#elif defined(__sun) && defined(__SVR4) || defined (__HP_cc)**

But still got the same error. 

I have been slogging at trying to fix this for some time, and I would sincerely appreciate any and all assistance. I have attached in a zip file the most recent files detailing my last compile attempt. I included these 6 hopefully relevant files:
config.log
config.status
make log (using make -d)
make log (using simply make)
the _inttypes.h file from the system
the tds_sysdep_public.h created by configure (and with the above addition of ' || defined (__HP_cc)')

Sincere thanks ahead of time for any and all tips, tricks and assistance.

Robert Moore
_Just trying to fix this 'n get back to my Perl hackin'_

[Make_stuff.zip](https://github.com/FreeTDS/freetds/files/5450078/Make_stuff.zip)

**Comment by freddy77** [comment]
Hi, I would try to change `#elif defined(__sun) && defined(__SVR4)` to `#elif 1` to force the inclusion of `inttypes.h`. Or even trying to include `stdint.h`.

For `__builtin_bswap32` I looked at documentation and it was introduced by GCC 4.3, so your GCC 4.2.1 does not have it (I'll update to check the proper version.

**Comment by freddy77** [comment]
It should be safe and correct to change `#elif defined(__sun) && defined(__SVR4)` to `#elif (defined(__sun) && defined(__SVR4)) || defined(__hpux)`

**Comment by freddy77** [comment]
`__builtin_bswap32` should now be fine with FreeTDS 1.2.10, please try the above change for `inttypes.h` change

**Comment by fziglio** [comment]
@LtCdr-FUDGE, did you test the change?

**Comment by freddy77** [comment]
Should be fixed
