### ISSUE TITLE
Slow data transfer with isql but no tsql

### ISSUE THREAD

**Issue by mtellezj** [FreeTDS/freetds#369]
Hi, I'm connecting to a Sybase server with `freetds` and `pyodbc`. The connection works fine and I can make queries, the only problem is that fetching several rows is too slow (with `python` or `isql`). It seems like it fetch 50-100 rows, then pause for 2-3 seconds, then another 50 or 100 rows, wait for 3 seconds and so on. I need to transfer 850,000 rows and it took 4 hours to complete. Funny thing, if I transfer the data with `tsql` the transfer took 5 minutes top. I also made a test with DBeaver client (java, no freetds) and the transfer speed is similar to `tsql`. My config is:
**freetds.conf**
```
[global]
	tds version = auto
	text size = 64512
[tlog]
	host = 192.168.1.11
	port = 2650
	tds version = 5.0 # I already try setting this to 7.0
```
---
**odbc.ini**
```
[tlog]
Driver = /usr/lib/x86_64-linux-gnu/odbc/libtdsodbc.so
Setup = /usr/lib/x86_64-linux-gnu/odbc/libtdsS.so
Server = 192.168.1.11
Port = 2650
Username = promoxxxxx
Password = xxxxxxxxx
```
---
**odbcinst.ini**
```
[FreeTDS]
Description=TDS driver (Sybase/MS SQL)
Driver=libtdsodbc.so
Setup=libtdsS.so
CPTimeout=
CPReuse=
UsageCount=1
```
Any help? Thanks in advance.

**Comment by freddy77** [comment]
Il giorno gio 19 nov 2020 alle ore 00:49 Mauricio Téllez <
notifications@github.com> ha scritto:

> Hi, I'm connecting to a Sybase server with freetds and pyodbc. The
> connection works fine and I can make queries, the only problem is that
> fetching several rows is too slow (with python or isql). It seems like it
> fetch 50-100 rows, then pause for 2-3 seconds, then another 50 or 100 rows,
> wait for 3 seconds and so on. I need to transfer 850,000 rows and it took 4
> hours to complete. Funny thing, if I transfer the data with tsql the
> transfer took 5 minutes top. I also made a test with DBeaver client (java,
> no freetds) and the transfer speed is similar to tsql. My config is:
> *freetds.conf*
>
> [global]
> 	tds version = auto
> 	text size = 64512
> [tlog]
> 	host = 192.168.1.11
> 	port = 2650
> 	tds version = 5.0 # I already try setting this to 7.0
>
> ------------------------------
>
> *odbc.ini*
>
> [tlog]
> Driver = /usr/lib/x86_64-linux-gnu/odbc/libtdsodbc.so
> Setup = /usr/lib/x86_64-linux-gnu/odbc/libtdsS.so
> Server = 192.168.1.11
> Port = 2650
> Username = promoxxxxx
> Password = xxxxxxxxx
>
> ------------------------------
>
> *odbcinst.ini*
>
> [FreeTDS]
> Description=TDS driver (Sybase/MS SQL)
> Driver=libtdsodbc.so
> Setup=libtdsS.so
> CPTimeout=
> CPReuse=
> UsageCount=1
>
> Any help? Thanks in advance.
>
Hi,
  the first two things that come into my mind are logging and conversions.
I cannot see anything in your configuration that is suggesting some logging
is enabled. Did you set some environment for logging?
In odbc.ini you should set TDS_Version to 5.0, but this affects only
connection, not transfer speed (and default is fine so it's just paranoia).
I don't understand why you should have this pause behaviour. I would
personally try using strace (with -tt and -T options) and isql, maybe
limiting the rows to less.
Which FreeTDS version are you using?
Which Linux distro?

Frediano

>

**Comment by mtellezj** [comment]
Thanks for the reply. I don't set enviroment for logging, and test this with debian 10 (buster) and freedts `v1.2.dev.20200212`. I also  test it from a docker container (using official image `python:3.6`) and freetds `v1.00.104`.

**Comment by freddy77** [comment]
Do you have any update on this issue?

**Comment by freddy77** [comment]
Closing, no responses
