### ISSUE TITLE
socket handle leak when fails to connect remote sql server

### ISSUE THREAD

**Issue by chenkunyun** [FreeTDS/freetds#37]
I'm compiling ftds without the ENABLE_ODBC_MARS macro. 

When the network between the client and the sql server (version 2008) is ok, all goes well. But if I shutdown the sql server service purposely, sock handle leak happens. Here the command I used:
watch -n 1 ' lsof -p <PID> | wc -l'

Every time my program tries to reconnect the server, the opened handle count of the program keeps increasing by three.

Here's the root cause of the leak.
![qq 20151209141309](https://cloud.githubusercontent.com/assets/5404886/11678066/5f5631d2-9e7f-11e5-8087-eb7ca662a688.png)

When I reconnect the server, which will certainly fail, the tds variable is DEAD. But tds->conn isn't closed here!

So I fix it by adding an else branch right after the if, like this:
![fix](https://cloud.githubusercontent.com/assets/5404886/11678221/8507532e-9e80-11e5-95f0-3ecc3af4d766.png)

**Comment by freddy77** [comment]
Hi, which FreeTDS are you using?
Looks like your else is very similar to the if branch.
Are you calling tds_free_socket? You should have only one file descriptor leak if your suppositions are true.

**Comment by chenkunyun** [comment]
Hi, we are using the tar file downloaded from ftp://ftp.freetds.org/pub/freetds/stable/freetds-0.95.18.tar.gz
I'll try git clone the master branch, and tell you the result

**Comment by chenkunyun** [comment]
sorry, man, my bad!
The master branch has fixed this bug in https://github.com/FreeTDS/freetds/commit/f498dcfd5074cf1cce9ef4302c7bfe4f948eb03d

**Comment by freddy77** [comment]
Backported fix to 0.95. Version is 0.95.75.
