### ISSUE TITLE
FreeBCP Query Limited to 92 chars

### ISSUE THREAD

**Issue by s-galante** [FreeTDS/freetds#370]
Is there a way to query a db without the 92 char limit on the query parameter.  We get a tblname is too long error from this line of code on the source bcp.c:
`if (strlen(tblname) > 92 && !IS_TDS7_PLUS(dbproc->tds_socket->conn))`
https://github.com/FreeTDS/freetds/blob/61ea6be722da172f43bb75732fbd2f073cab3833/src/dblib/bcp.c#L185

Is there another way to query with a file or make use of a longer query without a view or sp on the database side?

**Comment by s-galante** [comment]
*Please add to FreeTDS Mailing List if that is the better place to resolve this issue

**Comment by esoxy8** [comment]
This clarify, this limits the usefulness of the freebcp queryout functionality as any semi-long query fails with error 20239.

the following command with a short query will work: 
- freebcp "SELECT FIELD1, FIELD2 FROM [db].[owner].[table]" queryout test.del -S hostname:port -U *** -P *** -c

But as the query gets more specific, and surpasses 92 characters it will fail:
- freebcp "SELECT FIELD1, FIELD2, FIELD3, FIELD4, FIELD5, ...  FROM [db].[owner].[table]" queryout test.del -S hostname:port -U *** -P *** -c

**Comment by freddy77** [comment]
Yes, I think that if direction is DB_QUERYOUT this check should be ignored.

Frediano


Il giorno ven 20 nov 2020 alle ore 14:35 Ethan <notifications@github.com>
ha scritto:

**Comment by freddy77** [comment]
Fixed, both master and 1.2. Expect a new 1.2.12 version in some hours
