### ISSUE TITLE
Segmentation fault MSSQL

### ISSUE THREAD

**Issue by AleksandrovScloud** [FreeTDS/freetds#372]
Hi, I'm connecting to a MSSQL 2008 R2 server with freetds (1.1.6) and syslog-ng (3.29.1). 
Application "syslog-ng" crashes periodically - : mem.c:1202: tds_free_connection: Assertion `conn->in_net_tds == NULL' failed.

Is this related to MARS? Is it possible to work around the problem?

**Comment by freddy77** [comment]
Do you have some core or stack information? With these limited information is pretty impossible to understand what is going wrong. Which library is being used (dblib, ctlib, odbc) ?
More than a workaround I would fix it.

**Comment by AleksandrovScloud** [comment]
@freddy77, Syslog-ng uses libdbi to access databases. 
Dump generation is disabled (production environment). Enable dump generation?

**Comment by freddy77** [comment]
Dumps are usually pretty heavy. In this case I would use core files, they take resources (time to produce and disk space) only if a crash happens. I don't know your environment but I would avoid using `core_uses_pid` (`/proc/sys/kernel`) if you are using Linux so the core will be overridden. Depending on the system how to enable core on your environment differs. For instance you have to make sure `ulimit` is not set to not produce cores. Having the core dump and the executable is usually enough to get a reasonable stack trace.

**Comment by freddy77** [comment]
No reply for more than a year, closing
