### ISSUE TITLE
Connection pooling always calls SET ANSI_DEFAULTS OFF

### ISSUE THREAD

**Issue by Snowknight26** [FreeTDS/freetds#377]
I have an environment set up where I'm trying to transition from using non-pooled connections (FreeTDS connecting directly to the database server) to using pooled connections (FreeTDS connecting to the pool, which connects to the database server). With that in mind, I'm trying to implement a fallback in an application such that, if the pool is unreachable, the application should gracefully failover to the non-pooled connection.

During all this I discovered that, for reasons I can't understand, the pool connections seem to always send a `SET ANSI_DEFAULTS OFF SET CONCAT_NULL_YIELDS_NULL OFF` query after the login ack process.

https://github.com/FreeTDS/freetds/blob/acab2657d86a969ff426795cc8f4883181df84a9/src/pool/user.c#L374

Non-pooled connections, however, don't send the same query.

As a concrete example:
pool.conf contains the following relevant snippets:
```ini
[pool]
database = northwinds
server = contoso
```

freetds.conf contains the following relevant snippets:
```ini
[contoso]
host = db-server.internaldomain.ext
tds version = 7.3
text size = 300000

[pool]
host = 127.0.0.1
tds version = 7.3
text size = 300000
```

Regardless of what host I put into the DSN, be it `dblib:dbname=northwinds;host=contoso` or `dblib:dbname=northwinds;host=pool`, both eventually connect to the same Microsoft SQL Server instance.

Now the fun part begins. When doing an SQL server XEvent trace, the Audit Login event shows the pool connecting with the following options:
```tsql
-- network protocol: TCP/IP
set quoted_identifier on
set arithabort off
set numeric_roundabort off
set ansi_warnings on
set ansi_padding on
set ansi_nulls on
set concat_null_yields_null on
set cursor_close_on_commit off
set implicit_transactions off
set language us_english
set dateformat mdy
set datefirst 7
set transaction isolation level read committed
```

Then, the pool sends the following 4 queries, presumably the first one from the 'pool' config, 2nd because of the fODBC flag is not set in the login packet (see the line in user.c I quoted), 3rd because of the 'contoso' config, 4th I think from dblib.c:
```tsql
set textsize 300000
````
```tsql
SET ANSI_DEFAULTS OFF SET CONCAT_NULL_YIELDS_NULL OFF
````
```tsql
set textsize 300000
````
```tsql
set textsize 2147483647 set quoted_identifier on
````

When doing an SQL server XEvent trace, the Audit Login event shows the non-pooled connection connecting with the following options:
```tsql
-- network protocol: TCP/IP
set quoted_identifier off
set arithabort off
set numeric_roundabort off
set ansi_warnings off
set ansi_padding off
set ansi_nulls off
set concat_null_yields_null off
set cursor_close_on_commit off
set implicit_transactions off
set language us_english
set dateformat mdy
set datefirst 7
set transaction isolation level read committed
```

Then, the non-pooled connection sends the following 2 queries, presumably the first one from the 'contoso' config and the 2nd from dblib.c:
```tsql
set textsize 300000
````

```tsql
set textsize 2147483647 set quoted_identifier on
````

As you can see, even though the pool is configured to use the same TDS version, it sends an extra `SET ANSI_DEFAULTS OFF SET CONCAT_NULL_YIELDS_NULL OFF` query whereas the non-pooled connection doesn't.

Only after the FreeTDS queries have run (4 in the case of the pool, 2 in the case of non-pooled connections) can the application that is using FreeTDS send queries, but by then it's too late. It's no longer possible to have the pooled connections use the same user options as the non-pooled connections due to `SET ANSI_DEFAULTS OFF`.

Even when sending the appropriate SET queries to try to make them match and confirming that both pooled and non-pooled connections have the same user options (via `DBCC USEROPTIONS` or `SELECT @@OPTIONS`), the two behave differently, causing compatibility issues (such as stored procedures erroring because of different SET options) when trying to gracefully handle the application using either type of connection.

The problem with `SET ANSI_DEFAULTS OFF` is it's a server-level setting, whereas other SET queries are session-level.

With all that said
* what is the reason for the extra `SET ANSI_DEFAULTS OFF SET CONCAT_NULL_YIELDS_NULL OFF` query in [user.c](https://github.com/FreeTDS/freetds/blob/acab2657d86a969ff426795cc8f4883181df84a9/src/pool/user.c#L374)?
* is there any way to avoid it aside compiling FreeTDS myself?

I can provide dump logs if necessary, though another "bug" I've found is that there is no call to `tdsdump_log` in `pool_user_send_login_ack` so you won't see that pool-specific SET query in the logs.

If it matters, I'm using v1.1.24 due to it being the latest official version in RHEL's repos.

```
Compile-time settings (established with the "configure" script)
                            Version: freetds v1.1.24
             freetds.conf directory: /usr/local/etc
     MS db-lib source compatibility: yes
        Sybase binary compatibility: no
                      Thread safety: yes
                      iconv library: yes
                        TDS version: auto
                              iODBC: no
                           unixodbc: no
              SSPI "trusted" logins: no
                           Kerberos: no
                            OpenSSL: yes
                             GnuTLS: no
                               MARS: yes

```

**Comment by fziglio** [comment]
Well, there's a flag during connection which tell to use "odbc mode". The pool server works retaining old connection, resetting them and reusing them. Note that the not-odbc mode is used only by dblib which has been deprecated by Microsoft years ago. The difference are mainly the settings you spotted. So the pool server always connect to server setting the odbc flag but change the setting for dblib connection. That's the behaviour you are seeing.

The `set quoted_identifier on` query does not come from either dblib or pool server so probably it comes from upper layer.

**Comment by Snowknight26** [comment]
I'll admit I'm not too familiar with how the pool works but here's the problem from my perspective. When a user connects to the pool, ODBC mode is off.
https://github.com/FreeTDS/freetds/blob/da386827727ad90c81b795be5cf8f92489cda494/src/pool/user.c#L362  

As a result, two extra SETs are executed.
https://github.com/FreeTDS/freetds/blob/da386827727ad90c81b795be5cf8f92489cda494/src/pool/user.c#L374  


When not using the pool, ODBC mode is off (ODBC flag is set to off in OptionFlags2 in the LOGIN7 stream).
https://github.com/FreeTDS/freetds/blob/9b2bc4a7373ebe786eea61484d6f5cf48be95b02/src/dblib/dblib.c#L1248  
However, no extra SETs are executed.  

As far as QUOTED_IDENTIFIER, it actually does come from dblib:
https://github.com/FreeTDS/freetds/blob/9b2bc4a7373ebe786eea61484d6f5cf48be95b02/src/dblib/dblib.c#L4500

Regardless, because the pool uses different user options than dblib, it's not possible to match the behavior of an application connecting directly to the SQL server (using dblib) versus the connecting to the pool.

**Comment by freddy77** [comment]
@Snowknight26 I think the current behaviour it's the right one

**Comment by freddy77** [comment]
Closing, see previous comment.
