### ISSUE TITLE
tdsodbc_static.lib not installed

### ISSUE THREAD

**Issue by stef-pellegrino** [FreeTDS/freetds#382]
With cmake, windows 10, vc16, x64, last version of freetds :
After **nmake install**, tdsodbc_static.lib is not installed

**Comment by fziglio** [comment]
Well.. why do you want it installed ?

**Comment by stef-pellegrino** [comment]
I need to include it statically in my .dll for easy deployment

**Comment by fziglio** [comment]
I'm not really eager to to that change, is not recommended ODBC practice. As you already have a .dll you probably have also an installer or an executable too so I don't see the problem of adding an additional .dll. Also a manual copy file or edit of the project don't take that much. The purpose of tdsodbc_static is to support some tests needing it.

**Comment by stef-pellegrino** [comment]
Ok, your call. Thanks

**Comment by fziglio** [comment]
Sorry if it seems harsh but usually there is the assumption that installed libraries will keep ABI, we had to wait quite some years (6/7 if I remember) for Debian to pick up a new version due to ABI breakage.
