### ISSUE TITLE
declaration of DBRPCNORETURN in sybdb.h ?

### ISSUE THREAD

**Issue by blieusong** [FreeTDS/freetds#386]
`dbrpcparam`'s `status` parameter has only two possible values:
- DBRPCRETURN
- 0

But the Sybase's `sybdh.h` has the following declarations:

    sybdb.h-111817-/*
    sybdb.h-111820-** These constants are used for RPC parameter status values.
    sybdb.h-111881-*/
    sybdb.h:111884:#define DBRPCNORETURN   ((BYTE)0)
    sybdb.h-111918-#define DBRPCRETURN     ((BYTE)1)
    sybdb.h-111952-#define DB__NODEFAULT   ((BYTE)2)

What would be wrong with adding DBRPCNORETURN to `sybdb.h`? I can create a PR.

Thanks.

**Comment by fziglio** [comment]
It makes sense. I would merge this small change, I doubt can create issues.

**Comment by blieusong** [comment]
I have pushed the change to my own branch, but this has added it to my other PR (I'm relatively new to Github).

I don't think my other changes can break anything. It's been tested at work on both Sybase at SQL Server. And defncopy doesn't work anyways on Sybase at the moment. So maybe it's safe to merge my whole set of changes?

**Comment by freddy77** [comment]
I'm testing the commit with definition. I'll merge it separately. About the PR question you can update the PR with a git push (not unlikely having to use the force flag) on the branch. All commits added/removed will be added/removed from the PR so they should be related to the PR.
