### ISSUE TITLE
Change in what is considered a row set between v0.91 and v1.00.104

### ISSUE THREAD

**Issue by mikeyjk** [FreeTDS/freetds#389]
Hi there!
I'm going to apologise in advance as I'm not well versed in this area whatsoever.

I have a web application written in PHP that uses FreeTDS to talk to MSSQL.
We've noticed that when jumping from 0.91 to 1.00.104, /more/ statements result in a rowset than before.

To demonstrate we wrote a small test script:

```
<?php

$conn = new \PDO('dblib:host=host;dbname=dbname', 'user', 'pass');

$stmts = [
    // All 6 of these return a row set in freetds v1.00.104
    // Only 2 of these return a row set in freetds v0.91
    'CREATE TABLE #Test ( Id int not null );', // Row set for v0.91
    'INSERT INTO #Test SELECT 1;', // Row set for v1.00.104
    'DECLARE @maxid int = (SELECT MAX(Id) FROM #Test);', // Row set for v1.00.104
    'SELECT @maxid = 1 + ABS((CHECKSUM(NEWID())));', // Row set for v1.00.104
    'SELECT id FROM #Test;', // Row set for v0.91
    'DROP TABLE #Test;' // Row set for v1.00.104
];

$query = implode('', $stmts);

print(shell_exec('tsql -C | grep Version')) . "\n";

$rowsetCount = 0;
$valueCount = 0;
$i = 1;
$stmt = $conn->query($query);

do {
    $fetchedRow = $stmt->fetch(PDO::FETCH_ASSOC);
    if ($fetchedRow !== false) {
        $valueCount++;
        foreach ($fetchedRow as $colName => $colValue) {
            print "Row set has contents (#$i): '$colName' -> '$colValue'\n";
        }
    } else {
        print "Row set has no contents (#$i)\n";
    }
    $i++;
    $rowsetCount++;
} while($stmt->nextRowset());

print "\nTotal row sets retrieved: $rowsetCount\n";
print "Total values retrieved: $valueCount\n\n";
```

When running in containers with different versions of FreeTDS, we get these results:

```
Version: freetds v0.91
Row set has no contents (#1)
Row set has contents (#2): 'id' -> '1'
Total rowsets retrieved: 2
Total values retrieved: 1

Version: freetds v1.00.104
Row set has no contents (#1)
Row set has no contents (#2)
Row set has no contents (#3)
Row set has no contents (#4)
Row set has contents (#5): 'id' -> '1'
Row set has no contents (#6)
Total row sets retrieved: 6
Total values retrieved: 1
```

I've tried googling, looking through the FreeTDS changelog, StackOverflow posts, PHP bug tracker, etc, without any luck.
But of course I probably don't know exactly what I'm looking for under the hood.

My question is:
1) Is this change of behaviour intentional?
2) Is there any config that governs this?

I'm beginning to suspect we will just have to re-write our code, it's just unfortunate as we have locations where the amount of row sets was being assumed and failing when we upgrade FreeTDS > 0.91

Any insight or pointers in the right direction would be really appreciated.

Thanks for your time

**Comment by freddy77** [comment]
Il giorno ven 12 mar 2021 alle ore 06:29 Michael James Kiernan <
***@***.***> ha scritto:

> Hi there!
> I'm going to apologise in advance as I'm not well versed in this area
> whatsoever.
>
> I have a web application written in PHP that uses FreeTDS to talk to MSSQL.
> We've noticed that when jumping from 0.91 to 1.00.104, /more/ statements
> result in a rowset than before.
>
> To demonstrate we wrote a small test script:
>
> <?php
>
> $conn = new \PDO('dblib:host=host;dbname=dbname', 'user', 'pass');
>
> $stmts = [
>     // All 6 of these return a row set in freetds v1.00.104
>     // Only 2 of these return a row set in freetds v0.91
>     'CREATE TABLE #Test ( Id int not null );', // Row set for v0.91
>     'INSERT INTO #Test SELECT 1;', // Row set for v1.00.104
>     'DECLARE @maxid int = (SELECT MAX(Id) FROM #Test);', // Row set for v1.00.104
>     'SELECT @maxid = 1 + ABS((CHECKSUM(NEWID())));', // Row set for v1.00.104
>     'SELECT id FROM #Test;', // Row set for v0.91
>     'DROP TABLE #Test;' // Row set for v1.00.104
> ];
>
> $query = implode('', $stmts);
>
> print(shell_exec('tsql -C | grep Version')) . "\n";
>
> $rowsetCount = 0;
> $valueCount = 0;
> $i = 1;
> $stmt = $conn->query($query);
>
> do {
>     $fetchedRow = $stmt->fetch(PDO::FETCH_ASSOC);
>     if ($fetchedRow !== false) {
>         $valueCount++;
>         foreach ($fetchedRow as $colName => $colValue) {
>             print "Row set has contents (#$i): '$colName' -> '$colValue'\n";
>         }
>     } else {
>         print "Row set has no contents (#$i)\n";
>     }
>     $i++;
>     $rowsetCount++;
> } while($stmt->nextRowset());
>
> print "\nTotal row sets retrieved: $rowsetCount\n";
> print "Total values retrieved: $valueCount\n\n";
>
> When running in containers with different versions of FreeTDS, we get
> these results:
>
> Version: freetds v0.91
> Row set has no contents (#1)
> Row set has contents (#2): 'id' -> '1'
> Total rowsets retrieved: 2
> Total values retrieved: 1
>
> Version: freetds v1.00.104
> Row set has no contents (#1)
> Row set has no contents (#2)
> Row set has no contents (#3)
> Row set has no contents (#4)
> Row set has contents (#5): 'id' -> '1'
> Row set has no contents (#6)
> Total row sets retrieved: 6
> Total values retrieved: 1
>
> I've tried googling, looking through the FreeTDS changelog, StackOverflow
> posts, PHP bug tracker, etc, without any luck.
> But of course I probably don't want exactly what I'm looking for under the
> hood.
>
> My question is:
> Is this change of behaviour intentional? Is there any config that governs
> this?
>
> I'm beginning to suspect we will just have to re-write our code, it's just
> unfortunate as we have locations where the amount of row sets was being
> assumed and failing when we upgrade FreeTDS > 0.91
>
> Any insight or pointers in the right direction would be really appreciated.
>
> Thanks for your time
>

Hi,
  0.91 was released almost 10 years ago.
I don't really remember all changes but this subject (basically empty
results) had different changes.
First of all it's possible that new versions are using different protocol
versions which could affect the results.
Please check it, you could force 1.00.14 to use an old protocol to match
0.91 if it's the case.
I suppose you are using the same PHP+PDO version, right?
Another reason is compatibility. Some changes were done in the past to
align our libraries with proprietary ones, sometimes introducing changes
like these.
A change that could have caused this is prepared/not prepared statement.
The 2 produce slightly different results which could affect empty result
sets. Specifically I think this was changed to follow proprietary libraries.
You can try adding a "SET NOCOUNT ON" option to see if some result sets
disappear.

Regards,
  Frediano

**Comment by MiRacLe-RPZ** [comment]
```
        $options = [ /* */ ];
        if (version_compare(PHP_VERSION, '7.3.0') >= 0) {
            $options[PDO::DBLIB_ATTR_SKIP_EMPTY_ROWSETS] = true;
        }
       $conn = new \PDO('dblib:host=host;dbname=dbname', 'user', 'pass', $options);
 // 
```

see https://github.com/php/php-src/pull/1758

**Comment by MiRacLe-RPZ** [comment]
> I don't really remember all changes but this subject (basically empty results) had different changes

https://github.com/FreeTDS/freetds/commit/fc820490336c50d5c175d2a15327383256add4c9

**Comment by mikeyjk** [comment]
We haven't had time to properly address this, we will be trying to upgrade FreeTDS / re-writing our code not to rely on the historical rowset behaviour - if we are able to find anything interesting I might reach out.
Thanks for your eyes/feedback, I appreciate it.
