### ISSUE TITLE
Please add me to the freetds mailing list

### ISSUE THREAD

**Issue by mpeppler** [FreeTDS/freetds#391]
Building DBD::Sybase on MacOS with freetds and Sybase, and am having issues with cs_convert() for numeric values.

Thanks.

**Comment by fziglio** [comment]
Sure, but I need a valid e-mail address to add. You can send directly to me

**Comment by mpeppler** [comment]
Hi Freddy,

You can use ***@***.*** ***@***.***>

Thanks.

**Comment by freddy77** [comment]
done
