### ISSUE TITLE
Select unsigned smallint fails with unknown datatype for ASE 15.x

### ISSUE THREAD

**Issue by mpeppler** [FreeTDS/freetds#393]
In DBD::Sybase there is a test that does:

select convert(unsigned smallint, power(2, 15)), convert(bigint, power(convert(bigint, 2), 32))

This fails with FreeTDS in the ct_describe() call for column one, due to Sybase returning datatype 68, which is not mapped.
The tdsdump log shows:

ct.c:1196:ct_results(0x7f90d6f10d50, 0x7ffeea53aab0)
token.c:554:tds_process_tokens(0x7f90d6f0efe0, 0x7ffeea53a9fc, 0x7ffeea53a9f8, 0x6914)
util.c:179:Changed query state from PENDING to READING
packet.c:410:Received packet
0000 04 01 00 4a 00 00 00 00-61 22 00 00 00 02 00 00 |...J.... a"......|
0010 00 00 00 00 30 00 00 00-2c 00 00 00 44 02 00 00 |....0... ,...D...|
0020 00 00 00 00 30 00 00 00-2b 00 00 00 26 08 00 ae |....0... +...&..<AE>|
0030 02 00 00 00 d1 02 00 80-08 00 00 00 00 01 00 00 |....<D1>... ........|
0040 00 fd 10 00 02 00 01 00-00 00                   |.<FD>...... ..|

token.c:569:processing result tokens.  marker is  61(ROWFMT2)
token.c:1786:tds5_process_result2
mem.c:656:tds_free_all_results()
token.c:1810:num_cols=2
token.c:1876:col 0:
token.c:1877:   column_name=[]
token.c:1883:   flags=30 utype=44 type=68 server type 68 varint=1
token.c:1887:   colsize=2 prec=0 scale=0
token.c:1876:col 1:
token.c:1877:   column_name=[]
token.c:1883:   flags=30 utype=43 type=38 server type 38 varint=1
token.c:1887:   colsize=8 prec=0 scale=0
util.c:179:Changed query state from READING to PENDING
ct.c:1260:ct_results() process_result_tokens returned 0 (type 4049) 
token.c:554:tds_process_tokens(0x7f90d6f0efe0, 0x7ffeea53a9fc, 0x7ffeea53a9f8, 0x6a14)
util.c:179:Changed query state from PENDING to READING
token.c:569:processing result tokens.  marker is  ae(CONTROL/FEATUREEXTACK)
token.c:130:tds_process_default_tokens() marker is ae(CONTROL/FEATUREEXTACK)
token.c:249:Eating CONTROL/FEATUREEXTACK token
token.c:569:processing result tokens.  marker is  d1(ROW)
token.c:675:tds_process_tokens::SET_RETURN stopping on current token
util.c:179:Changed query state from READING to PENDING
ct.c:1260:ct_results() process_result_tokens returned 0 (type 4040) 
ct.c:2501:ct_res_info(0x7f90d6f10d50, 803, 0x7ffeea53aabc, -99999, 0x0)
ct.c:2520:ct_res_info(): Number of columns is 2
ct.c:2439:ct_describe(0x7f90d6f10d50, 1, 0x7f90d6f11a30)
ct.c:1987:_ct_get_client_type(type 68, user 44, size 2)

The weird thing is that 68 is NOT defined in the Sybase cstypes.h, so I don't really know why this is returned.

**Comment by freddy77** [comment]
Il giorno ven 9 apr 2021 alle ore 13:07 Michael Peppler <
***@***.***> ha scritto:

> In DBD::Sybase there is a test that does:
>
> select convert(unsigned smallint, power(2, 15)), convert(bigint,
> power(convert(bigint, 2), 32))
>
> This fails with FreeTDS in the ct_describe() call for column one, due to
> Sybase returning datatype 68, which is not mapped.
> The tdsdump log shows:
>
> ct.c:1196:ct_results(0x7f90d6f10d50, 0x7ffeea53aab0)
> token.c:554:tds_process_tokens(0x7f90d6f0efe0, 0x7ffeea53a9fc,
> 0x7ffeea53a9f8, 0x6914)
> util.c:179:Changed query state from PENDING to READING
> packet.c:410:Received packet
> 0000 04 01 00 4a 00 00 00 00-61 22 00 00 00 02 00 00 |...J.... a"......|
> 0010 00 00 00 00 30 00 00 00-2c 00 00 00 44 02 00 00 |....0... ,...D...|
> 0020 00 00 00 00 30 00 00 00-2b 00 00 00 26 08 00 ae |....0... +...&..|
> 0030 02 00 00 00 d1 02 00 80-08 00 00 00 00 01 00 00 |....... ........|
> 0040 00 fd 10 00 02 00 01 00-00 00 |....... ..|
>
> token.c:569:processing result tokens. marker is 61(ROWFMT2)
> token.c:1786:tds5_process_result2
> mem.c:656:tds_free_all_results()
> token.c:1810:num_cols=2
> token.c:1876:col 0:
> token.c:1877: column_name=[]
> token.c:1883: flags=30 utype=44 type=68 server type 68 varint=1
> token.c:1887: colsize=2 prec=0 scale=0
> token.c:1876:col 1:
> token.c:1877: column_name=[]
> token.c:1883: flags=30 utype=43 type=38 server type 38 varint=1
> token.c:1887: colsize=8 prec=0 scale=0
> util.c:179:Changed query state from READING to PENDING
> ct.c:1260:ct_results() process_result_tokens returned 0 (type 4049)
> token.c:554:tds_process_tokens(0x7f90d6f0efe0, 0x7ffeea53a9fc,
> 0x7ffeea53a9f8, 0x6a14)
> util.c:179:Changed query state from PENDING to READING
> token.c:569:processing result tokens. marker is ae(CONTROL/FEATUREEXTACK)
> token.c:130:tds_process_default_tokens() marker is
> ae(CONTROL/FEATUREEXTACK)
> token.c:249:Eating CONTROL/FEATUREEXTACK token
> token.c:569:processing result tokens. marker is d1(ROW)
> token.c:675:tds_process_tokens::SET_RETURN stopping on current token
> util.c:179:Changed query state from READING to PENDING
> ct.c:1260:ct_results() process_result_tokens returned 0 (type 4040)
> ct.c:2501:ct_res_info(0x7f90d6f10d50, 803, 0x7ffeea53aabc, -99999, 0x0)
> ct.c:2520:ct_res_info(): Number of columns is 2
> ct.c:2439:ct_describe(0x7f90d6f10d50, 1, 0x7f90d6f11a30)
> ct.c:1987:_ct_get_client_type(type 68, user 44, size 2)
>
> The weird thing is that 68 is NOT defined in the Sybase cstypes.h, so I
> don't really know why this is returned.
>
Hi,
  which version of FreeTDS are you using? I think 68 is SYBUINTN which is
not currently supported, apparently
by _ct_get_client_type.

Regards,

>   Frediano

**Comment by freddy77** [comment]
Il giorno ven 9 apr 2021 alle ore 20:32 Frediano Ziglio
***@***.***> ha scritto:
>
> Il giorno ven 9 apr 2021 alle ore 13:07 Michael Peppler ***@***.***> ha scritto:
>>
>> In DBD::Sybase there is a test that does:
>>
>> select convert(unsigned smallint, power(2, 15)), convert(bigint, power(convert(bigint, 2), 32))
>>
>> This fails with FreeTDS in the ct_describe() call for column one, due to Sybase returning datatype 68, which is not mapped.
>> The tdsdump log shows:
>>
>> ct.c:1196:ct_results(0x7f90d6f10d50, 0x7ffeea53aab0)
>> token.c:554:tds_process_tokens(0x7f90d6f0efe0, 0x7ffeea53a9fc, 0x7ffeea53a9f8, 0x6914)
>> util.c:179:Changed query state from PENDING to READING
>> packet.c:410:Received packet
>> 0000 04 01 00 4a 00 00 00 00-61 22 00 00 00 02 00 00 |...J.... a"......|
>> 0010 00 00 00 00 30 00 00 00-2c 00 00 00 44 02 00 00 |....0... ,...D...|
>> 0020 00 00 00 00 30 00 00 00-2b 00 00 00 26 08 00 ae |....0... +...&..|
>> 0030 02 00 00 00 d1 02 00 80-08 00 00 00 00 01 00 00 |....... ........|
>> 0040 00 fd 10 00 02 00 01 00-00 00 |....... ..|
>>
>> token.c:569:processing result tokens. marker is 61(ROWFMT2)
>> token.c:1786:tds5_process_result2
>> mem.c:656:tds_free_all_results()
>> token.c:1810:num_cols=2
>> token.c:1876:col 0:
>> token.c:1877: column_name=[]
>> token.c:1883: flags=30 utype=44 type=68 server type 68 varint=1
>> token.c:1887: colsize=2 prec=0 scale=0
>> token.c:1876:col 1:
>> token.c:1877: column_name=[]
>> token.c:1883: flags=30 utype=43 type=38 server type 38 varint=1
>> token.c:1887: colsize=8 prec=0 scale=0
>> util.c:179:Changed query state from READING to PENDING
>> ct.c:1260:ct_results() process_result_tokens returned 0 (type 4049)
>> token.c:554:tds_process_tokens(0x7f90d6f0efe0, 0x7ffeea53a9fc, 0x7ffeea53a9f8, 0x6a14)
>> util.c:179:Changed query state from PENDING to READING
>> token.c:569:processing result tokens. marker is ae(CONTROL/FEATUREEXTACK)
>> token.c:130:tds_process_default_tokens() marker is ae(CONTROL/FEATUREEXTACK)
>> token.c:249:Eating CONTROL/FEATUREEXTACK token
>> token.c:569:processing result tokens. marker is d1(ROW)
>> token.c:675:tds_process_tokens::SET_RETURN stopping on current token
>> util.c:179:Changed query state from READING to PENDING
>> ct.c:1260:ct_results() process_result_tokens returned 0 (type 4040)
>> ct.c:2501:ct_res_info(0x7f90d6f10d50, 803, 0x7ffeea53aabc, -99999, 0x0)
>> ct.c:2520:ct_res_info(): Number of columns is 2
>> ct.c:2439:ct_describe(0x7f90d6f10d50, 1, 0x7f90d6f11a30)
>> ct.c:1987:_ct_get_client_type(type 68, user 44, size 2)
>>
>> The weird thing is that 68 is NOT defined in the Sybase cstypes.h, so I don't really know why this is returned.
>
> Hi,
>   which version of FreeTDS are you using? I think 68 is SYBUINTN which is not currently supported, apparently
> by _ct_get_client_type.
>
> Regards,
>

Hi,
   1.2.19 version coming out. For some reasons the test I wrote to
test all types does not correctly set nullable types.

Regards,
  Frediano

**Comment by mpeppler** [comment]
I just did a pull, and I see the change in the code, which looks fine to me...

Thanks.
