### ISSUE TITLE
Missing version tags

### ISSUE THREAD

**Issue by kloczek** [FreeTDS/freetds#394]
Looks like there is no at all any git tags marking state of the code on exact released versiopns.
Is it possible to add at least last version tag by `git tag -a 1.1.42 775fbd784e37029249bc8947e93fd0709948744e`?

**Comment by freddy77** [comment]
Versions are in configure.ac.

**Comment by kloczek** [comment]
> Versions are in configure.ac.

Yes I'm talking about tahgiing git repo. Content of the configure.ac has nothing to do with what I'm pointing on. Git tags shoulk be matching with with version sued in files like configure.ac.
With git tags is possible to check what has changed since tag or between tags.

**Comment by freddy77** [comment]
Created for both 1.1 and 1.2

**Comment by kloczek** [comment]
Thank you :)
