### ISSUE TITLE
Question regarding software license

### ISSUE THREAD

**Issue by senolfeldmann** [FreeTDS/freetds#405]
The [website](https://www.freetds.org/faq.html) states, that FreeTDS is licensed under LGPL:
> LGPL was chosen because if you want a commercial client,

The repos README.md says:
> FreeTDS is licensed under the GNU LGPL license. See COPYING_LIB.txt for details.

Yet, the repos [licensing information](https://github.com/FreeTDS/freetds/blob/master/COPYING.txt) refers to the GPL.
This is confusing. What does the GPL license in COPYING.txt refer to?

**Comment by fziglio** [comment]
Code is licensed using either GPL or LGPL. All libraries are LGPL, tests and apps GPL. This allows reuse even in commercial software of both libraries and applications.

**Comment by senolfeldmann** [comment]
What exactly do you mean by "apps"? Would this mean that bsqldb.exe, datacopy.exe, defncopy.exe, freebcp.exe, tdspool.exe and tsql.exe are licensed under GPL?

**Comment by freddy77** [comment]
Sorry for late reply. Yes, apps are `bsqldb.exe`, etcetera.
No, libraries do not call .exe binaries. And even if they did GPL won't extend to them.
