### ISSUE TITLE
build fails when spaces are in build path

### ISSUE THREAD

**Issue by marsupilami79** [FreeTDS/freetds#413]
I tried to bild FreeTDS in a path where the name contains spaces. This fails at the following step:
> test -r /home/jan/freetds 1.3/freetds-1.3/doc/userguide.xml
> /bin/sh: 1: test: /home/jan/freetds: unexpected operator

It seems that the build path doesn't get quoted correctly. With #412 this seems to be fixed. This occurs in FreeTDS 1.3 as well as in master.

**Comment by fziglio** [comment]
Merged. Also backported to 1.3. A 1.3.1 version should be automatically be generated today.

**Comment by marsupilami79** [comment]
Thank you :)
