### ISSUE TITLE
bus errro(coredump) runing tsql command

### ISSUE THREAD

**Issue by bm2595** [FreeTDS/freetds#414]
built and installed freetds-1.3 on a SunOS  5.10 Generic_144500-19 sun4u sparc SUNW,Sun-Fire-V490.  when I run the tsql -C command works fine but when I try to run any other tsql command I get bus Error(coredump)
tsql -S zlty17544.vci.att.com -U sybtc2
Password:
locale is "/en_US.ISO8859-1/en_US.ISO8859-1/en_US.ISO8859-1/en_US.ISO8859-1/en_US.ISO8859-1/C"
locale charset is "ISO8859-1"
using default charset "ISO8859-1"
Bus Error(coredump)

built with gcc 3.4.3 version

**Comment by fziglio** [comment]
do you have a stack trace?

**Comment by bm2595** [comment]
pstack trace is 
core 'core' of 28725:   ./tsql -S T3_KC -U sybtc2
 00045884 get_utf16be (ffffffea, 8, ffbfd49c, 0, 4b57f, 66f3c) + 18
 0004601c tds_sys_iconv (4586c, ffbfd528, ffbfd524, ffbfd520, ffbfd51c, 4b57f) + 11c
 0003a4c0 tds_iconv_open (4b54f, 800, c00, 0, ffbfd540, 68240) + 338
 00024c78 tds_connect (ffffb1de, 68968, ffbfd884, 0, 0, 0) + 4ec
 00025b00 tds_connect_and_login (68460, 68968, 82b04, 654bc, 0, 671e0) + 10
 000171bc main     (1, ffbfde04, 4d340, 0, 0, 67e40) + 8e8
 00015d70 _start   (0, 0, 0, 0, 0, 0) + 5c
pmap of the core is
devtoss-a:pmap core
core 'core' of 28725:   ./tsql -S T3_KC -U sybtc2
00010000     280K r-x--  /home/bm2595/freetds/usr/local/bin/tsql
00064000      16K rwx--  /home/bm2595/freetds/usr/local/bin/tsql
00068000      40K rwx--    [ heap ]
FEF00000    1216K r-x--  /lib/libc.so.1
FF030000      40K rwx--  /lib/libc.so.1
FF03A000       8K rwx--  /lib/libc.so.1
FF060000      64K rwx--
FF080000     584K r-x--  /lib/libnsl.so.1
FF122000      40K rwx--  /lib/libnsl.so.1
FF12C000      24K rwx--  /lib/libnsl.so.1
FF150000      16K r-x--  /usr/lib/locale/en_US.ISO8859-1/en_US.ISO8859-1.so.3
FF162000      16K rwx--  /usr/lib/locale/en_US.ISO8859-1/en_US.ISO8859-1.so.3
FF170000       8K rwx--
FF180000    1112K r-x--  /usr/sfw/lib/libcrypto.so.0.9.7
FF2A0000       8K r-x--  /platform/sun4u-us3/lib/libc_psr.so.1
FF2A6000     104K rwx--  /usr/sfw/lib/libcrypto.so.0.9.7
FF2C0000       8K rwx--  /usr/sfw/lib/libcrypto.so.0.9.7
FF2D0000      24K rwx--
FF2E0000       8K r-x--  /lib/libdl.so.1
FF2F2000       8K rwx--  /lib/libdl.so.1
FF300000      48K r-x--  /lib/libsocket.so.1
FF310000      16K r-x--  /lib/libpthread.so.1
FF31C000       8K rwx--  /lib/libsocket.so.1
FF320000     216K r-x--  /usr/sfw/lib/libssl.so.0.9.7
FF360000       8K rwx--
FF366000      24K rwx--  /usr/sfw/lib/libssl.so.0.9.7
FF370000       8K rwx--
FF380000       8K rwx--
FF390000       8K rw---
FF3A0000       8K rw---
FF3B0000     232K r-x--  /lib/ld.so.1
FF3F0000       8K rwx--
FF3FA000      16K rwx--  /lib/ld.so.1
FFBFA000      24K rwx--    [ stack ]
 total      4256K

**Comment by bm2595** [comment]
more information abstracted using dbx on solaris
core file header read successfully
Reading ld.so.1
Reading libssl.so.0.9.7
Reading libcrypto.so.0.9.7
Reading libsocket.so.1
Reading libnsl.so.1
Reading libdl.so.1
Reading libpthread.so.1
Reading libc.so.1
Reading libc_psr.so.1
Reading en_US.ISO8859-1.so.3
t@1 (l@1) program terminated by signal BUS (invalid address alignment)
Current function is get_utf16be

**Comment by fziglio** [comment]
Found! Silly mistake. Expect a 1.3.2 version tomorrow. Change is this https://github.com/FreeTDS/freetds/commit/2007a98d4ba9b434aeab1b050e73e67ae7d4c243 (well, only `src/tds/iconv.c` change is needed).

**Comment by bm2595** [comment]
ok thanks
