### ISSUE TITLE
does FreeTDS work with Azure SQL datase Manage Instance

### ISSUE THREAD

**Issue by bm2595** [FreeTDS/freetds#415]
my question is does FreeTDS work with Azure SQL database Manage Instance.  I am running FreeTDS 1.3.2 (latest version )  and have gotten it working with Microsoft SQL Server Enterprise (64-bit) using FTDVER=70. but when I switch to Azure SQL database Manage Instance I can not get it to work. I keep getting 
devtoss-a:TDSVER=7.0 tsql -H csms-sql-managed-instance.d3d221ccb82a.database.windows.net  -p 1>
locale is "/en_US.ISO8859-1/en_US.ISO8859-1/en_US.ISO8859-1/en_US.ISO8859-1/en_US.ISO8859-1/C"
locale charset is "ISO8859-1"
using default charset "ISO8859-1"
**Error 20017 (severity 9):
        Unexpected EOF from the server
Error 20002 (severity 9):
        Adaptive Server connection failed**
There was a problem connecting to the server
and it does not matter what TDSVER I use.  is there way to get it working?

**Comment by freddy77** [comment]
Hi,
  federated authentication is not supported but Azure servers have been
reported to work perfectly.
7.0 version is the version used by SQL Server 7.0 released more than 20
years ago.
The default auto is perfectly file (actually I was testing it yesterday).

Regards,
  Frediano


Il giorno gio 26 ago 2021 alle ore 19:09 bm2595 ***@***.***>
ha scritto:

**Comment by bm2595** [comment]
thanks got it working

**Comment by docouto** [comment]
Hey @bm2595, tks for your post.
We are facing the same issue after bumping TDSVER to 7.4, before when it was 7.0 SQL MI was complaining about the minimum TLS version to connect to it.

Would you be able to share how you got it working?

Cheers
Denis Couto
