### ISSUE TITLE
Conflicting types for 'intptr_t' on a 32-bit system under C89

### ISSUE THREAD

**Issue by evanmiller** [FreeTDS/freetds#418]
As originally reported here:

https://trac.macports.org/ticket/63394

When compiling the project without C99 support, FreeTDS includes stdint.h via nettle, and then provides its own conflicting definitions in tds_sysdep_public.h.

It appears that FreeTDS wants intptr_t to be the exact size of a pointer, but on this 32-bit system (Mac OS X 10.4 / PowerPC) intptr_t is larger than a pointer (allowed by the spec), resulting in a conflict.

Compiling with -stdc=c99 fixes the issue. The complete configure output is available in the above link.

**Comment by fziglio** [comment]
Interesting. I just checked, intptr_t it's not used by public headers so removing from that header should be possible. Also using another type (like the old TDS_xINTPTR) would be possible. That would make sure to have a sizeof(TDS_xINTPTR) == sizeof(void*) and avoid the conflict.

**Comment by freddy77** [comment]
Should have been fixed.
