### ISSUE TITLE
Errors With `defncopy` On v0.95.latest 

### ISSUE THREAD

**Issue by metaskills** [FreeTDS/freetds#42]
I've never gotten the 0.95 `defncopy` binary to work where previously in 0.91 I have not had issues. My current setup is using SQL Server 2014 with a simple table. The error I keep seeing is:

```
Assertion failed: (ret >= 0), function print_ddl, file defncopy.c, line 511.
```

**Comment by freddy77** [comment]
Fixed in git (both 0.95 and master).
Expect a new snapshot tomorrow.
