### ISSUE TITLE
How to build for tds part only

### ISSUE THREAD

**Issue by naushadck** [FreeTDS/freetds#424]
How can i build for tds part only. Any step by step instructions for the same. 
I need to connect MSSQL using tds.   Is this possible. Or do i need to build for the whole bunch files... 

Thanks...

**Comment by fziglio** [comment]
If you mean `libTDS` only you could do some specific `cd XX && make` to save some time but maybe better to exclude some part with `configure`. Not clear why you want to use `libTDS` directly.

**Comment by naushadck** [comment]
Sorry, not clear (you could do some specific cd XX && make).  Can you elaborate on it. 
I like to build and use the TDS dll with my application. 
What is the step(s) to build and how to get list of functions that i can call from my application.

**Comment by freddy77** [comment]
Closing, already replied (if not please reopen).
