### ISSUE TITLE
PRELogin success but TLS with no reply.

### ISSUE THREAD

**Issue by naushadck** [FreeTDS/freetds#425]
Based on the  tds_ssl.html in doc folder tried to connect SQL 2012. Second step (TLS), failed.  Given below the steps executed.

1. Prelogin as specified in the doc  Status - Success. 
          Client to server
          -----------------
          12 01 00 34 00 00 00 00  00 00 15 00 06 01 00 1b
           00 01 02 00 1c 00 0c 03  00 28 00 04 ff 08 00 01 
           55 00 00 01 4d 53 53 51  4c 53 65 72 76 65 72 00 
           38 09 00 00  

          Server to client
          -----------------
          4 1 0 25 0 0 1 0 0 0 15 0 6 1 0 1B 0 1 2 0 1C 0 1 3 0 1D 0 0 FF C 0 17 88 0 0 0 0 0 0

2.  TLS as specified in the doc  Status - Failed

       12 01 00 46 00 00 00 00  16 03 01 00 39 01 00 00
       35 03 01 41 b9 5e 02 f8  7d 45 81 31 d9 73 9e 93
       91 b2 dd f4 4a 80 a3 92  a8 0f aa 67 32 8a 72 6d
       4b 22 07 00 00 0e 00 09  00 64 00 62 00 03 00 06 
       00 12 00 63 01 00        

What could be the reason. ... 

Thanks....

**Comment by fziglio** [comment]
I don't see any failure...

**Comment by naushadck** [comment]
OK. Thank you. 
1. For the MS SQL, the following part is correct.   ( TLS handshake wrapped in a TDS type 0x12 packet.)
     12 01 00 46 00 00 00 00 16 03 01 00 39 01 00 00 35 03 01   to be changed to as follows
      
     12 01 00 46 00 00 00 00 16 03 03 00 39 01 00 00 35 03 03

2. However, i am not sure what is the following bytes. 

      41 b9 5e 02 f8 7d 45 81 31 d9 73 9e 93
      91 b2 dd f4 4a 80 a3 92 a8 0f aa 67 32 8a 72 6d
      4b 22 07 00 00 0e 00 09 00 64 00 62 00 03 00 06
     00 12 00 63 01 00

Thanks .....

**Comment by fziglio** [comment]
> I have gone through the freeTDS documentation. But it not working as per that.
> 
> I have looked in to MSTDS documentation, it says "First PRELOGIN and then LOGIN7". This is also did not work.
> 

Well, the LOGIN7 is inside TLS in case TLS is used. Also the TLS is inside some PRELOGIN (0x12) packet.
So yes, it's confusing... but right.

> After lot of checking, found that after PRELOGIN, it is required to use TLS for the rest login process. FreeTDS says exactly the same in the tds_ssl.html. But the bits did not work for the TLS part. No details found on this.
> 

No, it's not required as documented inside MS TDS protocol. Depends on the PRELOGIN exchange.

> Can i make a dll using freeTDS ?. Will it work with windows ?. If so, where can i find the step by step instruction to build dll for windows...

Please read the user guide. The specific question is answered at https://www.freetds.org/userguide/osissues.html#Windows. CMake is used in Appveyor test.

**Comment by naushadck** [comment]
Thank you very much...  I appreciate that.  I will look in to it.  
Please share, if you have any other documentation on how to build freetds dll on windows.

**Comment by freddy77** [comment]
Hi, sorry for late reply. About compiling for Windows see https://www.freetds.org/userguide/osissues.html#Windows. Use CMake and enjoy. About Prelogin I would close this Issue, is not much related to FreeTDS project, more to the TDS protocol.
