### ISSUE TITLE
Build failure on macOS Monterey

### ISSUE THREAD

**Issue by yoKurt94** [FreeTDS/freetds#436]
After running the make command, the terminal returns: 

Undefined symbols for architecture x86_64:
  "_libiconv", referenced from:
      _tds_iconv_open in libtds.a(iconv.o)
      _tds_iconv in libtds.a(iconv.o)
  "_libiconv_close", referenced from:
      _tds_iconv_open in libtds.a(iconv.o)
      _tds_iconv_close in libtds.a(iconv.o)
      _tds_iconv_free in libtds.a(iconv.o)
      _tds_iconv in libtds.a(iconv.o)
      _tds_iconv_get_info in libtds.a(iconv.o)
      _tds_set_iconv_name in libtds.a(iconv.o)
  "_libiconv_open", referenced from:
      _tds_iconv_open in libtds.a(iconv.o)
      _tds_iconv_info_init in libtds.a(iconv.o)
      _tds_iconv in libtds.a(iconv.o)
      _tds_set_iconv_name in libtds.a(iconv.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [libct.la] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 

It also added warnings: 

ct.c:1955:10: warning: 20 enumeration values not handled in switch: 'SYBVOID', 'SYBINTERVAL', 'SYBUINTN'... [-Wswitch]
        switch (col->column_type) {
                ^
ct.c:1955:10: note: add missing switch cases
        switch (col->column_type) {
                ^

I tried to run it using the known [macOS specific fix ](http://www.freetds.org/userguide/osissues.html#osx). However, FreeTDS just won't compile.

**Comment by fziglio** [comment]
Can you post config.log file? configure should understand if and where these functions are in the system and use correct arguments to linker.

**Comment by yoKurt94** [comment]
Sure. I downloaded a fresh copy on [freetds.org](http://www.freetds.org/files/stable/) (freetds-1.3.tar.bz2) just in case. I ran ./configure without any optional arguments and then make. 

[config.log](https://github.com/FreeTDS/freetds/files/7710627/config.log)

**Comment by fziglio** [comment]
Weird. It seems that configure finds `iconv`, `iconv_open` and `iconv_close` in `libiconv` library (`-liconv`) however `iconv.o` is looking for `libiconv`, `libiconv_open` and `libiconv_close` functions instead, like something changed in the meantime and a different library is now required. The only flag that I found can change this is `-I/Users/yannik/opt/anaconda3/include`. Is there a `iconv.h` file in `/Users/yannik/opt/anaconda3/include`?

**Comment by fziglio** [comment]
It looks like the header in `/Users/yannik/opt/anaconda3/include` is from `libiconv` which redirect `iconvXXX` functions to `libiconvXXX` functions. I would try adding `--with-libiconv-prefix=/Users/yannik/opt/anaconda3` to `configure` command.

**Comment by yoKurt94** [comment]
Works. Brilliant!
