### ISSUE TITLE
No such sys root directory on Mac

### ISSUE THREAD

**Issue by yoKurt94** [FreeTDS/freetds#439]
I am trying to install FreeTDS for iOS using autotools. However, I get the following error:

```
    clang: warning: no such sysroot directory: '=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk' [-Wmissing-sysroot]
    ld: library not found for -lSystem
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

... but I can cd into that directory using copy and paste and the sdk is definitely there.

**Comment by fziglio** [comment]
Are you sure you have a `=/Applications` directory (not a `/Applications`) ?

**Comment by yoKurt94** [comment]
Thanks for pointing that out, but there is something strange going on. Even if I delete the "=" and all the whitespaces like in:

`export CFLAGS="-arch arm64 -miphoneos-version-min=11.0 -isysroot/Library/Developer/CommandLineTools/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk"`

it still returns the same error: 

```
clang: warning: no such sysroot directory: '/Library/Developer/CommandLineTools/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk' [-Wmissing-sysroot]
ld: library not found for -lSystem
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by yoKurt94** [comment]
Ok, I just realized that the system changed it's root directory in the message above. Thank you, this issue is fixed.

**Comment by fziglio** [comment]
How did you solve it?

**Comment by yoKurt94** [comment]
Just as you indicated, `isysroot` does not require an "=" when you set the path. That's all I needed to do. In my second comment, the path was automatically changed by Xcode after an update (compare my initial issue and my second comment: the path changed from /Applications/Xcode.app/ to /Library/Developer) and this directory did not exist.
