### ISSUE TITLE
Datetimeoffset(n) Hour Bug - v0.95 & v0.99

### ISSUE THREAD

**Issue by metaskills** [FreeTDS/freetds#44]
While testing both the Ruby C extensions for FreeTDS, I found a bug with the hour part of the `dbanydatecrack` in the following conditions. 

* Does not matter on scale. Been able to reproduce the bug in datetimeoffset(7), (2), etc.
* I have yet to trigger the bug when tzone is 0.
* Seems to be coupled to hour & tzone value relationship.

Headers below are DB values inserted. Blow I show different values from `dbanydatecrack` when reading said data.

#### 2010-12-31 15:00:00 -08:00

This value does not raise an error and hour appears fine.

`hour: 15, minute: 0, second: 0, nanosecond: 0, tzone: -480`

#### 2010-12-31 16:00:00 -08:00

Now that the the hour is changed to `16`, the hour comes back incorrectly.

`hour: 1432, minute: 0, second: 0, nanosecond: 0, tzone: -480`

From here I can keep playing with the zone in the DB increasing it and get in a win/loose tug of war. Any ideas where in the code I can look for this issue?

**Comment by freddy77** [comment]
Fixed by https://github.com/FreeTDS/freetds/commit/dafa450d33bf4374890ea2f5af2ab441f2d94a38
