### ISSUE TITLE
Error: 'system' is unavailable: not available on iOS

### ISSUE THREAD

**Issue by yoKurt94** [FreeTDS/freetds#440]
I am trying to compile freeTDS 1.3 for iOS but it won't compile. The terminal returns: 

```
fisql.c:335:15: error: 'system' is unavailable: not available on iOS
        switch (rv = system(cmd)) {
                     ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk/usr/include/stdlib.h:184:6: note: 'system' has been explicitly marked unavailable here
int      system(const char *) __DARWIN_ALIAS_C(system);
```

What is the problem here?

[config.log](https://github.com/FreeTDS/freetds/files/7740654/config.log)

**Comment by fziglio** [comment]
The problem is that `system` is not made available in iOS. The quickest workaround is to disable the entire apps (`--disable-apps` to configure).
Less quick you could disable `!!` command in `fisql` sources.
Proper fix would be to find an alternative to `system` in iOS.

**Comment by yoKurt94** [comment]
I disabled apps just to see what happens. The terminal error 
`fisql.c:335:15: error: 'system' is unavailable: not available on iOS
        switch (rv = system(cmd)) {`
disappeared, but my log file is still filled with errors, but why is that? To me it looks like there is a dependency missing or something, but I can't identify which one it is. The chain of errors starts in my config log in line 247 with: 

`conftest.c:54:10: fatal error: 'minix/config.h' file not found
#include <minix/config.h>
         ^~~~~~~~~~~~~~~~
1 error generated.`

[config.log](https://github.com/FreeTDS/freetds/files/7740858/config.log)

**Comment by fziglio** [comment]
That's normal to have a lot of errors in `config.log`. The purpose of configure is to check the system. For instance in the `minix/config.h` case the script is checking if `minix/config.h` header is present. As your system has no such file the script (and source files) won't try to use it.

**Comment by yoKurt94** [comment]
What exactly do you mean with finding an alternative to system? Does that mean changing each 'system' instance in the freetds files?

**Comment by fziglio** [comment]
I would say something like this https://github.com/holzschu/ios_system. `system` function execute the passed command using system shell (`sh`, `ksh` or other in Unix, `cmd` in Windows, etc). Possibly iOS does not have a system shell so iOS developers decided to remove `system` from C library. I think in all FreeTDS sources there's only that call to `system` (in fisql).

**Comment by yoKurt94** [comment]
Thanks for your helpful answers. As far as I can see, `--disable-apps` works for now but I am aware that it might backfire. Since it's compiling without an error, I close this issue.

**Comment by fziglio** [comment]
I think it would be better to detect if `system` is present and disable the specific `fisql` feature.

**Comment by yoKurt94** [comment]
Okay, as far as I can see there are 2 places inside fisql where system is called: 
1. inside `static void system_cmd(const char *cmd)`:
  `switch (rv = system(cmd)) { _[SWITCH CASES]_}`
2. inside `while (1) {_[...]_}`
```
		if (!(strncasecmp(line, "!!", 2))) {
			system_cmd(line + 2);
			continue;
		}
```
How do I check if system is available and enable/disable system in C?

**Comment by freddy77** [comment]
Testing this commit https://github.com/FreeTDS/freetds/commit/7f9d0067fde4dda9cf9155138a794ac941be2c73 . Can you test it with iOS ?

**Comment by yoKurt94** [comment]
Awesome! I tested it with MacCatalyst. There were no errors thrown in the terminal and I couldn't find any system error in my log file. I guess it's fixed?

[config.log](https://github.com/FreeTDS/freetds/files/7774348/config.log)

**Comment by freddy77** [comment]
Yes, expect a new 1.3 release package tomorrow

**Comment by yoKurt94** [comment]
Despite no error in the terminal, I realized that something failed because it didn't create a `libsybdb.a` file. When I download this git repository and run autogen.sh, the terminal says 
`./configure: line 19808: syntax error near unexpected token `IODBC,'`
Is it possible that there is an error inside `configure.ac` file with the line `PKG_CHECK_MODULES(IODBC, libiodbc)`?

**Comment by freddy77** [comment]
Maybe something went wrong generating again configure. I would wait for tomorrow tarball and try again.

**Comment by yoKurt94** [comment]
Thanks for the new release! I just downloaded `freetds-patched.tar.gz` and `freetds-1.3.5.tar.gz` and compiled them, but both throw an error in the terminal: 
```
fisql.c:336:15: error: 'system' is unavailable: not available on macCatalyst
        switch (rv = system(cmd)) {
                     ^
```

**Comment by freddy77** [comment]
Can you try https://www.freetds.org/files/freetds-1.4.dev.20211226.tar.bz2 ? I changed the way `system` is checked

**Comment by yoKurt94** [comment]
My terminal complains:
```
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [bsqlodbc] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```
I hope that I configured it correctly so that the problem is not me. I have lots of errors in my log (but not just in this build, in most of my previous builds as well):`fatal error: too many errors emitted, stopping now [-ferror-limit=]`

[config.log](https://github.com/FreeTDS/freetds/files/7777551/config.log)

**Comment by yoKurt94** [comment]
I tried your version with `--disable-apps` as well, same error. If I use the same .sh script with another FreeTDS version, it builds (with `--disable-apps` only, of course).

**Comment by freddy77** [comment]
Looking at your `config.log` the detection of system was now correct. Try ftp://ftp.freetds.org/pub/freetds/stable/freetds-1.3.6.tar.gz.

**Comment by yoKurt94** [comment]
Works now for iOS without the `--disable-apps command`! Thank you, this is great.
