### ISSUE TITLE
'SQLUSMALLINT' is unknown

### ISSUE THREAD

**Issue by yoKurt94** [FreeTDS/freetds#441]
I built FreeTDS for MacCatalyst. However, I get an error inside the `odbcss.h` file for 2 structs: 

```
typedef struct tagSS_TIME2_STRUCT {
	SQLUSMALLINT hour;
	SQLUSMALLINT minute;
	SQLUSMALLINT second;
	SQLUINTEGER fraction;
} SQL_SS_TIME2_STRUCT;

typedef struct tagSS_TIMESTAMPOFFSET_STRUCT {
	SQLSMALLINT year;
	SQLUSMALLINT month;
	SQLUSMALLINT day;
	SQLUSMALLINT hour;
	SQLUSMALLINT minute;
	SQLUSMALLINT second;
	SQLUINTEGER fraction;
	SQLSMALLINT timezone_hour;
	SQLSMALLINT timezone_minute;
} SQL_SS_TIMESTAMPOFFSET_STRUCT;
```

Xcode complains that `SQLUSMALLINT`, `SQLSMALLINT` and `SQLINTEGER` are unknown types. Additionally, inside `sybdb.h` file, Xcode is complaining that `typedef int BOOL;` is an redefinition from signed char to int. 
I tried to fix it by changing the ODBC driver from unixodbc to iodbc without any luck.
To me, it looks like there is a link or an imported file missing, which one is it or what else is wrong here?

**Comment by freddy77** [comment]
The `SQLxxx` types should be defined in the driver manager (unixodbc or iodbc) include files. Try to include after sql.h (or similar).
About `BOOL` it must be int, otherwise the ABI changes. Which file is causing the conflict?

**Comment by yoKurt94** [comment]
Do I understand you correct that I should add an `include sql` statement inside the `odbcss.h` file?

**Comment by yoKurt94** [comment]
To be honest, I couldn't find any other definitions of `BOOL`. I am not familiar with C, but I am looking for `typedef signed char BOOL`, right?

**Comment by yoKurt94** [comment]
I think I fixed the `SQLxxx` missing definitions (I say 'think' because the project is still not building due to the redefinition error of `BOOL`) I will confirm it once the project builds. Essentially, I gave a wrong path for the ODBC driver. I fixed it by reinstalling `unixodbc` via brew. I had to `brew unlink libiodbc` afterwards. Then I specified the installation path for the `unixodbc` driver with `--with-unixodbc=DIR` as mentioned [here](http://www.freetds.org/userguide/config.html). However, the redefinition of int is still an remaining issue.

**Comment by freddy77** [comment]
About the `BOOL` type the compiler usually shows the 2 conflicting definitions.

**Comment by yoKurt94** [comment]
Unfortunately, Xcode does not show me the original definition and I can also not jump to it:

![Bild 24 12 21 um 16 45](https://user-images.githubusercontent.com/62561593/147362940-65ea7573-6281-4f1b-9629-355fed336e5a.JPG)

However, I found a comment above mentioning: 

```
#ifndef __INCvxWorksh
/* VxWorks already defines STATUS and BOOL. Compiler gets mad if you 
** redefine them. */
/* __INCvxWorksh will get #defined by std. include files included from tds.h
*/
```

but I don't understand what that means. I tried browsing through the FreeTDS files and searching for the definition, but I couldn't identify the original definition.

**Comment by freddy77** [comment]
VxWorks is another operating system, nothing to do with Mac.
Maybe command line tools would give more details than Xcode. Or maybe clicking on the error message? Or is there some kind of output window to enable? Maybe IDEs have such option.

**Comment by yoKurt94** [comment]
Okay, I see. I tried everything I knew but couldn't find any way to let Xcode show me where the definition occurs. I created a brand new project and included a freshly built `libsybdb.a` and now it's compiling. I suspected that the issue could be that I included FreeTDS as a dynamic library, but it builds FreeTDS as a static or a dynamic library. So for now, I do not know what the issue#441 caused. I will dig deeper into it tomorrow.

**Comment by yoKurt94** [comment]
I tried importing the same `libsybdb.a` file into the project that wouldn't build, but it's still not working. The only explanation is that I accidentally set up Xcode in a wrong way or changed sth inside a file but I just can't figure out what the problem is. Therefore, it is not really an issue with FreeTDS.
