### ISSUE TITLE
Freetds fisql issue

### ISSUE THREAD

**Issue by mithilesh38cse** [FreeTDS/freetds#442]
I tried to install freetds-1.3.4 on Solaris(version 5.11).

1) executed 'sh configure --prefix=/path/to/installation_directory'
2) executed 'make'
It thrown below error. 

Dbstribg_concat   ../../dblib/.libs/libsybdb.so
ld: fatal: symbol referencing errors
Collect2: ld returned 1 exit status
*** Error code 1
The following command caused the error:
echo " CCLD " fisql;/bin/sh ../../../libtool --silent --tag=CC --mode=link gcc -D_REENTRANT -pthreads -g -O2 -I/usr/include -Wdeclaration-after-statement -L/usr/lib -o fisql fisql.o terminal.o edit.o handlers.o interrupt.o ../../dblib/libsybdb.la ../../replacements/libreplacements.la -lncurses -lreadline
Make: fatal error: command failed for target `fisql'
Current working directory /path/to/freetds-1.3.4/src/apps/fisql

Any help is much appreciated.

**Comment by freddy77** [comment]
It's not clear which symbol is missing. Is this the full log or is it partial? It's not clear what `Dbstribg_concat` is.

**Comment by mithilesh38cse** [comment]
Full log is too long. But make failed with error line dbstring_concat     ../../dblib/.libs/libsybdb.so

**Comment by freddy77** [comment]
`dbstring_concat` is an internal static function, not clear why is reported, it's only calling some very basic and standard functions (`malloc`, `free`, `strlen`, `memcpy`) and `dbperror` which is called in a lot of places.
Can you post 10/20 lines about the piece you reported?

**Comment by mithilesh38cse** [comment]
Making all in .
Making all in unittests
Making all in dblib
Making all in .
Making all in unittests
Making all in server
Making all in pool
Making all in apps
Making all in fisql
   CCLD.      fisql
Undefined.                                    first referenced
  symbol.                                               in file
dblib_get_tds_ctx.                        ../../dblib/.libs/libsybdb.so
dbstring_getchar.                        ../../dblib/.libs/libsybdb.so
dbpivot.c.                                      ../../dblib/.libs/libsybdb.so
dbacolptr.                                     ../../dblib/.libs/libsybdb.so

**Comment by mithilesh38cse** [comment]
Hope above output will help

**Comment by freddy77** [comment]
That's pretty weird! They are all static definitions in a file. Considering `fisql` is dynamically linking `libsybdb.so` it's not clear why these symbols should be even be considered by the linker, unless for some weird reasons it's doing static linking but I cannot see any reasons why. Also the linker used is `gcc` so I suppose even the compiler is `gcc`. `fisql` should be the first executable linking to external libraries compiled (`tdspool` is not linking external dynamic libraries beside `libc`, system default one). What happen if you issue `make -k` (continue). Do you have other linking issues? Could I have access to such a build machine?

**Comment by mithilesh38cse** [comment]
Apologies, due to security reason or policies, I can't give access.
On running make -k, I got other linking issue for other executable file like fisql, datacopy, bsqldb, freebcp, defncopy. All ended with error at the same point dbstring_concat.. 
I also tried ldd ../../dblib/.libs/libsybdb.so
All dependencies found except below one
libgcc.s.so.1 (GCC_4.3.0) => version not found

**Comment by freddy77** [comment]
No problem. I tried to download a VM image from Oracle and test with it. Not much success either, actually worse than yours. The libtool script generated has, on my side, some issue and it was not able to generate any shared object, so it failed with libct. Can you check if you have other warnings/errors with `ld` ? I also tried to add directory in the PATH (`/usr/gnu/bin`) to be able to find `objdump` and other GNU tools but this didn't help. I checked and `libtool` used by `FreeTDS` is the last.

**Comment by mithilesh38cse** [comment]
Are you getting "../../libtool[1724]: eval: syntax error at line 1: `|' unexpected"? If so, make changes in libtool and the changes is related to global_symbol_pipe.
It seems to be global_symbol_pipe empty. So, remove this variable from line to avoid double | in. 

To include shared library, try adding /use/gnu/lib in LD_LIBRARY_PATH and run if that works. ldd was giving all error related to dbstring_concat

**Comment by freddy77** [comment]
I managed to compile everything with success. Try this

```
$ export PATH=/usr/gnu/bin:$PATH
$ bash configure <OPTIONS>
$ make -j4
```
it seems that `configure` and `libtool` are more happy using GNU tools instead of system ones. Putting `/usr/gnu/bin` directory before system ones will led to use GNU tools.

**Comment by mithilesh38cse** [comment]
Are you on below system(command 'uname -a' output)?
"SunOS hostname 5.11 11.3 sunv4 sparc sunv4 Solaris'

I still have the same error

**Comment by freddy77** [comment]
```
test@solaris11:~$ uname -a
SunOS solaris11 5.11 11.4.0.15.0 i86pc i386 i86pc Solaris
test@solaris11:~$ ls /usr/gnu/bin/
'['          date      gprof       mktemp             reset     toe
 addr2line   dd        grep        msgfmt             rm        touch
 amd64       df        groups      mv                 rmdir     tput
 ar          diff      gstrip      ncursesw5-config   sdiff     tr
 as          diff3     head        neqn               sed       true
 awk         dirname   hostid      nice               sh        tset
 basename    du        id          nl                 size      tsort
 c++filt     echo      infocmp     nm                 sleep     tty
 captoinfo   egrep     infotocap   nohup              sort      uname
 cat         elfedit   install     nroff              split     unexpand
 chgrp       env       join        objcopy            strings   uniq
 chmod       expand    kill        objdump            stty      unlink
 chown       expr      ld          od                 sum       uptime
 chroot      factor    link        paste              sync      wc
 cksum       false     ln          patch              tabs      which
 clear       fgrep     logname     pathchk            tail      who
 cmp         find      ls          pr                 tar       xargs
 comm        fmt       make        printf             tbl       xgettext
 cp          fold      mkdir       pwd                tee       yes
 csplit      getopt    mkfifo      ranlib             test
 cut         gettext   mknod       readelf            tic
```

**Comment by mithilesh38cse** [comment]
libgcc.s.so.1 (GCC_4.3.0) => version not found

Which version of above you have?

**Comment by freddy77** [comment]
```
test@solaris11:~$ objdump -x /usr/lib/libgcc_s.so.1 | grep GCC
2 0x00 0x0b792650 GCC_3.0
3 0x00 0x0b792653 GCC_3.3
        GCC_3.0 
4 0x00 0x09265f61 GCC_3.3.1
        GCC_3.3 
5 0x00 0x0b792654 GCC_3.4
        GCC_3.3.1 
6 0x00 0x09265e62 GCC_3.4.2
        GCC_3.4 
7 0x00 0x09275a60 GCC_4.0.0
        GCC_3.4.2 
8 0x00 0x09276060 GCC_4.2.0
        GCC_4.0.0 
9 0x00 0x09275f60 GCC_4.3.0
        GCC_4.2.0 
10 0x00 0x09275d60 GCC_4.5.0
        GCC_4.3.0 
11 0x00 0x09275360 GCC_4.7.0
        GCC_4.5.0 
12 0x00 0x09275260 GCC_4.8.0
        GCC_4.7.0 
13 0x00 0x092a5a60 GCC_7.0.0
        GCC_4.8.0 
00000000 g     O *ABS*  00000000              GCC_3.3
00000000 g     O *ABS*  00000000              GCC_3.4
00000000 g     O *ABS*  00000000              GCC_4.5.0
00000000 g     O *ABS*  00000000              GCC_4.3.0
00000000 g     O *ABS*  00000000              GCC_3.4.2
00000000 g     O *ABS*  00000000              GCC_4.8.0
00000000 g     O *ABS*  00000000              GCC_4.0.0
00000000 g     O *ABS*  00000000              GCC_4.2.0
00000000 g     O *ABS*  00000000              GCC_3.3.1
00000000 g     O *ABS*  00000000              GCC_4.7.0
00000000 g     O *ABS*  00000000              GCC_3.0
00000000 g     O *ABS*  00000000              GCC_7.0.0
test@solaris11:~$ objdump -x /usr/gcc/7/lib/amd64/libgcc_s.so.1 | grep GCC
2 0x00 0x0b792650 GCC_3.0
3 0x00 0x0b792653 GCC_3.3
        GCC_3.0 
4 0x00 0x09265f61 GCC_3.3.1
        GCC_3.3 
5 0x00 0x0b792654 GCC_3.4
        GCC_3.3.1 
6 0x00 0x09265e62 GCC_3.4.2
        GCC_3.4 
7 0x00 0x09265e64 GCC_3.4.4
        GCC_3.4.2 
8 0x00 0x09275a60 GCC_4.0.0
        GCC_3.4.4 
9 0x00 0x09276060 GCC_4.2.0
        GCC_4.0.0 
10 0x00 0x09275f60 GCC_4.3.0
        GCC_4.2.0 
11 0x00 0x09275d60 GCC_4.5.0
        GCC_4.3.0 
12 0x00 0x09275360 GCC_4.7.0
        GCC_4.5.0 
13 0x00 0x09275260 GCC_4.8.0
        GCC_4.7.0 
14 0x00 0x092a5a60 GCC_7.0.0
        GCC_4.8.0 
0000000000000000 g     O *ABS*  0000000000000000              GCC_3.4.2
0000000000000000 g     O *ABS*  0000000000000000              GCC_3.4.4
0000000000000000 g     O *ABS*  0000000000000000              GCC_4.8.0
0000000000000000 g     O *ABS*  0000000000000000              GCC_4.3.0
0000000000000000 g     O *ABS*  0000000000000000              GCC_4.5.0
0000000000000000 g     O *ABS*  0000000000000000              GCC_7.0.0
0000000000000000 g     O *ABS*  0000000000000000              GCC_3.0
0000000000000000 g     O *ABS*  0000000000000000              GCC_3.3
0000000000000000 g     O *ABS*  0000000000000000              GCC_3.4
0000000000000000 g     O *ABS*  0000000000000000              GCC_3.3.1
0000000000000000 g     O *ABS*  0000000000000000              GCC_4.7.0
0000000000000000 g     O *ABS*  0000000000000000              GCC_4.2.0
0000000000000000 g     O *ABS*  0000000000000000              GCC_4.0.0
```
Many more than just 4.3.0.
`gcc --version` says I have version `7.3.0`.

**Comment by mithilesh38cse** [comment]
It seems like make command is successful for me as well. It is ending with a if statement (code to copy PWD.in content to PWD file if not present). 
When I do make check or make test it fails with 14 test cases out of 27. Do we require any configuration before make check or make test?

**Comment by fziglio** [comment]
> It seems like make command is successful for me as well. It is ending with a if statement (code to copy PWD.in content to PWD file if not present). When I do make check or make test it fails with 14 test cases out of 27. Do we require any configuration before make check or make test?

What did you do to fix the issue?
Yes, tests requires to have a properly configured server. See https://www.freetds.org/userguide/ConfirmInstall.html#Tests.
Can I close this issue?

**Comment by mithilesh38cse** [comment]
Apologies for being a bit late to reply.
1) I copied libtool from other places .
2) Modified the lmmain.sh and libtool file for ggrep. In my system ggrep is not available. So, I converted it with grep and respective changes. Which further resolved my issue.
Thanks for your quick help.
