### ISSUE TITLE
OSQL check: no potential directory strings in "/usr/local/bin/isql"

### ISSUE THREAD

**Issue by yoKurt94** [FreeTDS/freetds#443]
Until now, I couldn't get FreeTDS to connect with any server, so I checked tsql and osql as mentioned in the [FreeTDS documentation](http://www.freetds.org/userguide/help.html). Running `osql -S server -U user -P password` reveals some issues: 

```
/usr/local/bin/osql: line 53: ldd: command not found
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strings: can't open file: /.isql_history (No such file or directory)
osql: problem: no potential directory strings in "/usr/local/bin/isql"
osql: advice: use "osql -I DIR" where DIR unixODBC\'s install prefix e.g. /usr/local
isql strings are:
+ /.isql_history
checking odbc.ini files
	cannot read "/Users/<user>/.odbc.ini"
	cannot read "/odbc.ini"
osql: error: unable to locate server in any odbc.ini
```

I wanted to start with fixing the issue `no potential directory strings in "/usr/local/bin/isql"` first, so I ran `osql -I /usr/local/bin/isql` inside the directory where my unixODBC driver is installed. However, this command (which was recommended in the terminal) seems to have a syntax issue. Terminal answers with: `Syntax: osql -S server -U user -P password` 
How can I fix these missing directory strings? Or is there a way to fix all these issues at once because there is something I oversee?

**Comment by freddy77** [comment]
Mumble... I think here the issue is `ldd: command not found`. The script is expecting `ldd` to be present but it seems Mac does not have `ldd` by default.

**Comment by freddy77** [comment]
Can you try this:
```diff
diff --git a/src/apps/osql b/src/apps/osql
index acb0f2451..49b4efd37 100755
--- a/src/apps/osql
+++ b/src/apps/osql
@@ -49,8 +49,13 @@ exec 3> ${INI_DIRNAME}
 # Check the libraries, too. 
 if [ -z "${OVER_DIR}" ]
 then 
+       libcmd='ldd "${ISQL}" | awk "/libodbc\./ {print \$3}"'
+       if ! command -V ldd >/dev/null 2>&1 && command -V otool >/dev/null 2>&1
+       then
+               libcmd='otool -L "${ISQL}" | awk "/libodbc\./ {print \$1}"'
+       fi
        echo "checking shared odbc libraries linked to isql for default directories..."
-       (echo ${ISQL_DIR}; ldd "${ISQL}" | awk '/libodbc\./ {print $3}') \
+       (echo ${ISQL_DIR}; eval "$libcmd") \
        | while read L
          do 
                strings "$L" | grep '^/' | grep -v '/lib' \
```
