### ISSUE TITLE
Config.log error: "building for Mac Catalyst, but linking in dylib built for macOS"

### ISSUE THREAD

**Issue by yoKurt94** [FreeTDS/freetds#446]
When trying to install FreeTDS, I noticed that FreeTDS 1.3.6 stopped creating a `libsybdb.a` file. Looking at my log file, I noticed that there are dozens of error that look like:

```
fatal error: too many errors emitted, stopping now [-ferror-limit=]
conftest.c:85:10: fatal error: 'sys/eventfd.h' file not found
conftest.c:52:10: fatal error: 'sys/eventfd.h' file not found
```

Could the issue be that there is something wrong with my ODBC driver? I noticed that the log also says: 

`ld: building for Mac Catalyst, but linking in dylib built for macOS, file '/usr/local/opt/readline/lib/libreadline.dylib' for architecture x86_64`

[config.log](https://github.com/FreeTDS/freetds/files/7810766/config.log)

**Comment by yoKurt94** [comment]
I just found [this](https://lists.ibiblio.org/pipermail/freetds/2020q2/030516.html) entry of the mailing list with an error which resembles mine. In this case, it looked like the `-target` wasn't specified for the dynamic library. However, I cannot find any missing command for my dynamic library, or do I oversee something?

**Comment by fziglio** [comment]
From
```
configure:17507: /usr/bin/cpp   conftest.c
In file included from conftest.c:54:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/netdb.h:91:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/netinet/in.h:70:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/Availability.h:136:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityInternal.h:142:2: error: #endif without #if
#endif /* #if defined(__has_builtin) */
 ```
it looks like you either have a corrupted file or your environments is not correctly configured

**Comment by yoKurt94** [comment]
Thanks for your answer. Would you mind looking at my .sh file if there is something wrong with my variables? I don't see anything that could be wrong (but I am not so experienced in auto tools) and I had to customize a lot as I am trying to build for MacCatalyst.

[mybuild.txt](https://github.com/FreeTDS/freetds/files/7815982/mybuild.txt)

**Comment by yoKurt94** [comment]
Solution: deleting the FreeTDS folder and inserting a fresh copy from tarball.
Looks like there was some interference of environment variables from a previous make (if this is the correct terminology). I have to add that I still couldn't build FreeTDS.
