### ISSUE TITLE
odbcss.h conflicts with Windows SDK header

### ISSUE THREAD

**Issue by elmarco** [FreeTDS/freetds#454]
As discussed in https://github.com/msys2/MINGW-packages/pull/10634#issuecomment-1031277844

Windows SDK (and mingw64 headers) conflicts with freetds odbcss.h header.

Sadly, the headers are not compatible.

Maybe the solution for mingw is to use ``--includedir=$prefix/include/freetds``.

Of course, that would be easier if freetds shipped a .pc file.

**Comment by fziglio** [comment]
This should do https://github.com/FreeTDS/freetds/commit/5a1dd6b6691ab81a16a6ebc596d74aa30ae96e63

**Comment by fziglio** [comment]
This should do too https://github.com/FreeTDS/freetds/commit/cf501c5dee7a1d9be6f033cc241c34b7cd0e369f
