### ISSUE TITLE
tdspool detach from console / daemonize

### ISSUE THREAD

**Issue by vstaf** [FreeTDS/freetds#46]
Hi all!
Could you add feature correctly detach tdspool from console after it launch or add some command line option like -d to daemonize process?

**Comment by freddy77** [comment]
Yes, also accept patches :)
I don't know actually if is really ready for production. For instance it output many information on connections, perhaps would be worth to also implement a logging and a rotation (HUP signal to reopen logs)

**Comment by vstaf** [comment]
Yep, if any can implement a logging - it will be great too.:)

**Comment by freddy77** [comment]
Done!
-d to make it a daemon;
-l <filename> to log to a file;
send SIGHUP to make tdspool reopen the log file.

**Comment by vstaf** [comment]
Perfect! Thanks, @freddy77 !)
