### ISSUE TITLE
freetds error 2403 using foreign data wrapper

### ISSUE THREAD

**Issue by RonanMorgan** [FreeTDS/freetds#464]
Hello,

I have the following error when I use the foreign data wrapper from mssql to postgresql on a specific column which has a special setting ( character_set_name : iso1, collation_name : French_CI_AS)   

> 2022-05-11 10:59:46] [HV00L] ERROR: DB-Library error: DB #: 2403, DB Msg: Some character(s) could not be converted into client's character set.  Unconverted bytes were changed to question marks ('?'), OS #: 0, OS Msg: Success, Level: 4

freetds version : 1.2.3 (with tds 7.4)

According to the logs there is a conversion done with iconv : UTF8 <-> UCS-2LE

The postgresql has the following configuration : 
server_encoding = UTF8
client_encoding = UTF8
charachter_set_name = UTF8
character_repertoire = UCS
collation_server : SQL_Latin1_General

Do you have any idea what is happening ? I have to admit that I don't understand very well all these configurations ...

**Comment by fziglio** [comment]
I think for `foreign data wrapper` you mean a connector from MSSQL to PostgreSQL that makes you do query from MSSQL server to PostgreSQL, right? You linked PostgreSQL from MSSQL and are doing queries to MSSQL.
Collation can be a bit of a pain but better to do it right. Technically on MSSQL each column (yes, not each database, each column!) can have a different encoding. Also the remote database (in this case PostgreSQL) will have its encoding for characters (for each column? for each database? for each connection? it depends on database type and settings). If the PostgreSQL encoding is correct and match what MSSQL think you should not have issues. But if they don't match you can get some invalid character!
So.. what's PostgreSQL setting? Are there any specific setting on the data wrapper?

**Comment by fziglio** [comment]
So, it's the other way around, PG doing queries using MSSQL.
I don't understand why everything is UTF8 beside `collation_server` (PG or MSSQL) which is `SQL_Latin1_General`.
Anyway, as the PG is using UTF8 I would try to setup everything to use UTF8, that should do it.
So the client encoding for the data wrapper should be UTF8. No idea on how to setup it. MSSQL 2019 is also able to store data directly using UTF8 and new FreeTDS is able to support this directly.

**Comment by fziglio** [comment]
Try to select some varchar column with some French specific character (like `garçon`, `père`, `hors-d'œuvre`, well, you should know better than me)

**Comment by RonanMorgan** [comment]
Hello. Thanks for your answer. 

The problem was the following : the source colum was using varchar(max) but varchar is not compatible with utf8 et the max size is too big for utf8.

So after a concatenation to 100 and a migration to nvarchar, it worked.
