### ISSUE TITLE
FreeTDS library for 32 bits on a 64 bits machine

### ISSUE THREAD

**Issue by narcisC22** [FreeTDS/freetds#469]
Hello, please, can you help me with this problem?  I am trying to install freeTDS on a 64 bitness machine, but for a 32bits variant (since the application  32 bits based).  I have a centos 6 instaled. Is there any package available  or compiling the source code is the only way to do this? 
I know this is not actually an issue, but I was not able to find out how can I request subscription opening.

**Comment by fziglio** [comment]
We don't distribute binaries. Not hard to build. CentOS 6 is pretty old. Why such an old machine? I can help with the compilation (we support RPM, see https://www.freetds.org/userguide/osissues.html#RPM) or either send some compiled version.

About the subscription you can send me your email address and I can add it to the list.

**Comment by narcisC22** [comment]
Thank you so much for your reply. 
I managed to create the rpm package,
My goal is to have a MS Server connection against unixODBC driver manager.
 
I'm just not sure now what package will be suffice to be installed for this as there are four instances generated: freetds-unidodbc, freetds-devel, freetds-1.3 and freetds-doc. 
I think I onlly need freetds-unixodbc.i686.rpm?

**Comment by fziglio** [comment]
Yes, only `freetds-unixodbc` should be needed in your case although some other piece in `freetds` package could help with some troubleshooting and specific configurations.

**Comment by narcisC22** [comment]
Thank you, sir! Really appreciate all your help here!

**Comment by fziglio** [comment]
You're welcome.

Closing the issue
