### ISSUE TITLE
The second parameter to the dbopen function does not support [ipv6_addr]:port 

### ISSUE THREAD

**Issue by CCCClass** [FreeTDS/freetds#470]
master branch

example: when i called dbopen(xxx, "[ipv6_addr]:port"), The function call chain is:

dbopen-->tdsdbopen-->tds_read_config_info->tds_lookup_host_set-->tds_lookup_host-->getaddrinfo-->...

The getaddrInfo function returns NULL, causing an error.

The reason is that getaddrInfo passes a servername variable of the form [ipv6_addr], and the square brackets are superfluous.

My suggestion is to remove the square brackets in connection->server_name by modifying the parse_server_name_for_port function.

**Comment by fziglio** [comment]
Nice capture. Yes, `parse_server_name_for_port` should strip the quotes. Testing a solution.
