### ISSUE TITLE
DBCOL.TableName not populated

### ISSUE THREAD

**Issue by Gerrit2160** [FreeTDS/freetds#472]
I'am using DBLIB's dbcolinfo to retrieve some meta data of a query. While other attributes of DBCOL are filled correctly, the field TableName is always an empty string. I've tested dbtablecolinfo also with same results.
The version of FreeTDS ist 1.3.13.
Perhaps I'm doing something wrong...

**Comment by fziglio** [comment]
It's kind of expected. Most of the queries does not return database/table informations. It's the way the protocol works. Try to add `FOW BROWSE` clause to your queries.
