### ISSUE TITLE
Msg 20010: could not allocate sufficient memory (MSYS2/MinGW64)

### ISSUE THREAD

**Issue by Gerrit2160** [FreeTDS/freetds#476]
After updating MSYS2/MinGW64 the error occurs while opening a new connection to MSSQLSERVER 2017.
With our old MSYS2/MinGW tool chain (2 years ago) and on different linux machines everything is working fine.
It doesn't matter if I use the precompiled mingw package or if I compile the current FreeTDS sources.
In MSYS2 I tried both mingw64 and ucrt64.
Can this be a problem with the current MSYS2 distribution?
Any hint would be appreciated.

**Comment by fziglio** [comment]
How did you compile FreeTDS? CMake or Autoconf? I don't have issues with CMake+MSVC and Autoconf+Linux. It could be some combination trigger some bugs in either msys2 or FreeTDS.

**Comment by Gerrit2160** [comment]
FreeTDS was compiled on Windows using mingw-w64-x86_64-gcc.
The precompiled package mingw-w64-x86_64-freetds has same results.
dbopen(...) leads to message "Msg 20010: could not allocate sufficient memory"

**Comment by fziglio** [comment]
Try to set `TDSDUMP` environment. Maybe it will shed where exactly memory issue is reported.

**Comment by Gerrit2160** [comment]
Ok, thank you for this hint. I'll build a small test program first and report the results.

**Comment by Gerrit2160** [comment]
Hi Frediano,
the dump file helped. I could see that freetds.conf was not found.
As a result the driver tried to use "CP1252" client charset, but tds_iconv_info_init got "-1" as the charset name.
That lead to the message "Unable to allocate sufficient memory (localhost)".
After setting "FREETDSCONF" to "C:\msys64\mingw64\etc\freetds.conf" the configuration file and the entry
"client charset = UTF-8" where accepted.

On Linux systems I don't have such problems.
Thank you very much for your help. Here is the freetds log file:

[freetds.log](https://github.com/FreeTDS/freetds/files/10284729/freetds.log)

**Comment by fziglio** [comment]
The error is surely pretty misleading!
I thought last commit should have CP1252 even with trivial iconv implementation.
Beside that you should consider compiling with correct iconv support.
I'll have a look at the logs.

**Comment by freddy77** [comment]
Recently updated, error should be better.
