### ISSUE TITLE
Missing Link-time Deps prevent/hinder AppVeyor Windows artifact usage

### ISSUE THREAD

**Issue by usrlocalben** [FreeTDS/freetds#479]
The AppVeyor builds would be a useful source of windows binaries, but they fail to link due to missing _iconv.lib_.

Adding `copy ..\iconv\lib\iconv.lib %DEST_DIR%\lib\` before zipping would be very helpful (and may be what was intended to begin with.)

**Comment by fziglio** [comment]
I suppose you tried to link with static libraries instead of dynamic ones which already have it included statically. I'll add them

**Comment by usrlocalben** [comment]
That is correct. My deployment situation benefited from an all-in-one exe.

Somewhat build-wise related, I also patched the _cmakelist_ to add `#define MSDBLIB 1` to the _config.h_. I find it strange that it isn't the default but maybe I just have no idea how many Sybase instances there are in the world.
(I want MSDBLIB so I can get dbproc-less conversion functions.)

**Comment by freddy77** [comment]
Yes, configure allows to define `MSDBLIB`, cmake not. Adding same option to cmake.

**Comment by freddy77** [comment]
Option added
