### ISSUE TITLE
Connection issues to Azure introduced by v1.3.16

### ISSUE THREAD

**Issue by anorm** [FreeTDS/freetds#489]
## Summary

Starting at version v1.3.16, FreeTDS is unable to connect to Azure databases that are configured with a "Redirect" connection policy. If the connection policy is set to "Proxy", there are no connection issues.

![Screenshot 2023-03-31 140009](https://user-images.githubusercontent.com/2121844/229115019-d7ed9d15-6f92-4920-9100-32957c231e15.png)

## Reproduce

Running on clean alpine linux with the following packages:

```
~ # apk add \
    build-base \
    gcc \
    gnutls-dev \
    krb5-dev \
    linux-headers \
    unixodbc-dev
```

`test.sh`:

```
#!/bin/sh
VER=$1
TSQL=freetds-$VER/src/apps/tsql

if [ ! -e $TSQL ]; then
        wget ftp://ftp.freetds.org/pub/freetds/stable/freetds-$VER.tar.gz
        tar xf freetds-$VER.tar.gz
        cd freetds-$VER
        ./configure --with-gnutls --enable-krb5 --with-unixodbc=/usr
        make
        cd ..
fi

echo -e "select 1\ngo" | $TSQL -H "<redacted>.database.windows.net" -p 1433 -U "<redacted>" -P "<redacted>"
```

Running the tests:
```
~ # ./test.sh 1.3.15
...
locale is "C.UTF-8;C;C;C;C;C"
locale charset is "UTF-8"
using default charset "UTF-8"
1> 2>
1
(1 row affected)
```

```
~ # ./test.sh 1.3.16
...
locale is "C.UTF-8;C;C;C;C;C"
locale charset is "UTF-8"
using default charset "UTF-8"
 6Error 20002 (severity 9):
        Adaptive Server connection failed
There was a problem connecting to the server
```

## Test results

Testing on versions 1.3.10 - 1.3.17 yields:

- v1.3.10 - 🟢 OK
- v1.3.11 - 🟢 OK
- v1.3.12 - 🟢 OK
- v1.3.13 - 🟢 OK
- v1.3.14 - 🟢 OK
- v1.3.15 - 🟢 OK 
- v1.3.16 - 🔴 Fails
- v1.3.17 - 🔴 Fails

**Comment by freddy77** [comment]
can you try https://www.freetds.org/files/freetds-1.3.18.tar.bz2 ?

**Comment by anorm** [comment]
Yes, the `freetds-1.3.18.tar.bz2` with sha256sum `243191a8575b72e36798132d4a596a3ecba22f8d9b91187935622f15e873fd22` seems to work good.

**Comment by freddy77** [comment]
New official version will be packaged in a hour or so.
