### ISSUE TITLE
MacOs 13.0 -> 13.3 : Login failure (Sybase)

### ISSUE THREAD

**Issue by M-BELLAHCENE** [FreeTDS/freetds#490]
Hi,

I need a hand on MacOS/Sybase.

On MacOS 13.0 it logs in.
Since MacOS 13.3 update it doesn't.
Same Intel Machine, same login, same server : the MacOS update is the only change.

Environment handle allocation worked. 
SQLGetDiagRec shows an environment allocation error at login time.

My build : 
IODBC_LIBS=/usr/local/iODBC/lib ./configure --prefix=/usr/local --with-iodbc=/usr/local/iODBC
make
sudo make install

Is there some build option that may help with MacOS 13.3 ?

Regards

**Comment by freddy77** [comment]
Il giorno mar 2 mag 2023 alle ore 09:30 M-BELLAHCENE <
***@***.***> ha scritto:

> Hi,
>
> I need a hand on MacOS/Sybase.
>
> On MacOS 13.0 it logs in.
> Since MacOS 13.3 update it doesn't.
> Same Intel Machine, same login, same server : the MacOS update is the only
> change.
>
> Environment handle allocation worked.
> SQLGetDiagRec shows an environment allocation error at login time.
>
> My build :
> IODBC_LIBS=/usr/local/iODBC/lib ./configure --prefix=/usr/local
> --with-iodbc=/usr/local/iODBC
> make
> sudo make install
>
> Is there some build option that may help with MacOS 13.3 ?
>
> Regards
>
Hi,
  check the logging page, see https://www.freetds.org/userguide/logging.html
.
Recently it seems TLS settings were updated causing many login issues,
check if there are differences between MacOS 13.0 and 13.3 in that respect.
What do you mean by "SQLGetDiagRec shows an environment allocation error at
login time." ? Does it return some string message?
You could try using tsql utility, this will connect directly without using
ODBC, see for instance
https://www.freetds.org/userguide/serverthere.html#serverthere.tsql.

Regards,
  FredianoMessage ID: ***@***.***>
>
>

**Comment by M-BELLAHCENE** [comment]
Hi,

No problem in FreeTDS, MacOS changed the weak link architecture in 13.3

In XCode I linked to iODBC using iodbc.tbd and it worked on MacOSX 13.0
It seems it doesn't work anymore in MacOS X 13.3

It's not a FreeTDS issue, thanks :)
