### ISSUE TITLE
install 32-bits freetds library (for unixodbc) on unix 64 bits machine 

### ISSUE THREAD

**Issue by narcisC22** [FreeTDS/freetds#491]
OS: Centos 8, 64 bits

I have an application running against 32 bits.
I need freetds library on 32bits.

With Centos7 I was able to achieve this by building a rpm package from a 32bits machine , but I realised that package cannot be used anymore in Centos8 ( there are some gnutls libraries missing from Centos8).

Please, can you tell me if I can build the freetds sources directly from a 64bits machine to obtain the libtdsodbc.so 32-bit libraries?

**Comment by freddy77** [comment]
Il giorno mer 10 mag 2023 alle ore 09:34 narcisC22 ***@***.***>
ha scritto:

> OS: Centos 8, 64 bits
>
> I have an application running against 32 bits.
> I need freetds library on 32bits.
>
> With Centos7 I was able to achieve this by building a rpm package from a
> 32bits machine , but I realised that package cannot be used anymore in
> Centos8 ( there are some gnutls libraries missing from Centos8).
>
> Please, can you tell me if I can build the freetds sources directly from a
> 64bits machine to obtain the libtdsodbc.so 32-bit libraries?
>
Hi,
  yes, CentOS 8 does not support 32 bit (Intel I suppose) but it still
supports 32 bit applications (XXX.i686 packages). However this does not
surely make things easier.
However installing the right XXX.i686 and passing "--target i686" to the
rpm-build command solved the issue.
I don't have a CentOS 8 installation so I used docker.
Create an empty directory, enter it and create a file "build" with this
content
----------
#!/bin/bash
set -ex
cd
sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g'
/etc/yum.repos.d/CentOS-*
dnf install -y rpm-build gnutls-devel unixODBC-devel gcc binutils autoconf
pkg-config automake make libtool glibc-devel glibc-devel.i686
unixODBC-devel.i686 libgcrypt-devel.i686 gnutls-devel.i686 gmp-devel.i686
openssl-devel.i686 wget
wget https://www.freetds.org/files/stable/freetds-1.3.18.tar.bz2 -O
freetds.tar.bz2
tar xvf freetds.tar.bz2
cd freetds-*
sed -i 's,gnutls,openssl,g' freetds.spec
mkdir -p /root/rpmbuild/SOURCES
cp ../freetds.tar.bz2 /root/rpmbuild/SOURCES/$(basename $PWD).tar.bz2
rpmbuild -ba freetds.spec --target i686
cp -rv /root/rpmbuild/{SRPMS,RPMS} /build
----------
make it executable (chmod +x build), and run in with docker with CentOS
container like

$ docker run -it --rm --name builder -v $PWD:/build centos:latest
/build/build

it should build and copy the packages into the directory.

I had to replace gnutls with openssl, it seems there's a compatibility
problem with some code dealing with Sybase databases.
You can reuse the file to rebuild newer versions of freetds, just change
the URL with the version in it.
I did some experiments so the list of packages is longer than needed but it
will just take a bit more time to build.

Regards,
  Frediano

**Comment by narcisC22** [comment]
Thank you so much!
I managed to have that lovely 32bit library due to your help :)

Regards,
Narcis
