### ISSUE TITLE
IBM i - PASE environment (AIX) getting md4.0 is not valid 

### ISSUE THREAD

**Issue by pankratz22** [FreeTDS/freetds#493]
I'm on an IBM i (aka AS400) trying to install FreeTDS 1.3.9 using basic commands:
./configure --prefix=/usr/local/freetds
make

When running make, I had many warnings like this:
net.c: In function 'tds_socket_set_nosigpipe':                                                            
net.c:83:1: warning: visibility attribute not supported in this configuration; ignored [-Wattributes]     

And near the end of make, was getting errors like this:
  CCLD     libtdsutils.la                                               
ar: 0707-126 md4.o is not valid with the current object file mode.      
        Use the -X option to specify the desired object mode.           
ar: 0707-126 md5.o is not valid with the current object file mode.      
        Use the -X option to specify the desired object mode.           
ar: 0707-126 des.o is not valid with the current object file mode.      
        Use the -X option to specify the desired object mode.           
ar: 0707-126 hmac_md5.o is not valid with the current object file mode. 
        Use the -X option to specify the desired object mode.           
ar: 0707-126 dlist.o is not valid with the current object file mode.    
        Use the -X option to specify the desired object mode.           
ar: 0707-126 getpassarg.o is not valid with the current object file mode
        Use the -X option to specify the desired object mode.           
ar: 0707-126 sleep.o is not valid with the current object file mode.    
        Use the -X option to specify the desired object mode.           
ar: 0707-126 tds_cond.o is not valid with the current object file mode.   
        Use the -X option to specify the desired object mode.             
ar: 0707-126 win_mutex.o is not valid with the current object file mode.  
        Use the -X option to specify the desired object mode.             
ar: 0707-126 threadsafe.o is not valid with the current object file mode. 
        Use the -X option to specify the desired object mode.             
ar: 0707-126 bjoern-utf8.o is not valid with the current object file mode.
        Use the -X option to specify the desired object mode.             
ar: 0707-126 tdsstring.o is not valid with the current object file mode.  
        Use the -X option to specify the desired object mode.             
ar: 0707-126 net.o is not valid with the current object file mode.        
        Use the -X option to specify the desired object mode.             
make: The error code from the last command is 13.                         

I don't see anyone else even trying to install FreeTDS on this platform, so this could be a new thing.
And FYI: I'm an RPG programmer trying to get PHP to access a remote MS SQL Server 2022. lol.

**Comment by freddy77** [comment]
Il giorno ven 16 giu 2023 alle ore 12:31 pankratz22 <
***@***.***> ha scritto:

> I'm on an IBM i (aka AS400) trying to install FreeTDS 1.3.9 using basic
> commands:
>
Hi,
  why not 1.3.18?


> ./configure --prefix=/usr/local/freetds
> make
>
> When running make, I had many warnings like this:
> net.c: In function 'tds_socket_set_nosigpipe':
> net.c:83:1: warning: visibility attribute not supported in this
> configuration; ignored [-Wattributes]
>
The visibility attribute is mostly for optimization. Weird that it's not
detected as not supported during the configure. Can you post your
config.log?

> And near the end of make, was getting errors like this:
> CCLD libtdsutils.la
> ar: 0707-126 md4.o is not valid with the current object file mode.
> Use the -X option to specify the desired object mode.
>
Looking at ar manual it looks like the default is using only 32 bit
objects. Try to execute "OBJECT_MODE=64 make"instead of just "make".

> ar: 0707-126 md5.o is not valid with the current object file mode.
> Use the -X option to specify the desired object mode.
> ar: 0707-126 des.o is not valid with the current object file mode.
> Use the -X option to specify the desired object mode.
> ar: 0707-126 hmac_md5.o is not valid with the current object file mode.
> Use the -X option to specify the desired object mode.
> ar: 0707-126 dlist.o is not valid with the current object file mode.
> Use the -X option to specify the desired object mode.
> ar: 0707-126 getpassarg.o is not valid with the current object file mode
> Use the -X option to specify the desired object mode.
> ar: 0707-126 sleep.o is not valid with the current object file mode.
> Use the -X option to specify the desired object mode.
> ar: 0707-126 tds_cond.o is not valid with the current object file mode.
> Use the -X option to specify the desired object mode.
> ar: 0707-126 win_mutex.o is not valid with the current object file mode.
> Use the -X option to specify the desired object mode.
> ar: 0707-126 threadsafe.o is not valid with the current object file mode.
> Use the -X option to specify the desired object mode.
> ar: 0707-126 bjoern-utf8.o is not valid with the current object file mode.
> Use the -X option to specify the desired object mode.
> ar: 0707-126 tdsstring.o is not valid with the current object file mode.
> Use the -X option to specify the desired object mode.
> ar: 0707-126 net.o is not valid with the current object file mode.
> Use the -X option to specify the desired object mode.
> make: The error code from the last command is 13.
>
> I don't see anyone else even trying to install FreeTDS on this platform,
> so this could be a new thing.
> And FYI: I'm an RPG programmer trying to get PHP to access a remote MS SQL
> Server 2022. lol.
>

I remember somebody used FreeTDS on AIX in the past. Not recently.

Frediano

**Comment by pankratz22** [comment]
Thank you!

> why not 1.3.18?

Oh, I was using FileZilla to view the ftp site and 1.3.9 was at the end of the list. I should have sorted by date. 

> Try to execute "OBJECT_MODE=64 make" instead of just "make".

Yes, this compiled all the way through.  

I'm going to add few more notes in case other IBM i devs come this way. And in case there is more feedback / guidance to my process.

Results: 
In /usr/local/freetds/etc/freetds.conf I added this:
```
# Testing Server
[servername]
	host = servername
	port = 1433
	tds version = 7.3

```
In QP2TERM I ran this command to get the server's list of instances on servername:

`TDSVER=7.3 tsql -H servername -L`

From that list, I found the instance I wanted, and noted the tcp value.
Then this command to connect to that instance.

`TDSVER=7.3 tsql -H servername -p tcpvalue -D databasename -U username -P password`

This gave me a result like this:
```
locale is "POSIX POSIX POSIX POSIX POSIX POSIX"
locale charset is "ISO8859-1"
using default charset "ISO8859-1"
Setting databasename as default database in login packet 
1> 
```
At the > prompt, I typed an Sql statement, pressed enter, then GO and enter, it returned query results!!
```
select * from sometable;
GO
```

Now I need to figure out how to get PHP and PDO to work with FreeTDS, 

Thanks, again for getting me through that.
Best regards,
James

**Comment by pankratz22** [comment]
Just remembered this: 

> The visibility attribute is mostly for optimization. Weird that it's not
> detected as not supported during the configure. Can you post your
> config.log?

[config.log](https://github.com/FreeTDS/freetds/files/11781600/config.log)

**Comment by freddy77** [comment]
Checked visibility, it's just a warning. It's always specified if compiler supports it.
