### ISSUE TITLE
./configure: line 17956: syntax error near unexpected token `IODBC,' ./configure: line 17956: `	PKG_CHECK_MODULES(IODBC, libiodbc)'

### ISSUE THREAD

**Issue by LGRwx** [FreeTDS/freetds#494]
I get this trouble when I try to install the freetds from the source code. I enter the directory which have been unzip and run the ./autogen.sh as the Web introduction about the installation. I have tried to modifiy the configure file, and I install the libiodbc. But the thing what I have done is not very effective for this error, hoping to get your help ,my operate system is Kylin V10 , a linux distribution from the RHEL 6 ,here is some dependencied version information:
automake 1.15
autoconf 2.69
libtool 2.4.6
make 3.82
gcc 10.4.0
perl 5.16.3
gperf 3.0.4
If you can give some suggestion base on your experience, I will very appreciate you.

**Comment by freddy77** [comment]
Il giorno mar 1 ago 2023 alle ore 03:08 LGRwx ***@***.***> ha
scritto:

> I get this trouble when I try to install the freetds from the source code.
> I enter the directory which have been unzip and run the ./autogen.sh as the
> Web introduction about the installation. I have tried to modifiy the
> configure file, and I install the libiodbc. But the thing what I have done
> is not very effective for this error, hoping to get your help ,my operate
> system is Kylin V10 , a linux distribution from the RHEL 6 ,here is some
> dependencied version information:
> automake 1.15
> autoconf 2.69
> libtool 2.4.6
> make 3.82
> gcc 10.4.0
> perl 5.16.3
> gperf 3.0.4
> If you can give some suggestion base on your experience, I will very
> appreciate you.
>
> Hi,
   not sure why you need to change configure but probably you miss some
macro files. One package I don't see is gettext-devel. Some distro also
need autoconf-archive.
You should have seen some warnings running autogen.sh about missing macros

Regards,
  Frediano

**Comment by LGRwx** [comment]
As you said , I exactly have seen some warning about the missing macros, but I don't know how to fix it, the package what you said I have installed in my machine, I'm sorry I don't add this in the discription, the version of it is 0.19.8, I installed this when I search the problem on the internet, hoping you can continue to provide your advice about the missing macros and  so on。
      I tried to keep commenting out the error part in the configure file to avoid the error, and with the help of a colleague, I added the odbc parameter to run, and finally the installation seemed to be successful, but I still reported an error when running the autogen script of tds-fdw Stuck in the original place, so I guess the installation still failed

**Comment by LGRwx** [comment]
configure.ac:123: warning: macro 'AM_ICONV' not found in library
one warning about the missing macro is like this.

**Comment by LGRwx** [comment]
> Il giorno mar 1 ago 2023 alle ore 03:08 LGRwx ***@***.***> ha scritto:
> I get this trouble when I try to install the freetds from the source code. I enter the directory which have been unzip and run the ./autogen.sh as the Web introduction about the installation. I have tried to modifiy the configure file, and I install the libiodbc. But the thing what I have done is not very effective for this error, hoping to get your help ,my operate system is Kylin V10 , a linux distribution from the RHEL 6 ,here is some dependencied version information: automake 1.15 autoconf 2.69 libtool 2.4.6 make 3.82 gcc 10.4.0 perl 5.16.3 gperf 3.0.4 If you can give some suggestion base on your experience, I will very appreciate you. Hi,
> not sure why you need to change configure but probably you miss some macro files. One package I don't see is gettext-devel. Some distro also need autoconf-archive. You should have seen some warnings running autogen.sh about missing macros Regards, Frediano
> […](#)
> Message ID: ***@***.***>

 As you said , I exactly have seen some warning about the missing macros, but I don't know how to fix it, the package what you said I have installed in my machine, I'm sorry I don't add this in the discription, the version of it is 0.19.8, I installed this when I search the problem on the internet, hoping you can continue to provide your advice about the missing macros and  so on。
  I tried to keep commenting out the error part in the configure file to avoid the error, and with the help of a colleague, I added the odbc parameter to run, and finally the installation seemed to be successful, but I still reported an error when running the autogen script of tds-fdw Stuck in the original place, so I guess the installation still failed.
  configure.ac:123: warning: macro 'AM_ICONV' not found in library
  one warning about the missing macro is like this.

**Comment by freddy77** [comment]
If it's RPM based try `yum whatprovides /usr/share/aclocal/iconv.m4`. It should be in `gettext-devel`.

**Comment by LGRwx** [comment]
> Try also to check if there's a `pkgconf-m4` package

I really thank you, friend, I seem to have installed it successfully, freetds should have been installed successfully, and tds_fdw did not report an error after running the command. I am now preparing to test and study. Really really really very very thank you for helping me solve a problem that troubled me. Finally, thank you very much for taking the time to help me solve this problem. The communication with you is very effective, thank you very much!
