### ISSUE TITLE
configure file is outdated

### ISSUE THREAD

**Issue by fxcoudert** [FreeTDS/freetds#502]
The latest release of freetds does not build on recent macOS versions, because the `configure` script shipped is generated with Autoconf 2.69. This is a very old version of autoconf, released 11 years ago (2012-04-24) and does not know how to deal with modern Darwin / macOS versions.

Please consider using latest autoconf, automake and libtool in future releases.

**Comment by freddy77** [comment]
Updated Autoconf to 2.71. libtool is at the last version. I didn't manage to update automake for some reason but it's not that old.

Can you try it? See https://www.freetds.org/files/stable/freetds-1.4.1.tar.bz2

**Comment by fxcoudert** [comment]
Hum, 1.4.1 and 1.4.2 didn't work. configure still has the wrong code, the libtool code is not the latest version: see `libtool.m4` in the released version, is dated 2015 (instead of 2022).

**Comment by freddy77** [comment]
Found the issue. On the website they claim that the last version is 2.4.6 but there's a new 2.4.7 version. Updated on the packaging machine. So next version will pick it up.

**Comment by freddy77** [comment]
@fxcoudert new update, can you try from the website version 1.4.3 ? https://www.freetds.org/files/stable/freetds-1.4.3.tar.bz2

**Comment by freddy77** [comment]
Closing, after downloading and configuring:

```
 ./libtool --version
libtool (GNU libtool) 2.4.7
Written by Gordon Matzigkeit, 1996

Copyright (C) 2014 Free Software Foundation, Inc.
```
