### ISSUE TITLE
SQLDriverConnect cannot connect correctly under certain conditions

### ISSUE THREAD

**Issue by SakiTakamachi** [FreeTDS/freetds#504]
I cannot connect to the DB with a connection string like the following:
```
// my env
"Driver=FreeTDS;Server=mssql-server;Port=1433;Database=test;uid=test_user;pwd={p@ssw0rd}"
```

I can connect by adding a semicolon at the end:
```
"Driver=FreeTDS;Server=mssql-server;Port=1433;Database=test;uid=test_user;pwd={p@ssw0rd};"
```

This was originally a problem reported in php-src, but since there was no problem with SQL Server's ODBC and it occurred with FreeTDS, I am reporting it here.

Regards.

**Comment by freddy77** [comment]
Thanks. Which FreeTDS version are you using?

**Comment by freddy77** [comment]
Probably you are using version 1.3. The fix is already in 1.4, but it was released some days ago. I'll backport the fix to 1.3.

**Comment by SakiTakamachi** [comment]
Excuse me, I was eating dinner.

```
Version: freetds v1.1.6
```

Hmm. I installed it using apt-get a few days ago, but it seems to be quite old.
Thank you for your response.

**Comment by freddy77** [comment]
You can find version `1.3.21` or `1.4.2` at https://www.freetds.org/files/stable/.

**Comment by SakiTakamachi** [comment]
Thank you!
