### ISSUE TITLE
Is is possible to "configure" connection attributes under the hood in Python? (Specifically `ApplicationIntent`)

### ISSUE THREAD

**Issue by anguspmitchell** [FreeTDS/freetds#505]
I'm using PyMSSQL, and when I put `ApplicationIntent=ReadOnly` in the connection string, PyMSSQL throws an error saying it doesn't support that parameter. (More explanation here: https://github.com/pymssql/pymssql/issues/852)

However, I see that FreeTDS *does* support ApplicationIntent, according to this documentation - https://www.freetds.org/userguide/odbcconnattr.htm. 

So assuming that PyMSSQL doesn't allow for FreeTDS connection attributes to be arbitrarily configured, is there a way to circumvent PyMSSQL / SQLAlchemy and configure them in some other way under the hood?

**Comment by freddy77** [comment]
I would try to use a DSN and a `odbc.ini` DSN connection. You can put `ApplicationIntent` in `odbc.ini` and use a connection string like `DSN=my_dns_name;UID=my_username;PWD={my_password};`. See also https://www.freetds.org/userguide/odbcinionly.html

**Comment by anguspmitchell** [comment]
I haven't tried that. Have you ever wired that up with SQLAlchemy? I tried the typical SQLAlchemy string connection, and that did not work.

Also, I was under the impression that FreeTDS and ODBC were distinct from one another. But you're saying you can use ODBC with FreeTDS?

**Comment by freddy77** [comment]
FreeTDS is a project which provides 3 libraries to connect to SQL Server, CT-Library, DB-Library and ODBC driver. All of them use some code, called libTDS. `freetds.conf` is the configuration file for libTDS.

**Comment by freddy77** [comment]
@anguspmitchell, can I close the issue?

**Comment by anguspmitchell** [comment]
@freddy77 I haven't gotten this working, but yea, go ahead and close it
