### ISSUE TITLE
iodbctest fails on Redhat 8

### ISSUE THREAD

**Issue by aabrah25** [FreeTDS/freetds#506]
I am trying to connect to a remote MSSQL server from a Redhat (RHEL 8)  machine. I've set up freetds and iodbc (libiodbc-devel-3.52.13-1.el8.x86_64   ,   libiodbc-3.52.13-1.el8.x86_64)

I am  able to connect to the MSSQL server and run queries using tsql. No issues there.
But 'iodbctest "DSN=wbfreetds;UID=XX;PWD=XX" fails . I've attached the TDSDUMP file that iodbctest produces.

Here is what the output on the screen is when I run iodbctest:

[aabrah25@mrpzbsphdb01 ~]$ iodbctest "DSN=mssql;UID=XX;PWD=XX"
iODBC Demonstration program
This program shows an interactive SQL processor
Driver Manager: 03.52.1319.0723
1: SQLDriverConnect = ���������������������������������������� (20009) SQLSTATE=
2: SQLDriverConnect = ���������������������������������������� (20013) SQLSTATE=
3: SQLDriverConnect = ���������������������������������������� (0) SQLSTATE=
1: ODBC_Connect = ���������������������������������������� (20009) SQLSTATE=
2: ODBC_Connect = ���������������������������������������� (20013) SQLSTATE=
3: ODBC_Connect = ���������������������������������������� (0) SQLSTATE=

Have a nice day.

Can you help be identify why iodbctest fails. Thanks!
[freetds.log](https://github.com/FreeTDS/freetds/files/12836707/freetds.log)

**Comment by freddy77** [comment]
You could try using `TDSDUMPCONFIG` environment, see https://www.freetds.org/userguide/logging.html, it looks like you have configuration issues. The IP of the server to connect to is not found. Another issue could be that iODBC and unixODBC are different (having different ABIs) so if you installed FreeTDS from repository (like `dnf install freetds` or similar) you probably ended up with a wrong version compiled for unixODBC.

**Comment by aabrah25** [comment]
Hi @freddy77 
Thanks for the quick response. 
I have compiled freetds using the recommendation  from MYSQL WB (https://dev.mysql.com/doc/workbench/en/wb-migration-database-mssql-drivers-linux.html) . So I used their build_freetds.sh script, since this whole endeavor is to  finally use MySQL WB to migrate a DB from MSSQL to MySQL
The MySQL WB instructions say to install libiodbc-devel first and then compile freetds. I did that and the libiodbc-devel version that was installed was 3.52.13. Since that caused iodctest to fail, I uninstalled that and have installed a compiled version (3.52.16) now (this I did per the feedback from the iODBC folks, as I had logged a issue ticket with them and they recommended that I compile and install the latest  iODBC version).
The unixodbc versions installed are:
unixODBC-2.3.7-1.el8.x86_64
unixODBC-devel-2.3.7-1.el8.x86_64
These were installed using yum install, and not compiled.

I still  run  ' iodbctest "DSN=mssqldsn;UID=XX;PWD=XX;DATABASE=XX" '  and I get the same error as before.

The contents of my configuration files are as below:

/etc/odbc.ini:
------------------------
[ODBC Data Sources]
mssqldsn = MSSQL DSNN

[ODBC]
TraceFile = /tmp/sql.trace
Trace = 1

[mssqldsn]
Driver = /usr/local/lib/libtdsodbc.so
Host = 40.75.119.172
Port = 1433

/etc/odbcinst.ini
-------------------------
[ODBC Drivers]
freetds = TDS Driver

[freetds]
Description = v0.91 with protocol v7.4
Driver = /usr/local/lib/libtdsodbc.so

/usr/local/etc/freetds.conf
--------------------------------
#
# This file is installed by FreeTDS if no file by the same 
# name is found in the installation directory.  
#
# For information about the layout of this file and its settings, 
# see the freetds.conf manpage "man freetds.conf".  

# Global settings are overridden by those in a database
# server specific section
[global]
        # TDS protocol version
;       tds version = auto
        tds version = 7.4

        # Whether to write a TDSDUMP file for diagnostic purposes
        # (setting this to /tmp is insecure on a multi-user system)
        dump file = /tmp/freetds.log
        debug flags = 0xffff

        # Command and connection timeouts
;       timeout = 10
;       connect timeout = 10

        # To reduce data sent from server for BLOBs (like TEXT or
        # IMAGE) try setting 'text size' to a reasonable limit
;       text size = 64512

        # If you experience TLS handshake errors and are using openssl,
        # try adjusting the cipher list (don't surround in double or single quotes)
        # openssl ciphers = HIGH:!SSLv2:!aNULL:-DH

# A typical Sybase server
[egServer50]
        host = symachine.domain.com
        port = 5000
        tds version = 5.0

# A typical Microsoft server
[egServer73]
        host = ntmachine.domain.com
        port = 1433
        tds version = 7.3
[mssql]
        host = 40.75.119.172
        port = 1433
        tds version = 7.4
--------------------------------------------------------------

Attached files:
[freetds.log](https://github.com/FreeTDS/freetds/files/12848873/freetds.log)
[freetdsconfig.log](https://github.com/FreeTDS/freetds/files/12848874/freetdsconfig.log)
[freetds-error.log](https://github.com/FreeTDS/freetds/files/12848875/freetds-error.log)


When I run  'tsql -S mssql -U XX -P XX', I get the prompt and everything is good. The 2 attached file freetds.log(TDSDUMP is set to this file) and freetdsconfig.log(TDSDUMPCONFIG is set to this file) are from this run.

When I run 'iodbctest "DSN=mssqldsn;UID=XX;PWD=XX;DATABASE=XX"', it  generates only the freetds.log(attached with file name freetds-error.log). It does not generate the freetdsconfig.log

Any help would be much appreciated. Thanks!

**Comment by aabrah25** [comment]
Hi @freddy77 

This issue is resolved now. Per the iODBC folks, the iODBC DM uses UCS4 for Unicode String  which was causing the issue.
I had to put a new option DriverUnicodeType=UTF16 to switch iODBC DM to use UTF16  to interact via freetds odbc driver. 
I   put it in /etc/odbc.ini , right after "Driver =" line and the issue was resolved.
So my /etc/odbc.ini looks like this now:

[ODBC Data Sources]
mssqldsn = MSSQL DSNN

[ODBC]
TraceFile = /tmp/sql.trace
Trace = 1

[mssqldsn]
Driver = /usr/local/lib/libtdsodbc.so
DriverUnicodeType=UTF16
Server = 40.75.119.172
Port = 1433
TDS_Version = 7.4

Appreciate all the help. God bless

**Comment by freddy77** [comment]
I didn't know about the `DriverUnicodeType=UTF16` option, really nice. So you can use a driver with unixODBC ABI under iODBC with this option! You could also compile FreeTDS using iODBC ABI (so UCS-4) but I suppose it's easier to have a single driver.

Remember to disable tracing in production.
