### ISSUE TITLE
WSAEnumProtocols failed + Access Violation

### ISSUE THREAD

**Issue by marsupilami79** [FreeTDS/freetds#51]
In a test program the call to dbinit gives an access violation. Before this happens there is an error message printed saying:
tds_init_winsock: WSAEnumProtocols failed with 10055 (WSAENOBUFS: No buffer space available.)

The WSAEnumProtocols fails because on my PC windows wants to return 85 results and FreeTDS is only prepared for 64 results. According to the MS documentation WSAEnumProtocols will give the WSAENOBUFS error in this case.
I solved this problem for me with the attached patch. I had to rename it as a txt file for github. I can only assume that this mitigates the Access Violation. Unfortunately I don't have a chance to debug into this as I am not using C++ for my projects.

This is on WIN32, using the Branch-0_95 from 2016-01-28 compiled with cmake and Visual C++ 2013.
[mem.c-wsaenumprotocols.patch.txt](https://github.com/FreeTDS/freetds/files/124462/mem.c-wsaenumprotocols.patch.txt)

**Comment by freddy77** [comment]
I fixed calling WSAStartup just one. Both master and 0.95 branches
