### ISSUE TITLE
CMake build fails on Linux

### ISSUE THREAD

**Issue by warped-rudi** [FreeTDS/freetds#512]
With commit 1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a in place, CMake build on Linux fails due to missing 'sysconfdir.h'

**Comment by freddy77** [comment]
I think I know the commit you are speaking... but just to avoid mistakes, I think the hash you copied is wrong, it's a bit too long.

**Comment by warped-rudi** [comment]
You are right! I meant 4dc87b0800b67f3dbf4eddbdf35eab3bc133d2f7  "Remove the need for override of sysconfdir.h"

**Comment by freddy77** [comment]
@warped-rudi should be fixed in `master`. Can you try it?

**Comment by warped-rudi** [comment]
Yes, that solves the problem. However, your recent patch set introduced an unnecessary restriction on the version of CMake. This is caused by 2010478fb247fdcae878bac2ad4cf10c44a5dd07 . I suggest this minor change:

`diff --git a/CMakeLists.txt b/CMakeLists.txt
index 1ff486a..bd0cabd 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -507,6 +507,6 @@ set(FREETDS_CONF_FILES
 	${CMAKE_SOURCE_DIR}/locales.conf
 	${CMAKE_SOURCE_DIR}/src/pool/pool.conf)
 
-install(FILES ${FREETDS_PUBLIC_INCLUDE} TYPE INCLUDE)
+install(FILES ${FREETDS_PUBLIC_INCLUDE} DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})
 install(FILES ${FREETDS_PUBLIC_INCLUDE_2} DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/freetds)
 install(FILES ${FREETDS_CONF_FILES} DESTINATION ${CMAKE_INSTALL_FULL_SYSCONFDIR})`

**Comment by freddy77** [comment]
It sounds good. Why it introduced a restriction on CMake version ?

**Comment by warped-rudi** [comment]
The 'TYPE ...' clause was introduced with CMake 3.14. Prior versions only support 'DESTINATION'. Also I think not using 'TYPE' here is more consistent with the two following lines.

**Comment by freddy77** [comment]
Done, updated `master`.
