### ISSUE TITLE
tdspool reconnect to sql server

### ISSUE THREAD

**Issue by vstaf** [FreeTDS/freetds#52]
Hello all!
Tdspool don't reconnect to sql server if disconnect appear (for example, after sql server restart), only write to console "Uh oh! member disconnected" and continue running without any actions. Could someone add reconnect feature (every 10-30-etc seconds) or add trying to reconnect when first client send queries via pool?

**Comment by freddy77** [comment]
Actually tdspool should open another connection on next client connection.
Is this not happening?

**Comment by vstaf** [comment]
Hello @freddy77 !)
I made another test few minutes ago and yes, tdspool open another connection (but only one, instead of "min pool conn" setting) and write to console "No open connections left, opening new member". Don't know why i got this issue yesterday, sorry. continue testing >.<
