### ISSUE TITLE
Mising some basic SQLServer data types: NCHAR/XML/geography/geometry/UUID

### ISSUE THREAD

**Issue by taozuhong** [FreeTDS/freetds#520]
Mising some basic SQLServer data types: 
1. NCHAR
2. XML
3. geography
4. geometry
5. uniqueidentifier

These are foundational types, could identify them in TDS?

**Comment by freddy77** [comment]
They are supported. What do you find missing? Keep in mind that some old, not vendor supported libraries use to convert these types to library supported types. Like DB-Library for instance.

Not sure about CLR types (like geography and geometry).

**Comment by taozuhong** [comment]
sybdb.h Line 155:
https://github.com/FreeTDS/freetds/blob/master/include/sybdb.h

**Comment by freddy77** [comment]
Now that I remember potentially you can call `dbcolinfo` function passing a `DBCOL2` having field `ServerType` correctly filled with some types not defined as mnemonics.
