### ISSUE TITLE
Failure to connect to sql server 2008 with ssl version.

### ISSUE THREAD

**Issue by chenall** [FreeTDS/freetds#532]
2008 fail
[tdsdump-2008.log](https://github.com/FreeTDS/freetds/files/14544666/tdsdump-2008.log)

2012 ok
[tdsdump-2012.log](https://github.com/FreeTDS/freetds/files/14544667/tdsdump-2012.log)

**Comment by chenall** [comment]
dumps using wireshark to grab the same server using osql and osql connections

[wireshark-dump.zip](https://github.com/FreeTDS/freetds/files/14545720/wireshark-dump.zip)

**Comment by freddy77** [comment]
Usually TLS handshake failure means the server is not supporting recent enough settings. In this case the server seems to try using TLS 1.1.

**Comment by chenall** [comment]
I tried installing KB4057113 to support TLS 1.2

Works properly on Windows 10 with sqlserver 2008 r2
Failed on Windows 7 with sqlserver 2008 r2.

Is there any other way to solve this problem?
I'm currently  disable encrypted for SQL 2008.

**Comment by taozuhong** [comment]
This is my configuration at `%AppData%\.freetds.conf`, it can connect with SQL Server 2008 with port 1455
```
[global]
  # TDS protocol version
  tds version = auto
  enable tls v1 = true

  # Whether to write a TDSDUMP file for diagnostic purposes
  # (setting this to /tmp is insecure on a multi-user system)
  dump file = /tmp/freetds.log
  debug flags = 0xffff

  # Command and connection timeouts
  ; timeout = 10
  ; connect timeout = 10
  
  # To reduce data sent from server for BLOBs (like TEXT or
  # IMAGE) try setting 'text size' to a reasonable limit
  ; text size = 64512

  # If you experience TLS handshake errors and are using openssl,
  # try adjusting the cipher list (don't surround in double or single quotes)
  # openssl ciphers = HIGH:!SSLv2:!aNULL:-DH

[sql2008]
  host = localhost
  port = 1455
  tds version = 7.0
```

**Comment by chenall** [comment]
@taozuhong tds 7.0 does not use SSL.

`enable tls v1` I've tried it doesn't work.

Looks similar to #299.
