### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by ryandesign** [FreeTDS/freetds#542]
Running the test suite on macOS 12 failed for me:

```
FAIL: t0001
FAIL: t0002
FAIL: t0003
FAIL: t0004
FAIL: t0005
FAIL: t0006
PASS: t0007
PASS: t0008
FAIL: dynamic1
PASS: convert
FAIL: dataread
FAIL: utf8_1
FAIL: utf8_2
FAIL: utf8_3
PASS: numeric
PASS: iconv_fread
FAIL: toodynamic
PASS: readconf
PASS: charconv
FAIL: nulls
FAIL: corrupt
PASS: declarations
PASS: portconf
PASS: parsing
PASS: freeze
PASS: strftime
PASS: log_elision
PASS: convert_bounds
============================================================================
Testsuite summary for FreeTDS 1.4.11
============================================================================
# TOTAL: 28
# PASS:  14
# SKIP:  0
# XFAIL: 0
# FAIL:  14
# XPASS: 0
# ERROR: 0
============================================================================
See src/tds/unittests/test-suite.log
============================================================================
```

I have not run the tests before so I don't know how long these have been failing.

[test-suite.log](https://github.com/FreeTDS/freetds/files/14817919/test-suite.log)

**Comment by freddy77** [comment]
See https://www.freetds.org/userguide/ConfirmInstall.html#Tests, you need a database.

**Comment by ryandesign** [comment]
I don't have a database. I guess then I can't verify whether or not freetds has been compiled correctly.

**Comment by freddy77** [comment]
You need a server to run the tests. See https://www.freetds.org/userguide/ConfirmInstall.html#Tests. It's not hard to setup a docker image https://hub.docker.com/_/microsoft-mssql-server/.
