### ISSUE TITLE
FreeTDS 1.4.12: Undefined symbols: dbsetlshort on linux and macOS 

### ISSUE THREAD

**Issue by taozuhong** [FreeTDS/freetds#547]
FreeTDS 1.4.12
macOS: 13.5 (22G74)
CC: Apple clang version 14.0.3
Vala: 0.56.16

Found that the api dbsetlshort not yet exported, pls see the screenshot:

```
.......
ArchLinux:
/usr/sbin/ld: Providers/libproviders.so.p/meson-generated_Supports_SQLServer_provider.c.o: in function `kangaroo_providers_supports_sql_server_provider_real_open':
provider.c:(.text+0x1b5d): undefined reference to `dbsetlshort'
collect2: error: ld returned 1 exit status

macOS:
... /usr/local/opt/libpq/lib/libpq.dylib /usr/local/Cellar/freetds/1.4.12/lib/libsybdb.dylib ...
Undefined symbols for architecture x86_64:
  "_dbsetlshort", referenced from:
      _dbset_port in meson-generated_Supports_SQLServer_provider.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
![image](https://github.com/FreeTDS/freetds/assets/13451009/193e9924-0b8b-4785-9338-286ae064dd26)

![image](https://github.com/FreeTDS/freetds/assets/13451009/9277b397-0ff5-4063-9e35-37974582a3b6)

![image](https://github.com/FreeTDS/freetds/assets/13451009/90e2d74a-ae0e-4ddd-b75b-403109088f04)

**Comment by freddy77** [comment]
The change is in `master`

**Comment by taozuhong** [comment]
The issue is caused by the official package with freetds 1.4.12, I didn't get your mean.
