### ISSUE TITLE
Type '12' not allowed before login when connecting to sybase

### ISSUE THREAD

**Issue by dimon00** [FreeTDS/freetds#55]
Every time I open a connection with a sybase I get these lines in the sybase log:
00:0009:00000:00260:2016/03/04 11:53:00.94 server  Error: 1621, Severity: 18, State: 1
00:0009:00000:00260:2016/03/04 11:53:00.94 server  Type '12' not allowed before login.
00:0009:00000:00352:2016/03/04 11:53:00.95 server  Error: 1621, Severity: 18, State: 1
00:0009:00000:00352:2016/03/04 11:53:00.95 server  Type '12' not allowed before login.
00:0009:00000:00440:2016/03/04 11:53:00.95 server  Error: 1621, Severity: 18, State: 1
00:0009:00000:00440:2016/03/04 11:53:00.95 server  Type '12' not allowed before login.
00:0009:00000:00312:2016/03/04 11:53:00.96 server  Error: 1621, Severity: 18, State: 1
00:0009:00000:00312:2016/03/04 11:53:00.96 server  Type '10' not allowed before login.

I tested against several version (last freetds-dev.0.99.633).
The odbc setting include:
[tabdp]
Driver = SybaseASE
Server = 10.10.xx.xx
Port = 4901
Database = BDP
uid = sapsa
encryption = request

client side I don't get any error and I can query the db correctly.

**Comment by freddy77** [comment]
If you don't set the protocol to 5.0 (Sybase one) FreeTDS will try different versions including Microsoft one which will trigger these issues. Please check version you set and provide a TDSDUMP.

**Comment by dimon00** [comment]
I tried to specify:
TDS Version = 5.0
in the odbc.ini but it doesn't solve the problem.
[freetds.zip](https://github.com/FreeTDS/freetds/files/158648/freetds.zip)

**Comment by freddy77** [comment]
Surely, "TDS Version" is not supported, see http://www.freetds.org/userguide/odbcconnattr.htm. Please also enable the log and check at the top which protocol is used.

**Comment by dimon00** [comment]
Using:
TDS_Version = 5.0
solved the problem.
Clearly not a bug.

Grazie!

**Comment by freddy77** [comment]
Closing, see previous comment.
