### ISSUE TITLE
Request regarding LGPL & GPL

### ISSUE THREAD

**Issue by kowsikbabu** [FreeTDS/freetds#553]
While we understand the usage of GPL for binaries, 3 of the utility files listed below that are required for tdsODBC library have GPL text inside them. 

Can this text be removed from the files or changed to have LGPL, so we don't have conflicting licenses?

This is affecting our ability to use freeTDS. Appreciate any help regarding this request.

Dependency files:
- include/freetds/utils/dlist.tmpl.h
- include/freetds/utils/dlist.h
- src/utils/dlist.c

**Comment by freddy77** [comment]
I think I'm the only owner of these file. Yes, I can change them, no problems or arguments.

**Comment by kowsikbabu** [comment]
Sorry, please update:
include/freetds/utils/smp.h 
src/utils/smp.c

**Comment by freddy77** [comment]
Relaunched tests added these last. Not that I expect issues, changes are only code comments.

**Comment by kowsikbabu** [comment]
Understood, we can wait for the tests to complete.

**Comment by kowsikbabu** [comment]
Thanks for the quick resolution @freddy77 

I'm closing this issue now.

In case you would like to know other files that had this same mismatch (but not used for tdsODBC), they are:

- src/pool/util.c
- src/pool/user.c
- src/pool/stream.c
- src/pool/pool.h
- src/pool/member.c
- src/pool/main.c
- src/pool/config.c
- src/apps/fisql/terminal.h
- src/apps/fisql/terminal.c
- src/apps/fisql/interrupt.h
- src/apps/fisql/interrupt.c
- src/apps/fisql/handlers.h
- src/apps/fisql/handlers.c
- src/apps/fisql/handlers.c
- src/apps/fisql/fisql.c
- src/apps/fisql/edit.h
- src/apps/fisql/edit.c
- src/apps/defncopy.c

**Comment by freddy77** [comment]
It's fine for application files to be GPL (and expected).
