### ISSUE TITLE
Legacy numeric/decimal type support using Sybase ASE

### ISSUE THREAD

**Issue by marzolfb** [FreeTDS/freetds#56]
Quick question: Does FreeTDS support the legacy decimal type of 55 (0x37)?

Background:
As I was using [gofreetds](https://github.com/minus5/gofreetds) in a go app I was working with, I came across this error:

> Msg 20018, Level 12
> General SQL Server error: Check messages from the SQL Server
> 
> 
> Msg 7738, Level 12, State 2
> Server 'SYBASE', Line 2
> Message empty.

I noticed I would get this error in the Sybase ASE 16 database I was working with on some stored procedures and not others. It turns out the ones experiencing the error above had decimal/numeric input and/or output parameters.

After googling some, it became apparent that this type is regarded as a “legacy” type at least from TDS 7+’s standpoint and that 106 (0x6A) is the newer decimal type id value. You can see evidence of this on Microsoft/MSDN’s site where they provide the TDS7 specification. Specifically, on [this page](https://msdn.microsoft.com/en-us/library/dd358341.aspx) you see this:

```
 DECIMALTYPE         =   %x37  ; Decimal (legacy support)
 NUMERICTYPE         =   %x3F  ; Numeric (legacy support)
 BITNTYPE            =   %x68  ; (see below)
 DECIMALNTYPE        =   %x6A  ; Decimal
 NUMERICNTYPE        =   %x6C  ; Numeric
```

And then also wireshark has a TDS decoder plugin and if you look at [their github source](https://github.com/boundary/wireshark/blob/master/epan/dissectors/packet-tds.c) you see this:

```
#define TDS_DATA_TYPE_DECIMAL         0x37  /* Decimal (legacy support) */
#define TDS_DATA_TYPE_NUMERIC         0x3F  /* Numeric (legacy support) */
#define TDS_DATA_TYPE_BITN            0x68
#define TDS_DATA_TYPE_DECIMALN        0x6A  /* Decimal */
#define TDS_DATA_TYPE_NUMERICN        0x6C  /* Numeric */
```

However, when I look at the [FreeTDS TDS Protocol Documentation page](http://www.freetds.org/tds.html), in the Types section, I don't see any references to the legacy types. 

Also, in [sybdb.h](https://github.com/FreeTDS/freetds/blob/e61451418991b80df153ea150a3ee0f8093ce9ee/include/sybdb.h), I don't see a reference to the legacy numeric/decimal datatypes either.

**Comment by freddy77** [comment]
2016-03-24 20:04 GMT+00:00 Bret Marzolf <notifications@github.com>:

> Quick question: Does FreeTDS support the legacy decimal type of 55 (0x37)?
>

No, but it's almost 10 years both vendors do not use these types... I don't
even know the format.

> Background:
> As I was using gofreetds <https://github.com/minus5/gofreetds> in a go
> app I was working with, I came across this error:
>
> Msg 20018, Level 12
> General SQL Server error: Check messages from the SQL Server
>
> Msg 7738, Level 12, State 2
> Server 'SYBASE', Line 2
> Message empty.
>
> I noticed I would get this error in the Sybase ASE 16 database I was
> working with on some stored procedures and not others. It turns out the
> ones experiencing the error above had decimal/numeric input and/or output
> parameters.
>

Are you using 5.0 as protocol ? Can you post some dumps ?

> After googling some, it became apparent that this type is regarded as a
> “legacy” type at least from TDS 7+’s standpoint and that 106 (0x6A) is the
> newer decimal type id value. You can see evidence of this on
> Microsoft/MSDN’s site where they provide the TDS7 specification.
> Specifically, on this page
> <https://msdn.microsoft.com/en-us/library/dd358341.aspx> you see this:
>
>  DECIMALTYPE         =   %x37  ; Decimal (legacy support)
>  NUMERICTYPE         =   %x3F  ; Numeric (legacy support)
>  BITNTYPE            =   %x68  ; (see below)
>  DECIMALNTYPE        =   %x6A  ; Decimal
>  NUMERICNTYPE        =   %x6C  ; Numeric
>
> And then also wireshark has a TDS decoder plugin and if you look at their
> github source
> <https://github.com/boundary/wireshark/blob/master/epan/dissectors/packet-tds.c>
> you see this:
>
> #define TDS_DATA_TYPE_DECIMAL         0x37  /* Decimal (legacy support) */
> #define TDS_DATA_TYPE_NUMERIC         0x3F  /* Numeric (legacy support) */
> #define TDS_DATA_TYPE_BITN            0x68
> #define TDS_DATA_TYPE_DECIMALN        0x6A  /* Decimal */
> #define TDS_DATA_TYPE_NUMERICN        0x6C  /* Numeric */
>
> However, when I look at the FreeTDS TDS Protocol Documentation page
> <http://www.freetds.org/tds.html>, in the Types section, I don't see any
> references to the legacy types.
>
> Also, in sybdb.h
> <https://github.com/FreeTDS/freetds/blob/e61451418991b80df153ea150a3ee0f8093ce9ee/include/sybdb.h>,
> I don't see a reference to the legacy numeric/decimal datatypes either.
>
>
> Frediano

**Comment by marzolfb** [comment]
Thanks. Your response was helpful. My problem clearly lies somewhere outside FreeTDS. I was using 5.0 as the protocol version. When I turned tracing on, ran tsql, created a simple proc with a decimal output parameter and then executed it, I did indeed see the correct type value (106).
