### ISSUE TITLE
Moving DBMAXNAME to dblib.h broke sybperl

### ISSUE THREAD

**Issue by sthen** [FreeTDS/freetds#57]
a19a535e80 increased the size of DBMAXNAME to 128, but also moves it from sybdb.h to dblib.h (which is in noinst_HEADERS so doesn't get installed). Noticed because it broke OS packaging of sybperl. It's easy enough to workaround in sybperl, but should this move back?

**Comment by freddy77** [comment]
Moved back (with new value)
