### ISSUE TITLE
bsqldb throws an error if the "go" command does not start in the first column

### ISSUE THREAD

**Issue by smoyertech** [FreeTDS/freetds#58]
We have a deployment tool that uses bsqldb to run sql scripts to import data into SQL Server databases.

The issue is that some teams use SQL Developer to test their scripts and SQL Developer is ok with leading white spaces before the “go” command, but bsqldb is not ok so the deployment throws an error. 

Below is a snippet containing the fix I made locally to the next_query() func in bsqldb.c: 
(I just don't know how to incorporate this fix into your system)

    while (fgets(query_line, sizeof(query_line), stdin)) {
        /* 'go' or 'GO' separates command batches */
        const char *p = query_line;

        while(isspace((unsigned char) *p)) p++;  /* Skip past leading white spaces */

        if (strncasecmp(p, "go", 2) == 0) {
            for (p+=2; isspace((unsigned char) *p); p++) {
                if (*p == '\n')
                    return 1;
            }
        }

        fprintf(options.verbose, "\t%s", query_line);
		
        /* Add the query line to the command to be sent to the server */
        erc = dbcmd(dbproc, query_line);
        if (erc == FAIL) {
            fprintf(stderr, "%s:%d: dbcmd() failed\n", options.appname, __LINE__);
            return -1;
        }
    }

**Comment by smoyertech** [comment]
FYI, here is the error it throws:

Msg 102, Level 15, State 1
Server 'RICH-MSQL-19-RV\SQL2008R2', Line 6
        Incorrect syntax near 'GO'.
bsqldb: error: severity 15 > 10, exiting

**Comment by freddy77** [comment]
I actually don't consider this a problem.

**Comment by smoyertech** [comment]
I understand. Their argument is that the same script (with a space before the 'go') works when run via SQL Developer but fails when run via bsqldb. The workflow is that they use SQL developer to test their scripts, then they release their scripts, and then later the deployment tool (which uses bsqlsb) fails on the same script that passed their tests (because they tested using SQL Developer).

**Comment by freddy77** [comment]
Why don't you add an option to bsqldb?
So you will use the option while other user for compatibility won't.
You could even add an environment option.

**Comment by smoyertech** [comment]
Not sure it needs that much overhead. 
I see my flaw and added a "query_start" pointer to pass to dbcmd(). This should be safe ...

while (fgets(query_line, sizeof(query_line), stdin)) {
    /* 'go' or 'GO' separates command batches */
    const char *p = query_line;
    const char *query_start = query_line;

    while(isspace((unsigned char) *p)) p++;  /* Skip past leading white spaces */
    query_start = p;

    if (strncasecmp(p, "go", 2) == 0) {
        for (p+=2; isspace((unsigned char) *p); p++) {
            if (*p == '\n')
                return 1;
        }
    }

    fprintf(options.verbose, "\t%s", query_start);

    /* Add the query line to the command to be sent to the server */
    erc = dbcmd(dbproc, query_start;
    if (erc == FAIL) {
        fprintf(stderr, "%s:%d: dbcmd() failed\n", options.appname, __LINE__);
        return -1;
    }
}

**Comment by smoyertech** [comment]
Didn't mean to close this.

**Comment by freddy77** [comment]
I decided to apply it.
