### ISSUE TITLE
Question about odbc_mismatch

### ISSUE THREAD

**Issue by vstaf** [FreeTDS/freetds#60]
Hello @freddy77 !
Could you please explain what is "odbc_mismatch" in user.c?

Fragment of code:

> /* swicth to dblib options */
> if (odbc_mismatch)
> strcat(str, "SET ANSI_DEFAULTS OFF\nSET CONCAT_NULL_YIELDS_NULL OFF\n");

These options break results of our SPs. I understood that we can change this options after connect / or modife source code. Is this options need to be OFF in current version of freetds by default?

**Comment by freddy77** [comment]
In the connection packet there is a flag that say if connection has ODBC attributes or not.
The login to the server from the pool process is done with the ODBC flag ON always.
Mismatch means that you specified a no-ODBC (DB-Library probably) connection.

**Comment by vstaf** [comment]
Thank you!
