### ISSUE TITLE
the pseudo-functions YEAR MONTH and DAY are missing

### ISSUE THREAD

**Issue by freakout42** [FreeTDS/freetds#602]
`select {fn LCASE(ename)} from emps;` works fine but
`select {fn DAY(hiredate)} from emps;` gives `[ISQL]ERROR: Could not SQLExecute`
and `[42000][FreeTDS][SQL Server]Statement(s) could not be prepared.`
Same with MONTH and YEAR. It would be nice if these were working too.
Thanks for FreeTDS.

**Comment by freddy77** [comment]
As far as I know MSSQL should support ODBC syntax directly. Did you try `DAYOFMONTH` instead of `DAY` ?

**Comment by freakout42** [comment]
Yes but i want to build a database independent application ( https://formax.freakout.de/ ) therefore the use of the pseudo-functions and the usage of ODBC.

**Comment by freddy77** [comment]
The reason why MSSQL does not translate the string is that the server directly should support it... at least in theory. If not, well, then we need to add support for it in FreeTDS. BTW, the ODBC pseudo function for day of the month is `DAYOFMONTH`, not `DAY`, that's the reason `select {fn DAY(hiredate)} from emps;` preparation fails.

**Comment by freakout42** [comment]
DAYOFMONTH works - thank you

**Comment by freddy77** [comment]
See also https://learn.microsoft.com/en-us/sql/odbc/reference/appendixes/appendix-e-scalar-functions?view=sql-server-ver16.
