### ISSUE TITLE
Connection to MSSQL2008 server failes due to incorrect encryption negotiation

### ISSUE THREAD

**Issue by warped-rudi** [FreeTDS/freetds#605]
```14:38:56.349 10408 (packet.c:406):Received packet
0000 04 01 00 2b 00 00 01 00-00 00 1a 00 06 01 00 20 |...+.... ....... |
0010 00 01 02 00 21 00 01 03-00 22 00 00 04 00 22 00 |....!... ."....".|
0020 01 ff 0a 00 06 40 00 00-00 00 00                |.....@.. ...|

14:38:56.349 10408 (login.c:1444):detected crypt flag 0
```
The code in 'tds71_do_login()' does not handle the case that the server returns encrypt_flag=0 (TDS7_ENCRYPT_OFF). Therefore it enables encryption even though it's not supported.

**Comment by warped-rudi** [comment]
My initial analysis was bad. The problem was caused by the fact, that this particular server instance required to set "enable tls v1 = yes",

**Comment by warped-rudi** [comment]
Thinking a bit more about the issue, the behavior of the code is not ideal. Because even though TLS is not to be used at all, the connection fails because the server side supports TLS v1 only. 

```
19:07:20.464 28144 (tls.c:147):in tds_push_func_login
19:07:20.464 28144 (tls.c:1039):handshake failed with -1 12293 1
19:07:20.464 28144 (tls.c:1083):handshake failed
19:07:20.464 28144 (login.c:644):login packet rejected
19:07:20.464 28144 (query.c:3804):tds_disconnect() 
```

If encryption is set to 'default', the library should retry to connect without TLS in this situation.

**Comment by freddy77** [comment]
No, you cannot go beyond some base limit, otherwise you allow downgrade attacks.

**Comment by warped-rudi** [comment]
So for the time being I have 2 options: 

1. ship a config file that either enables tls v1 or disables encryption
2. disable TLS support completely in my private builds of the library (used on Windows and Android)

I will probably go with 2.) because none of my clients uses encryption for their server connections (all on Intranet) and it also removes the need to ship copies of the OpenSSL libs.

**Comment by freddy77** [comment]
You can set `encryption` to `off`. Which does not mean the same as `TDS7_ENCRYPT_OFF`! (yes, confusing, `TDS7_ENCRYPT_OFF` is a protocol definition).
See https://www.freetds.org/userguide/freetdsconf.html (`encryption`) and also https://www.freetds.org/userguide/OdbcConnAttr.html (for ODBC).
Yes, compiling without TLS works too but the settings would possibly make the connection more "portable" (same script will work even if TLS is enabled).
