### ISSUE TITLE
libtds not deployed

### ISSUE THREAD

**Issue by arbinada-com** [FreeTDS/freetds#616]
Hello,
as one can see the `libtds` and the `include/freetds` headers are not installed when deploying the `freetds` package from git sources or from Ubuntu repositories (`apt install freetds-*`)
What is the right way to deploy the `libtds` with a required portion of headers? 
The purpose is to use TDS directly as `tsql` does without db-library overhead.
Thanks

**Comment by freddy77** [comment]
Yes, it's wanted. libTDS has not ABI/API compatibility. It's an internal library used to share common code between DB-Library, CT-Library and ODBC driver. I suppose the easier way is to use something like git modules.

**Comment by arbinada-com** [comment]
Is it possible to know the list of "public" headers for `libtds` at least? This will allow to deploy it manually

**Comment by freddy77** [comment]
Usually public headers are the headers installed. So the reply is none.
Probably what you want to ask instead is: "Given that `libtds` is an internal library, which headers should I use?".
The internal headers are in `include/freetds`, quite a lot of them are to deal with compatibilities. Surely the main one for `libtds` is `tds.h`. `replacements` are definition replacing functions. `utils` generic utilities, shared code not related strictly to tds protocol. Most headers in `include` but not in `include/freetds` are public headers.
