### ISSUE TITLE
LC_MONETARY / money format in freetds

### ISSUE THREAD

**Issue by vstaf** [FreeTDS/freetds#63]
Hello @freddy77 !
Could you explain me some information about using system locale LC_MONETARY setting by freetds / tdspool?
We faced with issue that tdspool do not use correct money format stored in system locale setting. We want to use ru_RU.utf8 locale and russian money format, i try to set this locale at the system / added new section locales.conf / etc but it didn't help - money format is wrong. Any ways to change this setting in freetds / tdspool or we need to use specific format functions on php side?

Thank you in advance!

**Comment by freddy77** [comment]
Hi,
  tdspool just cache connection, all data came unchanged from server so it does not change using tdspool or connecting directly.
Unfortunately LC_MONETARY information are not used at all so would be better (for the times being) to fix in the PHP side.

**Comment by vstaf** [comment]
Ok, i see, thank you!
