### ISSUE TITLE
Build guide incorrect or incomplete

### ISSUE THREAD

**Issue by Treverix** [FreeTDS/freetds#65]
I've tried to build FreeTDS on centos for a docker image following the latest documentation here. I should execute `./configure` which isn't included the repository.

`autoconf` reports a couple of errors (possibly undefined macros) and the generated `configure` script fails with a syntax error:

    [freetds-R1_00RC5]# ./configure
    ./configure: line 2528: syntax error near unexpected token `dist-bzip2'
    ./configure: line 2528: `AM_INIT_AUTOMAKE(dist-bzip2 parallel-tests subdir-objects)'

**Comment by freddy77** [comment]
2016-05-13 10:51 GMT+01:00 Andreas Dolk <notifications@github.com>:

> I've tried to build FreeTDS on centos for a docker image following the
> latest documentation here. I should execute ./configure which isn't
> included the repository.
>
> autoconf reports a couple of errors (possibly undefined macros) and the
> generated configure script fails with a syntax error:
>
> [freetds-R1_00RC5]# ./configure
> ./configure: line 2528: syntax error near unexpected token `dist-bzip2'
> ./configure: line 2528: `AM_INIT_AUTOMAKE(dist-bzip2 parallel-tests subdir-objects)'
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeTDS/freetds/issues/65>
>
That's weird!

Anyway, I forgot in the server I had to redirect libtoolize to a new
version and I was using a different
libtoolize version. I packaged again RC5.

Are you actually sure you didn't run with an old autoconf ?

Did you use a tarball or git ? Maybe we require a more recent version of
autoconf.

Frediano

**Comment by jgujgu** [comment]
`INSTALL.GIT` has the correct instructions.

**Comment by freddy77** [comment]
Updated INSTALL pointing to our Users Guide.
