### ISSUE TITLE
FreeTDS apt-get package

### ISSUE THREAD

**Issue by jgujgu** [FreeTDS/freetds#66]
Hello,

I really appreciate all the work that's gone into FreeTDS over the years. I've been able to successfully use it when developing on OS X, but it seems that the packages on Debian apt-get is rather old (hoping to pull it into a docker container):
https://packages.debian.org/search?keywords=freetds&searchon=names&suite=stable&section=all
```
Package freetds-bin
jessie (stable) (database): FreeTDS command-line utilities 
0.91-6+b1: amd64 armel armhf i386 mips mipsel powerpc s390x 
0.91-6: arm64 ppc64el
Package freetds-common
jessie (stable) (libs): configuration files for FreeTDS SQL client libraries 
0.91-6: all
Package freetds-dev
jessie (stable) (devel): MS SQL and Sybase client library (static libs and headers) 
0.91-6+b1: amd64 armel armhf i386 mips mipsel powerpc s390x 
0.91-6: arm64 ppc64el
Package libdbd-freetds
jessie (stable) (libs): Freetds database server driver for libdbi 
0.9.0-3: amd64 arm64 armel armhf i386 mips mipsel powerpc ppc64el s390x
```
I understand that maintaining the code is different from updating it in the numerous package managers that exist, but I was hoping that one of the current maintainers might find it helpful (and, hopefully, not especially painful) to update these to the current stable release. I would consider doing it but I would almost certainly muck it up. Homebrew has `0.95.95`, and there is likely communal utility in having it on apt-get as well.

-Jeffrey

**Comment by freddy77** [comment]
Just released 1.0!

Unfortunately for official Debian packages you should open a bug to Debian.

Thanks.
