### ISSUE TITLE
Missing odbc_export.h & tds_willconvert.h

### ISSUE THREAD

**Issue by philoroussel** [FreeTDS/freetds#72]
Hello 
I'm on Windows 8.1 64 bits I tried to build FreeTDS using CMake
and actually it seems these two files tds_willconvert.h and odbc_export.h are missing.
There is #include "tds_willconvert.h" in src\tds\convert.c line 3053
There is #include "odbc_export.h" in src\odbc\odbc.c line 7509
I cloned the repository yesterday using Sourcetree and cannot find these files...
Thank you in advance for your help
Philippe Roussel

**Comment by philoroussel** [comment]
Ahhhh OK seems these files are produced by Perl

**Comment by freddy77** [comment]
Yes. If you don't want to install Perl you can download the snapshot from www.freetds.org and copy from them. There files are not changing that often.
