### ISSUE TITLE
Can not find ./configure

### ISSUE THREAD

**Issue by and-hom** [FreeTDS/freetds#75]
I've read INSTALL. To build I have to run ./configure
But I can't find "configure" executable in the repository:
```
$ git clone https://github.com/FreeTDS/freetds.git
$ cd freetds
$ find . -name configure
$ git branch
* master
```
What should I do to build the application?

**Comment by irmowan** [comment]
Download the release version

**Comment by freddy77** [comment]
configure script is generated using configure.ac so it is not in the git repository.
You can download snapshot which already contains autogenerated files.

**Comment by and-hom** [comment]
It would be great to mention it in the INSTALL file

**Comment by freddy77** [comment]
I put a note on master INSTALL file
