### ISSUE TITLE
implement support in ctlib for CS_TIMEOUT and CS_LOGIN_TIMEOUT

### ISSUE THREAD

**Issue by davidnich** [FreeTDS/freetds#77]
currently ctlib applications will get an indefinite timeout when trying to reconnect to a server after a lost connection.  This is correct according to the SAP/Sybase docs: http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc32840.1550/html/ctref/X69451.htm

however [ct_con_props()](http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.help.sdk_12.5.1.ctref/html/ctref/X57953.htm) does not support `CS_TIMEOUT` or `CS_LOGIN_TIMEOUT` which are needed to allow users to control these timeouts.

Timeouts are implemented in the freetds tds layer, but not controllable using `ct_con_props()` - this issue is for implementing support for this in ctlib (patch in progress).

**Comment by freddy77** [comment]
Merged your patch. Thanks.
