### ISSUE TITLE
Using latest version of FreeTDS, I am getting  Error 20020 (severity 9), when the older versions work just fine

### ISSUE THREAD

**Issue by vijay-koppala** [FreeTDS/freetds#79]
Platform: openSUSE Leap 42.1 (x86_64)
FreeTDS version: freetds v1.00.9
Connecting to: Microsoft SQL Server 2012 - 11.0.5058.0 (X64)
versions Tried couple of different versions <= 0.95.95 and  1.00.9

I am trying tsql to connect to a MS SQL Server to retrieve some data. When I try with version <= 0.95.95 it is working fine. But with the latest version 1.00.9, I am getting an error.

```
tsql -H xxxxxxx -U xxxxxxxxxxxxx -p 1433
[TinyTds][v1.0.5][tsql]: /usr/local/bin/tsql
Password: 
locale is "en_US.UTF-8"
locale charset is "UTF-8"
using default charset "UTF-8"

2> USE yyyyyyyyyy
3> GO
1> Select C.CustomerID, ISNULL(C.TreeRepCode, P.RepCode) RepCode, P.FirstName, P.LastName, P.Headline, P.PhoneNumber, 
2>       P.Email, P.Occupation, P.Interest, P.Education, P.Story, P.Why, P.Gender, P.Relationship, P.Location, P.Hometown, 
3>       P.ModDate, P.Private, P.CompanyName, P.Birthday, P.MobileDisplay, VCM.WebPath AvatarPath, VCM.Name AvatarName,
4>       CWS.Twitter, CWS.Facebook, CWS.LinkedIn, CWS.YouTube, CWS.GooglePlus
5>       from .....BUNCH OF JOINS...... OFFSET 0 ROWS FETCH NEXT 2000 ROWS ONLY
6> GO

############################ After printing some rows, it prints
Error 2401 (severity 4):
        Character set conversion is not available between client character set '%.*s' and server character set '%.*s'
(1168 rows affected)
Error 20020 (severity 9):
        Bad token from the server: Datastream processing out of sync
```

The above tsql errors match with freetds log errors

```
stream.c:125:Error: tds_convert_stream: tds_iconv returned errno 22, conv_errno 22
stream.c:129:Error: tds_convert_stream: Gave up converting 2 bytes due to error 22.
stream.c:132:Troublesome bytes:
0000 3a df                  -                        |:.|

stream.c:125:Error: tds_convert_stream: tds_iconv returned errno 22, conv_errno 22
stream.c:129:Error: tds_convert_stream: Gave up converting 2 bytes due to error 22.
stream.c:132:Troublesome bytes:
0000 3a df                  -                        |:.|

util.c:322:tdserror(0x16586a50, 0x15a96080, 2401, 0)
dblib.c:7949:dbperror(0x1f78aca0, 2401, 0)
```

The row tsql is failing at, has the following in the columns. column-headers are between  two *s, the column value are underneath it. The freetds.log said, it failed on **interest** column. It has `things&#55356;�` at the end (that could be a cause of concern)

```
*Occupation*
Registered Medical Assistant

*Interest*
I love to sew, read, work on my creative memory books, cook, bake, play casino games on my iPad , play bingo , work on crafts and many many other things&#55356;�

*Education*
Trade School
```

The column **interest** has the following metadata logged in freetds.log in the beginning

```
token.c:1507:tds7_get_data_info: 
        colname = Interest
        type = 39 (varchar)
        server's type = 231 (x UCS-2 varchar)
        column_varint_size = 8
        column_size = 2147483647 (1073741823 on server)
token.c:3160:adjust_character_column_size:
        Server charset: UTF-16LE
        Server column_size: 510
        Client charset: UTF-8
        Client column_size: 1020
```

The Bytes sequence from the freetds.log, corresponding to the end of the **interest** column-value is as follows. Each row has 16 bytes with a "-" after 8 bytes. On the right hand, we have equivalent characters, between pipes.

```
......
......
......
00 26 00 23 00 35 00 35-00 33 00 35 00 36 00 3b              |.&.#.5.5 .3.5.6.;|
00 3a df 00 00 00 00 18-00 54 00 72 00 61 00 64               |.:...... .T.r.a.d|
00 65 00 20 00 53 00 63-00 68 00 6f 00 6f 00 6c                |.e. .S.c .h.o.o.l|
......
......
......
```

In the final lines freetds dump, it was printing `3a df ----- trouble some bytes` twice and failing right afterwards. It corresponds to the second line in the byte sequence.

```
00   -> #####second-byte of the previous utf-16 Character
26 00   ->  &.
23 00   ->  #.
35 00   ->  5.
35 00   ->  5.
33 00   ->  3.
35 00   ->  5.
36 00   ->  6.
3b 00   ->  ;.    # 00 from next line

TROUBLE Starts here
3a df  ->  invalid UTF+16LE? If so, can we just ignore it?

```

This used to work with older versions of freetds. Does this mean the new freetds, is more strict? Is there anyway to tell freetds to ignore any byte-conversion errors.

**Comment by vijay-koppala** [comment]
May be, for this particular query I thought I should try disabling utf-16, (and use UCS-2 for the server-charset, if I can) in tsql and see what happens. I think that may be what, older freetds was doing

So, I tried following,

ADDED `use utf-16 = no` in my `~/freetds.conf` and there wre NO issues going through all rows using tsql . I guess this is what older freetds was doing.


Even though, for this query, I got it working by adding `use utf16 = no` in `~/freetds.conf`, it still doesn't quite help me, because, sometimes it has to be "no", to make some queries work and the other times I want it to be "yes" to get the emojis correctly.

I wish there is another setting where I can keep use utf16 = yes and ignoring the byte-conversion errors.

**Comment by vijay-koppala** [comment]
Is this commit, that is on just master https://github.com/FreeTDS/freetds/commit/4c572bbe028a0d5f0ae59aee38e20308b4f96ad8 trying to fix the issue that I have. The comment says `Support wrong encoding in the range U+D800-U+DFFF.`.

I got the nightly-snapshot of the freetds (which had that commit) and tried running the query. It still gave me the same error.

**Comment by freddy77** [comment]
Weird. Tried with --disable-libiconv and without and with both master and 1.0 branches. In some conditions I had the warning but never the "Bad token from the server: Datastream processing out of sync" which is quite bad.

I'm trying with a query like

select cast(cast(0x350036003adf as varbinary(100)) as nvarchar(max)), 123

which should reproduce the issue. Can you try the same query on your environment?
OpenSUSE should use Glibc iconv so I would expect to have the same issues on my machine (Ubuntu).
I checked and from my log is converting utf16 -> utf8 (so "use utf16" is yes).
About the log the 4 zeroes ("00 00 00 00") after the "3a df" sequence is due to nvarchar(max) being used (it's a 32 bit number specifying that the stream is finished) so the string ends after "3a df" bytes.

**Comment by vijay-koppala** [comment]
@freddy77  tried the query you gave, in two different scenarios.

1. **without**  `--disable-libiconv` and it threw the **same** error
2. **with** `--disable-libiconv` and it  **worked**

error details further below.  My glibc version is 2.19. Do I need to update it?


````
ldd --version
ldd (GNU libc) 2.19
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper
````



>select cast(cast(0x350036003adf as varbinary(100)) as nvarchar(max)), 123

and I got the same error

````
1> select cast(cast(0x350036003adf as varbinary(100)) as nvarchar(max)), 123
2> GO

Error 2401 (severity 4):
        Character set conversion is not available between client character set '%.*s' and server character set '%.*s'
(0 rows affected)
Error 20020 (severity 9):
        Bad token from the server: Datastream processing out of sync
````


And this is from freetds.log

````
13:32:43.423394 18545 (stream.c:125):Error: tds_convert_stream: tds_iconv returned errno 22, conv_errno 22
13:32:43.423402 18545 (stream.c:129):Error: tds_convert_stream: Gave up converting 2 bytes due to error 22.
13:32:43.423409 18545 (stream.c:132):Troublesome bytes:
0000 3a df                  -                        |:.|

13:32:43.423425 18545 (stream.c:125):Error: tds_convert_stream: tds_iconv returned errno 22, conv_errno 22
13:32:43.423432 18545 (stream.c:129):Error: tds_convert_stream: Gave up converting 2 bytes due to error 22.
13:32:43.423439 18545 (stream.c:132):Troublesome bytes:
0000 3a df                  -                        |:.|

13:32:43.423447 18545 (stream.c:136):No conversion possible: some bytes left.
13:32:43.423453 18545 (util.c:319):tdserror(0xfd0060, 0xfd07c0, 2401, 0)
13:32:43.423480 18545 (util.c:349):tdserror: client library returned TDS_INT_CANCEL(2)
13:32:43.423488 18545 (util.c:372):tdserror: returning TDS_INT_CANCEL(2)
13:32:43.423495 18545 (util.c:165):Changed query state from READING to PENDING
13:32:43.423505 18545 (token.c:525):tds_process_tokens(0xfd07c0, 0x7ffe0fe4711c, (nil), 0x6914)
13:32:43.423512 18545 (util.c:165):Changed query state from PENDING to READING
13:32:43.423518 18545 (token.c:540):processing result tokens.  marker is  7b()
13:32:43.423525 18545 (token.c:125):tds_process_default_tokens() marker is 7b()
13:32:43.423532 18545 (query.c:3796):tds_disconnect() 
13:32:43.423576 18545 (util.c:165):Changed query state from READING to DEAD
13:32:43.423585 18545 (util.c:319):tdserror(0xfd0060, 0xfd07c0, 20020, 0)
13:32:43.423598 18545 (util.c:349):tdserror: client library returned TDS_INT_CANCEL(2)
13:32:43.423605 18545 (util.c:372):tdserror: returning TDS_INT_CANCEL(2)
13:32:43.423611 18545 (token.c:273):Unknown marker: 123(7b)!!
13:32:43.423618 18545 (util.c:83):logic error: cannot change query state from DEAD to PENDING
13:32:43.423624 18545 (util.c:165):Changed query state from DEAD to DEAD

````

**Comment by vijay-koppala** [comment]
I also tried on ubuntu 14.04 with glibc 2.19 and I got the same error.

````
 lsb_release -a
Distributor ID:    Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:    14.04
Codename:    trusty
````

````
dd --version
ldd (Ubuntu EGLIBC 2.19-0ubuntu6.9) 2.19
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
````


And I happen to come across this bug on glibc which is fixed in 2.23.https://sourceware.org/bugzilla/show_bug.cgi?id=19727 . It is dealing with these UTF-16 surrogates.

So, I am thinking this could be the glibc version I am using. @freddy77  What version of glibc did you try this on?

**Comment by freddy77** [comment]
I use Xenial which has 2.23. It's not clear however which values the iconv returns to cause syncing problems.
I'll try an old version when I can.

**Comment by freddy77** [comment]
Tried with a very old glib (2.11) and not getting the crash, at least with tsql. Could be that the crash happens in tiny_tds as not able to handle this condition?
I'm trying to avoid the "Bad token from the server: Datastream processing out of sync".

**Comment by freddy77** [comment]
Beside the Glibc problem which is not up to me to fix now client does not lose sync with the server.
Still to write an automated test for this.

**Comment by mckaygerhard** [comment]
i tried this exactly as, using debian lenny (14 yeas older) and works good in both cases, also recompiled using the squeeze (quite some years old) and works prefectly

there's a good example that the lasted and more new are not always the good! here there's a problem in the glibc iconv implemnetation? or there are some change in wich the iconv must be implemented in the future? maybe
