### ISSUE TITLE
Error with rtrim function with multi-byte characters

### ISSUE THREAD

**Issue by neilmcguigan** [FreeTDS/freetds#80]
Please see the question and answer on stackoverflow: http://stackoverflow.com/questions/38984053/freebcp-unicode-data-is-odd-byte-size-for-column-should-be-even-byte-size

Seems that if the first part of a unicode character is `20` then freebcp assumes it's a space and trims it. For example `2018` is really left quote mark, but in UTF-16LE, it's `18 20` and freebcp sees the `20` and thinks it's a space and deletes it. This leads to an error

**Comment by freddy77** [comment]
Fixed. Expect a new patched version tomorrow.
