### ISSUE TITLE
FreeTDS and the iOS App Store?

### ISSUE THREAD

**Issue by zacherous** [FreeTDS/freetds#82]
Hello,
I'm wondering what FreeTDS's stance on iOS and the App Store is? FreeTDS uses the LGPL license which I am having a hard time determining its compatibility.

Specifically LGPL3 I think would be ok as it allows static linking of unmodified code or requires modified code to be distributed. LGPL2 allows dynamic linking (but iOS does not, so that point becomes mute). I'm not positive on LGPL1.

In the FreeTDS teams opinion, can an unmodified freetds library be used via the iOS App Store? Assuming proper credit is given?

**Comment by freddy77** [comment]
Was already done in the past.
It's LGPL2. Basically a licensed user of your application can asks you to be able to change the FreeTDS part of code.
The former solution was to create a single .o file (you can use ld to link all .o files together and strip all symbols to reduce reverse engineering attempts) that you could link to FreeTDS (or the part of FreeTDS you are going to use).
I hardly believe that somebody will ask such a binary but for legal reason you should be able to produce it.
A note about FreeTDS in some information page is really appreciated.
