### ISSUE TITLE
MSSQLODBC Transactions

### ISSUE THREAD

**Issue by alobban** [FreeTDS/freetds#85]
My coworkers initially wrote an existing application (Linux Fedora 23) utilizing the MS ODBC Driver 11 for SQL Server with unixODBC at the system level and Ruby-odbc at the application level. In the application, making performing any writes to the db they are using transactions; however, being on the Mac and not having the official MS ODBC Driver 11 for SQL Server, I am unable to perform transactions with FreeTDS 1.00.19 enabled with unixodbc 2.3.4.

The action will execute but will not actual complete or perform any of the transactions.

Does FreeTDS have transactions capability that is compatible with the MS ODBC Driver 11 or 13 for SQL Server?

**Comment by freddy77** [comment]
FreeTDS supports transactions.
How to you manage these transactions?
How are you committing them?
Can we have some ODBC code or trace of ms odbc driver?

**Comment by freddy77** [comment]
No reply in a couple of weeks, closing the issue, works for me
