### ISSUE TITLE
Unknown `dbcoltype` 98

### ISSUE THREAD

**Issue by metaskills** [FreeTDS/freetds#86]
From an issue filed on TinyTDS here: https://github.com/rails-sqlserver/tiny_tds/issues/317

```sql
SELECT LOGINPROPERTY('sa', 'IsLocked') as v
```

I noticed that the following function returns `98` for `dbcoltype` but this type is no where in sydb.h or tds.h. Have you encountered that one before? Should I treat 98 as an `int`?

**Comment by freddy77** [comment]
The constant is in proto.h, SYBVARIANT. I don't know the level of support with dblib. You can use dbprtype to get the string given the type returned by dbcoltype.

**Comment by metaskills** [comment]
Thanks, gonna close this issue.
