### ISSUE TITLE
missing datatype for sybase cannot resolve datatype 'univarchar'

### ISSUE THREAD

**Issue by mckaygerhard** [FreeTDS/freetds#88]
i got a error on some data types, seems related to unicode to UTF8 conversion

[01000][unixODBC][FreeTDS][SQL Server]TDS: cannot resolve datatype 'univarchar'

**this error resulting on many tables, and specially on proxy tables! seems that need convert UNIVARCHAR, UNICHAR, and UNITEXT data to utf-8 client encoding in this case the tdsodbc encoding when they are retrieved.

Of course alsio we need when updating a unicode column will cause Sybase to convert any incoming data from utf-8 to its internal utf-16 encoding. so the tdsodbc driver must send the data converted!**

i see a very older patch here: http://marc.info/?l=freetds&m=106941196411173&w=2 i this are so older today the univarchar support must have included! but seems does not!

```
SQL> select * from ta_cpp
+--------------+-------------+
| num_promocion| cod_sucursal|
+--------------+-------------+
+--------------+-------------+
SQLRowCount returns 0
SQL> select * from usuarios
[37000][unixODBC][FreeTDS][SQL Server]SQL Anywhere Error -85: Communication error
[01000][unixODBC][FreeTDS][SQL Server]TDS: cannot resolve datatype 'univarchar'
[01000][unixODBC][FreeTDS][SQL Server]TDS: cannot resolve datatype 'univarchar'
[01000][unixODBC][FreeTDS][SQL Server]TDS: cannot resolve datatype 'univarchar'
[01000][unixODBC][FreeTDS][SQL Server]TDS: cannot resolve datatype 'univarchar'
[01000][unixODBC][FreeTDS][SQL Server]TDS: cannot resolve datatype 'unitext'
[01000][unixODBC][FreeTDS][SQL Server]TDS: cannot resolve datatype 'unitext'
[01000][unixODBC][FreeTDS][SQL Server]TDS: cannot resolve datatype 'unitext'
[01000][unixODBC][FreeTDS][SQL Server]TDS: cannot resolve datatype 'univarchar'
[01000][unixODBC][FreeTDS][SQL Server]TDS: cannot resolve datatype 'univarchar'
[01000][unixODBC][FreeTDS][SQL Server]TDS: cannot resolve datatype 'univarchar'
[01000][unixODBC][FreeTDS][SQL Server]TDS: cannot resolve datatype 'univarchar'
[01000][unixODBC][FreeTDS][SQL Server]TDS: cannot resolve datatype 'univarchar'
[01000][unixODBC][FreeTDS][SQL Server]TDS: cannot resolve datatype 'univarchar'
[ISQL]ERROR: Could not SQLExecute
SQL> 
```

i posted the patch here if the source dissapears, dated from 2003:

```
Index: include/cspublic.h
===================================================================
RCS file: /cvsroot/freetds/freetds/include/cspublic.h,v
retrieving revision 1.42
diff -u -r1.42 cspublic.h
--- include/cspublic.h	1 Nov 2003 23:02:07 -0000	1.42
+++ include/cspublic.h	21 Nov 2003 10:33:23 -0000
@@ -737,6 +737,7 @@
 #define CS_VOID_TYPE	25
 #define CS_USHORT_TYPE	26
 #define CS_UNIQUE_TYPE	27
+#define CS_UNIVARCHAR_TYPE  28
 
 /* cs_dt_info type values */
 enum
Index: include/tds.h
===================================================================
RCS file: /cvsroot/freetds/freetds/include/tds.h,v
retrieving revision 1.154
diff -u -r1.154 tds.h
--- include/tds.h	16 Nov 2003 08:19:34 -0000	1.154
+++ include/tds.h	21 Nov 2003 10:33:23 -0000
@@ -413,8 +413,10 @@
 
 	SYBUNIQUE = 36,		/* 0x24 */
 #define SYBUNIQUE	SYBUNIQUE
-	SYBVARIANT = 98 	/* 0x62 */
+	SYBVARIANT = 98, 	/* 0x62 */
 #define SYBVARIANT	SYBVARIANT
+	SYBUNIVARCHAR = -1001
+#define SYBUNIVARCHAR	SYBUNIVARCHAR
 } TDS_SERVER_TYPE;
 
 #define SYBAOPCNT  0x4b
@@ -568,6 +570,7 @@
 #define is_unicode_type(x) (x==XSYBNVARCHAR || x==XSYBNCHAR || x==SYBNTEXT)
 #define is_collate_type(x) (x==XSYBVARCHAR || x==XSYBCHAR || x==SYBTEXT || x==XSYBNVARCHAR || x==XSYBNCHAR || x==SYBNTEXT)
 #define is_ascii_type(x) ( x==XSYBCHAR || x==XSYBVARCHAR || x==SYBTEXT || x==SYBCHAR || x==SYBVARCHAR)
+#define is_binary_type(x) (x==SYBLONGBINARY)
 #define is_char_type(x) (is_unicode_type(x) || is_ascii_type(x))
 #define is_similar_type(x, y) ((is_char_type(x) && is_char_type(y)) || ((is_unicode_type(x) && is_unicode_type(y))))
 
Index: src/ctlib/cs.c
===================================================================
RCS file: /cvsroot/freetds/freetds/src/ctlib/cs.c,v
retrieving revision 1.42
diff -u -r1.42 cs.c
--- src/ctlib/cs.c	1 Nov 2003 23:02:09 -0000	1.42
+++ src/ctlib/cs.c	21 Nov 2003 10:33:23 -0000
@@ -371,11 +371,13 @@
 				}
 			}
 			break;
+		case SYBUNIVARCHAR:
 		case SYBCHAR:
 		case SYBVARCHAR:
 		case SYBTEXT:
 			tdsdump_log(TDS_DBG_FUNC, "%L cs_convert() desttype = character\n");
 			if (src_len > destlen) {
+				tdsdump_log(TDS_DBG_FUNC, "%L src_len > destlen\n");
 				ret = CS_FAIL;
 			} else {
 				switch (destfmt->format) {
@@ -416,6 +418,7 @@
 					ret = CS_SUCCEED;
 					break;
 				default:
+					tdsdump_log(TDS_DBG_FUNC, "%L no destination format specified!\n");
 					ret = CS_FAIL;
 					break;
 				}
Index: src/ctlib/ct.c
===================================================================
RCS file: /cvsroot/freetds/freetds/src/ctlib/ct.c,v
retrieving revision 1.107
diff -u -r1.107 ct.c
--- src/ctlib/ct.c	16 Nov 2003 08:19:58 -0000	1.107
+++ src/ctlib/ct.c	21 Nov 2003 10:33:23 -0000
@@ -49,7 +49,7 @@
  */
 static int _ct_fetch_cursor(CS_COMMAND * cmd, CS_INT type, CS_INT offset, CS_INT option, CS_INT * rows_read);
 static int _ct_bind_data(CS_COMMAND * cmd, CS_INT offset);
-static int _ct_get_client_type(int datatype, int size);
+static int _ct_get_client_type(int datatype, int usertype, int size);
 static int _ct_fetchable_results(CS_COMMAND * cmd);
 static int _ct_process_return_status(TDSSOCKET * tds);
 
@@ -1369,6 +1369,11 @@
 	for (i = 0; i < resinfo->num_cols; i++) {
 		curcol = resinfo->columns[i];
 
+		tdsdump_log(TDS_DBG_FUNC, "%L _ct_bind_data(): column_type: %d column_len: %d\n",
+			curcol->column_type,
+			curcol->column_cur_size
+		);
+
 		if (curcol->column_hidden) 
 			continue;
 
@@ -1397,7 +1402,7 @@
 
 		if (dest && !tds_get_null(resinfo->current_row, i)) {
 
-			srctype = _ct_get_client_type(curcol->column_type, curcol->column_size);
+			srctype = _ct_get_client_type(curcol->column_type, curcol->column_usertype, curcol->column_size);
 
 			src = &(resinfo->current_row[curcol->column_offset]);
 			if (is_blob_type(curcol->column_type))
@@ -1413,7 +1418,8 @@
 			destfmt.locale = cmd->con->locale;
 			destfmt.format = curcol->column_bindfmt;
 			/* if convert return FAIL mark error but process other columns */
-			if (cs_convert(ctx, &srcfmt, (CS_VOID *) src, &destfmt, (CS_VOID *) dest, &len) != CS_SUCCEED) {
+			if ((result= cs_convert(ctx, &srcfmt, (CS_VOID *) src, &destfmt, (CS_VOID *) dest, &len) != CS_SUCCEED)) {
+				tdsdump_log(TDS_DBG_FUNC, "%L cs_convert-result = %d\n", result);
 				result = 1;
 				len = 0;
 				tdsdump_log(TDS_DBG_INFO1, "%L \n  convert failed for %d \n", srcfmt.datatype);
@@ -1472,9 +1478,9 @@
 
 
 static int
-_ct_get_client_type(int datatype, int size)
+_ct_get_client_type(int datatype, int usertype, int size)
 {
-	tdsdump_log(TDS_DBG_FUNC, "%L _ct_get_client_type(type %d, size %d)\n", datatype, size);
+	tdsdump_log(TDS_DBG_FUNC, "%L _ct_get_client_type(type %d, user %d, size %d)\n", datatype, usertype, size);
 	switch (datatype) {
 	case SYBBIT:
 	case SYBBITN:
@@ -1568,6 +1574,11 @@
 	case SYBUNIQUE:
 		return CS_UNIQUE_TYPE;
 		break;
+	case SYBLONGBINARY:
+		if (usertype == 35)
+			return CS_UNIVARCHAR_TYPE;
+		return CS_BINARY_TYPE;
+		break;
 	}
 
 	return CS_FAIL;
@@ -1635,6 +1646,8 @@
 	case CS_LONGBINARY_TYPE:	/* vicm */
 		return SYBLONGBINARY;
 		break;
+	case CS_UNIVARCHAR_TYPE:
+		return SYBUNIVARCHAR;
 	default:
 		return -1;
 		break;
@@ -1703,7 +1716,7 @@
 	strncpy(datafmt->name, curcol->column_name, len);
 	datafmt->namelen = len;
 	/* need to turn the SYBxxx into a CS_xxx_TYPE */
-	datafmt->datatype = _ct_get_client_type(curcol->column_type, curcol->column_size);
+	datafmt->datatype = _ct_get_client_type(curcol->column_type, curcol->column_usertype, curcol->column_size);
 	tdsdump_log(TDS_DBG_INFO1, "%L ct_describe() datafmt->datatype = %d server type %d\n", datafmt->datatype,
 		    curcol->column_type);
 	/* FIXME is ok this value for numeric/decimal? */
Index: src/tds/convert.c
===================================================================
RCS file: /cvsroot/freetds/freetds/src/tds/convert.c,v
retrieving revision 1.125
diff -u -r1.125 convert.c
--- src/tds/convert.c	24 Oct 2003 10:11:11 -0000	1.125
+++ src/tds/convert.c	21 Nov 2003 10:33:23 -0000
@@ -1608,6 +1608,7 @@
 	assert(srclen >= 0 && srclen <= 2147483647u);
 
 	switch (srctype) {
+	case SYBUNIVARCHAR:
 	case CASE_ALL_CHAR:
 		length = tds_convert_char(srctype, src, srclen, desttype, cr);
 		break;
@@ -3220,6 +3221,9 @@
 		break;
 	case SYBLONGBINARY:
 		result = "SYBLONGBINARY";
+		break;
+	case SYBUNIVARCHAR:
+		result = "SYBUNIVARCHAR";
 		break;
 	default:
 		break;
Index: src/tds/token.c
===================================================================
RCS file: /cvsroot/freetds/freetds/src/tds/token.c,v
retrieving revision 1.226
diff -u -r1.226 token.c
--- src/tds/token.c	16 Nov 2003 18:10:18 -0000	1.226
+++ src/tds/token.c	21 Nov 2003 10:33:23 -0000
@@ -1520,8 +1520,11 @@
 	switch (curcol->column_varint_size) {
 	case 4:
 		curcol->column_size = tds_get_int(tds);
-		curcol->table_namelen =
-			tds_get_string(tds, tds_get_smallint(tds), curcol->table_name, sizeof(curcol->table_name) - 1);
+		/* Only read table_name for blob columns (eg. not for SYBLONGBINARY) */
+		if (is_blob_type (curcol->column_type)) {
+			curcol->table_namelen =
+				tds_get_string(tds, tds_get_smallint(tds), curcol->table_name, sizeof(curcol->table_name) - 1);
+		}
 		break;
 	case 2:
 		curcol->column_size = tds_get_smallint(tds);
@@ -1812,7 +1815,7 @@
 {
 	unsigned char *dest;
 	int len, colsize;
-	int fillchar;
+	int fillchar, pos;
 	TDSBLOBINFO *blob_info = NULL;
 
 	tdsdump_log(TDS_DBG_INFO1, "%L processing row.  column is %d varint size = %d\n", i, curcol->column_varint_size);
@@ -1830,6 +1833,15 @@
 			tds_set_null(current_row, i);
 			return TDS_SUCCEED;
 		}
+		
+		/* LONGBINARY
+		 * This type just stores a 4-byte length
+		 */
+		if (curcol->column_type == SYBLONGBINARY) {
+			colsize = tds_get_int(tds);
+			break;
+		}
+		
 		/* It's a BLOB... */
 		len = tds_get_byte(tds);
 		blob_info = (TDSBLOBINFO *) & (current_row[curcol->column_offset]);
@@ -1949,6 +1961,7 @@
 	} else {		/* non-numeric and non-blob */
 		if (is_char_type(curcol->column_type)) {
 			/* this shouldn't fail here */
+			tdsdump_log(TDS_DBG_INFO1, "%L curcol->iconv_info? %d\n", (int)curcol->iconv_info);
 			if (tds_get_char_data(tds, (char *) dest, colsize, curcol) == TDS_FAIL)
 				return TDS_FAIL;
 		} else {
@@ -1968,6 +1981,11 @@
 				break;
 			/* FIXME use client charset */
 			fillchar = ' ';
+		/* just to prevent \0 to interrupt display, as long as we cannot decode utf-16 */
+		case SYBLONGBINARY:
+			for (pos= 0; pos < colsize; pos++) {
+				if (dest[pos] == '\0') { dest[pos]= '.'; }
+			}
 		case SYBBINARY:
 		case XSYBBINARY:
 			if (colsize < curcol->column_size)
@@ -3151,6 +3169,7 @@
 		TYPE(SYBAOPSUM, "sum");
 
 		TYPE(SYBBINARY, "binary");
+		TYPE(SYBLONGBINARY, "longbinary");
 		TYPE(SYBBIT, "bit");
 		TYPE(SYBBITN, "bit-null");
 		TYPE(SYBCHAR, "char");
```

**Comment by freddy77** [comment]
Adding a new type is quite complicated, see http://www.freetds.org/reference/a00002.html.
The "cannot resolve datatype" error came from server, not from our library. I suspect we are not telling the server some required type (in the webpage I pointed out is "enable the type from server" point).
I never encountered this issue. I suspect the types the server is expecting should be in the capabilities sent by the client. If you look at commit https://github.com/FreeTDS/freetds/commit/a498703ff9e309c656b19dd990f4cad0283a47c7 you should add `DATA_NLBIN` and `IMAGE_NCHAR` in srv/tds/mem.c, specifically you should add `REQ(i,DATA_NLBIN) REQ(i,IMAGE_NCHAR)` to the long `SUPPORTED_REQ_CAP` macro definition. This should tell the server we support the types. You should then send a dump (see http://www.freetds.org/userguide/logging.htm for how to do it) to let us understand how the server is sending back data.

**Comment by mckaygerhard** [comment]
hi @freddy77 , i cited the problem around new data type due was a solution in the past, as u noted, i cited that THE PROBLEM ARE NOT NEW!

but the origin of the problem may be the convertion of UNIVARCHAR, UNICHAR, and UNITEXT data to utf-8 client encoding in this case the tdsodbc encoding when they are retrieved.
Of course also we need when updating a unicode column will cause Sybase to convert any incoming data from utf-8 to its internal utf-16 encoding. so the tdsodbc driver must send the data converted!

so then, here are two ways/problems or maybe one but we dont know wich!?! a problem in the datatype missing convertion, or a problem of encoding!? or both?

**Comment by freddy77** [comment]
In 13 years lot of stuff was changed. I just tried to do the change I indicated and server looks pretty happy.
The charset conversion was quite entirely rewritten, I doubt it's still a problem.
I'm actually not seeing UNIXTEXT being correctly converted, but should be a couple of lines (at least for the select).
I cannot find a TDSDUMP from the thread you mentioned. The patch is pretty useless, too much stuff was changed, not even the logging will work. Would be really useful if you could provide a dump, I can't really be sure that I'm fixing your issue or not.

**Comment by mckaygerhard** [comment]
ok umm as u said, many was changed, i tried with the lasted, due the test was with 0.99, i tried to provide more info if with lasted does still not work, in some dais i'll back to office and got a machine to work in that, currently i not have access to the environment (was a odbc select froma proxy sybase table)

**Comment by freddy77** [comment]
Got some tests. Basically we don't report we support uni(var)char/unitext. Reporting uni(var)char works quite fine but unitext it's quite a different issue. I'll see what I can do.

**Comment by mckaygerhard** [comment]
i have tested some things and got this:

if the data between servers ater set to lati8n1 locate then the mapping are correctly made to varchar.. when client are different, got mapping to "nvarchar" and this seems does not convert the data to UTF8 from latin1, still need to test with 1.00 brand but i dont spec too much, due seem a problem of conversion encoding

**Comment by freddy77** [comment]
This is not a problem of mapping, this is a protocol error. Depending on the character set the gateway is using a type instead of another. If that type is not supported an error is reported. Probably the gateway to make sure characters can be represented convert the varchar types to univarchar. Is seems the gateway wants to use univarchar, not nvarchar. The univarchar is encoded as utf-16, not utf-8.

Can you try unitext branch at https://github.com/freddy77/freetds/tree/unitext ? I could send a .tar.gz if you need it.

**Comment by mckaygerhard** [comment]
for sure, freedts-odbc does not represent well the nvarchar type data property, i can see that its a communication problem at the protocol level when see the firts error `[37000][unixODBC][FreeTDS][SQL Server]SQL Anywhere Error -85: Communication error` by creating a table and use the columns with nvarchar type data, errors persist so in conclusion this issue are valid and its a problem urgency to resolve due this support are important to sue property the proxy tables

i can swicht to that brand and try, but now, I had to read a lot about utf8 and utf16, i will paste feedback here later, but please, start working in this, i need urgency

**Comment by freddy77** [comment]
Working on it. But probably will require a 1.1 version, supporting both directions (input and output) and CT-Library is quite complicated.

**Comment by mckaygerhard** [comment]
i can see a cmakelist and a autoconf systems, what i sould be used to compile, previously some commits ago i used autoconf but some erros in doc, noted that installed files must b tuned to ajust to debian..

**Comment by mckaygerhard** [comment]
i compiled susessfully, no when i connect got a 'FreeDTS SQLAnywhere error -131: sintax error near dbmain line1' where dbmain its the database

usin the 0.83 versionconect sucessfully with same parameters same files same config, both are debian machines, no firewall or special network rules are set, some ideas?

**Comment by mckaygerhard** [comment]
search at the sources, seem something was changed around config files or i have and old unixodbc, i have unixodbc 2.2.14 and compiled with sybase compat enabled and gnutls 2.6.X also kerberos support, there's the complete out and ini file (same result using 1.0 brand, due u folks that) :

```
root@systemaspc01:/home/systemas/Devel# isql OA1 dba sql -v
[S1000][unixODBC][FreeTDS][SQL Server]Unable to connect to data source
[37000][unixODBC][FreeTDS][SQL Server]SQL Anywhere Error -131: Syntax error near 'T_001642' on line 1
[01000][unixODBC][FreeTDS][SQL Server]TDS: unexpected token 0
[ISQL]ERROR: Could not SQLConnect
root@systemaspc01:/home/systemas/Devel# cat /etc/odbc.ini 
[ODBC Data Sources]
OA1 = Sybase JDBC Server

[OA1]
Driver          = /usr/lib/odbc/libtdsodbc.so
Description     = Sybase JDBC Server
Trace           = No
Server          = 10.10.34.21
Database        = T_001642
Port            = 2638

[Default]
Driver          = /usr/lib/odbc/libtdsodbc.so
root@systemaspc01:/home/systemas/Devel# 
```

**Comment by mckaygerhard** [comment]
after a har typing of u'r unitext brand and try some patch to the only owrking 0.9X brand i got susess on nvarchar and protocol work with some issues:

1) as u said ntext its not supported (i cannot track u'r changes correctly)
2) its a protocol problem, but in 1.00 brand , 0.91 does not support and 0.95 got work
3) there's errors connecting to AnyWhere flavors, and Anywhere flavors are not same SAP flavors

there's the text output and test:

```
root@systemaspc01:/home/systemas/Devel# isql OA1 dba sql -v
+---------------------------------------+
| Connected!                            |
|                                       |
| sql-statement                         |
| help [tablename]                      |
| quit                                  |
|                                       |
+---------------------------------------+
SQL> CREATE TABLE IF NOT EXISTS `tabla3` ( `col1` nvarchar(60), col3 nvarchar(60) );
SQLRowCount returns -1
SQL> select col1,col3 from tabla3
+----------------------------+
| col1         | col3           |
+---------------------------+
SQLRowCount returns 0
```
and with combined ntext not supported:

```
SQL> CREATE TABLE IF NOT EXISTS `tabla4` ( `col1` nvarchar(60), col3 ntext );
SQLRowCount returns -1
SQL> select col1,col3 from tabla4
[08S01][unixODBC][FreeTDS][SQL Server]Bad token from the server: Datastream processing out of sync
[ISQL]ERROR: Could not SQLPrepare
SQL> quit
root@systemaspc01:/home/systemas/Devel# 
```

but this issue could not marks as solved or in good way due still there's some more errors at the 1.0 brand, and u'r unitext brand comes from 1.0, please refers to the issue #92

**Comment by freddy77** [comment]
Got some updates. Now univarchar works correctly (master). unitext is still a work in progress. Tests are now working but there are some bug (like multiple row inserts) and I want to do more additional tests.

**Comment by mckaygerhard** [comment]
good work, in this way, freedts wil have a good shape.. from where i must take the changes or clone the code? to test? here using 1.X brand or from u'r personal clone? (url better please)

**Comment by freddy77** [comment]
Beside https://github.com/FreeTDS/freetds you can check at ftp://ftp.freetds.org/pub/freetds/current/ for a snapshot. There are from official repo.
In my repository there are some work for unitext https://github.com/freddy77/freetds/tree/unitext. As said this branch has some known issue.

**Comment by mckaygerhard** [comment]
github remove private message feature.. can u send me to my mail as show in my profile, where can i send to you

**Comment by mckaygerhard** [comment]
hi, i tested not deeply, selects and joins works good, inclusivelly having multiple columns of multiple typoes, i do not tests inserts and updates, due i'm very very busy at work implanting linux and removing guindosers, the dump log for this issue must have waith for one week more, in one week be sure u will have it

**Comment by mckaygerhard** [comment]
i'll close this issue, due at least selects and joins are working good, please focused in solve the others two.. if some problems appears i'll post new issues or comment here

selects works with any case, event if not all columns are nvarchar (crash before lasted commits)
inserts only works when all columns are nvarchar, 
multiple inserts are not tested

**Comment by mckaygerhard** [comment]
i compiled/backported  the FREETDS 1.00.104-0 from debian sources and i can post now that this problem was solved.. compiled in debian jessie and **tested agains Sybase 12 Anywhere working perfectly, many many thanks @freddy77 for your work! and also any other that already contributed for this issue to solve it!** well two years are better than forever! two years !!!!!!  "madre de dios que chingawhat!" but now works!
