### ISSUE TITLE
Unable to validate TLS hostname

### ISSUE THREAD

**Issue by alexloney** [FreeTDS/freetds#90]
When attempting to make a connection to a SQL Server and providing a CA Cert file, FreeTDS appears to be unable to validate a hostname (e.g. returns that differing hostnames are valid and exact hostnames are invalid). We tracked this down to the function [check_name_match in tls.c on line 765](https://github.com/FreeTDS/freetds/blob/master/src/tds/tls.c#L765).

That if-statement will set the return value to 1 if the lengths match and check_wildcard returns 0. However, check_wildcard returns 1 on success and 0 on failure, so this check will cause the function check_name_match to return a 1 on failure and 0 on success. Which ultimately causes the [check_hostname call in tds_ssl_init on line 964](https://github.com/FreeTDS/freetds/blob/master/src/tds/tls.c#L964) to incorrectly evaluate a successful match as failure (and vice versa).

In order to fix this, I believe that check_name_match should be checking to make sure check_wildcard is 1 (not 0):

	if (strlen(name_utf8) == name_len && check_wildcard(name_utf8, hostname) == 1)
		ret = 1;

**Comment by freddy77** [comment]
Yes, good spot. Thanks, merged
