### ISSUE TITLE
tsql command could not connect to sybase servers

### ISSUE THREAD

**Issue by mckaygerhard** [FreeTDS/freetds#92]
found this in 1.00 brand when try to connect, not happened with 0.91 version:

`SQL Anywhere Error -131: Syntax error near 'select' on line 1`

seems that the option that enabling the sybae compatibility was gone? the complete error are:

```
root@systemaspc01:/home/systemas/Devel# tsql -H 10.10.34.21 -p 2638 -U dbauser -P secretpass -D T_001642
locale is "es_VE.UTF-8"
locale charset is "UTF-8"
using default charset "UTF-8"
Setting T_001642 as default database in login packet
Msg 21 (severity 10, state 0) from [10.10.34.21]:
	"TDS: unexpected token 0"
Msg 102 (severity 15, state 0) from [10.10.34.21]:
	"SQL Anywhere Error -131: Syntax error near 'select' on line 1"
There was a problem connecting to the server
root@systemaspc01:/home/systemas/Devel# 
```

**Comment by freddy77** [comment]
Sybase compatibility is a client option, it does not change the protocol used with the server.
Could be the ASA server don't like some syntax used.
A dump could possibly explain the problem. Maybe is the select trying to get the spid. But I don't like the "TDS: unexpected token 0".

**Comment by mckaygerhard** [comment]
Please how can i dump more info to help to improve and make this issue solved?

**Comment by mckaygerhard** [comment]
NOTE: its not ASA, hey its the "anyWhere" flavors, there are different!

**Comment by mckaygerhard** [comment]
got some info, using 0.91 connect perfectly in odbc but with tsql not: does need tsql extra config in freetds.conf? 

this time said: `TDS: unexpected token 56` there's the output:

```
root@systemaspc01:/home/systemas/Devel# isql OA1 dba sql -v
+---------------------------------------+
| Connected!                            |
|                                       |
| sql-statement                         |
| help [tablename]                      |
| quit                                  |
|                                       |
+---------------------------------------+
SQL> qui6
[42W04][unixODBC][FreeTDS][SQL Server]SQL Anywhere Error -131: Syntax error near 'qui6' on line 1
[ISQL]ERROR: Could not SQLPrepare
SQL> quit
root@systemaspc01:/home/systemas/Devel# tsql -H 10.10.34.21 -p 2638 -U dba -P sql -D T_001642 -o v
locale is "es_VE.UTF-8"
locale charset is "UTF-8"
using default charset "UTF-8"
Default database being set to T_001642
Msg 21 (severity 10, state 0) from [10.10.34.21]:
	"TDS: unexpected token 56"
Msg 102 (severity 15, state 0) from [10.10.34.21]:
	"SQL Anywhere Error -131: Syntax error near 'use' on line 1"
There was a problem connecting to the server
root@systemaspc01:/home/systemas/Devel#
```

**Comment by freddy77** [comment]
For the dump see http://www.freetds.org/userguide/logging.htm.

**Comment by freddy77** [comment]
Closing, no replies or comments in more than a month.

**Comment by mckaygerhard** [comment]
hi @freddy77 i got the mail at the freetds mail list, tomorrow i'll send to u two debug dumps for the rest of issues, sorry for late, i'm very very busy at work and also i have many problems today

**Comment by mckaygerhard** [comment]
hi @freddy77  i send to u a mail with the dump, should i open new issue with this error? or u will reopen this issue?

the mail was with suject `"tsql dump error could not connect sybase errore near -1"` with the dumps using 0.91 and 0.95+git patches until january at this issue report

the proces was :

`root@syslvksrv1:/home/systemas# nano /etc/freetds/freetds.conf`

here i put only that :
```
[global]
        tds version = 5.0
        dump file = /tmp/freetds.log
        text size = 129024
[egServer50]
        host = <in the mail was>
        port = 2638
        tds version = 5.0
```

then save and exit to console with:

```
root@syslvksrv1:/home/systemas# export TDSDUMP=/tmp/freetds.log
root@syslvksrv1:/home/systemas# rm /tmp/freetds.log
root@syslvksrv1:/home/systemas# tsql -H <ip in mail> -p 2638 -U dba -P
sql -D <dbname> -o v
locale is "es_VE.UTF-8"
locale charset is "UTF-8"
using default charset "UTF-8"
Setting <dbname> as default database in login packet
Msg 102 (severity 15, state 0) from [<ip in mail>]:
        "SQL Anywhere Error -131: Syntax error near 'use' on line 1"
There was a problem connecting to the server
root@syslvksrv1:/home/systemas
```

the connection are prefecty and DB its running, using odbc connect perfect:

```
root@syslvksrv1:/home/systemas# rm /tmp/freetds.log
root@syslvksrv1:/home/systemas# more /etc/odbc.ini
[OP0]
Driver       = FreeTDS
Server       = <ip at mail>
Port         = 2638
Database     = <dbname>
ReadOnly     = No

root@syslvksrv1:/home/systemas# isql OP0 dba sql -v
SQL> SELECT cod_registro FROM gas_tem_registro_gastos ORDER BY
cod_registro LIMIT 1 OFFSET 1
+-----------------------------------------+
| cod_registro                            |
+-----------------------------------------+
| GAS20161014161418                       |
+-----------------------------------------+
SQLRowCount returns 1
1 rows fetched
SQL>
```

**Comment by mckaygerhard** [comment]
in the context to help to freetds project this are a 50c more to the connection process:

as i commented in the commit 74e0ff3, sorry for my bad english

hi @freddy77 i have to comment to clarify some issues (by the way quickly, more later in mail i'll explain more extended)

SQL anywhere support multiple databases, but not as same name in same "instance", sql anywhere works like oracle, each database need and engine running, those "engine" are called "instances"!

in common DBMS like mysql, postgres, there's a engine running that "handle databases" and as this, commonly we call that "support multiple databases", but its wrong, all the DBMS can run multiple engines and each can handle multiple databases, the difference its that in sybase (and specially anywhere) like oracle does, there's no a default instance (and each instance are an engine running databases or not)

what happened in the freedts context? seems that could connect to a "server" and assumes that this object called "server" have the databases.. that the problem

this object called "server" could have multiple engines running, and those engines could or not could have databases running.. i mean its not enought the ip of the server and the name of the database....

some weeks ago, i have a problem connecting with freetds, running a query, the expected results was not correct, that cos the server have two engines running two databases, but as connection does not specify what engine was connected, i dont know why but in some way choose the wrong database (i mean the wrong engine)

its quite complicated, i not espected to freetds support all complicated features but if this commit works at leat for one engine in one ip server its enought

i'll comment the same in the issue related

**Comment by freddy77** [comment]
Did you tried the "ASA database" option? See http://www.freetds.org/userguide/freetdsconf.htm. Looks like is what you are looking for. I forgot about that option.

**Comment by mckaygerhard** [comment]
the ASA database works in those cases when multiple db are runnign in same instance, but not in different instances in same server, but its a helpfull option.. thanks

currently still not tested lasted commit, i'm very busy trinying to understand some signature non-jquery depend implementations ... monday i try and paste here some feedback

**Comment by mckaygerhard** [comment]
hi @freddy77 now tested with lasted git the connection now does'n work neither with odbc, need a dump?

```
isql OP0 dba sql -v
[S1000][unixODBC][FreeTDS][SQL Server]Unable to connect to data source
[ISQL]ERROR: Could not SQLConnect
```

**Comment by mckaygerhard** [comment]
testing with tsql command, the DBMS always sybase anywhere 12 with same environment as this entry issue:

```
tsql -H <ip> -p 2638 -U dba -P sql -D 001037 -o v
locale is "en_US.UTF-8"
locale charset is "UTF-8"
using default charset "UTF-8"
Setting 001037 as default database in login packet
Msg 21 (severity 10, state 0) from [10.10.34.21]:
	"TDS: unexpected token 0"
1> connect()
2> ;
3> 
4> quit
```

**Comment by mckaygerhard** [comment]
tds dump attached, with trace.. compiled agains git current 

[freetds.txt](https://github.com/FreeTDS/freetds/files/1059204/freetds.txt)

**Comment by freddy77** [comment]
You are using protocol 4.2 instead of 5.0

**Comment by mckaygerhard** [comment]
hi @freedy77 thanks for quick response, now upload the right dump, set right protocol, i upload the wrong dump, now i changed the protocol,same results.. 

```
grep -A 6 -B 2 'version' /etc/freetds/freetds.conf 
# server specific section
[global]
        # TDS protocol version
	tds version = 5.0

	# Whether to write a TDSDUMP file for diagnostic purposes
	# (setting this to /tmp is insecure on a multi-user system)
	dump file = /tmp/freetds.log
	debug flags = 0xffff
```

now login try:
```
tsql -H <ip> -p 2638 -U dba -P sql -D OP_001037 -o v
locale is "en_US.UTF-8"
locale charset is "UTF-8"
using default charset "UTF-8"
Setting OP_001037 as default database in login packet
There was a problem connecting to the server
```
by odbc setting the version protocol hardcoded:
```
cat /etc/odbc.ini 
[oasis0]
Description         = TDS sybase SQL
Driver              = FreeTDS
Trace               = Yes
TraceFile           = /tmp/tdsqlodbc.log
Database            = OP_001037
Server              = 10.10.34.21
Port                = 2638
TDS_Version         = 5.0
```
testing now still failed:
```
isql oasis0 dba sql -v[S1000][unixODBC][FreeTDS][SQL Server]Unable to connect to data source
[ISQL]ERROR: Could not SQLConnect
```

**Comment by freddy77** [comment]
Can you try setting "encryption = request" ?

**Comment by mckaygerhard** [comment]
tested with that option in freetds.conf respect the documentation ... no connection
tested with that option in odbc.ini respect the odbc.ini parameters documentation.. no connection

attached the new dump file using las git build
[freetds.txt](https://github.com/FreeTDS/freetds/files/1061275/freetds.txt)

**Comment by mckaygerhard** [comment]
thanks for quick reponse, here the results:

tested with that option in freetds.conf respect the documentation ... no connection
tested with that option in odbc.ini respect the odbc.ini parameters documentation.. no connection

i tested that last dump with encription off attached the new dump file using las git build
freetds.txt

i tested that last dump with encryption request attached the new dump file using last git build
freetds-request.txt

**Comment by mckaygerhard** [comment]
newer build in different environment, no connection but different message:

```
tsql -S 10.10.XX.21 -U dba -P sql -D OP_001037
locale is "C"
locale charset is "ANSI_X3.4-1968"
using default charset "ISO-8859-1"
Setting OP_001037 as default database in login packet
Error 20009 (severity 9):
	Unable to connect: Adaptive Server is unavailable or does not exist
	OS error 111, "Connection refused"
There was a problem connecting to the server
```

[freetds.txt](https://github.com/FreeTDS/freetds/files/1062086/freetds.txt)

**Comment by mckaygerhard** [comment]
hi @freddy77 how are the progress in that.., please get me some news... i guess you are some busy but give some hope..

**Comment by mckaygerhard** [comment]
hi, any progress in that, since 0.95 i cannot conenct in any form!

**Comment by freddy77** [comment]
Yes, could help. Note that last freetds.txt file fails because the program attempted the connection to the wrong port (1433, default mssql) instead of 2638.
Maybe to make this faster I could have access to this installation (of course privately)?

**Comment by mckaygerhard** [comment]
the connection of wrong port was due i not parse the "-p" parameter in last command tested, **in the previous tested was specified and either was end in error connection**

Yes i can provide to you a provate access, please waith for a couple of days, due i must free a slot and ask to networking group in my job to free a access to the internal jail machine.. i'll send to you in private maiil in some days..

**Comment by freddy77** [comment]
Closing, please reopen with requested information

**Comment by mckaygerhard** [comment]
sorry for late too here, i'll let close untill tomorrow that i'll reopen due, i still not have a free slot in the virtual machine for remote access, but i can test with testing enviroment at my job.. thanks..

**Comment by mckaygerhard** [comment]
hi @freddy77  this it the second issue to check , now testing at 1.00.104 version, now connection does not return error protocol but return a warning, it's correct or something wrong?:

```
root@syslvksrv1:/home/systemas# tsql -H 10.10.34.21 -p 2638 -U dba -P sql -D T_001642 -o v
locale is "es_VE.UTF-8"
locale charset is "UTF-8"
using default charset "UTF-8"
Setting T_001642 as default database in login packet
Msg 21 (severity 10, state 0) from [10.10.34.21]:
	"TDS: unexpected token 0"
1>
```

**Comment by mckaygerhard** [comment]
hi @freddy77  this it the second issue to check , now testing at 1.00.104 version, now connection does not return error protocol but return a warning, it's correct or something wrong?: (also i cannot reopen the issue... something wrong?)

```
root@syslvksrv1:/home/systemas# tsql -H 10.10.34.21 -p 2638 -U dba -P sql -D T_001642 -o v
locale is "es_VE.UTF-8"
locale charset is "UTF-8"
using default charset "UTF-8"
Setting T_001642 as default database in login packet
Msg 21 (severity 10, state 0) from [10.10.34.21]:
	"TDS: unexpected token 0"
1>
```

**Comment by freddy77** [comment]
Try
`TDSVER=5.0 tsql -H 10.10.34.21 -p 2638 -U dba -P sql -D T_001642 -o v`
maybe is the protocol discovery trying version 7.4 and server complaining.

**Comment by mckaygerhard** [comment]
no warning now! so that its correct? here i can make querys? how to check if that are correct?
```
root@syslvksrv1:/home/systemas# TDSVER=5.0 tsql -H 10.10.34.21 -p 2638 -U dba -P sql -D T_001642 -o v
locale is "es_VE.UTF-8"
locale charset is "UTF-8"
using default charset "UTF-8"
Setting T_001642 as default database in login packet
1>
```

**Comment by mckaygerhard** [comment]
tsql command line are now working at 1.00.104-0 version compiled from debian unstable sources many thanks @freddy77 well two/three years later are better than nothing!:

```
root@syslvksrv1:/home/systemas# TDSVER=5.0 tsql -H 10.10.34.21 -p 2638 -U dba -P sql -D T_001642 -o v
locale is "es_VE.UTF-8"
locale charset is "UTF-8"
using default charset "UTF-8"
Setting T_001642 as default database in login packet
1> select * from entidad limit 1 offset 1;
2> go
cod_entidad	abr_entidad	abr_zona	des_entidad	status	tipo_entidad	cod_fondo	sello	rif_sucursal	rif_razonsocial	des_administradora	num_telefonofijo	des_nombreenc1	num_celularenc1	des_nombreenc2	num_celularenc2	sessionflag
using TDS version 5.0
1001	TG2	VE-ORI	El Tigre    	ESPECIAL	ADMINISTRATIVO	NULL	NULL	NULL	NULLNULL	NULL	NULL	NULL	NULL	NULL	NULL
(1 row affected)
using TDS version 5.0
1> 
```
