### ISSUE TITLE
TLS - intermittent bad_record_MAC error when connecting to MSSQL 2008 or 2012

### ISSUE THREAD

**Issue by beaudet** [FreeTDS/freetds#95]
Possibly related to MS KB3172605, using gnutls as default with freetds results in a bad_record_mac TLS error that is annoyingly intermittent. 

Details of this and a related problem and various troubleshooting are described here: http://stackoverflow.com/questions/38485313/freetds-fails-to-connect-to-sql-server-after-recent-windows-patches-and-tls1-bei

For 1.00 freetds versions, I was able to get around this by leaving out --with-gnutls from configure and including --with-openssl=yes but that only works for RHEL6, not RHEL5.  Interestingly, 0.82 when compiled from source on RHEL6 doesn't exhibit this problem with the default configuration options.

**Comment by freddy77** [comment]
Probably 0.82 use very old ciphers. Looks like some MS implementation are not 100% compatible.
Did you try a patched 1.00 version?

**Comment by beaudet** [comment]
I tried patched 1.0.24 but it wasn't explicitly named with .patched so I will try again tomorrow and report back.  Do you think it's odd that freetds with openssl would work but not gnutls, especially if this is due to an MS issue?

-------- Original message --------

**Comment by freddy77** [comment]
OpenSSL and GnuTLS are 2 TLS implementation, could be there are some differences.
Would be good to have last part of a tds dump (see http://www.freetds.org/userguide/logging.htm) to understand the ciphers used when it fails.
Time ago (not long ago) OpenSSL had a similar issue.

**Comment by beaudet** [comment]
Haven't forgotten about this.  We tried rolling back KB3172605 and it didn't make a difference.  I'll try the patched version, then move onto the tds dump if that doesn't work.  In a training course for the next few days so it will probably be next week.

**Comment by beaudet** [comment]
freetds patched version still has intermittent connection error. moving onto capturing a tds dump.

**Comment by beaudet** [comment]
Under RHEL5, there appear to be at least two problematic ciphers that I'm running up against.  They are defined in OPENSSL_CIPHERS in src/tds/tls.c.  Removing them and recompiling fixes the problem when connecting from RHEL5.  They are the first two ciphers using Diffie-Hellman as the key exchange:
DHE-RSA-AES256-SHA and DHE-RSA-AES128-SHA

I'm guessing the other DHE would also fail, but it's probably just not being used in my test since it's farther down the list.

I imagine that similar failures could be caused by a variety of factors. For OpenSSL implementations, it might make sense to let end-users specify the string argument to SSL_set_cipher_suite() themselves via the freetds.conf file.  

Being able to specify a pattern to SSL_cipher_site() like Apache permits through the SSLCipherSuite directive](https://httpd.apache.org/docs/2.4/mod/mod_ssl.html#sslciphersuite) seems like it would be more flexible in the long run, e.g. 'ALL:!ADH:!NULL:!EXP:!SSLv2:!LOW:!MEDIUM:RC4+RSA:+HIGH:-DH'

I'm experimenting with that and will submit a patch if all goes well and assuming there's not a critical reason for hardcoding the cipher list in tls.c?

**Comment by freddy77** [comment]
One issue could be that would affect only if you are using OpenSSL and same configuration will behave differently with different FreeTDS versions, but if the option clearly specify OpenSSL I don't see much problems.
I would say a HIGH:!SSLv2:!SSLv3 would be a better default also (also the list don't contain the 2 spotted cipher suites). I just tried with an old (XP) VM machine I have and works correctly.

**Comment by beaudet** [comment]
Did you want to change the default too or just leave it as is?  I'm working off the 1.00.24 patched version by the way.  Hope a diff is OK rather than a pull request.  I had some problems with some of the autoconf / automake tools having all the expected Macros under RHEL5.

**Comment by freddy77** [comment]
RHEL5 is quite old. Should not a big issue to port the patch by the way. Or you can get a recent development snapshot at ftp://ftp.freetds.org/pub/freetds/current/ with all autoconf files ready.

**Comment by beaudet** [comment]
Ok, I have it working. I'll send you a patch file later today.   I considered updating the default cipher list from it's current setting to HIGH:!SSLv3 but on RHEL5 (which granted is pretty old) it fails to connect to MSSQL at all.  However, HIGH:!SSLv2:-DH seems to work well without any connection failures so if you wanted to change the default to something simple, this might be a reasonable starting point.  Ideally, a per-openssl-version default list could be built, but I don't have time to do that.

For the record, the list of ciphers under this new proposed default configuration in RHEL5 would include: AES256-SHA:AES128-SHA:KRB5-DES-CBC3-MD5:KRB5-DES-CBC3-SHA:DES-CBC3-SHA

and under RHEL6 and RHEL7:
ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:AECDH-AES256-SHA:ECDH-RSA-AES256-GCM-SHA384:ECDH-ECDSA-AES256-GCM-SHA384:ECDH-RSA-AES256-SHA384:ECDH-ECDSA-AES256-SHA384:ECDH-RSA-AES256-SHA:ECDH-ECDSA-AES256-SHA:AES256-GCM-SHA384:AES256-SHA256:AES256-SHA:CAMELLIA256-SHA:PSK-AES256-CBC-SHA:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:AECDH-AES128-SHA:ECDH-RSA-AES128-GCM-SHA256:ECDH-ECDSA-AES128-GCM-SHA256:ECDH-RSA-AES128-SHA256:ECDH-ECDSA-AES128-SHA256:ECDH-RSA-AES128-SHA:ECDH-ECDSA-AES128-SHA:AES128-GCM-SHA256:AES128-SHA256:AES128-SHA:CAMELLIA128-SHA:PSK-AES128-CBC-SHA:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:AECDH-DES-CBC3-SHA:ECDH-RSA-DES-CBC3-SHA:ECDH-ECDSA-DES-CBC3-SHA:DES-CBC3-SHA:PSK-3DES-EDE-CBC-SHA:KRB5-DES-CBC3-SHA:KRB5-DES-CBC3-MD5

**Comment by freddy77** [comment]
Can you test HIGH:!SSLv2:!aNULL:-DH ? !aNULL will avoid possible MITM.
Seems like the !SSLv3 remove too much cipher suites. With GnuTLS disabling SSL 3 seems to work but it's using some cipher suites marked as SSL 3 in OpenSSL. Don't know who is right.

**Comment by beaudet** [comment]
Sure, good catch. HIGH:!SSLv2:!aNULL:-DH seems to work fine under RHEL5 and it actually produces the same set of ciphers on RHEL5 as HIGH:!SSLv2:-DH in openssl.  A few additional ciphers are removed under RHEL6/7.  I've changed the default list of ciphers in the patch listed at the end of this issue. I also rebuilt the RPMs with the patch on 32bit RHEL6 and it's working fine there with the default cipher list.  I don't have a reason to think it wouldn't work on RHEL7 or in a 64 bit RHEL based system either.

The SSL_set_cipher_list() doesn't barf when it receives input it doesn't understand, so it would be helpful to supplement the documentation showing that the line in /etc/freetds.conf needs to be without quotes, e.g.

`openssl ciphers = HIGH:!SSLv2:!aNULL:-DH 
`
RATHER THAN

`openssl ciphers = 'HIGH:!SSLv2:!aNULL:-DH' OR openssl ciphers = "HIGH:!SSLv2:!aNULL:-DH"`

RHEL6/7 with command `openssl ciphers 'HIGH:!SSLv2:!aNULL:-DH'` (remember that the shell eats the single quotes in this case and in the Apache configuration files, the single quotes are required I think or it might just strip them if present - freetds will not strip them and so will not have the intended effect).
`ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:ECDH-RSA-AES256-GCM-SHA384:ECDH-ECDSA-AES256-GCM-SHA384:ECDH-RSA-AES256-SHA384:ECDH-ECDSA-AES256-SHA384:ECDH-RSA-AES256-SHA:ECDH-ECDSA-AES256-SHA:AES256-GCM-SHA384:AES256-SHA256:AES256-SHA:CAMELLIA256-SHA:PSK-AES256-CBC-SHA:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDH-RSA-AES128-GCM-SHA256:ECDH-ECDSA-AES128-GCM-SHA256:ECDH-RSA-AES128-SHA256:ECDH-ECDSA-AES128-SHA256:ECDH-RSA-AES128-SHA:ECDH-ECDSA-AES128-SHA:AES128-GCM-SHA256:AES128-SHA256:AES128-SHA:CAMELLIA128-SHA:PSK-AES128-CBC-SHA:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDH-RSA-DES-CBC3-SHA:ECDH-ECDSA-DES-CBC3-SHA:DES-CBC3-SHA:PSK-3DES-EDE-CBC-SHA:KRB5-DES-CBC3-SHA:KRB5-DES-CBC3-MD5`

--- freetds-1.00.24/freetds.conf        2016-05-18 16:02:15.000000000 -0400
+++ ../freetds-1.00.24/freetds.conf     2017-01-31 15:17:00.000000000 -0500
@@ -26,6 +26,10 @@
        # Try setting 'text size' to a more reasonable limit
        text size = 64512

+        # If you experience TLS handshake errors and are using openssl,
+        # try adjusting the cipher list (don't surround in double or single quotes)
+        # openssl ciphers = HIGH:!SSLv2:!aNULL:-DH
+
 # A typical Sybase server
 [egServer50]
        host = symachine.domain.com

--- freetds-1.00.24/include/freetds/tds.h       2016-11-12 04:00:01.000000000 -0500
+++ ../freetds-1.00.24/include/freetds/tds.h    2017-01-30 10:30:52.000000000 -0500
@@ -519,6 +519,8 @@
 #define TDS_STR_DBFILENAME     "database filename"
 /* Application Intent MSSQL 2012 support */
 #define TDS_STR_READONLY_INTENT "read-only intent"
+/* configurable cipher suite to send to openssl's SSL_set_cipher_list() function */
+#define TLS_OPENSSL_CIPHERS     "openssl ciphers"


 /* TODO do a better check for alignment than this */
@@ -594,6 +596,7 @@
        unsigned int valid_configuration:1;
        unsigned int check_ssl_hostname:1;
        unsigned int readonly_intent:1;
+        DSTR openssl_ciphers;
 } TDSLOGIN;

 typedef struct tds_headers


--- freetds-1.00.24/src/tds/config.c    2016-05-18 16:02:15.000000000 -0400
+++ ../freetds-1.00.24/src/tds/config.c 2017-01-31 12:47:34.000000000 -0500
@@ -254,6 +254,9 @@
                tdsdump_log(TDS_DBG_INFO1, "\t%20s = %d\n", "check_ssl_hostname", connection->check_ssl_hostname);
                tdsdump_log(TDS_DBG_INFO1, "\t%20s = %s\n", "db_filename", tds_dstr_cstr(&connection->db_filename));
                tdsdump_log(TDS_DBG_INFO1, "\t%20s = %d\n", "readonly_intent", connection->readonly_intent);
+                # ifdef HAVE_OPENSSL
+                tdsdump_log(TDS_DBG_INFO1, "\t%20s = %s\n", "openssl_ciphers", tds_dstr_cstr(&connection->openssl_ciphers));
+                # endif

                tdsdump_close();
        }
@@ -677,6 +680,8 @@
        } else if (!strcmp(option, TDS_STR_READONLY_INTENT)) {
                login->readonly_intent = tds_config_boolean(option, value, login);
                tdsdump_log(TDS_DBG_FUNC, "Setting ReadOnly Intent to '%s'.\n", value);
+        } else if (!strcmp(option, TLS_OPENSSL_CIPHERS)) {
+               s = tds_dstr_copy(&login->openssl_ciphers, value);
        } else {
                tdsdump_log(TDS_DBG_INFO1, "UNRECOGNIZED option '%s' ... ignoring.\n", option);
        }
@@ -758,6 +763,11 @@
                res = tds_dstr_dup(&connection->db_filename, &login->db_filename);
        }

+        if (res && !tds_dstr_isempty(&login->openssl_ciphers)) {
+                res = tds_dstr_dup(&connection->openssl_ciphers, &login->openssl_ciphers);
+        }
+
+
        /* copy other info not present in configuration file */
        connection->capabilities = login->capabilities;

--- freetds-1.00.24/src/tds/mem.c       2016-05-18 16:02:15.000000000 -0400
+++ ../freetds-1.00.24/src/tds/mem.c    2017-01-31 11:03:02.000000000 -0500
@@ -984,6 +984,7 @@
        tds_dstr_init(&login->cafile);
        tds_dstr_init(&login->crlfile);
        tds_dstr_init(&login->db_filename);
+       tds_dstr_init(&login->openssl_ciphers);

        if (use_environment) {
                const char *s;
@@ -1037,6 +1038,7 @@
        tds_dstr_free(&login->cafile);
        tds_dstr_free(&login->crlfile);
        tds_dstr_free(&login->db_filename);
+       tds_dstr_free(&login->openssl_ciphers);
        free(login);
 }


--- freetds-1.00.24/src/tds/tls.c       2016-12-25 04:00:01.000000000 -0500
+++ ../freetds-1.00.24/src/tds/tls.c    2017-01-31 15:03:42.000000000 -0500
@@ -799,13 +799,7 @@
 int
 tds_ssl_init(TDSSOCKET *tds)
 {
-#define OPENSSL_CIPHERS \
-       "ECDHE-ECDSA-AES256-SHA ECDHE-ECDSA-AES128-SHA " \
-       "ECDHE-RSA-AES256-SHA ECDHE-RSA-AES128-SHA " \
-       "DHE-RSA-AES256-SHA DHE-RSA-AES128-SHA " \
-       "AES256-SHA AES128-SHA " \
-       "DES-CBC3-SHA DHE-DSS-AES256-SHA " \
-       "DHE-DSS-AES128-SHA EDH-DSS-DES-CBC3-SHA"
+#define DEFAULT_OPENSSL_CIPHERS "HIGH:!SSLv2:!aNULL:-DH"

        SSL *con;
        SSL_CTX *ctx;
@@ -873,8 +867,15 @@
        SSL_set_bio(con, b, b);
        b = NULL;

-       /* use priorities... */
-       SSL_set_cipher_list(con, OPENSSL_CIPHERS);
+        /* use default priorities unless overridden by openssl ciphers setting in freetds.conf file... */
+        if ( !tds_dstr_isempty(&tds->login->openssl_ciphers) ) {
+               tdsdump_log(TDS_DBG_INFO1, "setting custom openssl cipher to:%s\n", tds_dstr_cstr(&tds->login->openssl_ciphers) );
+                SSL_set_cipher_list(con, tds_dstr_cstr(&tds->login->openssl_ciphers) );
+        }
+        else {
+               tdsdump_log(TDS_DBG_INFO1, "setting default openssl cipher to:%s\n", DEFAULT_OPENSSL_CIPHERS );
+                SSL_set_cipher_list(con, DEFAULT_OPENSSL_CIPHERS);
+        }

 #ifdef SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS
        /* this disable a security improvement but allow connection... */

**Comment by freddy77** [comment]
There are some minor syntax like TLS_OPENSSL_CIPHERS should be TLS_STR_OPENSSL_CIPHERS but for the rest the patch is good.
What should I put in the subject and commit message? What's your e-mail address? Or should I just put your name as commit author?

**Comment by beaudet** [comment]
Glad to hear it!  

Subject:added support for dynamic openssl cipher list
Message:added new option to freetds.conf for specifying the cipher list supplied to openssl.  This is necessary for several reasons: 1. organizations that need more control over the specifics of encrypted connections, and 2. to overcome the occasional incompatibility (sometimes intermittent) between open source encryption libraries and Microsoft's implementations.  For example, several users reported intermittent connection problems where roughly 0.5% of connection attempts would fail for some reason.  Removing specific key exchange protocols provided relief in at least one case.  3. The cipher list can be specified in more generic terms, e.g. "HIGH:!SSLv2:!aNULL:-DH" rather than having to list specific cipher configurations that are otherwise subject to becoming outdated as the encryption landscape changes.

My github username is fine unless there's some benefit to using the e-mail address associated with my account.  Thanks Freddy.

**Comment by freddy77** [comment]
Hi, you can find a temporary commit at https://github.com/FreeTDS/freetds/commit/981bb64564ef4b1ad1c65f39ea12517291b8c1a1.
I put a dummy (dave.beaudet@dummy.com) email, git seems quite picky on the author format and require a kind of email. I can push with the dummy (or whatever real or fake email you like).

**Comment by beaudet** [comment]
Sure, in that case just put gmail.com after my github login handle.

**Comment by freddy77** [comment]
Applied! Thanks
