### ISSUE TITLE
Incorrect datetime value

### ISSUE THREAD

**Issue by rentechpro** [FreeTDS/freetds#96]
The query below from MS SQL SMS
`select a_date from dbo.test;`
shows
`2009-11-26 16:42:38.937`
`2008-05-16 17:29:08.397`
(The column a_date defined as datetime in MS SQL.)

But the query
`select a_date from my.ft_test;`
from foreign table of PG SQL shows
`2009-11-26 16:42:38.937`
`2008-05-16 18:29:08.397`

This column in foreign table defined as timestamp without time zone.
Foreign table is defined like this:
CREATE FOREIGN TABLE my.ft_test
(
    ...
    a_date timestamp without time zone,
    ...
)
SERVER fs_ms_sql
OPTIONS (table 'dbo.test');

**Comment by freddy77** [comment]
That's weird. Looks like PG is doing something to adjust the daylight that MS SQL does not.
Have you tried doing same query using isql (unixODBC console tool) or a similar tool?

**Comment by freddy77** [comment]
Closing, no reply or comments in a month.
