### ISSUE TITLE
Incorrect encoding characters

### ISSUE THREAD

**Issue by sound-code** [FreeTDS/freetds#98]
Hi guys,
please help me with the following issue, I'm using Centos7 and php7 and freetds protocol 8.0.
I'm using doctrine as orm, when the db generates the ID to make an insert it has  this charaters:
\xfe\x7b\xf9\x96\x2d\x77\x29\x4d\xad\x06\x73\xbe\x61\x9c\xef\x7b
instead of the uuid of 36 chars like 47996DA4-B303-4DDF-A669-4BD4594C9382.

Any ideas?it is a freetds issue or pdo?

thank you very much

G

**Comment by freddy77** [comment]
It's not exactly an encoding problem. Looks like php is showing binary data. Also is showing 16 bytes of data which make sense. Perhaps it's failing detecting that database can use GUID directly?
Looks like a PDO module but it's long time I don't use PHP so maybe I'm wrong. Which PDO module are you using?

**Comment by sound-code** [comment]
Hi, 
I'm using pdo_lib, I'm generating the uuid from php so I bypassed the problem but I hope the issue will be addressed.

thanks!

**Comment by freddy77** [comment]
Maybe I used the wrong terminology. Which PDO driver are you using? Can you post some php snippet of connection and insertion/select code?

**Comment by sound-code** [comment]
here is my phpinfo for pdo:

- PDO  support	  enabled
- PDO drivers	:  dblib, sqlite
- pdo_dblib
  PDO Driver for FreeTDS/Sybase DB-lib	enabled
  Flavour	freetds

I'm using Doctrine as ORM so the connection and all the queries are generated by it, however the problem is triggered when Dcotrine does:

select newId()

**Comment by freddy77** [comment]
I cannot find any newId usage in ORM.
Can you send a TDSDUMP file with the query?

**Comment by sound-code** [comment]
This is the annotation we use:
/**
  * @ORM\Id
 * @ORM\Column(name="id", type="guid")
 * @ORM\GeneratedValue(strategy="UUID")
 */ 
$id

and this is the class that Doctrine uses to generate the Id:

http://www.doctrine-project.org/api/orm/2.4/source-class-Doctrine.ORM.Id.UuidGenerator.html#32-41

**Comment by freddy77** [comment]
Closing ticket, was expecting a dump.
