### ISSUE TITLE
error retrieve rows from sysoption when protocol 5 (sybase)

### ISSUE THREAD

**Issue by mckaygerhard** [FreeTDS/freetds#99]
When executing `SELECT * FROM SYSOPTIONS WHERE "option" LIKE '%key%'` the results are different in freedts ODBC rather than Sysbase ODBC or Central, see the picture

Using ODBC freetds (versions 0.81, 0.86, 0.91 or 0.95) returns 0 rows, but using ODBC Sybase provider returns 4 rows

![error-freedts-rowscount](https://cloud.githubusercontent.com/assets/1571724/22373017/380d692c-e476-11e6-9ce1-9123981419e5.gif)

**Comment by freddy77** [comment]
Which type is option? Is it possible you are on a different database? "select db_name()" should return the current database name.

**Comment by mckaygerhard** [comment]
nop, theres only one db in that connection, and when a connection its made to sybase, engine and db name are the same in my environment, so in this way, select db_name() return the only db name selected, 

U must take in consideration that in ANY db on sybase, SYSOPTION its always present and "option" column its the propertie to consult, and in this table are stored all the options persisten OF the database...  and the "reserved_keywork" (as example) are always present as row, inclusive if the column "value" are not set. (all of this its for verify before enabling the LIMIT and OFFSET support in sybase after version 12)

```
SQL> select db_name()
+--------------------+
| db_name()         |
+--------------------+
| OP_001037       |
+--------------------+
SQLRowCount returns 1
1 rows fetched
SQL> 

```
As the picture shows, OP_001037 are the current database

**Comment by freddy77** [comment]
Thanks to confirm they are using the same database.
Now I think a TDSDUMP would help. You can send it to my privately if you feel there could be sensitive information.

**Comment by mckaygerhard** [comment]
seems github private feature message was remove some time!

**Comment by freddy77** [comment]
You can find my address on the ML, see http://lists.ibiblio.org/pipermail/freetds/

**Comment by mckaygerhard** [comment]
hello @freddy77 i just send to you in private mail the dumps as i described here, the mail subject are `"
tds dump problem with sysoption %key%  "`

the tdsodbc binary versions used was 0.91 and 0.95 the attached files are identified in the mail

the processs was:
1) instal 0.91 version odbc (tdsodbc)
2) rm /tmp/freetds.log
3) export TDSDUMP=/tmp/freetds.log
4) isql oasisf dba sql
5) take files and save and attache to this mail
6) unninstall 0.91 and build and install 0.95+git
7) rm /tmp/freetds.log
8) export TDSDUMP=/tmp/freetds.log
9) iql oasisf dba sql
10 take file and save and attach to this mail

the output with the 0.95 with the changes was:
```
SQL> select "option" from SYSOPTIONS where "option" like '%key%'
+---------+
| 'option'|
+---------+
+---------+
SQLRowCount returns 0
SQL> quit
```
the output with the 0.91 without the lasted git changes:
```
SQL> select "option" from SYSOPTIONS where "option" like '%key%'
SQLRowCount returns -1
SQL> quit
```

the server are remote in a different network, details in the mail i send to u

the odbc config used are same for both test, details are in mail i send to u

**Comment by mckaygerhard** [comment]
> Hi,   I'm really busy lately.

me too, sorry for delay in aswers, i'll try to make consice but please take carefully i'll try to help to improve this proyect and help more:

> These network capture are quite weird. Looks like this SQL Anywhere is a very old product. I have to look at the capabilities better but seems really empty compare to ASE.

Its AnyWhere 12.0.1, the all-in-one all-for-everywhere product, for mid-end consumers, ASE are a very focused group of products, despiste Anywhere that are a all-in-one general purpose product, that includes the Sybase Center, ODBC drivers, Engine DBMS and minimal development headers for integrations.
Take in consideration that sybase (now SAP) have focused products: SQS, ASE, ADS, Anywhere, well, the differences between one or other are some "more cheap and easy to use" functions.. by examples, the oracle extraction integration in OBI canot handle the anywhere flavors, only the ASE and ADS, and not the SQS due SQS are not for data management of bussines...

so the as conclusion for development of freedts i recomended usage of version 12.0.1 (not 12.5) of sybase DBMS, and mobilink/qanywhere
Theres a good example: http://infocenter.sybase.com/help/topic/com.sybase.infocenter.dc38151.1510/html/iqrefbb/iqrefbb642.htm here we can see that mayor option of anywhere applies to the iq flavor, but not otherwise, same for the ASE and ASD flavors...


ad final note, replication/remote sync are unique, in ASE, theres two options and on Anywhere and SQS there's one only option, ase use the replication server or ther internall replication publications, Anywhere use the replication internal publications, and SQS use only the replication server . The flavors of qAnywhere and mobilinks canot handle replication on all version only few

> Ar you actually expecting some rows? Looks like by the way that the
server returns nothing even if it accepts the prepared statement. But
maybe the prepared is wrong as some capabilities are missing.

The firts picture show that server "must" (seems) return a row, and me as user expected at least two rows, and as u said, seems some capabilities are misunderstanding, 

as i explain lines before and as i can see **i think u thread all the sybase DBMS as a ASE flavor, and there' not!** its a fortune i have both, also have anywhere 6 and 9 for mobiles.

> Can you use tsql to do the same query. tsql tend to use not prepared
statement and these request are supported by all versions.

ironically this depends of the issue 92, jajajaj whell i must post some feedback due i see lasted commit seems solved that problem, as i said, next week i'll test tsql and tri it in tsql this query

And finally **i added two cents by my part, here** to help improve the proyect:
> I know it could sound crazy but could you try
select option from SYSOPTIONS where option like '%key%'
or
select [option] from SYSOPTIONS where [option] like '%key%'
I don't understand why the server quote the column name, should not do it.

the word "option" its a reserved keyword in all sybase DBMS, in ASE and Anywhere u must suround reserved keywords with "

firts query and second "seems" acepted in the odbc level, i'm not expert but revising code freedts odbc only translated the query to the sybase engine, and when this query arrivals in the DBMS, the query will fail, retur a sql error command as invalid, so the real error never will be showed

http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc38151.1510/html/iqrefbb/Alhakeywords.htm
As u can see it, reserved keyword are different from sybase databases, in embebed flavors thei have a special function that qanywhere does not (not documented) so select quaery will fail!
http://infocenter.sybase.com/help/topic/com.sybase.infocenter.dc38151.1510/html/iqrefbb/CACDEHJA.htm

there's a way to use that reserved keyword, but again ironically that query must be make for revised some previous "reserved activated keywords", of course i can activate into the sybase central.. but...

activating reserved keyword "option" for normal usage as u proposed in the two querys are nod good idea, due may cause some kind of conflits in internals

**Comment by mckaygerhard** [comment]
awaiting fro #92 to property test this issue due now cannot conect using ODBC...

**Comment by freddy77** [comment]
Closing. Please reopen with updated information

**Comment by mckaygerhard** [comment]
sorry for late, i'll let close untill tomorrow that i'll reopen due, i still not have a free slot in the virtual machine for remote access, but i can test with testing enviroment at my job.. thanks..

**Comment by mckaygerhard** [comment]
hi this problem are still happened using freetds 1.00.104 compiled with debian jessie: 

```
remoto@sysanydesktop0:~/Devel/elgasto$ isql oasisdb dba sql -v
+---------------------------------------+
| Connected!                            |
|                                       |
| sql-statement                         |
| help [tablename]                      |
| quit                                  |
|                                       |
+---------------------------------------+
SQL> SELECT "option" FROM SYSOPTIONS WHERE "option" LIKE '%key%'
+---------+
| 'option'|
+---------+
+---------+
SQLRowCount returns 0
SQL>
```
must returns 4 rows! got 0 rows

**Comment by mckaygerhard** [comment]
now that freetds properts connect and #92 was solved, tested and got same result, no sysoption rows from database using freetds odbc:

```
remoto@sysanydesktop0:~/Devel/elgasto$ isql sybasedb dba sql -v
+---------------------------------------+
| Connected!                            |
|                                       |
| sql-statement                         |
| help [tablename]                      |
| quit                                  |
|                                       |
+---------------------------------------+
SQL> SELECT "option" FROM SYSOPTIONS WHERE "option" LIKE '%key%'
+---------+
| 'option'|
+---------+
+---------+
SQLRowCount returns 0
SQL>
```
must returns 4 rows! got 0 rows

**Comment by mckaygerhard** [comment]
currently seems that i cannot reopen this issue, but in any case i send a aditional dump log using tsql tool that was the process: 

```
root@sysanydesktop0:/etc/freetds# export TDSDUMP=/tmp/freetds.log;TDSVER=5.0 tsql -H <ipinmail> -p 2638 -U dba -P sql -D <dbinmail> -o v
locale is "es_VE.UTF-8"
locale charset is "UTF-8"
using default charset "UTF-8"
Setting <dbinmail> as default database in login packet
1> SELECT "option" FROM SYSOPTIONS WHERE "option" LIKE '%key%'
2> go
'option'
using TDS version 5.0
using TDS version 5.0
1> quit
```

**Comment by mckaygerhard** [comment]
re-done with the `TDS_version =5.0` already added to command line as requested and send dump lifes log with subject "Re:  tsqldump: error retrieve rows from sysoption when protocol 5 sybase" to your mail

still happened with the version parameter added... in both `isql` and `tsql` commands, waith for your response and hope to resolve this!

**Comment by freddy77** [comment]
Got the logs. The server is returning nothing to the client!
Try removing the quote like
```
SELECT option FROM SYSOPTIONS WHERE option LIKE '%key%'
```
also try to use a specific database like
```
USE master
SELECT option FROM SYSOPTIONS WHERE option LIKE '%key%'
```
or
```
SELECT option FROM master..SYSOPTIONS WHERE option LIKE '%key%'
```
try to remove the filter so
```
SELECT option FROM master..SYSOPTIONS
```
This issue looks more a database issue than a protocol one.

**Comment by mckaygerhard** [comment]
> Got the logs. The server is returning nothing to the client!

GOt the problem, and are a sybase 12 standart-break problem, i posted the conclusions and workarounds at the end of the messages, **but i posted some important notes to you @freddy77 for the freetds drivers respect sybase databases, please read it!**,  the problem are the reserved keywork `option`, see all at the end of this message.


**NOTE 1:** the nature of : http://infocenter.sybase.com/help/topic/com.sybase.infocenter.dc38151.1520/html/iqrefbb/BACHHIDE.htm` where:
*The SYSOPTION view is a SQL Anywhere system view. See "SYSOBJECT system view" in SQL Anywhere Server – SQL Reference.*  (that is my case, sysoptions area view, but in anywhere its a fake table remenber that!)
So some of your sugestions are invalid without tested!

as i can see, in ASE sybase sysoption its a fake table, but in anywhere its a system view in each database.. andone of the columns are named `option` so that word become a reserved word, so i cannot use `option` as is in the query, neither use `"option"` due that converts this in a hard-coded value du the usage of the `"` in the query.. that are the real problem... and that's why "resver retuns nothing" in the logs.. due i "asking nothing" due the usage of `"` in the query becose miscinterpretation of the reserverd keyword `option` and the right query must use ``` in the word.... at the end of the messages the results that give me the conclusion!


**NOTE 2:**
> Try to use a specific database like
> ```
> USE master
> SELECT "option" FROM SYSOPTIONS WHERE "option" LIKE '%key%'
> ```

there's one database, each sybase database it's selft contained and sysoption its a faketable/view depending of the sybase type (anywhere or ASE)

**NOTE 3**
> ```
> SELECT "option" FROM master..SYSOPTIONS WHERE "option" LIKE '%key%'
> ```

sysoption its a fake table / system view so that are nonsense


## Now the workaround results:

> try to remove the filter so
> ```
> SELECT "option" FROM master..SYSOPTIONS
> ```

that was the most interesting results, servers seems results all but not the value results? if i used "*" event "option"  i got the values, and so then the probles here are the reserved keyword `option`, so i got a workaround by using ``` in the query event using `"` and got results... so **but "why" i confused and use the `"` in the querys'? well as in the picture, i see that the very stupid sybase tools use that for reserved keyword i try stupidy to use at the freetds drivber, but that are non-standar way so i'll close this issue due the piucture use a non-standar way of query the database!**
```
SQL> SELECT "option" FROM master..SYSOPTIONS
+---------+
| 'option'|
+---------+
| option  |
/*.... more results cutted due i pasted in less space....*/
| option  |
+---------+
SQLRowCount returns 151
151 rows fetched
SQL> 
```
 


```
SQL> SELECT `option` FROM SYSOPTIONS WHERE `option` LIKE '%key%'
+---------------------------------------------------------------------------------------------------------------------------------+
| option                                                                                                                          |
+---------------------------------------------------------------------------------------------------------------------------------+
| non_keywords                                                                                                                    |
| reserved_keywords                                                                                                               |
| prevent_article_pkey_update                                                                                                     |
| secure_feature_key                                                                                                              |
+---------------------------------------------------------------------------------------------------------------------------------+
SQLRowCount returns 4
4 rows fetched
SQL>
```
